### ISSUE TITLE
How

### ISSUE THREAD

**Issue by SpeakerGames** [CTCaer/hekate#1000]
How to launch linux or android?
![Screenshot_2024-08-04-13-37-00-616_com android vending](https://github.com/user-attachments/assets/fbf1f24c-62f6-42d0-8f7f-cc240812ccc4)

**Comment by urherenow** [comment]
There are tutorials everywhere. This isn’t a support forum and you could easily type that question into Google and found the answer.

**Comment by SpeakerGames** [comment]
> There are tutorials everywhere. This isn’t a support forum and you could easily type that question into Google and found the answer.
I googled it 1000 times and haven't found an answer

**Comment by CTCaer** [comment]
literally the first search results have switchroot wiki in them.
also here's not a chat/forum to ask how to installed/setup something.
