### ISSUE TITLE
About charge voltage limit

### ISSUE THREAD

**Issue by hukaka22** [CTCaer/hekate#1002]
In hekate Battery Info,I found my Switch Lite charge voltage limit change to 4192mV,before is 4208mV,after in HOS 4 charge-discharge cycles(100%-0%-100%-0%-100%-0%-100%-0%), it always keep 4192mV,and now about 15% full battery capacity not use.
How can I fix it?
Thanks

**Comment by masagrator** [comment]
it's not an issue with Hekate.

**Comment by hukaka22** [comment]
If I don't have a backup, is there any way to fix it?

**Comment by impeeza** [comment]
No, read previous closed, issues  please seek for support on a site for that, like Discord or GBATemp.  Issues is for report software Bugs.

**Comment by CTCaer** [comment]
I released an actual fix for that: https://github.com/CTCaer/battery_desync_fix_nx/releases/latest
