### ISSUE TITLE
Can't boot into Hekate

### ISSUE THREAD

**Issue by tryfontheo** [CTCaer/hekate#1004]
I get a screen like [this](https://www.reddit.com/r/consolerepair/comments/1dr2un6/i_get_this_screen_when_i_try_to_inject_payload/ ) when using TegraRcmGUI or even trying to reboot to payload once I am in atmosphere. Everything is up to date, SD card is fine, no hardware damage to the device (1st gen switch). Just tried to update atmosphere and Hekate today and got this issue. Before I get that screen I get the following error: 
![IMG_0574](https://github.com/user-attachments/assets/4edc6731-fe5d-4c76-827b-4b7d7d6f2bbf)

So I can take my SD card out and get into the rudimentary hekate (which I can use to boot into the switch), but I cannot get into the actual hekate GUI no matter what.

**Comment by impeeza** [comment]
This is not a support site, please go to Discord or GBATemp,  saying that,  check your SD Card,  download latest Hekate and extract to your SD Card,  upgrade your Payload on TegraRcmGUI  to use latest bin from the zip.
