### ISSUE TITLE
Gamepad not detected on Debian 12

### ISSUE THREAD

**Issue by Arctic-Circle-System** [CTCaer/hekate#1005]
I plugged it in as you normally would and started the gamepad mode. It says "Started HID emulation", but any games with controller support just don't detect it. It doesn't show up as a device in moltengamepad. Gamepadtool also doesn't work. I'm not sure what's going on. If there's logs I need to submit, I don't know where they are. No errors are showing up on the Switch itself either.

**Comment by CTCaer** [comment]
The gamepad exposed to OS is simple hid.
So it should work everywhere. Except if your OS makes the exposed interface as root only and it expects a udev rule to fix it.
You can check with `sudo evtest` and also that it shows up in lsusb and /dev/

**Comment by Arctic-Circle-System** [comment]
@CTCaer Alright, I'll check that in a bit and let you know of the results. Thank you.

**Comment by CTCaer** [comment]
@Arctic-Circle-System did you check?

**Comment by CTCaer** [comment]
I'm assuming user fixed that at this point (probably a udev rule issue).
