### ISSUE TITLE
Preinstall sanity check (Help wanted)

### ISSUE THREAD

**Issue by non-bin** [CTCaer/hekate#1009]
Hi

I'm pretty late to the game I know, I just want to make sure I haven't missed anything because info is kinda sparse. I have a n HAC-001(-01) switch, with. serial **XKW**7001123XXXX switch, on 18.1.0. I know I can't use fuzzy-glee so I bought an RP2040 Hwfly Core, and I'm planning to follow [this hardware guide](https://guide.nx-modchip.info) and [this software guide](https://switch.hacks.guide/user_guide/modchip/preparing_hekate/) probably using emuEMMC to be safe

Does anyone have any experience/recommendations/cautions/confessions-of-love for me?

Thanks :)

EDIT: Turns out I accidentally bought a picofly lite so that's annoying, I'll get the proper one in a few weeks
EDIT 2: It looks like the motherboard is identical to the V1 switch, but the SoC is the same as the switch lite (ODNX10-1A). Is that what the second SoC ribbon cable that comes with the picofly core is for? the guide doesn't mention how to install it, just that it is compatible

**Comment by impeeza** [comment]
This is not a support site, please go to Discord or GBATemp

**Comment by non-bin** [comment]
Sure thing, thanks :)
