### ISSUE TITLE
Fatal error on boot

### ISSUE THREAD

**Issue by TiviGraphics** [CTCaer/hekate#1011]
Hi, im having issues booting the system, i´ve tried a lot of different things like formatting the SD card over and over again, and updating hekate, but it doesnt work. heres the fatal error report, i will be waiting for your response. 
[report_063134ed.zip](https://github.com/user-attachments/files/16923110/report_063134ed.zip)

**Comment by impeeza** [comment]
Sorry buddy, this is not a support site, this space is for report bugs and issues with Hekate, please go to Discord or GBATemp sure you will get support there.  and please when contact that sites provide more information about your setup, your console type, your injection mode, etc.

please close this issue.
