### ISSUE TITLE
Slow SD card in hekate causing lag

### ISSUE THREAD

**Issue by souldbminersmwc** [CTCaer/hekate#1014]
The SD card is very slow in hekate, but works just fine outside. This causes lag in menu. Tried reformatting, issue still persists
OLED Picofly

**Comment by souldbminersmwc** [comment]
This might be an issue with hekate memory clock on oled looking at code.

**Comment by CTCaer** [comment]
you have a hw issue.
also what hekate does has nothing to do with HOS (the stock os and its menu).
you lag in there because your sd reader fails to init or read stuff and initializes in 1bit mode.
