### ISSUE TITLE
I can't format or delete partitions on microSD after using Hekate.

### ISSUE THREAD

**Issue by jcornac** [CTCaer/hekate#1018]
Hello.

I just bought a new switch and have been trying to install hekate all day. When I was about to access the switch, I realized that the previous owner I bought it from had already installed it. I then looked for a way to (for security) format everything and leave it factory default to proceed with a new installation correctly. However, I don't really understand why it is in a read format that cannot be modified in any way. I have used third party programs, official programs, commands, diskpart but I can not get in any way to disable the read-only mode or format and delete the various partitions created.

Sorry for all this text or if it is explained somewhere in the readme.md but I don't understand English very well and I didn't find a way to contact you except by Issues on Github. I will try to solve this issue in the way you recommend me so that it is not a stain on the repository.

Back to the topic, I'm mainly interested in knowing what does the nintendo switch or Hekate do that once I insert a micro-SD it becomes read-only forever. I say this because I had my own micro-sd that was not read-only and was to follow the installation procedure, backup and such Hekate that I became permanently read-only.

Best regards and sorry for the inconvenience.

P.S. I also couldn't search on my own if any previous issue asked this same question.

**Comment by CTCaer** [comment]
Don't use fake cards or cards with extreme wear. they lock themselves on their own when they don't have writable cells anymore.
Get a good one that also has good reliability/life, like a samsung ones.

And btw never ever do full and especially not security formats on sd cards that are for personal use.
You just waste 1-5 full write cycles like that. If you want proper full format, use sd association's sd formatter.
It will use the ERASE command only which tells the nand to open all cells and make them ready for writing.
(Full format doesn't do that, next write will cause an erase and write again)

Anyway, if you are still wondering about various signs, you can post a photo from console info -> microsd here from the 2 cards and I will tell you the signs.
