### ISSUE TITLE
Update Hekate

### ISSUE THREAD

**Issue by schizofrog** [CTCaer/hekate#1019]
Please update Hekate to 1.9 Switch Firmware

**Comment by sykeo99** [comment]
Hopefully Hekate will update support for firmware 19.1.0 soon

**Comment by CTCaer** [comment]
Get the latest hekate version.

**Comment by schizofrog** [comment]
YAY

**Comment by Visualwit** [comment]
> Hekate won't release until new Atmosphere is released. So stop posting and wait.

Hekate was updated, but atmosphere is still in the works.
