### ISSUE TITLE
Failed to match warm boot with fuses! if you continue, sleep won't work!

### ISSUE THREAD

**Issue by District7** [CTCaer/hekate#1022]
Updated OFW to firmware 19 and running hekate and atmohsere current version on firmware 18.0.1 seem when I updated my OFW it started to cause the issue when going back to my partition EMUMMC what do I need to do to fix this issue?

**Comment by warzzy** [comment]
To avoid this problem in the future; never update OFW before the Hekate update that actually supports it!
You have to deal with this issue until new Hekate version is released.

**Comment by CTCaer** [comment]
Get the latest hekate version.
