### ISSUE TITLE
Sleep Mode Freeze

### ISSUE THREAD

**Issue by District7** [CTCaer/hekate#1024]
Hello updated to current hekate v6.2.2 & Nyx v1.6.4 and my OFW is firmware 19.0 but my CFW is 18.0.1 and I don't get the issue I had before with he warning  but now after I am in CFW and sleep mode is activated by timeout or pressing the power button it turns off but when pressed on to wake, I get a frozen black screen and have to force restart. is there something I can do to to fix this or need to wait for Atmosphere to be updated?

**Comment by CTCaer** [comment]
Boot stock once for the updated sleep firmware to be dumped.
(Doesn't matter if it fails to boot without updating atmosphere, it will still be dumped.)

**Comment by District7** [comment]
> Boot stock once for the updated sleep firmware to be dumped. (Doesn't matter if it fails to boot without updating atmosphere, it will still be dumped.)

SO I boot Stock and get blue screen I let it sit then restarted but still same issue I also booted OFW then back to CFW and still sleep freeze happens, Under OFW I have not issue there as its all stock but my CFW is still freezing and needs hard reset to turn back on. I have turn off sleep mode for now but not an ideal way to run the switch. any help would be appreciated.

**Comment by District7** [comment]
Atmosphere updated to support OFW 19 pre release updated and now have no issue using 19 firmware cross the board
