### ISSUE TITLE
Blue Screen on OFW with Hekate 6.2.2

### ISSUE THREAD

**Issue by vencraft** [CTCaer/hekate#1025]
I get a blue screen on OFW on my Nintendo Switch OLED after updating to version 6.2.2. I revert to version 6.2.1 and it works perfectly. My firmware on OFW is 19.0.0

**Comment by vencraft** [comment]
I'll add that if I start without the microSD inserted (bypassing Hekate), it also works correctly.

**Comment by CTCaer** [comment]
hekate has nothing to do with OFW.
OFW means all firmware is original (unlike stock, which in that context always had a different meaning for decades).
And that includes bootloader.

So if you have blue screen on OFW, that means the update was messed up and either your Package1/Package2 are mismatched or Package2 is corrupt.

**Comment by ghost** [comment]
I know necro but I came around this while searching closed ones having this issue my own ;)
I admit that the problem can occour if you are upgrading and phase the tasks with a chip as well...

1. adding new files to your sd-card EXCEPT Atmossphere, which you will do later cause sometimtes (mostly at major version changes) it wont boot with the new files not having the emunand upgraded.
2. so you have the new files, you update OFW
-> booting OFW can now cause a bluescreen while using the integrated boot type from menue
-> booting via hekate -> reboot -> OFW leads to a working OFW boot
-> issue has been told by CTCaer which makes sense at this step, cause u dont have updated the atmo yet
4. run your EMUnand and update this as well, after that add the new atmo files and you should be ready to go ;)
