### ISSUE TITLE
Booting, from Hekate v6.2.2 & Nyx v1.6.4, into SYSNAND 19.0.0 + EMUNAND 18.1.0 (Atmosphère 1.7.1) Not Working (either AutoRCM or not)

### ISSUE THREAD

**Issue by WillsitoGG** [CTCaer/hekate#1026]
AutoRCM with SYSNAND 19.0.0 + EMUNAND 18.1.0 (Atmosphère 1.7.1) Not Working, when going to SYSNAND from Hekate it gives a HOS error in the screen vertical mode.

**Comment by CTCaer** [comment]
>a HOS error

what's the error?

**Comment by WillsitoGG** [comment]
> > a HOS error
> 
> what's the error?

If the Auto RCM is off, and I launch SYSNAND from latest Hekate version, the screen turns full yellow and the only way is to hold the power button for 12 seconds to turn it off.
![AutoRCM Off](https://github.com/user-attachments/assets/7f6995bf-0d3c-4a6d-b9ec-59fba6236ff6)

If the Auto RCM is on, and I launch SYSNAND from latest Hekate version, the screen turns full black excep the following error:
HOS Panic Ocurred!
Color... Code: 06
Press any key
![AutoRCM On](https://github.com/user-attachments/assets/7ee0ddad-8e0a-4c0e-a8fe-281e383ad42c)

The only only change, before everything working as a charm, was pasting the latest hekate v6.2.2 & Nyx v1.6.4 files in the SD.

Hope it helps,

Best regards

Willsito

**Comment by WillsitoGG** [comment]
I correct the title to one more accurate:
Booting, from Hekate v6.2.2 & Nyx v1.6.4, into SYSNAND 19.0.0 + EMUNAND 18.1.0 (Atmosphère 1.7.1) Not Working (either AutoRCM or not).

**Comment by CTCaer** [comment]
Update atmosphere to 1.8.0. You can't boot 19.0.0 with 1.7.1. It doesn't have the necessary key generation.

**Comment by WillsitoGG** [comment]
But what do I do if I want to maintain the previous Atmosphere version, as it is far more stable compared to the last one, plus this last one has a lot of issues and bugs, for example, not being able to use forwarders?
