### ISSUE TITLE
Failed to match warmboot with fuses

### ISSUE THREAD

**Issue by Kingfadlan** [CTCaer/hekate#1033]
My cousins Mariko switch started suddenly showing this error a couple of months ago, and we've tried everything we knew. I already booting to sysMMC and it didn't work. We didn't update anything and we are new to the modding scene please help

**Comment by CTCaer** [comment]
You need to boot into sysMMC (stock or cfw mode) with hekate.
In case that's what you tried, get a screenshot from hw & fuses info (in console info in hekate).

**Comment by Kingfadlan** [comment]
Here is the screenshot. I have no idea which info you needed so it's the full screen
![Uploading IMG_20241101_152610.jpg…]()

**Comment by CTCaer** [comment]
When you said you didn't update anything, I thought you were talking about something else.
You have old hekate and you updated to 19.0.0.
So update hekate and atmosphere.
