### ISSUE TITLE
[Enhancement] 💡Allow direct value inputs for Partition Manager

### ISSUE THREAD

**Issue by MarsWonderBoy** [CTCaer/hekate#1034]
Title

As of now, when partitioning the SD card, the user must use the slider to their desired value. Add an option to simply tap at the value field to input a number directly.

I have a 512GB and partitioning for HOS, Linux, and Android. ...I've been fumbling between 61GB and 65GB when I only need 64GB to partition. 😭😭

![IMG_1791](https://github.com/user-attachments/assets/5d35461f-9a9a-4faf-a9d6-e002b03d5ae7)

**Comment by HeikesFootSlave** [comment]
Nice Idea!

2x29 emuMMC!?
No matter which version I always set it to 12GB and never had any problems or issues! (it's enough for me and three profiles!

**Comment by CTCaer** [comment]
The slider uses 700 pixels which means it allows for up to 700 selections.
If you find it difficult to select what you want, increase another (like linux) just to reduce max. And then reduce the other one back.
Or just use joycon mouse for even more precise movement.

On android though, what you see is not what you get (it just controls userdata partition and there are 6GB more of partitions), so dunno why you want to be precise.
