### ISSUE TITLE
Is there a way to avoid updating the Atmosphere version while still having the latest Hekate version working properly?

### ISSUE THREAD

**Issue by WillsitoGG** [CTCaer/hekate#1035]
I have a problem: if I want to maintain the previous Atmosphere version (1.7.1) within my EMUNAND, as it is far more stable compared to the last one, plus this last one has a lot of issues and bugs, for example, not being able to use forwarders, **how can I do it?**

This is the context of this problem: https://github.com/CTCaer/hekate/issues/1026

Many thanks in advance,

Best regards

**Comment by impeeza** [comment]
This is not a support site.

PIRACY IS NOT SUPPORTED

that is A ATMOSPHÈRE ISSUE, not Hekate SO THIS IS NOT THE PLACE.

GO AND READ THE TOPICS ON GBATEMP.NET.

the solution is CREATE NEW FORWARDERS COMPATIBLE WITH ALL ATM VERSIONS.

Please close this issue.

**Comment by impeeza** [comment]
> Hello, I’m sorry if my question came across the wrong way or offended you, but I believe there’s a misunderstanding here. As you mentioned in another post, Hekate indeed requires the latest version of Atmosphere to work properly. My question was about finding a stable solution within the limitations of Atmosphere 1.7.1, not about support for piracy or using the latest update.
> 
> I appreciate your recommendation, and I understand if you prefer to close this issue. Thanks again.
> 
> Best regards,
> 
> Willsito

The only «limitatiins» of Atmosphère 1.8.0 are piracy support, Atmosphère do not suppor the use of software needing patches.

Again, this is a space for issues and bugs report not a support site, for support go to GBATEMP or discord.

If you like to be on firmware 18 you can use Hekate 6.22, Atmosphère 1.8.0 and any homebrew built with latest tools like https://nsp-forwarder.n8.io/

Pleay any further questions go to support sites and close this issue

**Comment by WillsitoGG** [comment]
Thank you for the information. I’ll try keeping firmware 18 and using Atmosphère 1.8.0 to see if everything continues working as expected.

I appreciate the link and your advice; the issue has been closed since yesterday, and I’ll reach out to the support sites if I have further questions.

Best regards,

Willsito
