### ISSUE TITLE
Not work for 19.0.1

### ISSUE THREAD

**Issue by SeFiROOTpitu** [CTCaer/hekate#1037]
I update ofw to 19.0.1 and then installed picofly, i run hekate fine but i cant create good emunand and not run in ofw, y get this message "unknow pkg1 versión, hos not supported" and then run in ofw, show Nintendo screen and then black screen
![Screenshot_2024-11-07-12-43-41-322_com miui gallery-edit](https://github.com/user-attachments/assets/f78b47f2-3160-4364-b7af-634fcd61f32e)

**Comment by CostelaCNX** [comment]
Is not a hekate issue, is the Picofly install

**Comment by SeFiROOTpitu** [comment]
I did the same with other ns mariko in 19.0.0 and working fine i created the emunand perfectly, but when update the ofw to 19.0.1 get the same message, only boot in emunand

Yahoo Mail: Busca, organiza, conquista 
 
  El jue, nov 7, 2024 a 13:08, ***@***.***> escribió:   


Is not a hekate issue, is the Picofly install

**Comment by CTCaer** [comment]
Your package1 is corrupt in eMMC (sys). You need to fix it (it lives in BOOT0).

**Comment by SeFiROOTpitu** [comment]
I understand what happend here, if i disconect picofly the ns boot normaly, not emmc sys problem

**Comment by CTCaer** [comment]
That's even worse actually. Because it means the signal gets corrupted by bad impedance.
Which also means that any use of HOS on eMMC (ofw/stock/cfw) can corrupt and software brick it by bad writes.
And you have no way of knowing if it already corrupted something.

**Comment by SeFiROOTpitu** [comment]
Thank you, i Fix It, the problema was wire lenght
