### ISSUE TITLE
Hang Detected in LP0/Minerva

### ISSUE THREAD

**Issue by kPATm** [CTCaer/hekate#1038]
Hello. I have suddenly started getting an error when trying to boot Hekate on a v1 with a Mod Chip.

The error is

"hekate exception occured (LR 4000E7C0)

Hang Detected in LP0/Minerva/

I have tried a different SD card but I get the same error. I have also tried to reflash the RP2040 but it still gives the error. Any help is appreciated

**Comment by CTCaer** [comment]
User contacted me in discord and suggestions given but no answer.

**Comment by craftersshaft** [comment]
getting this error on a launch nintendo switch after using tegrarcmgui and a jig, do i need to worry about this
