### ISSUE TITLE
[Feature Request] Configuration file

### ISSUE THREAD

**Issue by tthe3d** [CTCaer/hekate#1045]
Consider adding hekate_ipl.ini configured to run atmosphere for newbies like me who are confused about how to make their "own" pack. :)

**Comment by urherenow** [comment]
https://github.com/CTCaer/hekate/tree/master/res

And all possible entries are on the first page you see when entering this github repo. It’s not included on purpose, because its inclusion would overwrite your own preferences every time you upgrade. Just RTFM.

**Comment by tthe3d** [comment]
That makes sense. Thank you for the clarification. 😸
