### ISSUE TITLE
Can't launch the firmware

### ISSUE THREAD

**Issue by bnxflazy** [CTCaer/hekate#105]
Maybe it's because I did something wrong, but right now the situation is that I can't even open the switch, and I can't go back to the original system, when I want to launch the firmware, it failed with a message "could not identify package1, version <= ''>. Failed to launch firmware, could you help me with this ?

**Comment by bnxflazy** [comment]
Thanks very much for replying me. It worked, but I think at the first time, I didn’t make the back up correct, the rawnand file should be 30GB, but it is only 4GB, and I used the BOOT0 and BOOT1 to restore my switch, and suddenly I can’t get into the firmware any more. And I tried to reinstall the firmware, but it doesn’t work, The version I used , I am not sure. <=”>  --> this said nothing, the whole sentence are like this:
-------------------
Initializaing…
Could not identify Package1,
Version <= ‘’ >.
Failed to launch firmware.
I think it’s because I restored something that I should not?




发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: Kostas Missos <notifications@github.com>
发送时间: Saturday, September 8, 2018 9:25:47 PM
收件人: CTCaer/hekate
抄送: Finbar; Author
主题: Re: [CTCaer/hekate] Can't launch the firmware (#105)


What switch version you have? Also what version this <= ''> says?
And what you did wrong?

―

**Comment by CTCaer** [comment]
BOOT0/BOOT1 must match the version of rawnand.
Also because it is showing '' as version, it means that the restored boot0/1 were initially corrupt.

You sd card or your backup had problems.

You are lucky that you only restored BOOT0/BOOT1.
You only have to restore these back. Use Choidujour to acquire a working folder with firmware files.
Then you can find BOOT0/BOOT1 there. Don't worry that they seem small.
You have to use hacdisktool to dd them back.

**Comment by bnxflazy** [comment]
What if I say that after I restored the B00TO/BOOT1 ,and I saw it doesn’t work, and then I backed up the whole system again? But without B00T0/B00T1, I mean I backed up the whole system , and I get a 30GB’s rawnand, and I used the B00T0/B00T1 to restore, after that, I also restored the rawnand. Is It still Okay?


发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: Kostas Missos <notifications@github.com>
发送时间: Saturday, September 8, 2018 9:38:11 PM
收件人: CTCaer/hekate
抄送: Finbar; Author
主题: Re: [CTCaer/hekate] Can't launch the firmware (#105)


BOOT0/BOOT1 must match the version of rawnand.
Also because it is showing '' as version, it means that the restored boot0/1 were initially corrupt.

You sd card or your backup had problems.

You are lucky that you only restored BOOT0/BOOT1.
You only have to restore these back. Use Choidujour to acquire a working folder with firmware files.
Then you can find BOOT0/BOOT1 there. Don't worry that they seem small.
You have to use hacdisktool to dd them back.

―

**Comment by CTCaer** [comment]
If you restored a corrupt BOOT0/1 and backed it up, you get that corrupt BOOT0.
So if you restore it, you are at where you started..

**Comment by bnxflazy** [comment]
Not really ,I mean I backed up a 30GB rawnand file. And I backed up the corrupt B00T0/1 again, and after that , I restored the rawnand file which is just backed up. Is this still be Okay?

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: Kostas Missos <notifications@github.com>
发送时间: Saturday, September 8, 2018 9:44:05 PM
收件人: CTCaer/hekate
抄送: Finbar; Author
主题: Re: [CTCaer/hekate] Can't launch the firmware (#105)


If you restored a corrupt BOOT0/1 and backed it up, you get that corrupt BOOT0.
So if you restore it, you are at where you started..

―

**Comment by CTCaer** [comment]
OK to what? You still have a corrupt BOOT0/1.

If you mean, if the rawnand is OK, it should be. It's on another physical partition of the eMMC.

**Comment by bnxflazy** [comment]
I can’t understand that, I just wanna tell you what did I do, I mean I restored the rawnand(backed up after I already had a corrupt B00T0/1,) , is it still okay that I can recover it using what you said, the Choidujour.

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: Kostas Missos <notifications@github.com>
发送时间: Saturday, September 8, 2018 9:52:36 PM
收件人: CTCaer/hekate
抄送: Finbar; Author
主题: Re: [CTCaer/hekate] Can't launch the firmware (#105)


OK to what? You still have a corrupt BOOT0/1.

If you mean, if the rawnand is OK, it should be. It's on another physical partition of the eMMC.

―

**Comment by CTCaer** [comment]
yeah. If that rawnand is ok, you'll be good.

Just try to restore boot0/1 only and check if it boots

**Comment by bnxflazy** [comment]
Thanks a lot. But I don’t know how to use choidujor.. I downed the choidujour110 from switchtools.sshnuke.net, but when I try to launch the exe file, it just showed up a terminal for a sec, and nothing happened…..


发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: Kostas Missos <notifications@github.com>
发送时间: Saturday, September 8, 2018 10:00:37 PM
收件人: CTCaer/hekate
抄送: Finbar; Author
主题: Re: [CTCaer/hekate] Can't launch the firmware (#105)


yeah. If that rawnand is ok, you'll be good.

Just try to restore boot0/1 only and check if it boots

―

**Comment by bnxflazy** [comment]
Okay, thanks anyway!


发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: Kostas Missos <notifications@github.com>
发送时间: Saturday, September 8, 2018 10:25:16 PM
收件人: CTCaer/hekate
抄送: Finbar; Author
主题: Re: [CTCaer/hekate] Can't launch the firmware (#105)


Sorry but I can't help you with that.
There are many support forums that can guide you.

―
