### ISSUE TITLE
what should I do if the choi boot0 didn't help

### ISSUE THREAD

**Issue by bnxflazy** [CTCaer/hekate#109]
please, just briefly tel me what should I do if I do not have back up of boot0 and I corrupted it , the choi didn't help as you said the size of that is only 1.5MB, right now I am clear that I only disrupted the boot0/1

**Comment by CTCaer** [comment]
First of all stop creating new issues, when existing one exists. Especially when that issue has nothing to do with hekate.

As I said, after that 1.5MB, are the keyblobs. These need to be restored
