### ISSUE TITLE
Error (4) while restoring

### ISSUE THREAD

**Issue by chxk** [CTCaer/hekate#110]
I have backup Boot 0/1 and Raw GPP in my exFAT TF card ,but it shows " Error (4) while opening backup....." .How can I solve this problem?

**Comment by chxk** [comment]
I made it when I change the version to 3.2 and change some locations of backup files.(backup is done by version 4.0)

**Comment by CTCaer** [comment]
Error 4 is `FR_NO_FILE /* (4) Could not find the file */`
You need to put the restore files into /backup/<emmc s/n>/restore/

You can create these folders by dumping sth, like fuses. Or manually by reading your emmc info.

**Comment by GiovanH** [comment]
Because this is marked as Informative, and I had the same issue, I wanted to note this:

Some tools dump boot0 and boot1 as boot0.bin and boot1.bin. **Hekate requires the file to be named BOOTX with no extension.**
