### ISSUE TITLE
hekate v4.1 release info

### ISSUE THREAD

**Issue by CTCaer** [CTCaer/hekate#111]
Just want to say that the release is ready weeks now.

It has full 6.0.0 support (hekate/atmo patches) and it will be released after making sure that the "leaked" 6.0.0 with revision 4.0 is indeed what it's going to be released officially.

Even if that's the case, don't update. Not until all new logging is RE'ed.

**Comment by CTCaer** [comment]
![image](https://user-images.githubusercontent.com/3665130/45726289-3660ce00-bbc7-11e8-9e48-dfaad62a67b7.png)

**Comment by mbarisa** [comment]
any ETA when you are going to release 4.1?

**Comment by mbarisa** [comment]
Great, thanks. :+1:

**Comment by IFireflyl** [comment]
Just to confirm, if I went completely stupid and updated to 6.0.0 last night I should still be able to homebrew the Switch once 4.1 is released sometime in the next few days? Or should I wait a while to make sure there aren't other issues that need to be addressed? Pretty much the only thing I want to do is backup my game saves. 😁

**Comment by CTCaer** [comment]
Well so I had time to check it. I'm disappointed with ninty..

**Comment by mbarisa** [comment]
Awesome, what is ninty?

**Comment by CTCaer** [comment]
nintendo

**Comment by CTCaer** [comment]
https://github.com/CTCaer/hekate/releases/tag/v4.1
