### ISSUE TITLE
Black screen on 6.0.0

### ISSUE THREAD

**Issue by mixon606** [CTCaer/hekate#112]
everything works besides the screen i show when i slide out the joy con

**Comment by CTCaer** [comment]
Where this happens?
Inside HOS?

**Comment by GhostlyCrowd** [comment]
Hmm i appear to have this as well as soon as it boots out of Hekate into latest layerd fs.  I get a black screen but the volume widget pops up and the power menu pops up if power held.

**Comment by mixon606** [comment]
yea when i posted this there wasn't SD files v9
