### ISSUE TITLE
AutoRCM proper shutdown method not optimal for people using PCs for payloads

### ISSUE THREAD

**Issue by noahc3** [CTCaer/hekate#114]
Hekate 4.1 introduced a feature where if the payload is launched after shutting down, instead of entering the menu, it will shutdown the switch properly. This is great for modchips (and dongles depending on who you ask) but not very helpful and even sometimes annoying for people who use a PC for payload launching. The main problem is many people only ever shutdown their Switch when they want to swap files on their SD. Having to push hekate twice to boot again after doing this is mildly annoying.

It isn't a huge issue, but having an option to disable this functionality in settings would be nice. Perhaps also including a message about what is actually happening on the image that displays would also be nice so people aren't confused.

**Comment by parkerlreed** [comment]
This actually explains a lot... It would show the hekate boot splash and then go dark. I was confused as to why this was happening. Now I know.

**Comment by CTCaer** [comment]
> Auto full power off when the device woke up from HOS' power off
Usefull with modchips/dongles when using AutoRCM. **(You can see it as a breathing backlight with hekate's logo)**

That's true though. I have a different workflow (the one below), so I didn't think a lot of it.

Until I add an option to disable it, for now do the following:
`When you power off from HOS, while having the jig, press VOL UP + PWR to enter rcm.`
`With autorcm, just PWR.`
This will register the buttons as a wake up reason and it will skip this.

**Comment by CTCaer** [comment]
https://github.com/CTCaer/hekate/commit/381d5c9236ed17270ddae4a2b181c165a2673d1e
