### ISSUE TITLE
sx os payload in 4.1 still broke

### ISSUE THREAD

**Issue by cryptolute** [CTCaer/hekate#115]
hekate 4.1 -> sxos loader shows the splash screen, then black. Console is 5.1 fw

With "Support payloads with broken/bad hw init..." I had assumed this meant a fix for sx os payload launching. Perhaps I misunderstood?

**Comment by CTCaer** [comment]
It did. Otherwise you couldn't see the splash.
Try to replace the boot.dat again.

**Comment by nitrozz** [comment]
the same problem 
i have last xsos version on root and payload.bin inside bootloader/payloads/
Booting with xecuter dongle run fine.

**Comment by cherup01** [comment]
Same issue here - anything you need which can be provided ?

**Comment by CTCaer** [comment]
https://github.com/CTCaer/hekate/commit/2f43b201241b9f596b2ea58220ebc79edc13ed58
