### ISSUE TITLE
Black screen after clicking CFW Hekate 4.1

### ISSUE THREAD

**Issue by zeq2mapper** [CTCaer/hekate#116]
I’m On 4.1.0. I inject the payload fine. The menu comes up fine. When I goto launch the CFW. It gives me writing and a black screen. Eventually booting normally. 

What and I doing wrong? Is it a bad SD a card?

**Comment by CTCaer** [comment]
You are in 6.0.0?

**Comment by zeq2mapper** [comment]
I’m on firmware 4.1.0

**Comment by CTCaer** [comment]
Oh wait a minute.
You said writing and a black screen.
Actually this is how it boots. Writing is what it currently does, and then it switches off the display and boots in HOS.

So where's the problem?

**Comment by zeq2mapper** [comment]
I don’t see any splash or anything. It just boots into regular mode. After a while it crashes and gives me this error 2162-0002

**Comment by zeq2mapper** [comment]
After booting. I went to Albums. And it loads Albums as normal. Why would this be happening??

**Comment by CTCaer** [comment]
That's a problem with your sd files. (modules/kips/etc)

Also the bootlogo is only shown in autoboot (except if you mean the nintendo/switch logo).

**Comment by zeq2mapper** [comment]
So maybe I need to extract the SDfiles again to my SD card? I’ll try that again then

**Comment by zeq2mapper** [comment]
The same thing happened again. It just loads OFW like normal. The Nintendo logo comes up then it quickly come off. It takes 3-5 seconds for the other sketch logo then it boots like normal. Then it crashes with that code I told you above. 

What could be causing that??

**Comment by zeq2mapper** [comment]
Do I need to just update to 6.0?

**Comment by CTCaer** [comment]
The files you are using are probably incompatible with 4.1.0.

**Comment by zeq2mapper** [comment]
The SD Files? How do I find the ones that are compatible?

**Comment by tumGER** [comment]
https://github.com/tumGER/SDFilesSwitch/issues/97

I'll stamp this as a user fault - This is the only case of crashing I have received yet

**Comment by CTCaer** [comment]
^
