### ISSUE TITLE
[Enhancement] Add option to autoboot payload

### ISSUE THREAD

**Issue by Rickardo987** [CTCaer/hekate#129]
Ok so, you can autoboot a selection from your hekate.ini, but not a payload... now I know what your about to say...

1. Payloads can be added to the hekate.ini as a launch option.
2. You are launching the hekate payload, just launch the payload you want instead of hekate.

Yes, yes those are good points, but it’s more of an enhancement thing. If your using a modchip and want to have hekate on there as a multi boot menu, but mostly want something like SXOS autobooted, this makes life easier for those who don’t know how to edit the ini.

Edit: I accidentally pressed enter when I barely had finished writing the title, sorry
Edit 2: Screw autocorrect

**Comment by lunalik2** [comment]
I'll try to implement this, then make PR. No promises though.

**Comment by matt-teix** [comment]
You can add the payload to the .ini and autoboot that way

**Comment by Rickardo987** [comment]
...Did you read the post?

**Comment by XiaoNiaoZZJ** [comment]
add
[EMUORG]
payload=bootloader/payloads/fusee-primary.bin
to your hekate_ipl.ini and set autoboot=<1based-index to this "EMUORG">
It works well.

its my hekate_ipl.ini
[config]
autoboot=1
autoboot_list=0
bootwait=3
backlight=100
autohosoff=0
autonogc=1
updater2p=1

[EMUORG]
payload=bootloader/payloads/fusee-primary.bin

[EMUDEF]
fss0=atmosphere/fusee-secondary.bin
kip1patch=nosigchk
emummcforce=1
atmosphere=1
icon=bootloader/res/icon_payload.bmp
logopath=bootloader/bootlogo.bmp

[STOCK]
emummc_force_disable=1
fss0=atmosphere/fusee-secondary.bin
stock=1

**Comment by masagrator** [comment]
Helping with 1.5 year old issue. Nice. :P

**Comment by CTCaer** [comment]
I wonder why I never closed that.. hmm
