### ISSUE TITLE
Fix sleep mode for 3.X.X

### ISSUE THREAD

**Issue by CTCaer** [CTCaer/hekate#13]

**Comment by michaelshiel** [comment]
Any ideas on this? 

I've looked at the original diff for sleep support, and it seems like everything is in place for these versions. 

Could the warmboot_base be wrong? I'm guessing if the patchset was wrong for these versions it wouldn't boot at all?

**Comment by CTCaer** [comment]
Yeah. Also last time I checked, the address was correct.

Yes, it would hang at boot.
I don't have time currently to work on this. If I want to try some things, are you available (what version you have)?

**Comment by michaelshiel** [comment]
I am definitely available to test stuff. My console is on 3.0.1, and I'm very interested in the sleep support so I can keep my fuses the way they are.

I've got a fair bit of embedded ARM C experience (STM32, not Tegra) as well, so if you don't have time for the code but you know conceptually what needs changing/doing I can help out with that also.

**Comment by vgmoose** [comment]
I have a 3.0.0 console and am also interested in this and can do some testing.

**Comment by CTCaer** [comment]
The more the merrier.

@michaelshiel 
You can start by REing your nxbootloader. There's the most important stuff for lp0 power state.

**Comment by CTCaer** [comment]
@michaelshiel @vgmoose 
Anyone available please contact me via email. (Comms via discord is preferable.)

**Comment by cspencer49519** [comment]
I'm also on 3.0.0 and can test.

**Comment by CTCaer** [comment]
Email me

**Comment by CTCaer** [comment]
Fixed internally.

Will be released when some other changes are ready.

**Comment by CTCaer** [comment]
Are you sure about cross-matching/checking everything in dissasembly?
The current behavior matches Nvidia's behavior on coreboot.
https://github.com/MrChromebox/coreboot/blob/master/src/soc/nvidia/tegra210/sdram_lp0.c

**Comment by michaelshiel** [comment]
Yeah my mistake, I was interpreting the offsets incorrectly.

**Comment by tumGER** [comment]
I think you can close this @CTCaer - Nice work btw :D

**Comment by CTCaer** [comment]
https://github.com/CTCaer/hekate/commit/7af531de77b5f0e5b23843e16f520078d6351d93

@tumGER 
Thanks ^^
