### ISSUE TITLE
kip1patch=nosigchk not applying on Atmosphere 0.7.1

### ISSUE THREAD

**Issue by awkimball** [CTCaer/hekate#132]
With the recent release of Atmosphere 0.7(.1) moving to a bundled payload .bin it appears as though kip1patch=nosigchk isn't being applied anymore.

 I am assuming this is because hekate now loads Atmosphere's own loader, which likely loads the kips after hekate has attempted to apply the kip1patch=nosigchk but this is pure speculation.

I understand that hekate's method of patching is different from Atmosphere's IPS file patching, however, would the quickest way to implement this patch be to apply it using Atmosphere IPS patching?

Best regards,
Addison

**Comment by awkimball** [comment]
If Atmosphere supports kip patching from SD card however, wouldn't it be preferable to not have to modify the Atmosphere files themselves, not to mention the ability to boot without the patch applied is eliminated unless you have both a patched and unpatched version of the kip on your SD card.

**Comment by awkimball** [comment]
Regardless of a quick fix for the issue I am also curious about how hekate's current functionality, i.e the ability to specify a patch in .ini and have it applied even to a payload .bin and not just individual kips, will be maintained. 

Is it even possible now that some of the loading work appears to have been manually implemented by the Atmosphere team?

**Comment by awkimball** [comment]
Also I suppose I should ask because it is related to this issue, what is the proper way to load atmosphere now that it is bundled into a payload?

Current I am loading fusee-primary.bin which in turn uses BCT.ini to find fusee-secondary.bin, as well as identifies the offsets for kip location inside the payload .bin. It would seem that this is currently the only way other than manually extracting the kips from fusee-secondary.bin, because BCT.ini is what defines the kip file offsets.

**Comment by CTCaer** [comment]
This is the intended behavior for payloads. You can't patch them on the fly.
Also BCT.ini does not have the kip offsets. If it did, I could create a loader that takes fussee secondary and parse its kips.

The kips exist though when you compile atmosphere. Builds will start showing up anyway.

In the future I may add a search function that searches secondary for the relevant kips and load them. We'll see.

**Comment by awkimball** [comment]
So you recommend that I use the new atmosphere, but use a compiled build that includes the kips and just list them in hekate_ipl.ini as opposed to loading fusee-primary.bin?

**Comment by awkimball** [comment]
Testing with:

`kip1=test/*
atmosphere=1  
kip1patch=nosigchk` 

using the kip files loader, sm, and pm from Atmosphere 0.7.1 results in a successful boot, however nosigchk is still not applied, plus homebrew menu doesn't work either.

**Comment by awkimball** [comment]
WHOOPS turns out my sd card was just corrupted and I used the archival bit tool and voila problem solved. Sorry about this!

**Comment by CTCaer** [comment]
if the archive bit was the problem, it's not corrupt.

Just nintendo being nintendo..
