### ISSUE TITLE
Wildcards should not load files starting with `.`

### ISSUE THREAD

**Issue by jakibaki** [CTCaer/hekate#133]
MacOS likes to place files starting with `._` and ending the same way as the original files in folders which results in hekate trying to load them.

This causes issues like this one: https://github.com/tumGER/SDFilesSwitch/issues/132

I would submit this as a pr but forking on github seems to be broken for me right now for some reason.

**Comment by StevenMattera** [comment]
I may have a fix for this, but currently at work and can't test it. I had a similar check in Switchblade for the splash screen folder. https://github.com/StevenMattera/hekate

**Comment by jakibaki** [comment]
I guess this should be closed now that 14cdcc1497b3108b420f6b57e449452d9ec60092 got merged
