### ISSUE TITLE
Joiner scripts are inefficient

### ISSUE THREAD

**Issue by CodingKoopa** [CTCaer/hekate#136]
The Linux/Mac OSX batch script included in [this](https://github.com/CTCaer/hekate/releases/tag/v4.2) release, for combining 15 2GB parts currently does the following:
```sh
cat rawnand.bin.00 rawnand.bin.01 rawnand.bin.02 rawnand.bin.03 rawnand.bin.04 rawnand.bin.05 rawnand.bin.06 rawnand.bin.07 rawnand.bin.08 rawnand.bin.09 rawnand.bin.10 rawnand.bin.11 rawnand.bin.12 rawnand.bin.13 rawnand.bin.14 > rawnand.bin
```
Code-wise, this is a silly thing to do, when Unix offers wild cards. A better way of doing this (mentioned [here](https://wiki.dolphin-emu.org/index.php?title=Ripping_Games#Joining_Split_Files)) would be to combine both of the scripts, for something like this:
```sh
cat rawnand.bin.?? > rawnand.bin
```
The Windows batch script does the same thing, I'm not familiar with how BAT file globbing works though. Apologies for the somewhat pedantic issue, I would submit a PR but these scripts don't seem to be stored in the repo.

**Comment by CTCaer** [comment]
https://github.com/CTCaer/hekate/issues/54

It's for redundancy.
