### ISSUE TITLE
Dump BIS keys to SD

### ISSUE THREAD

**Issue by ThatNerdyPikachu** [CTCaer/hekate#137]

**Comment by fennectech** [comment]
I would kill for this!  Default ability to mount usb from hekate would be badass!

**Comment by noirscape** [comment]
That would be awesome to have :+1: .

**Comment by Endar-Marit** [comment]
biskeydump.bin is now on version 7 and dumps to sd card

**Comment by CTCaer** [comment]
I'll close this issue as a better payload exists that does the whole job:
https://github.com/shchmue/Lockpick_RCM

As for memloader, there's still an issue about file transfer.
https://github.com/CTCaer/hekate/issues/58
