### ISSUE TITLE
Printing TSEC keys throws error

### ISSUE THREAD

**Issue by agentcatcat** [CTCaer/hekate#143]
trying to print the TSEC keys gives me this error:
```
Could not identify package1 version 
to read TSEC firmware <= '20180802162753'>.
```
any idea what is happening here, or how to fix it?

**Comment by CTCaer** [comment]
hekate version?

**Comment by agentcatcat** [comment]
4.2

**Comment by CTCaer** [comment]
hmm looks like your BOOT0 is corrupt.
You can boot in HOS?

**Comment by agentcatcat** [comment]
yes

**Comment by EternityShack** [comment]
What do you mean you think you can?

**Comment by agentcatcat** [comment]
i hadnt checked properly after i got the error, now i have
yes i can boot into HOS

**Comment by CTCaer** [comment]
That's the 6.0.0-6.1.0 pkg1.1 version.

Which is already supported since v4.1.
So dunno where's the problem..

(it works on 6.x.x)

**Comment by Endar-Marit** [comment]
I'm getting a similar error with 6.2 when trying to dump the tsec keys 

 `Unknown package1 version for reading TSEC firmware (= '20181100705733'). `

Everything else can be dumped bar the tsec keys and package 1/2

**Comment by CTCaer** [comment]
6.2 is not supported yet.
The crypto moved to tsec fw which is encrypted with keys residing in TSEC co-processor.

The new tsec fw needs a specific sanitized environment to work. Basically it checks everything.

**Comment by CanadianHummus** [comment]
I am on 8.0.0 using Hekate V2.5 and when I try to print my keys I get 

"Found pkg1 <'################'>

Uknown pkg1 version for reading TSEC firmware"

**Comment by ELY3M** [comment]
You need to update your hekate to 4.10.1

**Comment by flippnswithez** [comment]
i am on 8.1 using hekate 4.10.1 and get the same error
