### ISSUE TITLE
[Feature request]. Boot into safe mode

### ISSUE THREAD

**Issue by fennectech** [CTCaer/hekate#145]
I would love a option to boot into that Nintendo recovery menu.   I have found you need to disable autorcm and even then the key combo timing is irritating.

**Comment by CTCaer** [comment]
You don't need to disable autorcm.
Just power off from hekate and use the RCM key combo to enter normal RCM and then do the safe mode combo after launching your fw.

Also that decider code resides in secmon, so it falls out of the scope of a bootloader.
You can use a custom exosphere that has an easier combo, if you want.
