### ISSUE TITLE
sleep mode can't wake up

### ISSUE THREAD

**Issue by ds3x1216** [CTCaer/hekate#146]
Describe the bug
sleep mode can't wake up

To Reproduce
add debugmode=1 and fullsvcperm=1 in hekate_ipl.ini

Inject by hekate4.2

Expected behavior
sleep mode can't wake up

Version (please complete the following information):
Kosmos v11.0.1 & Kosmos v11 & SDFiles v10.1.1
CFW
OS 6.1.0

**Comment by CTCaer** [comment]
https://github.com/CTCaer/hekate/issues/119

debug mode breaks sleep mode on 6.x.x by never calling smcCpuSuspend
It's also a duplicate
