### ISSUE TITLE
Red screen after the splash creen

### ISSUE THREAD

**Issue by Dxnielo** [CTCaer/hekate#159]
As of version 4.5 of hekate, I booted it in rcm mode, got the splash screen, and got a red screen on my switch. Can anyone tell me how to fix it ?

**Comment by CTCaer** [comment]
Red screen?
Any specific? What CFW was used?
What secure monitor was used? ninty's secmon or exosphere?
etc..

**Comment by Dxnielo** [comment]
I'm really sorry, I don't know any specifics, except that I injected the payload with tegrarcmgui

**Comment by Dxnielo** [comment]
I fixed it, I just had to redownload the payload, it was corrupted somehow, thanks for the help, none the less.
