### ISSUE TITLE
After update in 4.5 Auto HOS not working

### ISSUE THREAD

**Issue by nExNihilo** [CTCaer/hekate#160]
Hello,
This is my stuff: 

Switch in 6.2 fw
Using a modchip
Reinx 2.0
AutoRCM

After the update of hekate, the auto HOS not works properly... I check the .ini file, it's enable with parameter 1 (with logo)
My switch goes to 0% of battery because of that :(

After some manipulations to get battery back, I roll back the update.bin to the hekate 4.2 and now everything works fine...

Maybe I did something wrong ?
Thanks :) and greatjob btw

**Comment by CTCaer** [comment]
What file you inject for using Auto HOS power off?

**Comment by nExNihilo** [comment]
Mmh I took the hekate-4.5.bin file into the zip , rename it on "update.bin" and drag and drog into "bootloader"

**Comment by CTCaer** [comment]
And then what payload you used for injecting? (with tegrasmash or shofel2 or fusee gelee)

**Comment by nExNihilo** [comment]
Mmmh I didn't change the UF2 file inside my modchip

But when I push the minus button, I see the hekate interface 4.5

**Comment by CTCaer** [comment]
Just tested this with 4.1, 4.2 and 4.5 in the modchip and 4.5 as as update.bin in sd and it works.

How you are trying to trigger this? also what you see? It just boots or enters the menu?

**Comment by nExNihilo** [comment]
Mmh strange, I'll try again so ..

When I power off my switch, didn't see the "IPL HEKATE" , staying with a black screen, and can't power ON again ...
I have to eject the SD, push 12 sec the power button, power ON on HEKATE, insert the sd, and then , boot on reinx

**Comment by nExNihilo** [comment]
Still doesn't work for me...
I do it again : 
- Download hekate_ctcaer_4.5.bin
- Rename it on update.bin
- Replace the update.bin in the bootloader folder from my sd card
- The first time I boot after the update, I can go on the hekate menu by holding the minus button
- I boot on Reinx
- I power off the switch (or reboot, did the same thing)
- After that, I don't see the "IPL HEKATE" 

The switch is in a bug state ... I have to eject sd , pussh 12 sec etc etc etc

**Comment by CTCaer** [comment]
Fixed with https://github.com/CTCaer/hekate/commit/98d715243a3d806a25ca06c1260d9ea1f7c62d83

**Comment by CTCaer** [comment]
**This is a breaking change.**
That means that your dongle/modchip must be updated with **the release that will include that fix**.

**Comment by nExNihilo** [comment]
Thanks, after updating my uf2 file, everything is okay !
