### ISSUE TITLE
Cannot launch payload from 128GB XC but can from 32GB HC on 4.1

### ISSUE THREAD

**Issue by twilightsembrace** [CTCaer/hekate#161]
Hello all.

I have a stock 4.1 without the XC-compatibility update, that has never been modded using any method.

Using a SanDisk 128GB XC, l spent hours trying many different combinations of Hekate and Atmosphere versions to get into CFW in order to use ChoiDuJour to update the OFW, but no such luck. The Switch kept black screening, and after 2 minutes landing on a Nintendo error screen. This happened both when pushing Atmosphere and ReiNX from Hekate 4.5.

Upon switching to an ADATA 32GB HC, the process went smoothly without a hitch.

Now, from everything I read from Raj's posts this is not intended behavior? Hekate is supposed to be able to push the CFW from a XC micro into an unpatched system, especially so that the user can safely push the update via Choi while staying offline, isn't it?

Just wanted to leave this case here in case you find it is unintended behavior.

**Comment by ValliantStorme** [comment]
If your SD card is formatted exfat, but your Switch doesn't have Nintendo's exfat_fs, the Switch can't read the SD card under horizon and Atmosphere will crash. Since it works on the 32GB card, I assume that's the case.

You can most likely fix this by formatting the uSDXC as fat32 (on Windows this can be done with tools like [guiformat](http://www.ridgecrop.demon.co.uk/index.htm?guiformat.htm) on Windows, [gparted](https://gparted.org/download.php) on Linux, or Disk Utility on macOS (although you'll run into unrelated issues on macOS due to the way it uses the archive bit on folders.)

**Comment by twilightsembrace** [comment]
I updated to 4.1 exFAT version using Choi on the 32GB FAT32 card, and now it's launching the 128GB exFAT just fine. Just thought maybe Hekate could just go right through the requirement as it could hold the modules required for exFAT? Oh well, dunno Switch architecture enough to say.

**Comment by twilightsembrace** [comment]
What is it like to operate under FAT32 in this case? Can the firmware/tinfoil manage installing huge games like Diablo III to the SD?

**Comment by ValliantStorme** [comment]
You have to split files larger than 4GiB (4294967296 bytes) into pieces 4GiB or smaller, which can be done with a handful of tools, put them all in a folder, and then set the archive bit on that folder.

**Comment by ObscenityIB** [comment]
@ValliantStorme well, more than that.

**FAT32**:
Max Volume: 2TB
Max Files in Total: 268,173,300
Max Filename length:  8 name chars 3 extention chars, without LFN
Maximum Date: 2099-12-31
Compression: No
Encryption: No
**exFAT**:
Max Volume: 512TB
Max Files per Directory: 2,796,202
Max Filename length: 255 UTF16 chars
Maximum Date: 2107-12-31
Compression: No
Encryption: No

**Comment by ObscenityIB** [comment]
@twilightsembrace its is solved, format the big card as FAT32 with a 32k cluster size, thats your solution.
