### ISSUE TITLE
Add other navigation buttons

### ISSUE THREAD

**Issue by murad-d12** [CTCaer/hekate#163]
My volume “+” & “-“ are not working so i cant navigate through the menu.
It would be great to have another option beside the “power”, “-“, and “+” to navigate.

Thanks for the awesome work!

**Comment by danastyone** [comment]
why cant we get touch working ? , I would have thought touch would have been the next thing we got.

**Comment by CTCaer** [comment]
We have it working. It will just need to wait a bit to be proper.
