### ISSUE TITLE
Red Screen

### ISSUE THREAD

**Issue by Aeci** [CTCaer/hekate#167]
So I was using Hekate, I got a red screen on my switch. None of the buttons worked so I plugged it in to my pc to try and rerun the payload but it caused my computer to crash and now neither one is working what do I do?

**Comment by Aeci** [comment]
Update: My PC is working now it just needed some time, but my switch screen is still red

**Comment by CTCaer** [comment]
Red screen means you run exosphere.
Did you include `atmosphere=1` key?

**Comment by Aeci** [comment]
I'm not sure

**Comment by Aeci** [comment]
in my ini folder, I have FTP_Server and sys-netcheat

**Comment by CTCaer** [comment]
It's better to redownload the CFW package you used and clean the folders except Nintendo and switch folders.
Or converse with whom released that in order to get help.

Normally a red screen is what I said. A key missing from the ini or some other needed file.

**Comment by Aeci** [comment]
Do you know how to reboot my switch because its been on this red screen for hours

**Comment by CTCaer** [comment]
Press the Power button for 12 seconds.

**Comment by Aeci** [comment]
Alright thank you

**Comment by pdalfarr** [comment]
Hi.

Thanks a lot for your great work!

On my side: Hekate 4.6 working fine on my Switch.
Have a Red screen with 4.8, 4.9 & 4.9.1
I recreated my SDCard from here https://www.sdsetup.com/console?switch (Atmosphere Kosmos default + 1 option which is Tinfoil)

How can I investigate the problem?

Thanks

**Comment by pdalfarr** [comment]
Probably an SD card issue. I am now on FAT32 (before EXFAT) and ReINX. working fine.
