### ISSUE TITLE
Some way to globally apply patches to all configs

### ISSUE THREAD

**Issue by noahc3** [CTCaer/hekate#171]
For example, for people who use nogc, there is no situation where they wouldn't want that patch enabled, and it would suck if they forgot to add it to a new config. 

Being able to do this from another file would be nice as well, to further reduce chances for screw ups.

**Comment by CTCaer** [comment]
Hmm now that fuses doesn't matter I can't make it automated and also have force disabled.

So maybe a global option with Enable/Disable is better.
And default from set_default_config set to Disabled. It's on user to care for that anyway.

I'll check the available options and decide.

**Comment by CTCaer** [comment]
https://github.com/CTCaer/hekate/commit/de830df7e7781192db4d5bf22530a922e5e2cdd8
