### ISSUE TITLE
Dumping Fuse-List  and TSEC Keys from EmuNand

### ISSUE THREAD

**Issue by spacerat1** [CTCaer/hekate#173]
Hello. 
Is there a possibility to dump the Fuse-List and TSEC Keys from Emunand? I have HOS @6.1 and (SX) Emunand @6.2.

Dumping the keys with lockpick result in some missing keys (for example master_key_06)
So i guess the dumped files (TSEC and Fuse-List) are from the Sysnand.

Is it possible to add support for Emunand, so you can choose the source? 

Thx in advance.
(and sorry for my bad english)

**Comment by ThatNerdyPikachu** [comment]
We're not going to support a closrd-source, botched, emuNAND implementation.

**Comment by CTCaer** [comment]
How I didn't see that issue..

Ask help from your cfw provider.

This is not an issue with hekate.
