### ISSUE TITLE
Get stuck at "Cannot Identify Package One" when trying to boot cfw on 6.2.0

### ISSUE THREAD

**Issue by therf311** [CTCaer/hekate#176]
If you need the numbers after "cannot identify package 1" i can post them. Never booted up a cfw before trying to get it running for the first time.

**Comment by CTCaer** [comment]
Please use the latest version: v4.6

**Comment by therf311** [comment]
I am.

**Comment by CTCaer** [comment]
what's the pkg1 version?

**Comment by therf311** [comment]
Sorry, what is that? Kind of a newbie here.

**Comment by CTCaer** [comment]
The number after that message.

Btw the message "cannot identify package 1" does not exist in hekate. So what are you using?

**Comment by CTCaer** [comment]
You use v3.2 and not the latest.
That message was change in v4.0 and it's now 
```
Unknown pkg1,
Version (= '20181107105733').
```

please inject the newest. 
https://github.com/CTCaer/hekate/releases/download/v4.6/hekate_ctcaer_4.6.zip

**Comment by therf311** [comment]
So I injected the 4.6 version, and when I select the "Load Firmware" option, it displays "Failed to load /hekate_ipl.ini/. "Using default launch configuration." "Could not identify package 1 version <= /20181107105733/>."

**Comment by CTCaer** [comment]
Hmm, load firmware? v3.2
What does it say above the menu?

Also how you inject the payload?

**Comment by therf311** [comment]
Above the menu it say hekate - ipi.
I use Tegra Rcm GUI to inject it.
Am I using the wrong payload? Is that it?

**Comment by CTCaer** [comment]
That payload is even older than v3.2.
You need to add it in the list of that GUI and select it to inject it. Currently you launch an older version

**Comment by therf311** [comment]
Where can I get the newer version?

**Comment by CTCaer** [comment]
https://github.com/CTCaer/hekate/releases/download/v4.6/hekate_ctcaer_4.6.zip

**Comment by therf311** [comment]
Which file do I inject?

**Comment by CTCaer** [comment]
hekate_ctcaer_4.6.bin

**Comment by CTCaer** [comment]
and the bootloader folder you copy it inside your sd card

**Comment by therf311** [comment]
Thanks a lot. Worked like a charm.
