### ISSUE TITLE
7.0.0

### ISSUE THREAD

**Issue by aveao** [CTCaer/hekate#180]
Are you aware that 7.0 breaks this? I want you to try your best to add 7.0 support. I was foolish enough to update. I was like "Oh, it's just another update."

[*insert shrek*](https://github.com/CTCaer/hekate/issues/147)

**Comment by CTCaer** [comment]
![image](https://user-images.githubusercontent.com/3665130/51919839-ee5f7c80-23ec-11e9-80d4-1e6f8ff492e3.png)

**Comment by aveao** [comment]
Not to mention, the update also blows a fuse so no downgrading. :(

**Comment by ZachyCatGames** [comment]
@nfitzen 
This was a joke lol.

**Comment by aveao** [comment]
@nfitzen see #147, and uh, I'm already in RS.

**Comment by m4xw** [comment]
This is a Issue tracker, not a meme or small-talk tracker.
