### ISSUE TITLE
7.0.0

### ISSUE THREAD

**Issue by christianhacksnothin** [CTCaer/hekate#181]
when is this going to be fixed if u know anything thank you

**Comment by simontime** [comment]
Username checks out

**Comment by ZachyCatGames** [comment]
It’ll be fixed either Soon(tm) or on June 15th /s

Ok but seriously, 7.0.0 support will be added when its ready probably within the next 1-4 weeks

**Comment by christianhacksnothin** [comment]
k thx

**Comment by ThatNerdyPikachu** [comment]
🥖

**Comment by CTCaer** [comment]
https://github.com/CTCaer/hekate/releases/tag/v4.8
