### ISSUE TITLE
SD Card and eMMC data (@lba 034ED000), do not match

### ISSUE THREAD

**Issue by Real96** [CTCaer/hekate#185]
I'm trying to make Backup eMMC RAW GPP but it gave me this error:

```
SD card and eMMC data (@LBA 034ED000), do not match!

Verification failed...

Press any key and try again...

Time taken: 233m 43s.

```
I've got a 64GB Kingston SD FAT32 formatted and it's new, It stopped at the 90%

**Comment by balika011** [comment]
Kingston cards known to be a lower quality. You have to retry the process. I never faced the same issue using Samsung evo cards.

**Comment by Real96** [comment]
Going to try with another card and let you know what happens

**Comment by CTCaer** [comment]
Take a readable photo of `Console info -> Print Sd card info`
and up it here

**Comment by Real96** [comment]
Unfortunately i've got only Kingston 16GB SD cards, so i would like first to know if the problem can be solved before i spend money on a new SD card....Here the screen you asked:
https://imgur.com/JthbY9s

**Comment by Real96** [comment]
If needed i've also got the screen of the error, but i wrote everything in the issue

**Comment by CTCaer** [comment]
Your card is fake :/

If you want to do the backup now, artificially limit it.
Using a partition manager, get it to 16GB.
(24 because it fails at 26GB, but it may have a good faking algorithm and just overwrites other stuff.)

The thing is that your kingston 16GB, if it's real, it will be better and faster than this fake one.

**Comment by Real96** [comment]
Is there a way to check if my cards are fake or not using this screen? How did you do?

**Comment by CTCaer** [comment]
I check CID (like this screen)
Some have crap faking, others very good.

And then format it and test with hw2testw or another fake card tool tester.

They basically write data and then they read it back and compare it bit by bit.

**Comment by Real96** [comment]
Dang i put the 64GB one near my 16GB card and it's so obvious that it is fake...you told me to limit to 16GB with a partition manager, do you mean the switch backup i made?

**Comment by Real96** [comment]
Sorry for late replay, in the end using an original 64GB SD card worked perfectly. Thanks a lot for your reply! You made a great job!
