### ISSUE TITLE
Function request | NS formatted backup installed game

### ISSUE THREAD

**Issue by love768952693** [CTCaer/hekate#186]
NS formatted backup installed game

Functional description：
NS needs to be formatted, and according to the NS rules, although the game has been selected to be installed in the SD card, but some game installation files are installed in the NS machine.

I don't want to format the machine and then reinstall the game. If there is such a tool, we can use it to upgrade the system or format the machine. Just backup the NS to install the game files and the corresponding archive.

I don't know if I have backed up the game tools that are installed on this machine.

**Comment by CTCaer** [comment]
Redownload them from eshop.
