### ISSUE TITLE
Hekate still auto-reboots into RCM when using STOCK

### ISSUE THREAD

**Issue by ThatNerdyPikachu** [CTCaer/hekate#189]
```ini
[config]
autoboot=1
bootwait=2
customlogo=1
verification=2
autohosoff=1
backlight=100

[Atmosphere]
atmosphere=1
kip1=cfw/*
kip1patch=nosigchk
secmon=cfw/exosphere.bin
warmboot=cfw/lp0fw.bin

[Stock]
atmosphere=1
secmon=cfw/exosphere.bin
warmboot=cfw/lp0fw.bin
```

Fresh clones of both Hekate and Atmosphere, no clue what to say...

**Comment by CTCaer** [comment]
update your update.bin and sept/payload with hekate4.8
And make sure lp0fw is correct

Also you are sure that is RCM?

**Comment by ThatNerdyPikachu** [comment]
I'm booting on 6.2.0 for now, to update to 7.2.0
and yes, my payload injector reinjects after hekate displays green Booting... text

**Comment by urherenow** [comment]
You’re using an auto-injector? Try turning that feature off.

**Comment by ThatNerdyPikachu** [comment]
No, I left my injector plugged in.
I just tried unplugging it, screen went black after Booting...
after that, I plugged it into my PC and was able to use fusee launcher.

definitely RCM

**Comment by ThatNerdyPikachu** [comment]
it works on AMS profile -- not on Stock tho
does Exo / lp0fw require AMS sysmodules?

**Comment by CTCaer** [comment]
```ini
[Stock 7.x.x]
secmon=path/to/exosphere.bin
warmboot=path/to/lp0fw.bin
atmosphere=1
```

**Comment by ThatNerdyPikachu** [comment]
i'm using a profile that is exactly the same -- see above ini

**Comment by CTCaer** [comment]
It should work then. Try to add a newline after `warmboot=cfw/lp0fw.bin`

**Comment by Rickardo987** [comment]
Is “semi-stock” safe enough to go online with? ~~BuT RiCkArD0!?, nOtHiNg Is 100% SaFe?!!?1~~ Not 100% safe but probably safe?

**Comment by ZachyCatGames** [comment]
> Is “semi-stock” safe enough to go online with? BuT RiCkArD0!?, nOtHiNg Is 100% SaFe?!!?1 Not 100% safe but probably safe?

I’ve been using atmosphere online every day since hekate got sleep support :P. I’m not banned. So just exo and lp0fw is probably also pretty safe

**Comment by CTCaer** [comment]
Nothing is 100% safe.
But `pretty safe`? Yeah.

**Comment by CTCaer** [comment]
@ThatNerdyPikachu so you fixed it?

**Comment by ThatNerdyPikachu** [comment]
@CTCaer haven't been able to test -- been sick for the past 3 days

will close

**Comment by CTCaer** [comment]
Then forget the testing, get well.
