### ISSUE TITLE
Cant boot on STOCK

### ISSUE THREAD

**Issue by renatosk** [CTCaer/hekate#192]
When i click  stock it just boot atmosphere instead, here is my config

[config]
autoboot=1
autoboot_list=0
bootwait=0
verification=2
backlight=100
autohosoff=0
autonogc=1

[Atmosphere CFW]
payload=bootloader/payloads/fusee-primary.bin

{---- Miscellaneous ---}

[Stock (7.0+)]
secmon=modules/required/exosphere.bin
warmboot=modules/required/lp0fw.bin
atmosphere=1

**Comment by CTCaer** [comment]
That's because sept/payload.bin is fusee instead of hekate.
I have a way to mitigate that though. So wait till next update.

**Comment by renatosk** [comment]
Changed the payload and it works fine, thanks!
