### ISSUE TITLE
How to turn off the information output of logo and initializing....

### ISSUE THREAD

**Issue by love768952693** [CTCaer/hekate#193]
Hello, developer. I want to know how to turn off logo output and initializing... information output.

I want to configure whether logo will never be displayed, and the information shown by initializing....

After selecting the custom menu, Nintendo information will appear and then enter the system.

**Comment by CTCaer** [comment]
I'm not sure I understand..
If you don't want to see logging, don't use Launch, and setup Auto Boot.
If you don't want to show auto boot logo, you can choose disable it from Options.

**Comment by love768952693** [comment]
First of all, thank you developers, the tools provided.

I want to disable this
![29a14ada942c414637c95391f5de681](https://user-images.githubusercontent.com/24494048/53643580-61b81080-3c6f-11e9-904c-added7fe7df3.jpg)
and this
![b7838c9d9a7cac6f657a2af0e14a7d8](https://user-images.githubusercontent.com/24494048/53643588-65e42e00-3c6f-11e9-8c3f-faff5926e1bc.jpg)

My current startup is started from Launch, so I can choose the space. After selecting the machine, the above two images will appear. I don't know how to stop them. I hope I can output the first loaded information, and the boot image. Direct Nintendo logo, just enter the machine.

**Comment by urherenow** [comment]
Github is not a support forum, and the sept splash screen has nothing to do with hekate. There will never be a way to disable it.

**Comment by CTCaer** [comment]
Sept logo for 7.x.x and up is here to stay for a specific reason.

As for the "Initializing.." use
`Options` -> `Auto boot` -> Choose the CFW taht you launch from `Launch`.
Then go to
`Options` -> `Boot time delay` -> `0 seconds (Bootlogo disabled)` to disable hekate's logo.

That way it will only show Sept logo and then nintendo.

**Comment by love768952693** [comment]
The number is 10,000.

Thank you

**Comment by CTCaer** [comment]
what number?

**Comment by love768952693** [comment]
The meaning of this number is that I said thank you N times.

**Comment by CTCaer** [comment]
Ah, you are welcome!
