### ISSUE TITLE
Selectively launch kips in fusee-secondary.bin

### ISSUE THREAD

**Issue by fennectech** [CTCaer/hekate#196]
I would like to see the ability to selectively launch kips contained in fusee-secondary.bin.  This would allow Kosmos to use fusee-secondary.bin instaid of compiling allowing users to update atmo in Kosmos themselves.

**Comment by CTCaer** [comment]
https://github.com/CTCaer/hekate/commit/f139f9c56f2e01dccc0e119eebc5f0cf3e8a729a

...
