### ISSUE TITLE
Switch nonResponsive 

### ISSUE THREAD

**Issue by JumpperCC** [CTCaer/hekate#199]
Hi.Ok i updated my switch using choidunjour to the latest fw 7.1 then i loaded up hetake to get to atmosphere so while in the hetake menu i turned off autorcm on purpose then back to the menu selected power off no my switch does not power on when i connect to the dock the tv light flashes for 1 sec

**Comment by CTCaer** [comment]
It stays on a black screen and no RCM?
Go into RCM and check autoRCM status again.
If it's off, that means that sth went wrong with your manual upgrade.

Also if you wanted to burn fuses, why you updated via choi?

**Comment by CTCaer** [comment]
I assume you found out what really happened.
