### ISSUE TITLE
Does this work on 5.1.0?

### ISSUE THREAD

**Issue by nanashi89** [CTCaer/hekate#2]
I wanna update to the latest FW, but I also wanna continue using the HBL.

Will this work on the latest FW?

**Comment by CTCaer** [comment]
Hekate works with 5.1.0.

The files in the atmosphere folder need an update though.

**Comment by aagallag** [comment]
[v2.3](https://github.com/CTCaer/hekate/releases/tag/v2.3) seems to work on FW 5.1.0.  You will just have to add an empty file in your atmosphere folder.  See this Tweet for more info: https://twitter.com/SciresM/status/1003515292037726210

**Comment by CTCaer** [comment]
This^
