### ISSUE TITLE
sd and emmc data <@LBA 00800000>, do not match

### ISSUE THREAD

**Issue by farukotakeru** [CTCaer/hekate#200]
When I try to perform a full eMMC NAND backup on my Switch it always gives me this error:

SD Card and eMMC data <@LBA 00800000>, do not match!
Verification failed..

Press any key and try again...

I am currently running on hekate 4.9 with my microSD formatted to exFAT. My Switch is currently on 7.0.1. My microSD is a 128GB Kingston.

**Comment by MichaelRebirth** [comment]
I got the same problem, tested with:
64gb sandisk extreme
256gb sandisk extreme
128gb sandisk ultra 
*all exFAT
2 switch unit, same error msg... (verify 1/2 all the same result)

**Comment by farukotakeru** [comment]
> When I try to perform a full eMMC NAND backup on my Switch it always gives me this error:
> 
> SD Card and eMMC data <@lba 00800000>, do not match!
> Verification failed..
> 
> Press any key and try again...
> 
> I am currently running on hekate 4.9 with my microSD formatted to exFAT. My Switch is currently on 7.0.1. My microSD is a 128GB SanDisk Ultra.

Below is the test results of H2testw
`Warning: Only 118911 of 118912 MByte tested.
Test finished without errors.
You can now delete the test files *.h2w or verify them again.
Writing speed: 13.4 MByte/s
Reading speed: 20.7 MByte/s
H2testw v1.4
`

**Comment by hlc1209** [comment]
Same here.
Samsung 128Gb

**Comment by bzennn** [comment]
Same problem. Tested with Samsung Evo 128 GB

**Comment by farukotakeru** [comment]
> When I try to perform a full eMMC NAND backup on my Switch it always gives me this error:
> 
> SD Card and eMMC data <@lba 00800000>, do not match!
> Verification failed..
> 
> Press any key and try again...
> 
> I am currently running on hekate 4.9 with my microSD formatted to exFAT. My Switch is currently on 7.0.1. My microSD is a 128GB Kingston.

Tried with Hekate 4.8 and it worked fine. Downgrading to Hekate 4.8 till this issue is fixed

**Comment by CTCaer** [comment]
Hmm at 4GB mark.
I'll check.

Btw you all stop at 0x**00800000**?

**Comment by farukotakeru** [comment]
> Hmm at 4GB mark.
> I'll check.
> 
> Btw you all stop at 0x**00800000**?

I did but I'm not sure about the rest.

> I got the same problem, tested with:
> 64gb sandisk extreme
> 256gb sandisk extreme
> 128gb sandisk ultra
> *all exFAT (original card) ams 0.8.5 & 7.0.1
> 2 switch unit, same error msg... (verify 1/2 all the same result)



> Same here.
> Samsung 128Gb



> Same problem. Tested with Samsung Evo 128 GB

Guys?

**Comment by CTCaer** [comment]
No problem I found the issue.
It's the classic 64bit problem.

Thank you all for reporting that.

**Comment by CTCaer** [comment]
Please test this:
[iplctc.zip](https://github.com/CTCaer/hekate/files/2948529/iplctc.zip)

Report back if it reached more than ~9%.

**Comment by farukotakeru** [comment]
> Please test this:
> [iplctc.zip](https://github.com/CTCaer/hekate/files/2948529/iplctc.zip)
> 
> Report back if it reached more than ~9% in verification (green bar).

This is the payload to be injected via Tegra?

**Comment by CTCaer** [comment]
Yeah. Locally I still name them iplctc.bin to distinguish them from officially released binaries.
It's hekate though.

**Comment by farukotakeru** [comment]
> Yeah. Locally I still name them iplctc.bin to distinguish them from officially released binaries.
> It's hekate though.

Ah okay, gonna run it now

**Comment by farukotakeru** [comment]
![IMG_20190310_000801](https://user-images.githubusercontent.com/22510897/54074024-afb0c200-42c8-11e9-9bf4-2a3c09f7703e.jpg)

Looks like it managed to get past 9%

**Comment by CTCaer** [comment]
Ok, I'll cook up a hotfix version

**Comment by CTCaer** [comment]
https://github.com/CTCaer/hekate/commit/61401d733e416c830b0ea9f23be87c1042afc758#diff-10557f14a06929c52a3feda4d5d68cecR90

**Comment by leonardobsjr** [comment]
Good lord, i was freaking out because i've tried 3 nand backups before checking the issues. Having the exact same problem: same address, same everything. @CTCaer it is safe to use Hekate 4.8 for the backup procedure or it's better to wait for the fix to be deployed?

**Comment by CTCaer** [comment]
ofc it's safe. don't wait for 4.9.1 if you need to do that now.
4.9.1 will come out after I made sure that the new stuff are good to go.
Don't wanna a 4.9.2

**Comment by jcklpe** [comment]
@CTCaer : I'm currently having this problem though the address for me is 0020000 instead of 0080000  
  
Any clues on what is the issue?

**Comment by mattdehat** [comment]
i have this problem also 
![158317444_436737717411529_852465615555882556_n](https://user-images.githubusercontent.com/45385749/110257304-2f93c480-7f95-11eb-82b3-7e826cf29d59.jpg)
![158283051_471409624026371_2724492537179665806_n](https://user-images.githubusercontent.com/45385749/110257306-302c5b00-7f95-11eb-99cd-0d918207ffa1.jpg)

**Comment by impeeza** [comment]
Check your card is almost sure a fake or damaged one. Use h2test

**Comment by mattdehat** [comment]
Many thanks for the quick reply. X2 corrupt cards. I really appreciate your time and knowledge. Many thanks again.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
