### ISSUE TITLE
no response when inject payload

### ISSUE THREAD

**Issue by kusoname** [CTCaer/hekate#202]
The TegraRcmGUI indicate that RCM O.K with green color.

hekate is not responding when I inject payload.

It's okay with using ReiNX payload.

and sx pro also okay.

But only hekate is not responding.

What should I do?

**Comment by kusoname** [comment]
format sd card several times
download hekate again and replace the bin file.
and it's okay.

**Comment by fennectech** [comment]
Test your sdcard with h2testw also.
