### ISSUE TITLE
Reboot to payload into chainloading memloader

### ISSUE THREAD

**Issue by ckurtz22** [CTCaer/hekate#203]
When I try to use the newish reboot-to-payload functionality of Atmosphere to reboot into hekate, and then launch memloader via chainloading with Hekate, it will run fine, but my computer won't mount the SD card. It works fine chainloading if I launched hekate through rcm though.

**Comment by fennectech** [comment]
This has something to do with sept i think. Ive seen people talking about sept breaking memloader.

**Comment by CTCaer** [comment]
It has to do with warmboot. So both sept and reboot to payload are affected.
There's no fix for now

**Comment by ckurtz22** [comment]
Yeah I'm not even using sept (haven't really touched my switch since before 7.0). 
Not that big a deal if it is not an easy fix, works well enough just unplugging my SD card in Hekate (when I have a card reader with me)

**Comment by CTCaer** [comment]
new Nyx has UMS built in
