### ISSUE TITLE
update past 4.0.0 without updating gamecart controller firmware

### ISSUE THREAD

**Issue by brnnnrsmssn** [CTCaer/hekate#204]
i am on OFW 3.0.0 and want to update to a newer firmware. i have set up to chainload/autoboot atmosphere-0.8.5 through hekate-4.9.1. i have ensured that nogc option is set to automatic.

after i update will i need to do anything special to ensure that the game cart controller firmware is not updated when i insert a gamecart?

**Comment by CTCaer** [comment]
Fyi, you can't use your gamecarts if nogc kicks in. (Which it will in your case.)
NOGC disables the updating by disabling usage of gc reader.

So you don't need to do anything else as long as this is set to auto.

**Comment by brnnnrsmssn** [comment]
thank you for the information.
