### ISSUE TITLE
Hekate 4.10 issues with some Sandisk U1 SD cards

### ISSUE THREAD

**Issue by crckmc** [CTCaer/hekate#210]
Since updating my switch to 8.0.0 and using Hekate 4.10 I'm unable to boot from my transcend SD card (128gb A1). 

With fusee primary it boots from the problematic SD card.
Another SD card also works with hetake. 

I have formatted and checked the card for errors about ten times so I dont think this is a hardware issue with my card.

Any way for me to debug?

Related posts on reddit:

-snip-

*Moderation: Don't post links to pirating forums*

**Comment by CTCaer** [comment]
https://github.com/CTCaer/hekate/commit/91606334c46a93f0d8cd8e94b01aab40412c73e6

> [sdmmc] Revert 204MHz sd device clock
> Again some Sandisk U1 cards do not behave at all at speeds like that (204MHz / 102MB/s).
> Revert back to 163.2MHz / 81.6MB/s.

This is a known issue and a hotfix release for these cards will be released today

**Comment by crckmc** [comment]
Thank you, I didnt look at the latest commits...

**Comment by CTCaer** [comment]
https://github.com/CTCaer/hekate/releases/tag/v4.10.1
