### ISSUE TITLE
Printing TSEC keys throws error

### ISSUE THREAD

**Issue by CanadianHummus** [CTCaer/hekate#212]
I am on 8.0.0 using Hekate V2.5 and when I try to print my keys I get

"Found pkg1 <'################'>

Uknown pkg1 version for reading TSEC firmware"

**Comment by james-d-elliott** [comment]
You need to use a later Hektate version for 8.0.0. Minimum supported is 4.10, though 4.10.1 is out and fixes an SD card issue.

**Comment by CanadianHummus** [comment]
close
