### ISSUE TITLE
Text size

### ISSUE THREAD

**Issue by pcwizard7** [CTCaer/hekate#214]
Is there a way to change the text size of the menu as very hard to read?

thanks

**Comment by CTCaer** [comment]
Nope. And it's as big as it can realistically get, while fitting most of the text.

I suppose you never experienced the struggle with the first versions and the 8px font.

**Comment by pcwizard7** [comment]
i ve been in the homebrew seen of the switch since day 1. and 3ds since fw v2.x

**Comment by pcwizard7** [comment]
i do remember a old version that had larger text

**Comment by CTCaer** [comment]
yeah that's intended because the 16px bar is slower to draw, for now.
