### ISSUE TITLE
No Main Configs found

### ISSUE THREAD

**Issue by SpongErsin** [CTCaer/hekate#219]
Whenever i try to boot up the switch through hekate it says that there are no main configs found.

**Comment by CTCaer** [comment]
You need to create a boot entry first in hekate_ipl.ini

What format this supports, can be seen from the example ones here:
https://github.com/CTCaer/hekate/blob/master/res/hekate_ipl_template.ini

Different ways, same thing.
Any CFW that has fss0 or kips, can be booted via hekate.
Or you can even chainload a CFW's bootloader (if you don't want to add its kips by hand), a tool or Linux.
