### ISSUE TITLE
Is this normal or my battery is desync

### ISSUE THREAD

**Issue by renatosk** [CTCaer/hekate#221]
so my switch died for the same reason as this issue #217  i let it charge again , booted horizon with 3% a let it do a full 100% , but after this i noticed something , theres a diference  between hekate and horizon , for exemple on horizon just changed to  93% while on hekate is showing 92.3% , i did what you recommended on the issue 217 , leting it die again and draining the remain on hekate , but again i booted and let it charge full 100% on horizon so maybe this is why it didnt sync ?

**Comment by CTCaer** [comment]
Percentages in hekate are not 100% correct.

It doesn't restore your battery calibration and uses the POR configuration. So the percentage will always differ with HOS.

**Comment by renatosk** [comment]
ok thanks
