### ISSUE TITLE
Trying to restore on fat32, Hekate errors out looking for "rawnand.bin.15"

### ISSUE THREAD

**Issue by vipertongn** [CTCaer/hekate#223]
I'm using the latest hekate, and was under the impression we can restore part files now.  I get the error that the ".15" file is missing, but I thought there was only suppose to be 15 files 00-14.  Currently seeing if joining the files and restoring on exfat will work

**Comment by CTCaer** [comment]
The restore process is automatic. That means that it doesn't care how the files are split.
It just checks file sizes and continues to search for new parts until the total of file sizes is == emmc size.

So check if your total matches that

**Comment by vipertongn** [comment]
thanks for the quick response!  You are right!
