### ISSUE TITLE
Update Hekate to support EmuMMC and Atmosphere 0.9.1

### ISSUE THREAD

**Issue by gr33k** [CTCaer/hekate#226]
Update Hekate to support EmuMMC and Atomsphere 0.9.1

This will also allow Kosmos to update their build :)

Checked https://github.com/CTCaer/hekate/issues/225 but did not seems to be the same (trying to avoid a dupe!).

Thank you CTCaer for all your hard work and contributions to the open source community!

**Comment by SwitchLover** [comment]
is this done yet or not

**Comment by nicoboss** [comment]
> is this done yet or not

They already have it working privately and according to m4xw it will be released "soon(TM)".
NYX might end up being the successor of hekate but that's just speculation: https://twitter.com/CTCaer/status/1143103754964819968

![Hekate_8 1_soon](https://user-images.githubusercontent.com/623410/60186592-6612c580-982c-11e9-9d5f-448990e70d10.PNG)

**Comment by CTCaer** [comment]
https://github.com/CTCaer/hekate/commit/bd7f572989de35d5ae7188ba967da56ca76fe7de
