### ISSUE TITLE
black screen

### ISSUE THREAD

**Issue by genio340** [CTCaer/hekate#227]
this happened to me while opening a hacked game, by mistake I selected download the update, the switch was connected to internet, so tried to download it, now I have tried with atmosphere 0.9.0, 0.8.9 and 0.7.6, I keep on getting the same: says welcome to atmosphere at the right of the screen, and then back screen. I have tried formatting the SD card, changing versions, etc. still have the problem.

**Comment by bmastergamer** [comment]
try atmosphere 0.9.1 https://github.com/Atmosphere-NX/Atmosphere/releases

**Comment by CTCaer** [comment]
Update hekate and atmo to latest. This is fixed there
