### ISSUE TITLE
Sometimes power OFF won't fully work.

### ISSUE THREAD

**Issue by GGLinnk** [CTCaer/hekate#23]
On hekate, when you go to power off, the screen turn powered off but the console itself isn't powered off until you press power button for 10-12secs.

**Comment by GGLinnk** [comment]
Temporaly closed, issue cannot be verified for now, awating for a 80% power charge to try it again with a charging switch.

**Comment by RenaKunisaki** [comment]
I've seen this too, but I'm not sure it's really an issue? I think, if you have AutoRCM enabled, then whenever the system is turned off but USB is plugged in, it will turn on and enter RCM.

Does it power off correctly if USB is not plugged in?

**Comment by CTCaer** [comment]
If USB is plugged in **or** not, it powers off.
If you leave it at your PC or phone though, it will wake up on shutdown (PC) or Sleep (phone).
