### ISSUE TITLE
Error thrown when trying to take screenshot while SD card removed

### ISSUE THREAD

**Issue by westonmyers** [CTCaer/hekate#230]
Present on v5.0.0:

When the SD card is removed from the device, Nyx waits for the SD card to be reinserted. During this time you are not prevented from taking a screenshot in this state. As of now, an error is thrown via a non-pretty way.

![IMG_20190630_010539](https://user-images.githubusercontent.com/3401094/60392614-a4caa900-9ad4-11e9-88ec-2f387f40416d.jpg)

**Comment by CTCaer** [comment]
I'll add touch lock when sd card is removed, to protect from that.

**Comment by CTCaer** [comment]
Screenshot is now disabled while this pop up is showing.
