### ISSUE TITLE
"Failed to find applicable partition!"

### ISSUE THREAD

**Issue by imPRAGMA** [CTCaer/hekate#233]
![screen_032EC6CA](https://user-images.githubusercontent.com/17136956/60392741-bc6c5680-9b01-11e9-8110-bfe092231285.png)

Just got 5.0.0 spinning up, I have a formatted factory reset nand, not even passed setup screen yet.
My SD card is fat32 formatted with guiformat.

**Comment by NickHam13** [comment]
Create a FAT32 partition that's 31 GB. Use the rest of the SD for CFW. I had this same problem and this is what fixed it.

**Comment by imPRAGMA** [comment]
Was this documented somewhere as instructions? 31gb sounds oddly specific no?

**Comment by NickHam13** [comment]
To be precise, it has to be just big enough to house your NAND backup. This isn't documented anywhere, it's just something I tried that worked. I would go with 31 GB to be safe but you can make it exactly as big as your backup.

**Comment by imPRAGMA** [comment]
If its just enough to hold nand, I guess it would be overall optimal to do 32gb, since that is the filesize of the nand storage size, if I had 21gb of that 32gb used, and made a backup, wouldnt I end up with a 21gb NAND backup, and if I create a partition of 21gb, id probably limit myself and result in errors.

**Comment by suppai** [comment]
NAND backups are 29.1GB in size. As long as your partition is above that, it's fine. Either way, this is not a hekate/Nyx issue and should be closed.

**Comment by NickHam13** [comment]
@suppai I agree, it should be closed now but how is this not relating to hekate and/or Nyx? He was getting an error in the payload and didn't know what was causing it, so naturally he assumed it was an issue.

**Comment by imPRAGMA** [comment]
It isnt really a bug, just it should have been a tad bit documented, I know v5 just came out, but it would have been ideal.

**Comment by igoticecream** [comment]
i had this issue and solved it by incresing the emummc partition to 31.30 gb, if you use a Mac:

```
sudo diskutil eraseDisk FAT32 HOMEBREW MBRFormat /dev/disk4
sudo diskutil splitPartition /dev/disk4s1 FAT32 HOMEBREW 165.56g FAT32 EMUMMC 31.30g
```

(200gb sdcard)

**Comment by CTCaer** [comment]
For now it expects a good sized primary partition (so unallocated space is a no also).
This will later change when support for resizing comes.

**Comment by imPRAGMA** [comment]
![image](https://user-images.githubusercontent.com/17136956/60401199-bfa12a00-9b75-11e9-9619-f5d349c1c75c.png)
This is my current SD card, yet it still gets the same error, am I missing something?

**Comment by imPRAGMA** [comment]
Wait so I need the emummc partition to be fat32 formatted (which will result in there being 2 drives, 2 different drive letters)?

**Comment by igoticecream** [comment]
Format both partitions as FAT32

**Comment by imPRAGMA** [comment]
Perfect, working nicely. And I decided to go for 32gb because it would just be more even, and just look a tad bit better, I probably wont gain anything from it though.

**Comment by CTCaer** [comment]
You don't need to format it. You just need to create a primary partition (raw - empty) in there. Unallocated is not yet supported.

**Comment by pOOBAH73** [comment]
It only worked when i formatted both partitions as FAT32 here. Leaving the second (emuMMC) partition allocated (EXT4) but unformatted didn't work. Might be a Windows thing, depending on the partition tool you use.

**Comment by Ericvf** [comment]
> It only worked when i formatted both partitions as FAT32 here. Leaving the second (emuMMC) partition allocated (EXT4) but unformatted didn't work. Might be a Windows thing, depending on the partition tool you use.

Thanks for sharing this. I can confirm this solved the same issue for me. The homebrew guide explicitly states that the partition should not be formatted but this seems wrong. Everything works now.

**Comment by CTCaer** [comment]
It depends on the partition tool or if you are in Linux.

Basically some tools or Linux still apply partition type to unformatted partitions as x83 (Linux partition).

The trick is to format them as Linux swap, which is x82 and bypasses the check.

On the other hand it's a big no to format them as fat. Currently I don't wipe the first sectors and so the partition seems intact and this can corrupt emummc if you write anything in there.
