### ISSUE TITLE
boot seemingly broken in 5.0.0

### ISSUE THREAD

**Issue by AlexS2412** [CTCaer/hekate#239]
no matter what i select, even with clean configs or configs that had worked in hekate 4.10.1 it will always boot hekate instead of cfw or ofw. it always boots to hekate after the sept logo or if you push the button to boot cfw.

**Comment by CTCaer** [comment]
hmm. no errors shown?
Cna you try to rename /bootloader/sys/nyx.bin and try to boot via TUI?

**Comment by AlexS2412** [comment]
sadly i somehow corrected it just by running kosmos updater, so i can no longer help with the issue.

**Comment by CTCaer** [comment]
probably a configuration issue.
I'll close the issue. If this shows up again, tell me. Maybe I'll need to add a check here or there
