### ISSUE TITLE
[Enhancement] Access to power options when SD card is removed (Nyx)

### ISSUE THREAD

**Issue by FusionFernia0000** [CTCaer/hekate#240]
Nyx GUI is locked until you put back in a SD card and let it reload.
While a cold shutdown is fine, having a shutdown option in the the software side feels more reliable.

**Comment by CTCaer** [comment]
I may add a button.

But this is designed like that especially for patched switches.

**Comment by CTCaer** [comment]
https://github.com/CTCaer/hekate/commit/205dab6cbdf8234945dbeec7c73a59e0739e8bb3
