### ISSUE TITLE
pkg1 not dumped

### ISSUE THREAD

**Issue by LittleStinky123** [CTCaer/hekate#242]
I updated to nyx with the kosmos sd setup and if I select to dump pkg 1/2 it dumps pkg2 like normal, but the pkg1 directory is missing even though there are no errors displayed in the log.

![screen_04F61E97](https://user-images.githubusercontent.com/36611440/60401538-3b55a380-9b83-11e9-9e4d-2a436c8de159.png)

**Comment by CTCaer** [comment]
With HOS v7.x.x and up, that file is encrypted. So not many things that you can do with it.

**Comment by LittleStinky123** [comment]
Sorry I didn't know that.
Does yuzu need it or can it be ignored, as the copy script references the pkg1 files.

**Comment by CTCaer** [comment]
Dunno what yuzu needs. But if they need it as is, then they need to change the script to be able to load stuff another way
