### ISSUE TITLE
[Enhancement] Add option to boot into the old hekate menu

### ISSUE THREAD

**Issue by NickHam13** [CTCaer/hekate#248]
I was just thinking this would be a cool addition for people who don't like the new UI.

**Comment by CTCaer** [comment]
If there are ppl that don't like the new UI, just delete /bootloader/sys/nyx.bin.

**Comment by NickHam13** [comment]
Huh. I thought hekate needed it to boot. I personally like the new UI but there are probably people who don't prefer jt.

**Comment by CTCaer** [comment]
it's not needed for booting. Hekate main handles the actual booting.
So yeah, it's as easy as deleting the file.
