### ISSUE TITLE
Package Backup Loop

### ISSUE THREAD

**Issue by AykoPredator** [CTCaer/hekate#249]
whenever i try to launch atmosphere without using hekate it always backs up the package and sends me to hekate and even if i delete the bootloader folder and try to load atmosphere it re makes the bootloader is there a way to load atmosphere without it downloading the backup

**Comment by CTCaer** [comment]
remove /sept/payload.bin.
If you want to use both, keep your main payload there. Hekate knows what to do about it if you want to boot via hekate.
