### ISSUE TITLE
Fix SD Files Attributes renders games installed on SD card unable to boot.

### ISSUE THREAD

**Issue by austin5623** [CTCaer/hekate#25]
I used the Fix SD Files Attributes option in tools and when I attempted to run a game that was installed on my SD card (including carts) it would crash immediately after opening. When attempting to reinstall the games, I got error 2005-0004 which is an SD card error. Only way to fix it was to format my SD card on the Switch.

**Comment by CTCaer** [comment]
@austin5623 
I reopened an previous issue please continue the discussion there:
https://github.com/CTCaer/hekate/issues/15
