### ISSUE TITLE
allow emummc to use full partition size

### ISSUE THREAD

**Issue by raidwastwo** [CTCaer/hekate#253]
As seen [here](http://pascoe.pw/2018/09/switchnand.html) it is possible to replace the emmc with a bigger one. It would be nice if there would be a (simpler) way for achieving the same but with emummc. 
For example I would like to partition my SD card into a 50GB partition for hos and use the rest (more than 32GB) as emummc for the cfw.

**Comment by CTCaer** [comment]
Same as #256

**Comment by CTCaer** [comment]
I'll keep the other issue, as I mentioned there about it.
