### ISSUE TITLE
explore sd card 

### ISSUE THREAD

**Issue by ImanCol** [CTCaer/hekate#254]
I would like to have the possibility that in Hekate + Nyx there would be a file manager. I do not say it for pleasure, or for suggesting it, but because I wanted to eliminate (or modify) the CFW configuration files related to the KIP load, this is because when I activated a KIP In Kosmos ToolBox (Use Kosmos .. .) when starting the CFW I get an error. Well I would like to use it only in case of emergency like when you delete a custom Theme and you do not want to start the Nintendo Switch, so to remove the Title that causes the problem from Hekate + Nyx would save me a lot of loading MemLoader + SDCard Command or extracting the SDCard.

**Comment by CTCaer** [comment]
It was planned initially. Got scraped for emuMMC manage. It will come eventually. I still have the code at side.

**Comment by CTCaer** [comment]
There's code here that can be possibly used for that
https://github.com/CTCaer/hekate/pull/317/commits/b91e48c999ab8211fb19c14d5067907b543e2733#diff-a15cc7dd475cd046b56bea55bd82bc58

**Comment by juju35** [comment]
This is feature is still planned or not ?

**Comment by impeeza** [comment]
It's planned. By now you can use the UMS tool on NYX and connect the switch as a USB stick on your computer

**Comment by Visualwit** [comment]
An eMMC/emuMMC explorer would also be great!

**Comment by ImanCol** [comment]
This was not implemented, but there are alternatives
