### ISSUE TITLE
Progress goes back and forth during restore

### ISSUE THREAD

**Issue by alessbelli** [CTCaer/hekate#255]
During restore for full gpt with n part files, the progress bar will repeat each (100/n)th part of the progress. Very minor but confusing, I guess when running verification on a part file, the progress will reset. Would probably be better to either make progress bar fixed during verification or have those be part of the progress status. Some UI status update alongside the filename could also help with the initial confusion.

**Comment by CTCaer** [comment]
It was always like that. When verification is on, Green is verification and white is write.
This will not change as I don't want 2 bars.
