### ISSUE TITLE
Allow resizing /user for emuMMC

### ISSUE THREAD

**Issue by alessbelli** [CTCaer/hekate#256]
Related to #253 , but on the opposite end I think allowing smaller user folder in the emummc partition could make emummc take a lot less space than 32Gb. Since most games can live in the main data partition most of the emummc will be empty.

**Comment by CTCaer** [comment]
both are the same issue and planned eventually.

As I write to TODO, resizing means resizing, not only shrinking or expanding.

**Comment by HyperLemons** [comment]
wasn't this done with hekate's latest update

**Comment by CTCaer** [comment]
Nope. This needs proper BIS support.
I added the base but not the whole implementation.

**Comment by CTCaer** [comment]
Added in Nyx 1.0.0
