### ISSUE TITLE
Lakka L4T messes with Temperature display

### ISSUE THREAD

**Issue by staccmang** [CTCaer/hekate#257]
Hekate version: 5.0.0

Issue:
booting into lakka l4t (version 20190515), then rebooting into rcm and pushing the hekate payload again temporarily makes the temperature display at the bottom display °F values (the indicator itself still says °C, but the value is ~101, which corresponds to about 38°C)

the switch itself is not hot at all and the issue occurs even when you just boot lakka and immediately reboot into rcm/hekate. 

powering off from hekate fixes the issue.

**Comment by CTCaer** [comment]
Hmm, it probably configures it to have that. I'll check it

**Comment by CTCaer** [comment]
@staccmang 
Is it possible for you to test the one in retronx server?
I added some init to reset specific values.

**Comment by staccmang** [comment]
sure, i'd be happy to help,
i just got into all of the switch stuff recently and don't really know any of the resources, could you provide a link?
or are we talking about the retronx discord?

**Comment by CTCaer** [comment]
https://github.com/CTCaer/hekate/commit/fed15a2f2f56a2babbcbc0eccd906e623c86375f
