### ISSUE TITLE
Currently, Fix Nintendo arc bit, can't be applied to emuMMC Nintendo folders.

### ISSUE THREAD

**Issue by CTCaer** [CTCaer/hekate#261]

**Comment by jesusvallez** [comment]
How can I fix it in OSX while this problem is solved? @CTCaer

**Comment by jesusvallez** [comment]
I fixed my emummc corrupted moving Nintendo_XXXX to root and renaming it Nintendo. Run hekate and fix archive bit with "unset archive bit" and after "fix archive bit - Nintendo". Later, i moved agains the nintendo folder to emummc and i renamed it Nintendo_XXXX... and voilà, works

**Comment by CTCaer** [comment]
https://github.com/CTCaer/hekate/commit/c50e61f961e9e70368bfdfa29a06ccbabcc5bb4c
