### ISSUE TITLE
Add warning to clear archive bits on nintendo folder

### ISSUE THREAD

**Issue by fennectech** [CTCaer/hekate#262]
It is highly recommended NOT to clear archive bits on the nintendo folder if you have a fat32 filesystem.  This will render all games over 4gb unbootable and you will have to re install them.  This is because the switch uses the archive bit for the NCAs stored for installed titles.  This information isnt communicated to the user.

**Comment by CTCaer** [comment]
It clears the arc bit from everything and only adds it for .nca folders.

https://github.com/CTCaer/hekate/blob/master/nyx/nyx_gui/frontend/gui_tools.c#L208

**Comment by fennectech** [comment]
Oh. Thats cool.  👍    Didn’t know you handled that :)

**Comment by CTCaer** [comment]
https://github.com/CTCaer/hekate/commit/0d9aebda7bc1225806375350e075cacf6956158f

**Comment by fennectech** [comment]
Could we set archive bit on all directories containing a “00”.   This will get all files intended to be split that way.
