### ISSUE TITLE
After restore BOOT 0/1 without autorcm, hekate show me the autorcm is ON

### ISSUE THREAD

**Issue by davedave85** [CTCaer/hekate#263]
After i restore BOOT0/1 hekate keep me showing the autorcm is ON, i need to OFF and ON again to keep me the autorcm ON

**Comment by CTCaer** [comment]
It's known issue. The button isn't updated after a restore.
Will be fixed.

**Comment by CTCaer** [comment]
https://github.com/CTCaer/hekate/commit/9533dea124ca29c8911cfcb5d82c46639f19a539
