### ISSUE TITLE
Warn user on emuNAND creation

### ISSUE THREAD

**Issue by Luro02** [CTCaer/hekate#268]
As someone, who just wrote the emuMMC to the main partition (the one with all the files) of the sd card, I propose to add a warning for the user, that you have to create a separate partition or you will corrupt your sd card! (or even better: prevent hekate from writing to partitions with files/folders on it)

**Comment by Strat00s** [comment]
Maybe show what is on the partition that you chose.

**Comment by CTCaer** [comment]
Can you give steps to reproduce?
The checks start at partition 1 and not 0 which is the main.
Also it says which partition chose. It says [Part #] and below the partition table.

**Comment by Luro02** [comment]
Never mind, I just saw, that this is no longer possible :+1:

**Comment by CTCaer** [comment]
Hmm, it wasn't possible even before.
That's why I asked for possible steps to reproduce
