### ISSUE TITLE
Add Toggle to disable "CFW (SysNAND)" option

### ISSUE THREAD

**Issue by Pokemoncollector** [CTCaer/hekate#271]
Add a Toggle inside "Options" to enable users to disable the boot into CFW using SysNAND option under 'Launch'.

Many users take advantage of a secondary partition to allow for online play on SysNAND, and this would prevent mistakes that could result in a ban.

**Comment by m4xw** [comment]
stock=1 ? :thonk:

**Comment by Pokemoncollector** [comment]
This is possible inside of more configs?

**Comment by CTCaer** [comment]
Edit your config (hekate_ipl.ini) then and remove that.
