### ISSUE TITLE
failed to init sd card with 5.0.1

### ISSUE THREAD

**Issue by kuaner** [CTCaer/hekate#273]
sd card init failed with 5.0.1 but the same sd card works great with 5.0

**Comment by CTCaer** [comment]
Can you fetch a photo of `Console info -> SD card / microSD info` from a working hekate version?

**Comment by Clydefrosch22** [comment]
it's possible that your sd card/card slot are just a little wonky

whenever i take my card out, it takes a couple attempts before the switch feels like recognizing it again. possibly, the reader is lose or the connector has some issue, or the contacts on the card itself are damaged/scratched in too much.

**Comment by CTCaer** [comment]
@kuaner any news about that info?

**Comment by kuaner** [comment]
![11564363341_ pic](https://user-images.githubusercontent.com/1484437/62016085-8c889f80-b1e2-11e9-8d31-49658d96db34.jpg)
![21564363342_ pic](https://user-images.githubusercontent.com/1484437/62016089-91e5ea00-b1e2-11e9-9a1b-05d6500ce634.jpg)

i use 5.0.0 as payload to init the bootup, then it works great with  5.0.1

that's very strange

**Comment by CTCaer** [comment]
This can happen with fake sd cards.

Your card uses a valid id/oem/model but the year/size are wrong. And I doubt it's a V30 card.
What speeds you get for read/write with usb3 UHS-I sd card reader?

**Comment by kuaner** [comment]
It's a 64 GB sd card
50MB read speed
80MB write speed

I would glad to try the payload

**Comment by CTCaer** [comment]
I added some possible fixes for your issues. Please test again.

Otherwise, ping me at retronx discord for a special testing build that has some big SDMMC driver changes that will come out with v5.1.0.

**Comment by CTCaer** [comment]
I didn't have any contact in discord, so I will mark it as solved.
Feel free to reopen if not.
