### ISSUE TITLE
Ini folder configurations list in Auto Boot configuration is empty

### ISSUE THREAD

**Issue by ThatNerdyPikachu** [CTCaer/hekate#275]
```
bootloader/
    ini/
        0-android.ini
```

Doesn't show up in ``Options -> Auto Boot``

**Comment by CTCaer** [comment]
This will might be a bug with my parsing and list preparing for autoboot window in Nyx.
(Because it works for booting).

I'll check it.

**Comment by Lesking72** [comment]
The ini folder configurations appear if there are options in hekate_ipl.ini, but they seem to take the name of options that are in hekate_ipl.ini

For example, if I have a boot option named ReiNX in hekate_ipl.ini and an ini file named Lockpick, then the auto boot menu will show "ReiNX" under both main configurations and ini folder configurations, but the one in ini folder configurations is actually Lockpick.

**Comment by CTCaer** [comment]
https://github.com/CTCaer/hekate/commit/6159d94e5df232877f7ace9490a814a2fa36fbe7
