### ISSUE TITLE
[FatFS] Error: NoFAT

### ISSUE THREAD

**Issue by AlxC10** [CTCaer/hekate#278]
Hello I've an issue where when I boot into hekate and I need to launch a CFW I get this error 
[FatFS] Error: NOFAT 
Failed to mount a SD Card (FatFS Error 13)
Make sure that a fat partition exists..
------------
I've got a 16 GB SD card in  I keep on trying to format it and try again but the same problem keeps happening.
_
Oh and I'm running Hecate 5.0.1

**Comment by fennectech** [comment]
This isnt a bug.  Your going to want to follow these directions then format it again. https://www.lifewire.com/how-to-partition-a-hard-drive-2626081

**Comment by AlxC10** [comment]
Yes ok I'm going to close this issue and try this I'll get in contact with you if I need help thank you
