### ISSUE TITLE
Removing archive bit causes issues.

### ISSUE THREAD

**Issue by plaidman** [CTCaer/hekate#28]
In the newest version you added the ability to remove the archive bit for files to solve an issue with HBMenu loading files. This is a brilliant idea and I'm super glad it's there. I was able to reproduce the issue and solve it with this boot option.

However, there is an issue where now none of my legit downloaded games work. Based on [the post here](https://gbatemp.net/threads/newest-hekate-sdfiles-zip.506280/page-21#post-8110599), I believe the solution might be to skip the Nintendo directory when turning off the archive bit. I haven't tried the solution there to see if it worked for me (I don't have a windows computer handy) but if you whip up a new build, I'll be happy to test.

**Comment by AnalogMan151** [comment]
Seems to be addressed in this commit from 11 hours ago: d4731bb540e1aa1d0cbce7ce9da978b6d59682af
