### ISSUE TITLE
Emummc not booting, "Unknown pkg1 version" message for half a second in red

### ISSUE THREAD

**Issue by Dramkissoon** [CTCaer/hekate#282]
This happens on my new micro sd 256gb. I boot my emummc after setting it up, and it is working fine until i install an nsp and after that, it just shows the Kosmos splash screen, displays the "Unkown pkg1 version" in red for half a second and then brings me back to hekate. 

Edit: This is my second micro sd card Im using with this switch. I have an emunand setup on another switch, I tried image copying it over to the new microsd and extend the unallocated space but that gave me the same result after installing an nsp, it just brings me right back to hekate after trying to boot emunand. Now I am trying to just set it up from the beginning without copying over the image and it's still giving me the same problem.

**Comment by CTCaer** [comment]
Easy fix:
Stop pirating and using brickers.
(And don't tell me you don't, because I doubt these nsps are homebrew)

**Comment by Dramkissoon** [comment]
> Easy fix:
> Stop pirating and using brickers.
> (And don't tell me you don't, because I doubt these nsps are homebrew)

Using brickers? As in don't install nsp's?
