### ISSUE TITLE
Allow mounting of SD as USB drive

### ISSUE THREAD

**Issue by deurk** [CTCaer/hekate#283]
Would we wonderful if Hekate could include memloader functionality and provide SD card access over USB :)

**Comment by Rohaq** [comment]
As someone who just accidentally overwrote his payload config while travelling (which admittedly is my own dumb fault), and doesn't have a MicroSD reader to hand, this would be exceptionally useful!

**Comment by evertonstz** [comment]
Hi, any news on when this will be committed? I'm kinda on Rohaq's foots right now: got a corrupted atmosphere, a broken SD adapter and can't get a new one due to covid lockdown :/

**Comment by CTCaer** [comment]
Added in version
