### ISSUE TITLE
Fix archive bit (Nintendo only) is only affecting Nintendo Folder in the Root of the SD

### ISSUE THREAD

**Issue by aut0mat3d** [CTCaer/hekate#287]
When using EmuMMC (tested here with 5.0.1 and EmuMMC on separate Partition) function
("Fix archive bit (Nintendo only)", fix_sd_nin_attr does not check and repair Archive Bits in 'emuMMC\XXXn\Nintendo' which is annoying as the whole Card has to be checked - think about having Retroarch and many Roms installed....

**Comment by CTCaer** [comment]
Download the latest
