### ISSUE TITLE
I tried to setup emuMMC

### ISSUE THREAD

**Issue by AlpGoXd** [CTCaer/hekate#288]
Hello i set up emuMMC to my console. When i try to launch emuMMC i get error and go back to hekate.
Error code comething like this Pkg2 decrypyion failed!

**Comment by CTCaer** [comment]
How you did you setup the emuMMC?
Also what HOS version is sys and what is emu?

**Comment by CTCaer** [comment]
As I said to #289 this is not a hekate issue but old CFW files. And especially the *sept* folder.
Update them.
