### ISSUE TITLE
not working pkg2 decryption failed

### ISSUE THREAD

**Issue by seawave11** [CTCaer/hekate#289]
there something wrong with my nand or the keys for 9.0 updated fully yet? then i tried to dump the keys it says unknown and no way seems to be no way to start hekate now,

**Comment by seawave11** [comment]
then i tried to dump the keys it says unknown

**Comment by CTCaer** [comment]
You might want to included more info:
HOS version that you are trying to boot?
Sys or Emu?
hekate 5.0.2?

**Comment by seawave11** [comment]
hekate ctcar 5.02
is system not emu
hekate 5.02

**Comment by CTCaer** [comment]
You sure you inject hekate 5.0.2?
That error can only happen on 5.0.1 and lower

**Comment by seawave11** [comment]
by inject you mean into firmware? no i don't think so,
i'm on newly firmware so the files on the sdcard old?

**Comment by CTCaer** [comment]
How you run hekate?

**Comment by seawave11** [comment]
it was injected by usb and yes it hekate_ctcaer_5.0.2

**Comment by CTCaer** [comment]
Show me your hekate_ipl.ini

**Comment by seawave11** [comment]
[config]
autoboot=0
autoboot_list=0
bootwait=1
verification=1
backlight=100
autohosoff=0
autonogc=1

{AtlasNX/Kosmos v13.2}
{}
{Discord: discord.teamatlasnx.com}
{Github: git.teamatlasnx.com}
{Patreon: patreon.teamatlasnx.com}
{Pegascape DNS: pegascape.sdsetup.com}
{}

{--- Custom Firmware ---}
[CFW (SYSNAND)]
emummc_force_disable=1
fss0=atmosphere/fusee-secondary.bin
kip1patch=nosigchk
atmosphere=1
logopath=bootloader/bootlogo.bmp
icon=bootloader/res/icon_payload.bmp
{}

[CFW (EMUMMC)]
fss0=atmosphere/fusee-secondary.bin
kip1patch=nosigchk
atmosphere=1
logopath=bootloader/bootlogo.bmp
icon=bootloader/res/icon_payload.bmp
{}

{--- Stock ---}
[Stock (SYSNAND)]
emummc_force_disable=1
fss0=atmosphere/fusee-secondary.bin
stock=1
icon=bootloader/res/icon_switch.bmp
{}

**Comment by CTCaer** [comment]
Dunno what you do but you don't run hekate_ctcaer_5.0.2 but an older version.
Or you have something strange at /sept/payload.bin that is a fake 5.0.2 version.
(hekate does a version check there)

**Comment by seawave11** [comment]
so that size is of the payload happen be 5.193 mb

**Comment by CTCaer** [comment]
Go to hekate menu and take a photo of it

**Comment by seawave11** [comment]
how can i do that from hekate ipl menu?

**Comment by CTCaer** [comment]
Use your phone

**Comment by seawave11** [comment]
![IMG_20190915_220741](https://user-images.githubusercontent.com/55362597/64931458-c8b1a700-d806-11e9-9ac9-e5dfeba7f550.jpg)
![IMG_20190915_220935](https://user-images.githubusercontent.com/55362597/64931502-ee3eb080-d806-11e9-82ec-d9783a97a6d4.jpg)
![IMG_20190915_221057](https://user-images.githubusercontent.com/55362597/64931508-f72f8200-d806-11e9-8ee7-eb3ca12216f0.jpg)

**Comment by CTCaer** [comment]
Well I asked for the main menu. The one that shows Launch/Morecfg/Payloads/emummc.

Your Nyx is old for sure. You are supposed to drag n drop the bootloader folder and replace the files.

**Comment by seawave11** [comment]
ok my bad

![IMG_20190915_224125_1](https://user-images.githubusercontent.com/55362597/64932063-72defe00-d80a-11e9-834a-af9b45835abd.jpg)

**Comment by MACandCHEEZWIZ1** [comment]
Not that I'm trying to hijack, but I'm having a similar problem to this and also this
https://github.com/CTCaer/hekate/issues/288

In short,
-I'm using 5.0.2
-I formatted my SDXC card to FAT32 according to the guide on NH Switch and downloaded all the latest updates to Atmosphere, Hekate, etc.
-I'm currently on OFW 9.0
-I backed up BOOT0/1, RAW GPP, SYS, and USER. For Dump package1/2, I get "Found pkg1" but "Pkg2 decryption failed!"
-It refuses to let me launch FSS0 EmuMMC, FSS0 SYS, or Stock SYS. Every time I choose one, it cycles back to the Hekate IPL boot up screen and then the main menu. I'm still able to boot the console normally.
-I did try using the ReiNX payload not long before this, but the splash screen was really quick and didn't load into Atmosphere at all.

**Comment by CTCaer** [comment]
The issue is that all 3 of you never updated sept.
Sept changed to add 9.0.0 support. Without it, you get that pkg2 decryption error.
The unk pkg1 in nyx is simply because old nyx.

Basically update your files and stop leaving out the important ones when nitpicking or not.

**Comment by seawave11** [comment]
so that why i get that pkg2 decryption error as booting ofw haves no problems

**Comment by m4xw** [comment]
I dunno why we do all the effort to create drag & drop bundles only for users to not drag and drop them

**Comment by MACandCHEEZWIZ1** [comment]
> The issue is that all 3 of you never updated sept.
> Sept changed to add 9.0.0 support. Without it, you get that pkg2 decryption error.
> The unk pkg1 in nyx is simply because old nyx.
> 
> Basically update your files and stop leaving out the important ones when nitpicking or not.

Aaaah, I see. I must have switched the sept folder over to an older version when I downloaded ReiNX 2.4. Everything was working before I added all the ReiNX stuff.

**Comment by seawave11** [comment]
I really don't know if you know idea either cuz I've tried with you said it still doesn't work it the firmware updates did someting

**Comment by CTCaer** [comment]
Update your CFW.
hekate is only the bootloader for it.
Download the latest version of your CFW and drag n drop the files.
Especially the **sept** folder.

Same goes with hekate. Download the latest release (hekate v5.0.2 & Nyx 0.8.2) and drag n drop the bootloader folder to your sd.

This issue is not a hekate issue but old files that do not support 9.0.0.

**Comment by mrvnklm** [comment]
@seawave11 Did you actuall find a solution? I am facing exactly the same issue...

**Comment by MACandCHEEZWIZ1** [comment]
I think I just did a clean install in the end. I kind of hate updates
because updating one thing can make everything else stop functioning. One
of the annoying things was that the SDsetup file downloader page had a
Trojan in one of its files.

In short, homebrew is a huge pain.

**Comment by urherenow** [comment]
No, taking shortcuts is a pain. Do it right, and grab the latest from the source, and you won't have any issues. Stay away from "packs".
