### ISSUE TITLE
Can i get a link for this background?

### ISSUE THREAD

**Issue by gatekeeper1122** [CTCaer/hekate#297]
does any1 have this theme (background.bmp)? would be great if i can get a download link for it
![60391751-95605580-9afe-11e9-9e20-f84163247dcf](https://user-images.githubusercontent.com/16184353/67047310-5676ff80-f0ef-11e9-874e-0c9139685103.png)

**Comment by CTCaer** [comment]
[background.zip](https://github.com/CTCaer/hekate/files/3741623/background.zip)
