### ISSUE TITLE
Failed to init SD card. Make sure that it is inserted. Or that SD reader is properly seated!

### ISSUE THREAD

**Issue by Samii571** [CTCaer/hekate#298]
When i try to launch something or when i want to use anything sdcard related, this error message comes out. 
But when i press the sdcard reader (from the case) its working...
Do someone has a solution for this problem?

**Comment by maskmark** [comment]
apparently it's a hardware related issue. try make your card reader mini-board steady fixed onto the MB slot.

**Comment by Samii571** [comment]
(I come from germany, and even with a translator i didn't understand you properly)So you think I should unscrew the switch and attach the card reader better?
And if so, where should I fasten the card reader, or should I leave it where it is and then fasten it?

**Comment by maskmark** [comment]
![mmexport1571571808747](https://user-images.githubusercontent.com/42833659/67159028-ec21c180-f371-11e9-8fc1-06b97a141ccd.jpg)
well, re-inatall this thing firmly on your main PCB.

**Comment by maskmark** [comment]
re-inatall=re-install

**Comment by ELY3M** [comment]
I seen few people who have missing pins from the sd reader connector part on motherboard. make sure to check the connector for any missing pins.   use phone camera and zoom.

**Comment by CTCaer** [comment]
Closing as this is a hardware issue
