### ISSUE TITLE
Verification forever bugged...

### ISSUE THREAD

**Issue by CTCaer** [CTCaer/hekate#30]
There's a new issue with verification.

Currently it tries to parse a u64 number with a u32 storage.
This way it tries to compare the wrong eMMC segment with the correct SD one.

A fix is planned for release ASAP!
It's currently in testing, by users that had this problem.

**Comment by cleggorz** [comment]
Is this the same error that results in

SD card and emmc data (@LBA 00000200) do not match.
Verification failed.

**Comment by CTCaer** [comment]
The x2000 bug was only a false printing.
It has 3 bugs:
* For partial backup, it does not take the correct start LBA after continuing a partial backup
* For single file (exFAT) it uses a 32bit storage for a 64bit value
* Any of the 2 may break if it reaches the ~70 minute mark.

The last case is the only one not fixed internally. It's obscure and strange.

**Comment by CTCaer** [comment]
Fixed (?!?) in:
https://github.com/CTCaer/hekate/commit/ebb9ca5bf56c28824cfbea4b0cb0668e6df7cb32
https://github.com/CTCaer/hekate/commit/5e8eb1c57aa5498d056482ecb808f0d96abd6bf2

Awaiting testers' results before closing.

**Comment by cleggorz** [comment]
Testing now but this seems fixed. Already past where it would normally fail.

**Comment by CTCaer** [comment]
I know.
Internally, it succeeded for all testers.
(And I currently test verification for restore option).

But I'll clean up the issues when the code reaches release state.

**Comment by CTCaer** [comment]
All testers and users on v3.1 release report that it doesn't break anymore.
