### ISSUE TITLE
Advanced EmuMMC controls

### ISSUE THREAD

**Issue by ziobbe** [CTCaer/hekate#304]
I'd like to have the same backup and restore options we have for EMMC for EmuMMC too, this way changing sd cards, even consoles if user partition are interchangeable and managing emmc backups in general would be much more userfriendly.

**Comment by CTCaer** [comment]
emuMMC backup, which is the only missing thing on the backup/restore options will come eventually.
That's because it is supposed to parse the emuMMC and see its size, in case a user made it smaller.

**Comment by CTCaer** [comment]
Added in version
