### ISSUE TITLE
GUI vs Simple UI

### ISSUE THREAD

**Issue by thed1zm** [CTCaer/hekate#306]
When i reboot my switch i get the basic UI of hekate (long vertical style), i have to reinstall hekate on my sd card every time to get the nice GUI.
is this a common problem?

**Comment by fennectech** [comment]
you probally have a shitty fake flash sdcard
run h2testw on it   https://3ds.hacks.guide/h2testw-(windows).html

**Comment by thed1zm** [comment]
the card is fine. i use a 512 sandisk ultra, bought from retail. ran a h2testw and its as what it seems.

**Comment by CTCaer** [comment]
Well if your card is not fake then
something corrupts or deletes the `bootloader` folder.
Find that app and remove it.

**Comment by CTCaer** [comment]
Try latest hekate if the issue was not a fake sd
