### ISSUE TITLE
BOOT0 and BOOT1 backup not working

### ISSUE THREAD

**Issue by Mariominedude** [CTCaer/hekate#307]
soooo this is an interesting story, I was trying to downgrade to 8.0.0 with ChoiDujourNX, but when I rebooted the console, It just kicked me back to Hekate, I remembered I backed up my BOOT0 and BOOT1 on 9.0.1, so I tried restoring it the Hekate. It said it was successful so I tried again, BUT IT STILL WON'T BOOT! Can someone please help?

**Comment by CTCaer** [comment]
Ofc they won't work. You need rawnand.bin also. BOOT0/1 are paired with it.
