### ISSUE TITLE
tsec error

### ISSUE THREAD

**Issue by gamingtheohd** [CTCaer/hekate#309]
when i try to print tsec keys it says unknown pk91 version for reding tsec firmware

**Comment by CTCaer** [comment]
There's a bug that might get proc'ed in some switches.
This is fixed on master but not on release.

Use https://github.com/shchmue/Lockpick instead

**Comment by gamingtheohd** [comment]
ok let me see if its working

**Comment by gamingtheohd** [comment]
if lockpick works

**Comment by gamingtheohd** [comment]
i taught it is because the higher firmware i had this error

**Comment by gamingtheohd** [comment]
it says that all the keys where dumped just not the tegra ones

**Comment by gamingtheohd** [comment]
soo not working

**Comment by gamingtheohd** [comment]
Yup,it was because the higher firmware i downgraded to 8.1.0
