### ISSUE TITLE
OFC 9.1.0 okay with latest hekate version?

### ISSUE THREAD

**Issue by 0opsie** [CTCaer/hekate#318]
Hey I was just about to install my first CFW on my switch and accidentally updated to OFW Version 9.1.0.
Is it still safe to continue with the installation or do you recommend waiting till a 9.1.x supporting hekate version is online?

I'm following this guide:
https://youtu.be/uL0rD69doSU

**Comment by fennectech** [comment]
9.1.0 is.not yet supported with hekate or atmosphere.   I recomend waiting

**Comment by CTCaer** [comment]
I'll close this as duplicate of https://github.com/CTCaer/hekate/issues/314
