### ISSUE TITLE
v5.1.0 black screens on injection with old minerva

### ISSUE THREAD

**Issue by MegaSuperab** [CTCaer/hekate#319]
After updating to the latest version, hekate straight up doesn't load. The screen doesn't even turn on. I've tested other payloads and they boot up, so it's not my Switch that's the problem.

**Comment by CTCaer** [comment]
Did you drag n drop the bootloader folder?

**Comment by MegaSuperab** [comment]
> Did you drag n drop the bootloader folder?

I have, and it still doesn't work.

**Comment by CTCaer** [comment]
Are you able to join retronx discord so I can provide test builds?

**Comment by MegaSuperab** [comment]
Oh. When you said "drag n drop", I somehow didn't process the fact that I had to do so into my sd card. It works now, sorry.

**Comment by CTCaer** [comment]
You are welcome.
It is still a bug I suppose.
It wasn't supposed to hang with old minerva. I'll reopen it.

**Comment by CTCaer** [comment]
https://github.com/CTCaer/hekate/commit/e4f7928513ebe00c482bb5a3a3b81fc935738471

Will close the issue when hotfix version is out.
