### ISSUE TITLE
Unable to boot CFW (SysNAND or EMUMMC)

### ISSUE THREAD

**Issue by xgorinx** [CTCaer/hekate#321]
When trying to boot CFW, receiving errors:

Failed to apply 'nosigchk'!
Failed to launch HOS!

Stock and payload fusee-primary do launch, however.

hekate: v5.1.0
System: 9.1.0
Atmosphere: 0.10.0

**Note: the CFW in question is KOSMOS.  Could the issue be that KOSMOS hasn't been updated yet past v14.2?

**Comment by Goma1337** [comment]
Came to report the same error. 

9.0.1 EmuMMC boots fine, 9.1.0 SysNAND doesn't.

Not sure if it's a problem with applying the patches or with the patches themselves. Using Joonie86's patches (https://github.com/Joonie86/hekate/releases).

**Comment by CTCaer** [comment]
Failed to apply a patch, means the patch is missing or empty.

Also no piracy here

**Comment by xgorinx** [comment]
I'm sorry to ask, but what does that mean exactly?  I haven't pirated anything.  I use atmosphere so I can use Edizon.

**Comment by urherenow** [comment]
Then you don’t need to enable sigpatches. Those are for installing games and such.

**Comment by xgorinx** [comment]
I found it.  In the bootloader folder, the hekate_ipl.ini config file said 

{--- Custom Firmware ---}
[CFW (SYSNAND)]
emummc_force_disable=1
fss0=atmosphere/fusee-secondary.bin
**kip1patch=nosigchk**
atmosphere=1
logopath=bootloader/bootlogo.bmp
icon=bootloader/res/icon_payload.bmp
{}

...so I removed the kip1patch=nosigchk line.  However, this was a file I had never touched before, so I think this was bundled with one of the hekate downloads.  Should hekate be informed that the .ini file has this setting enabled?

**Comment by funkyouo** [comment]
Thank you for your issue. I had a same problem as you when I wanted to boot sysnand to use the Checkpoint. It's just that Atmosphère‘s author has no intention of supporting piracy,you know.
