### ISSUE TITLE
Can't boot into CFW after last update. 

### ISSUE THREAD

**Issue by AshbalaGang** [CTCaer/hekate#323]
I'm getting the following error when trying to boot:

Failed to apply 'nosigchk'!
Failed to launch HOS!

I have alredy download the most recent files from Atmosphere and hekate. The payload I'm injecting on is the 5.1.0 and I've updated the libraries.

**Comment by kristal91** [comment]
anche io mstesso problema

**Comment by kristal91** [comment]
I am also a problem myself

**Comment by kristal91** [comment]
I also have this problem

**Comment by urherenow** [comment]
Not needed unless you are pirating. Do you think it’s supported on Github?

**Comment by AshbalaGang** [comment]
I'm not pirating any type of software.

**Comment by TKCentaurus** [comment]
I also only had my previously downloaded games and DLC from the eShop, but I accidentally updated to 9.1.0 while in emuMMC, and i'm getting these same errors.

**Comment by CTCaer** [comment]
This is **missing** patches or **broken/mismatched** patches.
I will pretend to believe the no pirate quote, **once**,
and just tell you to remove the `kip1patch=nosigchk`
