### ISSUE TITLE
[Enhancement] Add option to autoboot Entry Menu

### ISSUE THREAD

**Issue by pcwizard7** [CTCaer/hekate#324]
could you add the option to autoboot to the launch menu?

**Comment by james-d-elliott** [comment]
In the config set autoboot=0. This should force Nyx to boot each time you turn on.

**Comment by CTCaer** [comment]
pcwizard7 asks for another thing.

I would say that you just need to wait a bit.
(hint: Nyx big update)

**Comment by CTCaer** [comment]
Added in version
