### ISSUE TITLE
Error :Unable to boot into the "NYX"

### ISSUE THREAD

**Issue by gmailman** [CTCaer/hekate#325]
Is this the correct place to post?

https://imgur.com/a/HEMrVDC
Unable to boot into the "NYX" menu i think it is to create the MMUnand 9.1 FW & Hekate 5.1.0
"NYX is missing"
Is my brain too smooth to comprehend something?
Followed the same guides as the 3 bros who've cracked but mine had the latest firmware
TY x

**Comment by CTCaer** [comment]
You forgot to copy `bootloader` folder or your sd card has issues.

And normally no, it's not the place for that. Github issues are for bugs and not for support.
But I sometimes wait for results just in case.
