### ISSUE TITLE
Atmosphere System Memory Increase Kernel Patches

### ISSUE THREAD

**Issue by SassyCultist** [CTCaer/hekate#326]
In a new commit, Atmosphere has implemented some new kernel patches that I am guessing Hekate needs to add for people who don’t use fusee-secondary to boot.
https://github.com/Atmosphere-NX/Atmosphere/commit/28717bfd27f7fe651b523b27a35336760183e0ac

**Comment by CTCaer** [comment]
Yeah I know. There will be a hotfix when the new atmo version is released.

**Comment by CTCaer** [comment]
https://github.com/CTCaer/hekate/commit/24d30a40f92d25f7e40ce0d834a11090da55dfdc
