### ISSUE TITLE
pkg2 error, “is sept updated”

### ISSUE THREAD

**Issue by atlasquinn** [CTCaer/hekate#328]
I’ve done the drag and drop method and made sure I’m on the current CfW, but my Switch will not boot into Mmc. Any clue why or if Sept is not being recognized?

**Comment by CTCaer** [comment]
When updating atmosphere you need all folders from the zip. You forgot to copy the Sept folder and thus your sesept is the old one

**Comment by Mistera91** [comment]
> When updating atmosphere you need all folders from the zip. You forgot to copy the Sept folder and thus your sesept is the old one

Where is the atmosphere release ?
