### ISSUE TITLE
Doesn't dump pk1?

### ISSUE THREAD

**Issue by pcwizard7** [CTCaer/hekate#329]
the latest Hekate dumps pk2 but not pk1 when using Hekate>Tools>Dump Package 1/2.
and when you go to the backup folder there only a pk2 folder 

if you have dumps made by a previous hekate is there any point for a newer dump?

thanks

**Comment by CTCaer** [comment]
You can't get pkg1 from HOS 7.0.0 and up.
Also the dumps of these are not useful to non devs.

Making a BOOT0/1 and raw GPP (rawnand.bin) basically backups these also.
