### ISSUE TITLE
unset archive bit not hitting /switch folder

### ISSUE THREAD

**Issue by plaidman** [CTCaer/hekate#33]
But it is hitting files within the /switch folder.

I've compiled a new .bin from the most recent master branch to test the archive bit update. It doesn't seem to be working when I use the 'switch folder only' option. From what I can understand of your code, I think it might be opening the /switch folder to list all files and unsetting the archive bit for those files inside, but it doesn't actually unset the bit for the /switch folder itself.

I was able to verify by loading up a windows computer and unsetting the archive bit for only that folder, then everything worked for me. Homebrew and Switch games.

**Comment by CTCaer** [comment]
Thank you.
Gonna check this today.

**Comment by CTCaer** [comment]
Ok I saw the issue. We enter the directory right away without checking its object.

**Comment by CTCaer** [comment]
fixed in https://github.com/CTCaer/hekate/commit/ebb9ca5bf56c28824cfbea4b0cb0668e6df7cb32#diff-799c7cc4c061751437d68637b5d9ae27R1895
