### ISSUE TITLE
Failed to appply 'no sigchk' failed to launch HOS

### ISSUE THREAD

**Issue by Initializist** [CTCaer/hekate#333]
After I updated hekate to the latest version, whether I try to enter SYSNAND or EMUMMC. The message 'Failed to appply 'no sigchk' and 'failed to launch HOS' will show on the screen. 
I am using the latest Atomsphere 0.10.1 and hekate 5.1.1
My Switch firmware is 9.1.0. (I also replaced my bootloader folder with the new one.)
I am also using Kosmo 14.2.

**Comment by SilverCam** [comment]
I actually have the same exact problem as you. Did you find a fix?

**Comment by fennectech** [comment]
update your sigpatches or delete nosigchk from hekate-ipl.ini.   Were not allowed to tell you how to update your patches. Thats up to you and your google foo
