### ISSUE TITLE
Fusee-primary only boots emummc if emummc has been created 

### ISSUE THREAD

**Issue by 0mega-spartan** [CTCaer/hekate#339]
With an emummc created, using the config below still loads into emunand vs sysnand. 

[Atmos Fusee-Primary SYS]
payload=atmosphere/fusee-primary.bin
emummc_force_disable=1
icon=bootloader/res/sys_cfw_boot.bmp

**Comment by CTCaer** [comment]
Of course.
Any key in a hekate ini is only for hekate. And thus, that boot entry above is wrong.
If you want to switch between sys nand and emummc with a simple reboot, you need to use hekate to natively boot atmosphere. Otherwise you can enable/disable it in the hekate's emuMMC menu.
