### ISSUE TITLE
Is there no way to restore the machine?

### ISSUE THREAD

**Issue by luhongtao** [CTCaer/hekate#34]
![qq 00000](https://user-images.githubusercontent.com/32369608/42314554-e091aef2-8077-11e8-9fb6-d83a6d5a6d4f.jpg)
用的join_15_2GBparts_windows 是不是需要返厂了，黑屏进不去系统

**Comment by luhongtao** [comment]
Join _ 15 _ 2GBparts _ windows need to return to the factory, black screen can not enter the system

**Comment by CTCaer** [comment]
What you did was a restore of the one of the 3 physical partitions.
You need to also restore BOOT0 and BOOT1?
These are essential to do a FULL restore.

The black screen you are saying, is probably from incompatible rawnand.bin and the current BOOT0/1 you have.

So, copy the BOOT0 and BOOT1 backups you did, to /Backup/Restore and run the option "Restore eMMC BOOT0/1".

**Comment by GGLinnk** [comment]
Rajkosto's tools can help you in nand restoring :
1. Use [gptrestore payload](https://files.sshnuke.net/gptrestorev1.zip) to fix gpt table.
2. With [HACDiskMount](https://files.sshnuke.net/HacDiskMount1044.zip) extract all parts of your rawnand.bin (Use your dumped biskeys : can be dumped by using [this payload](https://files.sshnuke.net/biskeydumpv6.zip) ).
3. Use [memloader](https://files.sshnuke.net/memloaderv1.zip) to put your switch into USB eMMC UMS Mode.
4. With [HACDiskMount](https://files.sshnuke.net/HacDiskMount1044.zip) with admin right, open your eMMC nand by opening device Linux UMS Device 0, and restore 1 by 1 extracted files from rawnand.bin by using biskey too.

**Comment by luhongtao** [comment]
![qq 201112](https://user-images.githubusercontent.com/32369608/42367048-75214740-8135-11e8-9c98-6508c19a51de.jpg)Why filling in key fails

**Comment by oCanna** [comment]
Can you start the recovery mode pressing power + vol+ + vol- ?

**Comment by CTCaer** [comment]
@luhongtao 
Check that you got your BIS keys correctly.
This works great here.

**Comment by luhongtao** [comment]
Can enter rcm. system 3.0.0 can not restore firmware, restore the end of the black screen, you can now view the biskey

**Comment by CTCaer** [comment]
You tried to launch firmware through hekate?

**Comment by luhongtao** [comment]
If you want to resume booting, you will not be running the system on the black screen at the moment.

**Comment by CTCaer** [comment]
In the end, because this is not an actual issue with hekate and here is not a support forum, I'm closing this.

@luhongtao 
Try to get help through support forums.
