### ISSUE TITLE
Battery de-sync

### ISSUE THREAD

**Issue by chrisf95** [CTCaer/hekate#341]
Hi, my switch at 15% give me the low battery alert and go to stand-by... I try to do a calibration with a fully discharge, but I can't on horizon (because go stand-by every 10 sec) and on hekate menu it shutdown at  about 20%... Furthermore the voltage at a value (about 3000 MV) became a value written in a strange way like "FFF00083000". I don't know what to do because the battery desync fix is automatically done at boot

**Comment by CTCaer** [comment]
In hekate, if the voltage drops to 2800mV it shutdowns to protect the battery.
Basically 0% is 3200mV. If it shows 15% or 20% and it's lower or significantly higher, then you have a calibration issue.

This can be normally fixed, with the classic 0-100% (3.2V - 4.2V) full charge cycles.

As for the `FFF8000`, fixed it internally. I forgot to add # which denotes a color value (also the value is wrong, the correct is FF8000 for orange).

**Comment by chrisf95** [comment]
I retry and after put it in charge give me 18% on a 2850mv in hekate... So, how I can recalibrate to 3200 = 0%?

P.s. For the FF, I noted that is a FFF8000 with 3 "F", but it's not a problem

**Comment by CTCaer** [comment]
Charge it back to 100% (4.2V), then to 0% (3.2V), then back to 100%. **Check note**
This will count as 2 full charge cycles and the % will probably be fixed on its own, or at least get closer to the correct one.

**Note:**
Mind you, that when you reach 100% it's not actually 100%. You need to leave it at 4.2V so it can saturate. Leave it charging for **additional** ~1-2 hours after you see 100% (time depends on the charger used).

**Comment by chrisf95** [comment]
Really thanks... I do this yesterday, so today is the 2 full cycle... I hope it resolves

**Comment by CTCaer** [comment]
You are welcome.

Also the color will be fixed in next version (https://github.com/CTCaer/hekate/commit/9263e2192fe5190f2381e8d51e9c58062fe867c6).

**Comment by chrisf95** [comment]
Hi, I did 2 cycle (100--> 0% at 3.2v) but the 3.2v is marked as 60%. I try to shutdown and power on at 100% in order to apply the fix battery, but nothing... I don't know what do now

**Comment by CTCaer** [comment]
Only one power cycle is not enough.
If you don't remove the battery, wait and replug it, it needs some cycles to fix itself.
That's ofc if it wants to fix itself.

**Comment by chrisf95** [comment]
I did two cycles, then I continue until It fix. Re-thanks

**Comment by chrisf95** [comment]
Today It says 100% all time and in hekate it is 255%... Now it gives me changing value (2% after some second 60, then 100 and this continuously) in also in hekate and booted... What can I do?😱

**Comment by chrisf95** [comment]
Today After I put on charge seems all OK, but when it reach 1% while boot, in hekate it is at 3800mv, now I try to discharge in hekate

Online I see a version of hekate with manual battery fix, can this be usefull?

**Comment by chrisf95** [comment]
Hi, if I recontact you from here but I think is useless open another 3d...
The problem persist: the switch when was shutdown, the next day after I start it says that is 1%

I did different full cycle and I don't know what to do.
online I find a version of hekate with the manual fix, do you think that this can help?
really thanks and sorry for the disturb

**Comment by CTCaer** [comment]
It won't help @chrisf95 .
You need to at least try discharging it to 3200mV in hekate. Then charge it fully in HOS. And fully means seeing 100% and leave for about an hour more.

**Comment by chrisf95** [comment]
I retry, but I did It many times and when I shutdown and the Day After start It I have 1% also if the battery Is fully charged (4200mv in hekate)

**Comment by CTCaer** [comment]
what are the capacity `now` and capacity `full` values?

**Comment by chrisf95** [comment]
In this Moment the capacity now Is 0, the full 2930
Sometimes during the full cycle I did It became 4300

**Comment by CTCaer** [comment]
Probably HOS has garbage values.
For now the simplest way is to always charge inside HOS until it settles again.

**Comment by chrisf95** [comment]
I try thanks

**Comment by Elionna** [comment]
I am having a similar issue with the battery desync after not using my switch after 2 months. Before storing it I had autorcm on but I turned off the switch via the power off option in hekate.

Will turning autorcm off help with this problem? I have done 4 cycles and the battery is still shutting off in HOS around 40%, getting worried if I can even fix this.

**Comment by CTCaer** [comment]
>For now the simplest way is to always charge inside HOS **until** it settles again.

**Comment by cristianrj9** [comment]
hola CTCaer tengo el problema del indicador de bateria de la switch en si la duracion de la bateria es normal el problema es el indicador ya que cuando logre cargalo al 100%  y apagar la consola con ese porcentaje al encenderlo despues de unas horas la consola enciende con el 1% despues de haberlo dejado cargado al 100% como podria solucionarlo?
ayuda por favor
