### ISSUE TITLE
pkg1 Not Being Dumped...

### ISSUE THREAD

**Issue by JustinB77** [CTCaer/hekate#343]
I've been trying to dump Mario Kart 8 DX's files for over 3 hours now and the main issue I'm running into is LockPick_RCM not finding pkg1. Turns out, Hekate never dumped pkg1 period. Everything e;se (pkg2, kernel.bin, ini1.bin, etc.) was all dumped. Im on Switch version 9.1.0, Atmosphere 0.10.2, and hekate 5.1.1. I've already checked the dump location and tried a fresh dump, but no dice, still no pkg1. If anyone could please help I would greatly appreciate it.

**Comment by CTCaer** [comment]
You misunderstood the issue.
First, you can't dump a decrypted pk1 on 7.0.0+.
Second, the issue is that you are probably using emuMMC and you messed the config.
Or you use old lockpick rcm or it has a bug.

You should seek help at @shchmue 's repo: https://github.com/shchmue/Lockpick_RCM
