### ISSUE TITLE
Unkown pkg1 version 

### ISSUE THREAD

**Issue by BladeStrde** [CTCaer/hekate#345]
I have installed everything to the newest version and nothing has fixed anything I have

- Redownloaded sig patches
- Redownloaded fusee-primary for atmosphere which results in a black screen

Everything is updated to the latest version and I cant seem to get things running. I'm also using an EmuMMC and someone had mentioned a hekate bit fixer but i cant seem to find a link on the page or else where

**Comment by CTCaer** [comment]
Either your emuMMC is corrupt or created wrongly or the emummc.ini points to the wrong sector.
```ini
[emummc]
sector = 0x#######  <---- This
```

The sector MUST always point to BOOT0 wherever it is and not necessarily to the partition start.
For emuMMC created via hekate, that's on partition start sector + 0x8000.
