### ISSUE TITLE
Error while executing payload

### ISSUE THREAD

**Issue by estelavg** [CTCaer/hekate#350]
What I can do? 
![WhatsApp Image 2020-01-31 at 20 40 09](https://user-images.githubusercontent.com/60523107/73569035-e86e0280-4469-11ea-89ab-7844aa1bfee3.jpeg)

**Comment by deadair3210** [comment]
Literally tells you on the screen what to do.....

**Comment by estelavg** [comment]
No, I done this but it don't help. I used 4 differents sd cards and in the last I could do it. I don't know why the others didn't work.

**Comment by CTCaer** [comment]
what @deadair3210 said.

Dl the hekate release zip (not the source code) and throw the `bootloader` **folder** to your sd card root.

hekate release doesn't replace your hekate configs and payloads, so you can merge it with existing bootloader folder and hit the replace button.

EDIT:
If you have it working on 1 sd card only, it means that the other cards are fake or have improper/corrupted filesystem or your sd reader is busted.
But I don't see an error message from the mounting code, which is strange

**Comment by estelavg** [comment]
I has downloaded the release zip and the message didn't change and the other sd cards are not corrumpted because I use on my 3DS and it works.

PS: The switch is new and I'm doing a clean installation.

**Comment by CTCaer** [comment]
not corrupted means improper filesystem then.
Init them so it creates the MBR and create a partition and format it after.
With a proper tool

**Comment by azoreseuropa** [comment]
> I has downloaded the release zip and the message didn't change and the other sd cards are not corrumpted because I use on my 3DS and it works.
> 
> PS: The switch is new and I'm doing a clean installation.

I had the same problem as you. I resolved it on my own. Please let me know so I can help you. Very easy.
