### ISSUE TITLE
Waarning: Nyx is missing!

### ISSUE THREAD

**Issue by Myselfs-s** [CTCaer/hekate#351]
I formated my Samsung sd card and copied bootloaded carpet in it, it says nyx is missing and when i try to launch hekate it says failed to initiate sd card

**Comment by CTCaer** [comment]
A missing bootloader carpet means that the format you did messed with MBR.
Either it initialized wrongly or it converted it to GPT. You need to init the sd card with a proper tool and then format it.

This because I assume it worked before formatting it.

**Comment by HeroCC** [comment]
Something for future folks: make sure your SD card is in the switch, not your laptop :sweat_smile:

**Comment by rock20xx** [comment]
I'm actually having the same issue.. it say I need an updated payload but its the most recent.
