### ISSUE TITLE
Kernels problem 

### ISSUE THREAD

**Issue by Stev3nM** [CTCaer/hekate#354]
What should I do 
![03E07AD9-DC5A-43E8-A465-86DC63BE33EB](https://user-images.githubusercontent.com/61605690/75594600-3bca7500-5a57-11ea-9ea9-55ca7be454e3.jpeg)

**Comment by CTCaer** [comment]
This can happen if there was sth wrong with decrypting it or hashing it. Either by a corrupted file or SE error. You can reliably produce that?

**Comment by Stev3nM** [comment]
im noob for this , anything  can do decrypting or hashing and how to dump pkg 2file. use hakate or sth

**Comment by Stev3nM** [comment]
> Try to dump pkg2 (Tools -> Dump pk1/2) and see what it outputs.

it said 
Found pkg1 ('20191021113848')
setp will run to get the keys.
Then rerun this option.

and nothings happened   awalys black screen.
can not return to it 


and other thing when i run hakate or other cfw 
and aways stuck in hakate logo
and its said 
Failed to identify kernel /.
Failed to lauch HOS /
press any key..

**Comment by CTCaer** [comment]
Try to update `sept folder` from an official and latest atmosphere release zip.
And also drag n drop the `bootloader folder` again (and hit merge and replace files when you are asked) from the hekate v5.1.1 zip.

**Comment by CTCaer** [comment]
I assume you fixed the issue.
