### ISSUE TITLE
feature request : random bootlogo

### ISSUE THREAD

**Issue by Heartbeat-Heartbreak** [CTCaer/hekate#356]
I made a lot of bootlogos and I'm tired of using only one.
a little random, a lot of fun : )

**Comment by fennectech** [comment]
I second this owo

**Comment by ELY3M** [comment]
this is easy to do.    add randombootlogos in config and add randomizer in the code.   set /bootloader/bootlogos as the path for bootlogos.

**Comment by ELY3M** [comment]
this is not done yet but I can do it in my hekate fork.

**Comment by wiiNinja** [comment]
I vote for a selectable logo, not a random one. :)

**Comment by CTCaer** [comment]
@wiiNinja 
> I vote for a selectable logo, not a random one. :)

It's supported since ever..
Use `bootloader/bootlogo.bmp` if you want a global one.
Use `logopath=path/to/logo.bmp` in a boot entry if you only want that entry to have a custom bootlogo.

**Comment by CTCaer** [comment]
This will not be implemented for size constrain reasons
