### ISSUE TITLE
updater2p=1 doesn't update reboot_payload

### ISSUE THREAD

**Issue by charagarlnad** [CTCaer/hekate#358]
Even with setting updater2p=1 in hekate_ipl.ini, /atmosphere/reboot_payload.bin is not replaced with hekate but stays as a fusee-primary payload.

hekate version: 5.1.2
nyx version: 0.8.5
atmosphere version: 0.10.3

# hekate_ipl.ini:
```ini
[config]
autoboot=1
autoboot_list=0
bootwait=5
customlogo=1
verification=2
backlight=100
autohosoff=0
updater2p=1

[Atmosphere]
payload=bootloader/payloads/fusee-primary.bin
```

**Comment by CTCaer** [comment]
That's because you are not using hekate to boot atmosphere.
The updater relies on fss0 to get the path of the reboot_payload.bin.
That behavior won't change in the short future. Except if you can propose a better way without hardcoding paths.
