### ISSUE TITLE
Implement some kind of status bar

### ISSUE THREAD

**Issue by CTCaer** [CTCaer/hekate#36]

**Comment by CTCaer** [comment]
https://github.com/CTCaer/hekate/issues/22

**Comment by CTCaer** [comment]
Added in https://github.com/CTCaer/hekate/commit/828b6164683a41de12faedaa0048fc3a6d9d11a1

(battery info only for now)

**Comment by ValliantStorme** [comment]
I really like this feature, it's good to know whether or not my Switch is draining battery during long NAND dumps.
