### ISSUE TITLE
i have auto rcm off i injected cfw from hekate and my screen turns off and wont turn on i leave on charge for 2 hours try to turn it on wont work i plug it into my pc wont work my only rcm jig is a homemade one and works like 1 outta 50 tries please show ways my only picture is a switch thats not on

### ISSUE THREAD

**Issue by DEeznuts123343** [CTCaer/hekate#360]

**Comment by CTCaer** [comment]
First, of all use the description and not the title for the issue.
Secondly, get a better jig or just use autorcm.

**Comment by DEeznuts123343** [comment]
wow nice attitude first off second of all thats not my problem my problem
is i cant boot my switch as said it won't turn on i dont see the fat
problem band im sorry my first post was messed up thank you very much i
probably wont be using this github anymore thank you!
