### ISSUE TITLE
Failed to identify kernel

### ISSUE THREAD

**Issue by venom19910** [CTCaer/hekate#364]
Well, I was installing tinfoil, and some message of I have to update tinfoil pops up (like a game update) but I was mashing the A button and I press update, then my Nintendo restarts, and that message of failed to identify kernel shows. 

Thank u in advance, I really appreciate any help.

**Comment by CTCaer** [comment]
No piracy...

**Comment by deadair3210** [comment]
For future reference, button mashing is a bad idea in general

**Comment by saduwuhour** [comment]
well that really solved the issue...
