### ISSUE TITLE
[Enhancement] A Checkpoint style Save Manager outside of HOS?

### ISSUE THREAD

**Issue by OldGnashburg** [CTCaer/hekate#365]
I wonder if it would be a good idea to implement some sort of checkpoint style save manager integrated with hekate to make transferring save data between EmuNAND and SysNAND a lot less painful and for those who want to inject edited saves on SysNAND without potentially dirtying it with Atmosphere and risking a ban.

**Comment by fennectech** [comment]
Neat idea. But not a hekate problem

**Comment by CTCaer** [comment]
This is a good idea when I finish the module api.
But still it won't be developed by me if any. So closing the issue.
