### ISSUE TITLE
error: unknown pkg1 version.

### ISSUE THREAD

**Issue by lpt2007** [CTCaer/hekate#366]
Hi I created my sdcard using this turtorial:
[LINK](https://www.partitionwizard.com/partitionmagic/set-up-emummc-emunand-on-nitendo-switch.html)

Then I go to hekate --> emuMMC --> Create emuMMC --> SD Partition - Part 1 - Cantinue

Creating process takes about 30min and than say finished. Then I press close in right top corner.

Then I enabled emuMMC with Change emuMMC -- SD RAW 1 (screen says The emuMMC configuration was saved to sd card!) -->Ok.

Now If I Close --> Launch ---> CFW (EMUMMC) I get error: unknown pkg1version.

If I try "Migrate emuMMC" before I try first launch cfw I get screen Found SD Partition emuMMC! Do you want to repair the config for it? And when I press continue -->close --> launch --> cfw (emummc) I get same error.

If I go after error to emuMMC --> Migrate emuMMC I get screen No emuMMC or foreign emunand founds!

**Comment by fennectech** [comment]
Create a new EMUMMC after wiping the emummc partition     This is sounding like something went wrong in the process of creating your emummc

**Comment by CTCaer** [comment]
Take a screenshot or photo of `Console Info -> SD card` and post it here

**Comment by lpt2007** [comment]
> Create a new EMUMMC after wiping the emummc partition This is sounding like something went wrong in the process of creating your emummc

I try multiple times.



> Take a screenshot or photo of `Console Info -> SD card` and post it here

![20200317_205424](https://user-images.githubusercontent.com/38924279/76896291-dcab9380-6891-11ea-9739-4b356ef52d9e.jpg)

**Comment by urherenow** [comment]
I could be wrong, but it looks to me like your card is fake. I’m shown all of the info on the left, that you appear to be missing.

**Comment by lpt2007** [comment]
> I could be wrong, but it looks to me like your card is fake. I’m shown all of the info on the left, that you appear to be missing. Is your card _REALLY_ 1TB?
> 
> ![80C24790-BD5F-4789-9F7B-6AF30DEA5616](https://user-images.githubusercontent.com/6448336/76902414-4bfba480-68df-11ea-8901-bd1c99e56ba5.jpeg)

Card is realy 1Tb. Not fake.

**Comment by urherenow** [comment]
It’s either fake or defective. Sorry. It’s not reporting vendor, serial number, or anything like that. Try a different card.

**Comment by fennectech** [comment]
This is DEFINITLY fake.  It lies about capacity https://youtu.be/J-D6tYBX8vE

**Comment by CTCaer** [comment]
@lpt2007 
Your card is definitely fake:
![image](https://user-images.githubusercontent.com/3665130/76916521-4e530400-68c9-11ea-84c5-ce987d31d052.png)

Not only that, but it's a class 4 card even. Probably its real size is 16GB. Maybe less. Hw2testw will tell you.

Have in mind, that even if you partition it to its real size in order to salvage it, it will still be extremely slow.

**Comment by XxFlamexTrollxX** [comment]
How do I fix the unkown pkg 1 error?

**Comment by impeeza** [comment]
In this case:. Using a new SD card. A verified one

**Comment by XxFlamexTrollxX** [comment]
then how would I know if the SD is verified?

**Comment by impeeza** [comment]
H2testw. Google it

**Comment by XxFlamexTrollxX** [comment]
Alright, so I tested my sd card with h2testw. It normal and without error. So what do I do from here to correct my unknown pkg1 error?

**Comment by impeeza** [comment]
You could go to discord, wikis or other support channels and read the guides. On Gbatemp there is a post about that error and how to fix it, i think is something about missing files or using the wrong version of firmware update

**Comment by XxFlamexTrollxX** [comment]
Alright, thanks!

**Comment by XxFlamexTrollxX** [comment]
Yeah going to gbatemp was helpful.
