### ISSUE TITLE
Payload succesfully injected but a black screen

### ISSUE THREAD

**Issue by Pinkie-Pie-is-High** [CTCaer/hekate#367]

**Comment by Pinkie-Pie-is-High** [comment]
hello...
I've injected the payload but the screen is black. I know that my switch isn't patched so I don't know what is going on. If someone could help me I'd greatly appreciate it

**Comment by CTCaer** [comment]
Is your switch charged? If lower than 2.8V, hekate shuts down to protect the battery.

**Comment by Pinkie-Pie-is-High** [comment]
it is at 100%

**Comment by CTCaer** [comment]
Make sure then that bootloader folder is up to date.

**Comment by ELY3M** [comment]
make sure you are using latest hekate bin.

**Comment by ailin-nemui** [comment]
try hekate_ctcaer_5.1.2.bin
