### ISSUE TITLE
Hekate 5.1.2 don't boot itself after rebooting

### ISSUE THREAD

**Issue by Etheric-Mahes** [CTCaer/hekate#368]
Hi,

I just updated Hekate by dragging the booloader folder to the root of my SD and replacing files.

Now Hekate dont boot after rebooting the Switch from EMUMMC, I never seen this before, EMUMMC just launch by skipping it. Even with spamming "L" it dont show up.

All I can do is shut off, RCM, and injecting Hekate from Tegra.

Its like I dont have "built-in" Hekate anymore.

However I didnt change my Hekate_ipl since a while and it always worked.

Here:

[config]
autoboot=0
autoboot_list=0
bootwait=3
verification=1
backlight=100
autohosoff=0
autonogc=1
updater2p=0

{AtlasNX/Kosmos w/ nosigchk}
{}
{Discord: discord.teamatlasnx.com}
{Github: git.teamatlasnx.com}
{Patreon: patreon.teamatlasnx.com}
{Pegascape DNS: pegascape.sdsetup.com}
{}

{--- Custom Firmware ---}
[CRACK (EMUMMC)]
fss0=atmosphere/fusee-secondary.bin
kip1patch=nosigchk
atmosphere=1
logopath=bootloader/bootlogo.bmp
icon=bootloader/res/icon_payload.bmp
kip1=atmosphere/kips/ams_mitm.kip
{}

{--- Stock ---}
[OFFICIAL (SYSNAND)]
emummc_force_disable=1
fss0=atmosphere/fusee-secondary.bin
stock=1
icon=bootloader/res/icon_switch.bmp
{}

Any suggestion ?

Thanks for your work and your help

Mahes

**Comment by CTCaer** [comment]
Replace reboot_payload.bin with hekate. Or Just change `updater2p=0` to `updater2p=1`. You are not supposed to spam L or sth.
