### ISSUE TITLE
Support for external autoboot and settings that remain when hekate-ipl.ini is updated

### ISSUE THREAD

**Issue by fennectech** [CTCaer/hekate#37]
With the use of sdfiles updater hekate-ipl.ini is often overwritten with a new version.  I would like to see an external file that is also parsed after hekate-ipl.ini that will allow for custom boot menu entry’s and autoboot that doesnt go away when sdfiles are updated.

**Comment by CTCaer** [comment]
What? You seriously asking for this?
Don't update your ini...
