### ISSUE TITLE
lvgl: Static text labels corrupt .data when set to heap text after init

### ISSUE THREAD

**Issue by OldGnashburg** [CTCaer/hekate#371]
The NAND backup percentage bar is having issues. It's gone from being stuck at 0 all the way to 6, or it hits 24% and goes back to 20%, when it's having the issues, the percentage bar is a different color.
Using the latest Hekate/Nyx as of today.
Update: The text above eMMC BOOT0 and BOOT1 is corrupted I'm getting a '  B above it.

**Comment by CTCaer** [comment]
The percentage is normal. The color of the bar denotes if it's copying or verifying. And ofc for verification, it must start from the beginning of that part.

As for the text, can you take a photo?

**Comment by OldGnashburg** [comment]
Thanks for explaining the percentage thing. Also the text issue isn't always there, I used Hekate again shortly after and it was fine. It made me think sending the payload got screwed up. But if you get the issue too than maybe it isn't just me.

**Comment by CTCaer** [comment]
Found the issue and it's a lvgl lib bug. It doesn't check some stuff when it sets text label.
I'll change description and mark this as bug.

**Comment by CTCaer** [comment]
Fixed in https://github.com/CTCaer/hekate/commit/a39ba2cd71190d3e289722cc7bd1199baf7f3af1
