### ISSUE TITLE
Black screen after injecting the hekate payload to my switch.

### ISSUE THREAD

**Issue by amitbartfeld** [CTCaer/hekate#374]
when I'm injecting payload into my switch it says that it's ok but the screen stays black (trying to use hekate).

I'm at 9.2.0 and my serial num is XAJ7004...

I had CFW on my switch before and I tried to update it to 9.2.0 and from then it's not working.

It's not working with tegra + with an external RCMloader.

**Comment by urherenow** [comment]
Define “external RCMloader”. You need to, at a minimum, extract the entire contents of the latest Atmosphere (all folders and overwriting all files), same with Hekate, MINUS the hekate.bin, and hekate.bin is what you inject. If you have a dongle of sorts that does the injection, you need to rename hekate.bin to payload.bin, and get it onto your dongle.

**Comment by amitbartfeld** [comment]
I did all the following except the lest line... (didn't understand what do you mean in it. can you explain?)

**Comment by CTCaer** [comment]
Did you drag n drop the latest `bootloader` folder?
Also does your switch have enough battery?

**Comment by amitbartfeld** [comment]
yes to both.

**Comment by urherenow** [comment]
You plugged your rcmloader to your pc (via microUSB) deleted payload.bin from the top folder, dropped hekate.bin in there, renamed it to payload.bin, and also made sure the rcmloader was set to the correct folder before plugging it in to your switch? (Blue light, iirc...)

**Comment by amitbartfeld** [comment]
yes I did

**Comment by CTCaer** [comment]
Try running this and tell me what it gets printed on the screen:
[check.zip](https://github.com/CTCaer/hekate/files/4371984/check.zip)

**Comment by amitbartfeld** [comment]
Ok Thanks

**Comment by amitbartfeld** [comment]
The TegraRcmGUI is crashing.
and with the RCMLoader The screen stays black...
:/

**Comment by CTCaer** [comment]
Yeah the issue is not hekate then.

This binary is a simple hw init (without sd stuff or extra, no bpmp freq change or dram freq).
If it doesn't work, the issue is in your cable or loader or your usb port, or VOL/Jig buttons.

**Comment by amitbartfeld** [comment]
Ok thank you very much!
