### ISSUE TITLE
Suggestion: Need SD exFat support 

### ISSUE THREAD

**Issue by tonyalfaro** [CTCaer/hekate#375]
I use EmuNand over partition (I have 2 partition on my SD):

1. First is for Nand over partition.
2. Second is for files, games, folders...

When I use fat32 atmosphere run normally but when I use exFat atmosphere not run and stuck on black screen

**Comment by urherenow** [comment]
Did you chose the correct option when updating your emunand with choi? Try again, and chiose exfat one.

**Comment by CTCaer** [comment]
Nothing to do with hekate, emuMMC and atmosphere.
As @urherenow pointed, you are probably missing the exFAT microupdate, which can be installed with choinx
