### ISSUE TITLE
Atmosphere wont boot unless emunand is disabled in hekate

### ISSUE THREAD

**Issue by Cubuss** [CTCaer/hekate#376]
Im trying to setup emunand with hekate +atmosphere, But am not able to boot atmosphere whenever emunand is enabled in hekate, Im able to boot into sysnand just fine , whenever i try to boot atmosphere with emunand enabled it shows the atmosphere splash/load screen then it goes to a black screen, after that it will get stuck on the Nintendo Switch logo,

Using latest Atmosphere and hekate as of today, also using SD file emunand , fat32

**Comment by CTCaer** [comment]
File based is extremely slow. It can take 2-8min to boot depending on sd card.
Switch to partition based or wait for the new emummc changes
