### ISSUE TITLE
Hekate can't create sept/payload.bin if there is no sept folder

### ISSUE THREAD

**Issue by friedkeenan** [CTCaer/hekate#377]
Trying to boot without the sept folder will result in a quick flash of `[FatFS] Error: FOV` after saying it unpacked and loaded the components from fusee-secondary, and then will freeze at a pure black screen.

**Comment by CTCaer** [comment]
Fixed in https://github.com/CTCaer/hekate/commit/281e5a138efd6806eb6f3f05305388b30cde024c
