### ISSUE TITLE
Add FORCE ERASE for eMMC

### ISSUE THREAD

**Issue by CTCaer** [CTCaer/hekate#38]

**Comment by LiamMCW** [comment]
Can #18 be undone? And does this remove the password and let you restore?

**Comment by fennectech** [comment]
No.    Force erase cannot be undone other than restoring a nand backup.   What this does is erase the nand and remove the password allowing you to read and write to the nand again.

**Comment by fennectech** [comment]
Imagine a password protected nand as a Locked chest and breaking the lock automatically destroys whats inside.   What this does is break the lock destroying whats inside allowing you to put a new copy of the stuff inside your chest and not lock it.

**Comment by LiamMCW** [comment]
In in issue #18, he said that it would be possible to stop the password locking of SX OS. After doing this, could I undo this and allow my nand to by password locked?

**Comment by fennectech** [comment]
Oh.  Probably.   The force erase command should in theory work too.

**Comment by fennectech** [comment]
Worst case scenerio you need to spend 10$ on a new nand and restore your backup to it.

**Comment by CTCaer** [comment]
I chose not to follow https://github.com/CTCaer/hekate/issues/18 for many reasons.
The most important reasons are that it is identifiable and irreversible.
If you disable any locking mechanism, you also disable the erasure mechanism.
It can be seen by nintendo.

**Comment by fennectech** [comment]
Well.  You can easily reflash a replacement nand.  
https://www.ebay.com/i/163037793227?chn=ps&ul_ref=https%253A%252F%252Frover.ebay.com%252Frover%252F1%252F711-117182-37290-0%252F2%253Fmpre%253Dhttps%25253A%25252F%25252Fwww.ebay.com%25252Fi%25252F163037793227%25253Fchn%25253Dps%2526itemid%253D163037793227%2526targetid%253D313776934696%2526device%253Dt%2526adtype%253Dpla%2526googleloc%253D9020101%2526poi%253D%2526campaignid%253D833559251%2526adgroupid%253D39417365901%2526rlsatarget%253Dpla-313776934696%2526abcId%253D1123856%2526merchantid%253D101829820%2526gclid%253DCjwKCAjwspHaBRBFEiwA0eM3kWOfSkiT6vmjIE5U0GESqkkAD6TwPMl72HAc9Mw_abLCxus-2RJGZRoCNUUQAvD_BwE%2526srcrot%253D711-117182-37290-0%2526rvr_id%253D1594069142254%2526rvr_ts%253D8641a1be1640a88a9cd17ffafff957f7

For 20$ you can reverse this then.

**Comment by LiamMCW** [comment]
Thank you for explaining. I think I understand now.

**Comment by CTCaer** [comment]
We still need this?
Should we give the cmd code to malicious script kiddies?
