### ISSUE TITLE
Blue Screen when Booting into sys CFW/Stock. AutoRCM doesn't work properly.

### ISSUE THREAD

**Issue by Sasan16** [CTCaer/hekate#382]

**Comment by CTCaer** [comment]
HOS 10.0.0?

**Comment by cezar1984** [comment]
i have a problem, i updatet to 10.0.0 and after launch emu mmc is  failed to apply nosigchk.I copied atmosphere 11.1 and hekate 5.1.4 on micosd.....please help.....

**Comment by DeadDr4gon** [comment]
Hey i habe the same problem. Just updated my switch. I've downloaded everything whats needed and put it where it belongs. After booting into sys cfwthere are 2 screens showing up (as normal) and then a light-blue screen

**Comment by CTCaer** [comment]
Remove the piracy nosigchk line and use better configs. Any issue from here on that is related with that will closed.

@DeadDr4gon update atmosphere to 0.11.1
