### ISSUE TITLE
Nosigchk and black screen!

### ISSUE THREAD

**Issue by fred170491** [CTCaer/hekate#384]
I have updated my switch to 10.0 and I made atmosphere and Hekate newest updates.

After Injecting Hekate, and booting custom eMMC I get the nosigpatch check problem.

I tried to delete the code line, I don't get this problem anymore but after loading atmosphere et get a black screen. I

What is wrong with what I did?

**Comment by CTCaer** [comment]
Also update atmosphere.

**Comment by fred170491** [comment]
I did!

**Comment by fred170491** [comment]
I made it work. Just deleted the entire atmosphere folder and replace it by the new one!
