### ISSUE TITLE
Black screen when creating new sd based partition

### ISSUE THREAD

**Issue by mbamber1986** [CTCaer/hekate#385]
Heya All i have created a sd based emmuc on hekate when its completed and i have chosen the actual partion when i boot it does the ams and sept loading screens but then a black screen after failing to boot the rest of the way

**Comment by CTCaer** [comment]
Get me a screenshot or photo of Console info -> sd card in Nyx

**Comment by mbamber1986** [comment]
Hello thanks for your response as i explained i have managed to create a sd partition based emummc  however the sd file based one creates but does not  load after the atmosphere arrow logo and just g
![IMG_20200419_084209](https://user-images.githubusercontent.com/30671636/79682546-1cf88b80-821b-11ea-9ae7-8d771488fde3.jpg)
ives a black screen
![IMG_20200419_082053](https://user-images.githubusercontent.com/30671636/79682517-e753a280-821a-11ea-9bbd-fc5eb2660753.jpg)
![IMG_20200419_082053](https://user-images.githubusercontent.com/30671636/79682538-0f430600-821b-11ea-9511-4b92c8a1f42c.jpg)
![IMG_20200419_083413](https://user-images.githubusercontent.com/30671636/79682539-14a05080-821b-11ea-99dd-dc02e90c9df6.jpg)
![IMG_20200419_083615](https://user-images.githubusercontent.com/30671636/79682543-1833d780-821b-11ea-9279-2074e18b0fb0.jpg)


Sorry after reading original message seems confusing the issue is with sd file based not partition based

**Comment by deadair3210** [comment]
Unless it changed recently, file based emunand is incredibly slow compared to partition based or sysnand, it might still be loading , just veeeeery slowly

**Comment by masagrator** [comment]
Yup, I confirm. File based is very slow.

**Comment by CTCaer** [comment]
Yep, sd **file** based just takes forever to load. Especially with a U1 card.
You can try a **partition** based or wait around a week.
