### ISSUE TITLE
No mandatory warmboot or secmon provided.

### ISSUE THREAD

**Issue by fennectech** [CTCaer/hekate#386]
After updating to the latest hekate and atmosphere last night ( 0.11.0 ) i am running into “no mandatory secmon or warmboot provided”. The issue still happens on 0.11.1. I’m able to boot. By chainloading fusee-primary from hekate but i cant boot atmo directly.  My Google fu has failed me.

**Comment by CTCaer** [comment]
Your ini is wrong then. This can only happen if fss0 is malformed or if you use the kips way, you forgot to set `secmon=` and `warmboot=` keys

**Comment by fennectech** [comment]
i was commenting out the nosigchk with # instaid of ;   Thats where my problem is.

**Comment by skudi** [comment]
I've just made the same mistake when commenting lines in /bootloader/hekate_ipl.ini thanks for this tip :)

**Comment by frntn** [comment]
Hello traveller from the future.
Same issue, same fix : I removed my "#" starting lines from the ini file

**Comment by Blumpkus** [comment]
> Your ini is wrong then. This can only happen if fss0 is malformed or if you use the kips way, you forgot to set `secmon=` and `warmboot=` keys

explain this in dummy terms please

**Comment by fennectech** [comment]
Your hekate_ipl.ini is fucked or /atmosphere/package3 is corrupted

**Comment by urherenow** [comment]
Why are you commenting on an issue that was closed FOUR YEARS AGO? Boot semi-stock or stock, or even to OFW from within nyx, then reboot to CFW. Remove cal0blank=1 if you intend to use fw 17.0.1, and setup dnsmitm.

https://gbatemp.net/threads/quick-one-on-atmosphere-dns-mitm-feature.587581/
