### ISSUE TITLE
Updated hekate and atmosphere by dropping the newest versions of both into my sd card and now cant boot.

### ISSUE THREAD

**Issue by jafooleZ** [CTCaer/hekate#388]
When I try to boot into CFW (SYSNAND) it says "failed to apply nosigchk" and "failed to launch HOS". I've been up for hours trying to figure this out but I cant please help.

**Comment by deadair3210** [comment]
Sig patches are set up wrong. Piracy isn't supported, so you will have to figure out how to fix it yourself
