### ISSUE TITLE
Nyx supports Joy Con

### ISSUE THREAD

**Issue by chihwa** [CTCaer/hekate#391]
It would be great if Nyx supports Joy Con for the consoles that have touchscreen issues.

**Comment by urherenow** [comment]
Or docked...

**Comment by MilkiiJugs** [comment]
It would require drivers just made for that. May add too much consumption. Also, this is made for Issues, not suggestions. Maybe in the future?

**Comment by CTCaer** [comment]
Issues here are for feature requests also.

**Comment by MilkiiJugs** [comment]
My bad, I will correct that.

**Comment by fennectech** [comment]
Something like that is super low on the priority   Ctcaer has much more impactful features     Joycon support is more of a "Would be sweet but may never come"   Theres only so much that can be done in BPMP

**Comment by CTCaer** [comment]
https://github.com/CTCaer/hekate/releases/latest

**Comment by chihwa** [comment]
Wow. It's a surprise that you come up with the implementation this quick! Thank you very much. Big applause to CTCaer and the team! 👏 👏 👏  Thank you very much!

**Comment by fennectech** [comment]
Same.   I did NOT see this comming.   There has gotta be some voodoo going on here!!
