### ISSUE TITLE
Mass confusion with "stock"

### ISSUE THREAD

**Issue by borntohonk** [CTCaer/hekate#393]
referencing this: https://github.com/Atmosphere-NX/Atmosphere/issues/895

references to "stock" should be called "barebones-mode" or similar, as people are confusing the function as to booting "cleanly" into sysnand, and this misinterpretation seem to be common enough for people to spread it as common knowledge.

**Comment by CTCaer** [comment]
There's no way they will start checking exosphere. If they do, they will start causing fatals on OFW.

How ppl are calling their configs is not my concern actually. And as for the key, I won't start adding duplicate keys that do the same thing. If they want to call the boot entries that way, they can.
There's no misinterpretation. There are 3 places in here that tell what stock is. 3 of them. So, there are only ppl not reading. 

Stock in this case means stock OS. And that gets fulfilled.
Secmon (exosphere) is not the OS. It's above all. There's a reason it's called stock and not OFW.
Barebones is completely wrong as a name.

Anyway it's as simple as that.
Make proper configs (no patches/nogc/kips/etc) and update your stuff.
10.0.0 via stock option (exosphere 0.11.1 for HOS 7.0.0 and up) works.
