### ISSUE TITLE
Failed to init card, fatfs error 13 with kosmos hekate

### ISSUE THREAD

**Issue by pitrako** [CTCaer/hekate#395]
Bad or old 8GB microsd hc Toshiba card? (or card slot?), missing sleep mode and minerva libraries. and failed to mount card, any help?

**Comment by ebiak** [comment]
try mounting your sd card on your pc if it doesn't work on your pc either, then you probably have a dead sd card if it works then check the files and make sure they are complete and if it still doesn't work then try another working sd card and if THAT doesn't work then you may have a faulty card slot

**Comment by ebiak** [comment]
try mounting your sd card on your pc if it doesn't work on your pc either, then you probably have a dead sd card if it works then check the files and make sure they are complete and if it still doesn't work then try another working sd card and if THAT doesn't work then you may have a faulty card slot

**Comment by urherenow** [comment]
What version of Kosmos? 15.5 was messed up. Try 15.6. But test your sad card first...

**Comment by pitrako** [comment]
Sometimes It loads correctly like now:
![IMG_20200421_183714](https://user-images.githubusercontent.com/42267151/79890799-4fafa900-8400-11ea-93bf-2f91fc5feb9c.jpg)
But other times shows the errors mentioned above.

**Comment by pitrako** [comment]
I'm in version 15.6, in pc windows always detects the card.

**Comment by masagrator** [comment]
There is a chance that your sdcard slot is broken. Just boot to system, check if your sdcard is detected and try slightly slap it where is sdcard slot. If Switch will show that sdcard was ejected, sdcard slot is broken.

**Comment by CTCaer** [comment]
If you managed to boot Nyx even once, it means that your sd card is supported (HC as you said).
Based on the photo, it is also legit.

So yeah, as said here, it's probably your switch sd card reader.
Also no need to slap it... HOS will not crash so easily if it's in 1bit mode. Just open the back cover and press on the black padding you see there. Add some extra to be sure. Then close the back cover without screwing it back and do some tests (while holding it with similar pressure as it was closed).

**Comment by pitrako** [comment]
I tried exfat with only goldleaf and kosmos toolbox, made atmosphere crash various times by trying to update goldleaf without internet connection by pressing the home button, and rebooting to hekate various times and It not corrupted (before It corrupted often with crashing and rebooting to hekate with FAT32), I think It's more stable now (no fatfs errors or failed to init sd card for now, weird, because I'm using exfat now).
