### ISSUE TITLE
kosmos pkg2 decryption failed

### ISSUE THREAD

**Issue by btcioner** [CTCaer/hekate#396]
https://s1.ax1x.com/2020/04/26/JcbunK.jpg
https://s1.ax1x.com/2020/04/26/Jcb1tH.jpg
https://s1.ax1x.com/2020/04/26/JcbP7F.jpg

**Comment by CTCaer** [comment]
Your pkg1 is HOS 5.x.0.
If pkg2 decryption fails, that must mean that your pkg2 is not 5.x.x.
