### ISSUE TITLE
Was that why I was driving txos's automatic rcm backup?

### ISSUE THREAD

**Issue by luhongtao** [CTCaer/hekate#40]
If there's a problem backing up firmware, is there no way to recover it?

**Comment by CTCaer** [comment]
I said that this is not a discussion forum. And especially for other software, which is pirate tool.

I'll only say this:
Any AutoRCM feature must be disabled from the software that enabled it.
hekate, Briccmii and probably SX OS, have different ways of corrupting BOOT0's BCT.

But you can still boot with hekate when in AutoRCM.
