### ISSUE TITLE
wrong emuMMC Nintendo path when using "emupath" key

### ISSUE THREAD

**Issue by HookedBehemoth** [CTCaer/hekate#401]
https://github.com/CTCaer/hekate/blob/master/bootloader/storage/emummc.c#L108
The custom emupath get's overwritten with /Nintendo instead of appending it.

**Comment by CTCaer** [comment]
Just a reminder that users should avoid using `emupath` key until this is fixed!

Because that update is huge, I will gather more bug reports and then release a cumulative hotfix.

**Comment by CTCaer** [comment]
Fixed in v5.2.1.
