### ISSUE TITLE
Partition Manager : emuMMC (RAW)

### ISSUE THREAD

**Issue by deejay87** [CTCaer/hekate#404]
Hi
I'll do somes tests :
Don't know if it's an issue but can't create a partition for emumcc , only linux and android can be set with the slider

**Comment by CTCaer** [comment]
If you have a small sd card < 32GB, that's why probably. Or you didn't move the slide to middle place.

**Comment by deejay87** [comment]
no it's 128go

**Comment by CTCaer** [comment]
Did you put the slider to the middle?

**Comment by deejay87** [comment]
the red slider don't move

**Comment by CTCaer** [comment]
Well it's not a bug. It works like that.
You need to catch the red and move it to middle.
If you leave it before middle, it will return back.

I will check if I can mitigate that, but don't expect anything. This is how the GUI lib works.

**Comment by deejay87** [comment]
yes but like i say you can't move at start, you have to clic to middle directly

**Comment by CTCaer** [comment]
Again, that's how it works. **It doesn't move**.
It **only** moves when your finger reaches the middle.

**Comment by deejay87** [comment]
ok thanks :), i continue to test

**Comment by CTCaer** [comment]
Catch the red circle with your finger and move it left and right without removing you r finger.
You will get what I mean.

**Comment by deejay87** [comment]
yes i have understand, have to slide very large to the middle and it move, now i'm testing install of the 2 emummc now

**Comment by deejay87** [comment]
Perfect 2 emunand is ok :+1:

**Comment by CTCaer** [comment]
>yes i have understand, have to slide very large to the middle and it move

Yeah exactly

**Comment by deejay87** [comment]
Just one question to finish this perfect test, possible to setup on hekate_ipl.ini to launch RAW1 and RAW2 here, and not going on "Change emuMMC"
Thanks

**Comment by CTCaer** [comment]
@deejay87 That was supposed to work on 5.2.0 with the `emupath` key.
But I have a bug and it doesn't work.

I'm currently collecting bugs, so I can fix them in about 3 days.

**Comment by deejay87** [comment]
oki perfect, when it's done i test, have one sdcard ready :+1:
