### ISSUE TITLE
[Feature request] Promt save if user leaves options with pending changes

### ISSUE THREAD

**Issue by HookedBehemoth** [CTCaer/hekate#405]
Currently set options will get discarded when you leave nyx without selecting "Save Options".

**Comment by CTCaer** [comment]
What about removing the button, and ask user if a save changes is wanted (if any changes), when they leave the options tab.
If yes -> saves
If not-> restores from ini
Like in games.

**Comment by fennectech** [comment]
That sounds better actually

**Comment by CTCaer** [comment]
Added in v0.9.1
