### ISSUE TITLE
[Feature request] Disable emuMMC if resolving emupath wasn't successful

### ISSUE THREAD

**Issue by HookedBehemoth** [CTCaer/hekate#407]
Currently when setting an invalid `emupath` it will fall back to the path set in the emuMMC config.

My suggestion is that on [emummc_set_path](https://github.com/CTCaer/hekate/blob/master/bootloader/storage/emummc.c#L103) when neither file was found that it should disable emuMMC or halt boot in some way.

I also think that `emupath` should imply `emummcforce=1` to prevent accidental boot to NAND.

**Comment by CTCaer** [comment]
I believe that the best behavior is to stop the booting completely if emummc is not found in that case.

**Comment by CTCaer** [comment]
Added in v5.2.1.
