### ISSUE TITLE
USB eMMC Mount Settings

### ISSUE THREAD

**Issue by x7l7j8cc** [CTCaer/hekate#414]
Could you put an option to always set the Read-Only to OFF or ON, when mounting the eMMC (both sys and emu)?
Which can be saved/edited in the hekate ini file, example "usbmmcro=0" (0 off, 1 on).

Because I always forget to activate it.

**Comment by CTCaer** [comment]
I will but I will not expose it. You will have to manually edit nyx.ini
I prefer users that do not know what they are doing to get denied and users that know to reconnect with read only off.

**Comment by x7l7j8cc** [comment]
Its okay for me... better than nothing. ;)

**Comment by CTCaer** [comment]
Added in v0.9.1.
