### ISSUE TITLE
Changing EmuMMC ini to boot different payload crashes

### ISSUE THREAD

**Issue by OldGnashburg** [CTCaer/hekate#425]
I want to use the main configs menu to boot Atmosphere, I also want to use fusee-primary without having to navigate the payloads menu. So I decided to throw fusee-primary, in the atmosphere folder and change the path to match it and when I go to boot EmuMMC, it fails. Is this bug or am I doing something wrong

**Comment by CTCaer** [comment]
You can't control other payload's configuration via hekate. All related keys are for hekate only.
fusee-prim will read and do what emummc.ini says. If emummc.ini has it enabled and it fails to boot, either you use file based and that takes currently too long to boot via fusee-prim or it's missing/corrupted.
