### ISSUE TITLE
Launching Atmosphere creates Cyan Screen

### ISSUE THREAD

**Issue by Urbanxx001** [CTCaer/hekate#426]
I'm not sure on which end this is an issue (hekate, atmosphere, or user error), but when I launch Atmosphere, first it flashes the hekate logo and then an unresponsive bright cyan screen. Thankfully I can exit it by holding the power button, but I searched onlne and found no mention of this particular issue. Previously I had the 'old nyx gui found there will be dragons' warning but I believe it's resolved after updating hekate on the SD root. I've tried the following:

Updated both Hekate and Atmosphere, on SD card and payload injector
Recreated Emu on SD partition
Removed 'kip1patch=nosigchk' and 'kip1=atmosphere/kips/*' lines in hekate_ipl.ini
Removed CFW (Edizon, Goldleaf, etc.)

**Comment by CTCaer** [comment]
Did you updated your emummc with choinx?
If yes, check that your pkg1 and pkg2 match.

**Comment by Urbanxx001** [comment]
I don't use ChoiNX, only updated using the SD card, RCMloader brand injector, and (initially) Tegra.

**Comment by CTCaer** [comment]
Normally issues with blue screen are because of mismatches or corruption.

Can you get a photo or screenshot of Console info -> Sd card?

**Comment by Urbanxx001** [comment]
Here's the SD info: [https://imgur.com/a/H3OyofV](url)

**Comment by CTCaer** [comment]
Sd card seems legit. Only issue is that it says A2. And you can't have A2 on a U1/V10 card.
(Also sandisk doesn't make such cards.)

Can you take a macro photo of the sd card with good lighting?
Also try the h2testw or another sd card checker.

**Comment by Urbanxx001** [comment]
After inspecting, you're right the info says A2 even though the card is A1. Here it is: https://imgur.com/a/LmatNVN

I don't know if the discrepancy was before or after the update, but I was able to use EmuNand before. I'll run the h2testw and report back. Thank you so much for your help

**Comment by CTCaer** [comment]
In case the test is good:
Have in mind that normally a blue screen happens when there's pkg2 mismatch or sth went wrong with the update.
Maybe you can try to manually re-update to 10.
