### ISSUE TITLE
File-based emunand stuck on NS bootlogo

### ISSUE THREAD

**Issue by rashevskyv** [CTCaer/hekate#428]
Tried to make Emu with SX and with hekate - same result. Tried exFAT and FAT32. 
10.0.2, ATM 0.12.0

EmuNAND was made by nyx 0.9.1

When I tried to downgrade hekate and Nyx to previouse stable (5.1.4-0.8.7), there is no NS bootlogo at all. Black screen after Atmosphere's white triangle.

**Comment by CTCaer** [comment]
How you created it?
File based or partition based?

Show me a photo or screenshot from Nyx **0.9.1** > Console info > Sd card

**Comment by rashevskyv** [comment]
File-based. 
Partition-based works without issues

**Comment by rashevskyv** [comment]
I tried different cards

Samsung EVO 64 FAT32:
![изображение](https://user-images.githubusercontent.com/18294541/81469471-a6352980-91ed-11ea-82ec-94e6dab61893.png)


SanDisk Ultra 128 exFAT:
![изображение](https://user-images.githubusercontent.com/18294541/81469443-89005b00-91ed-11ea-8803-6e344a31c688.png)

**Comment by Viperbite** [comment]
![screen_025C52B4](https://user-images.githubusercontent.com/47257874/81469485-5f433600-91e5-11ea-85cd-8e117b69594e.jpg)
Similar problem, file based emunand stops after the Nintendo logo. Created in the CX OS or via Hecate. Tested for FAT32 and exFAT.

**Comment by CTCaer** [comment]
All cards are legit.
How you boot it? I need the boot entry used in the .ini

**Comment by rashevskyv** [comment]
```
[config]
autoboot=1
autoboot_list=0
bootwait=3
customlogo=1
verification=2
backlight=40
autohosoff=0
logopath=bootloader/bootlogo.bmp
autonogc=0
{ }
[Atmosphere]
payload=bootloader/payloads/fusee-primary.bin
{ 
```}

Partition-based boots fine with this ini

Cards are legit, but I can test it with h2testw if you need

**Comment by CTCaer** [comment]
Well, there's your issue. emuMMC code is something that bootloader injects.
Each bootloader has its own method.
For now the fast file-based can only be attained by using hekate to boot atmosphere (fss0 or the old kip style).
If you still want to use fusee-prim to boot, just wait some minutes and it will boot. Or wait until it gets updated.

Also your config needs cleaning. Go to options tab (last tab) once and press save options to fix it.
