### ISSUE TITLE
beckaup emmc

### ISSUE THREAD

**Issue by kristal91** [CTCaer/hekate#429]
hi is it possible to create a beckaup from an emmc that I have on the sd and restore it on the original nand? I broke the nand and I don't have the beckaup automatically so it would be beckaup from the emmc I have and restore it

**Comment by CTCaer** [comment]
Yes you can. What type of emuMMC you have?

**Comment by kristal91** [comment]
i have emmc created by hekate

**Comment by CTCaer** [comment]
file based or partition based?

**Comment by kristal91** [comment]
partition based

**Comment by CTCaer** [comment]
Go to backup and press the button on the bottom. The one that enables SD raw based partition.
The buttons will change names from eMMC to emuMMC.
Backup both boot0/1 and raw GPP.

**Comment by kristal91** [comment]
after the beckaupnsd emummc raw reset the state from sd to nand and restore the beckaup on the nand?

**Comment by CTCaer** [comment]
you need to move the files into the restore folder

**Comment by kristal91** [comment]
okok now i feel thank you

**Comment by CTCaer** [comment]
You probably already finished your restoration project.
Closing issue.

**Comment by kristal91** [comment]
yes thanks
