### ISSUE TITLE
Checksums do not mutch when mount BOOT0\1 with hekate 

### ISSUE THREAD

**Issue by rashevskyv** [CTCaer/hekate#430]
Trying to write Boot0\1 with etcher, but got an error: 

![image](https://user-images.githubusercontent.com/18294541/81475237-9fb9a880-9213-11ea-8471-198a7b869d05.png)

Nyx 0.9.1, hekate 5.2.1, Read-Only is OFF 

With memloader_v3 all going well:

![image](https://user-images.githubusercontent.com/18294541/81475347-35edce80-9214-11ea-8d76-4dea9871fad9.png)

**Comment by CTCaer** [comment]
Which etcher version?

**Comment by rashevskyv** [comment]
It was 1.5.76
On the last version I got this - 

![изображение](https://user-images.githubusercontent.com/18294541/81480460-a9063d80-9232-11ea-8f92-0ed53ef6d4bf.png)

**Comment by CTCaer** [comment]
Just found time to test and do wireshark dumps.

Issue is that it works splendidly here (balenEtcher v1.5.86):
![image](https://user-images.githubusercontent.com/3665130/81489458-3d49c200-927e-11ea-8238-b9e33c57f7f4.png)
Wireshark dumps are also perfect. No issues or retries.

Have in mind that hekate is more strict with cable issues. It can detect a disconnection immediately.
Check that your cable and its connectors are fine.
(Btw, I did the tests with a nintendo cable and another 2 which were usb2 and usb3, both with proper cable impedance.)

As for the strictness, I can try to ease it up in next versions.
For now, try to keep your cable steady and make sure that is nicely connected.
