### ISSUE TITLE
[Enhancement] Backup eMMC and emuMMC via USB

### ISSUE THREAD

**Issue by NickHam13** [CTCaer/hekate#431]
First things first, I'm sorry if this is already a feature and I've somehow missed it, or already a planned addition.

I think the option to backup your eMMC and emuMMC via USB would be a great quality of life feature. I don't have much space left on my SD card but would still like to make full backups directly to my PC without going through the trouble of joining all the files. 

And to end things off, thank you for your continued work on this project. I'm excited to see what you have in store for this year.

**Comment by CTCaer** [comment]
Hi.
This is already supported.

Tools -> USB Tools -> Choose an eMMC or emuMMC button -> Use a tool to backup the mounted disk.

**Comment by NickHam13** [comment]
Is there a specific tool you can recommend for this?

**Comment by CTCaer** [comment]
There are many and depend on your OS

**Comment by leandrodeassis** [comment]
> Is there a specific tool you can recommend for this?

I suggest NxNandManager
