### ISSUE TITLE
[bug] Cursor is not centered

### ISSUE THREAD

**Issue by masagrator** [CTCaer/hekate#432]
I'm using Hekate 5.2.1 / NYX 0.9.1 and accidentally discovered that cursor is not centered. Touch point is somewhere in left upper corner outside of drawed circle. It may result in pushing wrong options.

**Comment by CTCaer** [comment]
Well the reason I left it like that was because you can't actually push the wrong thing easily.
But I guess I can put some +- 16

**Comment by CTCaer** [comment]
Fixed in latest release
https://github.com/CTCaer/hekate/releases/latest
