### ISSUE TITLE
[Feature request] Autoboot sysnand instead throughing error when emummcforce=1

### ISSUE THREAD

**Issue by rashevskyv** [CTCaer/hekate#433]
Please make optional autoboot in sysnand instead throughing error when emummcforce=1

**Comment by CTCaer** [comment]
Don't use `emummcforce=1` if you want that behavior.

**Comment by rashevskyv** [comment]
But when I do not use `emummcforce=1` I boot to sysnand even if emunand enabled in hekate

**Comment by CTCaer** [comment]
That's not possible if hekate is used to boot CFW. Except if you use `emummc_force_disable=1`.
You might need to fix your hekate ini with proper values.

**Comment by rashevskyv** [comment]
My bad. For behavior I want to see I haven't use emummc_force_disable or emummcforce at all, so hekate would boot to emunand when its enabled on hekate and boot to sysnand when emunand is disabled. Thank you for your time!
