### ISSUE TITLE
About SD cards partitions management

### ISSUE THREAD

**Issue by LeyendaV** [CTCaer/hekate#439]
Yesterday, I made a partition for Android using the tool for SD partitions management that comes within Hekate. I had this idea about installing LinageOS in the same SD card I already have Atmosphere and everything else, but in the end I decided to wait for now.

Thing is, the partition was already made at that point (32 GB). Inside Windows, you can't see nor access that partition in any way, and for I can see, inside Hekate you don't have any option to resize/delete partitions, which means those 32 GB are lost if I don't partition and format the entire card again from scratch.
Would be nice to have this kind of options inside Hekate in a near future.

**Comment by CTCaer** [comment]
Resizing/Moving partitions will never be added to hekate.
Issue is that no library exists that works on baremetal. And I don't want to waste my free time to port one.
Especially when it would be painfully slow on BPMP (the super tiny cpu core that hekate runs on)
