### ISSUE TITLE
[Feature Request] Allow continuing boot process on nosigchk error

### ISSUE THREAD

**Issue by fennectech** [CTCaer/hekate#442]
Can you make it possible to continue booting on a nosigchk failure that way users can update their sigpatches ether over ssh or using an application. without having to get a USB out and sort it out manualy

**Comment by CTCaer** [comment]
Or don't pirate

**Comment by fennectech** [comment]
I dont pirate  use hoembrew NSPs  (and installed eshop dumps that i bought myself)
