### ISSUE TITLE
Soft-Brick After Creating emuMMC

### ISSUE THREAD

**Issue by cDOTwav** [CTCaer/hekate#443]
I'm having trouble with hekate and emuMMC. I had trouble with this in the beginning of me installing CFW and creating a emuMMC, in which it would just soft-brick when loading into Atmosphere, so I abandoned using hekate and just booted straight into Atmoshere. Flashforward to now and it's the same problem. It boots up fine when powering on to stock firmware, but when it comes to booting into CFW it just soft-bricks and I have to turn my Switch off. Any idea why this is happening? Maybe I'm missing a step?

**Comment by CTCaer** [comment]
Black screen is not a soft-brick.
What type of emummc you created? Also take a photo or screenshot from Console Info -> Sd card

**Comment by cDOTwav** [comment]
> Black screen is not a soft-brick.
> What type of emummc you created? Also take a photo or screenshot from Console Info -> Sd card

I saved it as an SD file 

![](https://cdn.discordapp.com/attachments/502208013487308800/716711829124022302/20200531_135417_HDR.jpg)

**Comment by CTCaer** [comment]
Your sd is legit.
Currently sd file based only works properly if booted natively via hekate.
In both cases you booted via fusee-prim (chainload via hekate also counts as not using hekate's native boot). You need to use the fss0 method.
