### ISSUE TITLE
Suggested Feature: Add confirmation prompt when booting CFW

### ISSUE THREAD

**Issue by StiraGHB** [CTCaer/hekate#444]
Hello,

I would like to suggest a possible feature that could be added to a future version to hekate. I think there should be a confirmation prompt when you select emuMMC or sysMMC. Basically something that says "You have selected emuMMC/sysMMC. Are you sure you want to continue booting CFW?" This is because I think it's entirely possible that someone can accidentally select sysMMC if they are trying to keep a clean eMMC or avoid Nintendo telemetry.

Thanks,
Cole

**Comment by CTCaer** [comment]
Hi there's 0 reason for that.

Open your hekate_ipl.ini and remove the boot section you don't want.
In your case it should be marked with a block starting with **[** *{text}* sysMMC **]**
