### ISSUE TITLE
[Bug]  Not able to launch HOS 10.0.4

### ISSUE THREAD

**Issue by tk1076408** [CTCaer/hekate#445]
Description:
System firmware: 10.0.4
Atmosphere: 0.12.0
Hekate: 5.2.1
SD card: Samsung EVO 64BG

A clean SD card, created emuMMC then launch shows error:
```
Failed to apply 'nosigchk'
Failed to launch HOS!
```

Let me know what else info that can help debug. Thanks!

**Comment by m4xw** [comment]
Kek

**Comment by deadair3210** [comment]
don't use sig patches and it will boot fine

**Comment by tk1076408** [comment]
> don't use sig patches and it will boot fine

With that config line removed, I am able to launch HOS, but after that, Goldleaf not able to install NSP from SD card. Reported issue here https://github.com/XorTroll/Goldleaf/issues/556
Do you think it’s related to this?

Thanks!

**Comment by CTCaer** [comment]
No piracy discussion here
