### ISSUE TITLE
Will not boot beyond the Hekate part of the chainloading process with Atmosphere 0.13.0

### ISSUE THREAD

**Issue by dothackjhe** [CTCaer/hekate#451]
Hekate 5.3.0 struggles to boot past the Hekate step in the chainloading process when using the files for Atmosphere 0.13.0.

Conversely, the system boots just fine with Atmosphere 0.12.0.

**Comment by CTCaer** [comment]
What do you mean precisely? What are the steps to reproduce that?

**Comment by dothackjhe** [comment]
I think this may be a false alarm. I have not have the time to test everything yet, but I think the fault lies in how I do the supposed chainloading. 

Based on another person's comment on GBATemp, I might be booting the game via a modified Atmosphere (CFW SYSNAND) by default, instead of fusee-primary.bin.

**Comment by CTCaer** [comment]
You have a wrong notion of what is chainloading.
Also your message implies piracy.

**Comment by dothackjhe** [comment]
So, I just tested the hypothesis provided to me. Apparently, there is indeed an issue with Hekate 5.3.0 having trouble chainloading fusee.primary.bin for Atmosphere 0.13.0.

**Comment by CTCaer** [comment]
Well the issue is not hekate. And that's why I said you have a wrong notion of chainloading.
You obviously have mixed files and expect 0.13 to run with 0.12 parts.
Also if your Atmosphere (CFW SYSNAND) was using hekate to boot, it would have just worked.

**Comment by dothackjhe** [comment]
I tried both ways: it did not work.
