### ISSUE TITLE
Unable to compile hekate payload - build error

### ISSUE THREAD

**Issue by raytan1807** [CTCaer/hekate#452]
![build error](https://user-images.githubusercontent.com/66457456/84753260-59651f80-aff1-11ea-86fb-de0ebb887355.jpg)
Hi, not sure if anyone facing this error when trying to build the file but previously I have no encounter any error when building the hekate v5.2.1 & Nyx v0.9.1. I run cmd as administrator and put in the "make" command and execute makefile in the source directory. Sorry, not sure whether is it appropriate to post and ask here but appreciate if someone could help. Thanks.

**Comment by CTCaer** [comment]
What's that? msys?
(Because it works on linux and wsl1)

**Comment by raytan1807** [comment]
msys2, I set up the building environment using devkitpro 3.0.3. does it support that ? as I was able to just build it without any error for the last version. thanks for your quick reply :)

**Comment by CTCaer** [comment]
Fixed with https://github.com/CTCaer/hekate/commit/c5f032fcb2cd6eba9899249387ee736ef1ebdcf8

**Comment by raytan1807** [comment]
Thanks for the quick fix !! I can build without issues now !! :D
