### ISSUE TITLE
error chainloading fusee primary "0100000000000003"

### ISSUE THREAD

**Issue by MichaelRebirth** [CTCaer/hekate#453]
on latest hekate: 

[Fusee/AMS v0.13.0S]
payload=fusee-primary.bin
kip1patch=nosigchk
atmosphere=1

got an error "0100000000000003" (after sept logo)

**Comment by CTCaer** [comment]
When you chainload a payload, the moment you see the screen turn off (after bootlogo for Launch method) it already left hekate.
So you need to ask in atmosphere repo. Also your config has random stuff inside.

**Comment by MichaelRebirth** [comment]
Thanks
