### ISSUE TITLE
[Feature Request] Redirecting /atmosphere/ (or any arbitrary folder/file) to another path

### ISSUE THREAD

**Issue by FusionFernia0000** [CTCaer/hekate#457]
Related reference: https://github.com/Atmosphere-NX/Atmosphere/issues/704

The idea is to achieve booting separate atmosphere instances (that can contain different LayeredFS / kip / exefs / nxthemes patches / saves redirection / or even an entirely different version of Atmosphere ) so as not to interfere with other eMMC instances, by utilizing [m4xw's SDMMC driver](https://github.com/CTCaer/emuMMC) (somehow) (also since support for /Nintendo folder redirection to a arbitrary path is already in place for a while now).

For configuration, this would preferably be done in hekate_ipl.ini per boot entry (concept as shown):

> redirect_path= "source" "destination"

> in hekate_ipl.ini :
>
>[emuMMC instance 1]
_emupath=emuMMC/RAW1_
fss0=emuMMC/RAW1/atmosphere/fusee-secondary.bin 
atmosphere=1
**redirect_path="emuMMC/RAW1/atmosphere/" "atmosphere/"**
>
>[emuMMC instance 2]
_emupath=emuMMC/RAW2_
fss0=emuMMC/RAW2/atmosphere/fusee-secondary.bin
atmosphere=1
**redirect_path="emuMMC/RAW2/atmosphere/" "atmosphere/"** 

The preferred outcome would be when Horizon is reading from and writing to /atmosphere/, its actually accessing "/emuMMC/RAW1/atmosphere/" (as an example).

Other related details:
> From [Atmosphère 0.10.4](https://github.com/Atmosphere-NX/Atmosphere/releases/tag/0.10.4)
>- Stratosphere system modules now use new Nintendo-style FS bindings instead of stdio.
>- This also lays the groundwork for changes necessary to support per-emummc Atmosphere folders in a future update.

> From [Atmosphère 0.10.0](https://github.com/Atmosphere-NX/Atmosphere/releases/tag/0.10.0)
>- ams.mitm was rewritten as part of Stratosphere's refactor.
>Saves redirected to the SD card are now separated for sysmmc vs emummc. ____(Though not sure how it works)

>From [Atmosphère 0.9.0](https://github.com/Atmosphere-NX/Atmosphere/releases/tag/0.9.0)
>- In addition, some niceties (e.g. having a separate Atmosphere folder per emummc instance) still need some thought put in before they can be implemented in a way that makes everyone happy.

**Comment by CTCaer** [comment]
Hekate has nothing to do with that. The support must come from the cfw side.

Something that you can do is to replace all these folder strings and **recompile** atmosphere. This way you can have atmo1, atmo2, etc folders. Like how some people opted to do, in order to have different atmosphere folders for sys and emu.

Also the fusee-secondary.bin file for fss0, doesn't matter where it is. hekate can launch it from anywhere. The issue as I said is that the kips from inside fusee-secondary.bin have the folders hardcoded.

Anyway, there's nothing I can do.
