### ISSUE TITLE
cannot run

### ISSUE THREAD

**Issue by sandbox404** [CTCaer/hekate#459]
I have a SX Core installed NS, I want to run hekate, but when I run the payload via the SX OS, the screen goes black, what should I do?

**Comment by r1cola** [comment]
it's unlikely you'll receive support when using that kind of product...

**Comment by sandbox404** [comment]
> it's unlikely you'll receive support when using that kind of product...

Why? There’s no other jailbreak solution for patched NS.

**Comment by CTCaer** [comment]
hekate doesn't have t210b01 currently
