### ISSUE TITLE
[Feature request] Mount directly a Specific Partition

### ISSUE THREAD

**Issue by x7l7j8cc** [CTCaer/hekate#462]
Hi, as the title suggest, i wanted to know if its possible to put a "mount of a specific partition" of the NAND with Hekate.
For example, instead of mounting the entire NAND, i want to mount the USER partition or SYSTEM partition etc etc.
But, having only the mount USER partition option its good... 

If this is possible, it would be a nice addition.

**Comment by CTCaer** [comment]
I don't find a reason for that. Every single pc tool is supposed to work with physical disks and volumes. 
Also with so many partitions it will need so many buttons and I don't really want to waste time on coding GUI for this niche feature.
