### ISSUE TITLE
SD File based emuMMC not working when fusee-primary.bin is used (AMS 0.13.0)

### ISSUE THREAD

**Issue by jshsakura** [CTCaer/hekate#463]
`https://opencourse.tistory.com/439`
Unfortunately, there is no English version, so please refer to the photo only.
My SD Card's file system is FAT32.

First of all, thank you for making such a great program.
Cannot boot after creating SD File Type emuMMC

Currently in the latest versions of Atmosphere 0.13.0 and Hekate 5.3.0
A boot error occurs when using emuMMC based on SD File.

The payloed file used is fusee-primary.bin and the existing SD Partiton emuMMC runs fine without problems.
Is there a workaround for this?

**Comment by CTCaer** [comment]
Well hekate has nothing to do with anything after it gets chainloaded to something else.
The chainloaded payload takes complete control of the boot process. In that case, fusee-prim.

In your case I would check if it works via booting with hekate first and then redirect the issue to the atmosphere repo.

**Comment by CTCaer** [comment]
On the other hand I already checked v5.3.0 native boot compatibility with all firmware and the result is this:
v5.3.0 release:
- Boots all firmware with 0.12.0 atmosphere.
- Boots all firmware except 8.1.0 and 9.0.x with 0.13.0 atmosphere.

v5.3.0 fixed (https://github.com/CTCaer/hekate/issues/460#issuecomment-647030977):
- Boots all firmware with 0.12.0 atmosphere.
- Boots all firmware with 0.13.0 atmosphere. Including 8.1.0/9.0.x

So I will change the issue name but still wait for a validation from you.

**Comment by KaimanDoro** [comment]
I am having the same issue as described; used latest Hekate, latest Atmosphere, file-based emuMMC, and fusee-primary is not launching.  Only difference is that I am using exFAT.  Both directly injecting and booting through Hekate fail.  Here is a screenshot:

https://i.imgur.com/bC5yiHd.jpg

Also this user on Reddit seems to be experiencing the same issue: https://www.reddit.com/r/SwitchPirates/comments/ek6ngh/cant_inject_fuseeprimary_black_screen/fvt6j63/

**Comment by CTCaer** [comment]
Well this is the wrong repo to report that.
Any issues with fusee-primary should be reported to the atmosphere repo.

Basically, all of you need to understand that when payloads button or payload= in ini is used, it is like injecting that payload.

You can report issues here, **if** hekate's **native** boot method is used. And hekate's native method works.

**Comment by jshsakura** [comment]
Thanks for the answer.
