### ISSUE TITLE
Add option to show bootlogo in launch screen

### ISSUE THREAD

**Issue by Ali-Asim800** [CTCaer/hekate#464]
I'm kind of surprised this isn't a thing but I definitely think that there should be an option to show the bootlogo in the launch screen as well as showing it normally on the main screen there is an option that  you can change in the nyx settings but when you save the setting it shows the bootlogo on the launch screen but once you exit out it removes itself , this Is very weird and should not even be included at all, if you wanted to implement a way to show the bootlogo on the launch screen then you should've done it properly, I always use tools and stuff like USB ums and want my bootlogo to show when I inject the hekate payload on the main first screen and on my launch screen permanently. Not permanently as in you can't change it, you should have an option for it to toggle on and off. Would like to please see this implemented in the new hekate release hopefully and hope you get back to me CTCaer, keep up the good work!

**Comment by CTCaer** [comment]
I will assume that this is a troll issue, especially from the tone of entitlement.
