### ISSUE TITLE
Add option to show background on main screen+launch screen

### ISSUE THREAD

**Issue by Cobra89** [CTCaer/hekate#465]
Launch and main screen should show the background,  right now the background disappears when you exit.
Had seen an issue like this before but don't know where it went so I've decided to put my own up.

**Comment by CTCaer** [comment]
This was answered before. You need to use a background bmp as described here: https://github.com/CTCaer/hekate/blob/master/nyx/README_RES.md and place it at `bootloader/res/background.bmp`

As for Launch to have it you need to select it as home screen in Nyx options. That's for performance reasons and lower complexity.
