### ISSUE TITLE
Black screen when injecting payload

### ISSUE THREAD

**Issue by AgentGalactic** [CTCaer/hekate#466]
I'm trying to install android on my switch following this guide: [](https://www.youtube.com/watch?v=HsJsSJ8CcRE)
But Hekate doesn't load on my screen and stays black. TegraRcmGui says it was successfully injected. 
I'm using a rcm jig from amazon I just got today
XAW101035XXXXX Don't know if you need that 
Drivers are installed and everything looks to be working except the black screen.
I've looked into this and others have the black screen but for other reasons

**Comment by CTCaer** [comment]
You can't mix old `bootloader` folder with a newer hekate.
The compatibility groups are 5.0.0 to 5.0.2 and 5.1.0 to latest (5.3.0).
The compatibility issue with libsys_minerva.bso. Old one (5.0.0-5.0.2 group) hangs latest (5.1.0-5.3.0 group).
