### ISSUE TITLE
SD-Card is initialized in 1-bit mode.

### ISSUE THREAD

**Issue by tegutistgut** [CTCaer/hekate#467]
Hello,
I have a SanDisk 128GB Microsd card and I'm running the latest version of Hekate.
When I boot into Hekate this error shows up: https://ibb.co/3f0gHZ4
Here is another picture:
https://ibb.co/tQ210fZ

My sdcard is formatted in Fat32

Thanks in advance

**Comment by CTCaer** [comment]
It's what you read on the pop up.
Your sd card reader is either not properly seated or a pin broke on the motherboard connector because of many ejections/insertions.

You can still use CFW and OFW. But the sd performance will be a mere 5MB/s until you repair that.

**Comment by tegutistgut** [comment]
So I can use cfw and emummc but it will be slow?

**Comment by CTCaer** [comment]
Yeah. Extremely slow on emuMMC which uses SD exclusively.

**Comment by tegutistgut** [comment]
Ok. Thank you very much for your help

**Comment by tegutistgut** [comment]
So today I opened my switch and I saw, that a pin is missing (like on this video: youtu.be/F4aNuKR8Ies)
Is there anything I could do except what that guy in the video does?

**Comment by impeeza** [comment]
Yes the only options are:

Repair the connector or use the alternative on vídeo.  a Hardware error can't be solved on software, if the SD doesn't have any of the Serial communications pins, will work on a 1-bit mode there is nothing to do.

**Comment by tegutistgut** [comment]
Ok thanks

**Comment by tegutistgut** [comment]
What if I use cfw sysnand? Would it be slow too if I play my dumped games (legally bought, of course) from my SD card?

**Comment by Masamune3210** [comment]
Literally anything that access the SD card will be extremely slow. If it's on the nand it's fine for the most part as the system doesn't mess with the SD much other than cfw

**Comment by tegutistgut** [comment]
Ok thanks

**Comment by tegutistgut** [comment]
Would sx os work with the missing pin?
I remember that ctcear said that this problem could be fixed with a update of Hekate, gut he wouldn't do it.

**Comment by impeeza** [comment]
It's a hardware issue no software can arround that.  The only way is get the hardware  fixed

**Comment by tegutistgut** [comment]
Ok thanks

**Comment by toastyishere21** [comment]
hello i use my ultra sandisk SD card fat32 im in 1 bit mode the sd card is speed is 6mb and it doesnt load cfw on the switch just blank screen when launched any possible ways to fix without buying another sd card if thats the case.

**Comment by impeeza** [comment]
Read all the post. There is nothing to do brside repair the software. Hekate can not suppor anymore 1 bit mode

**Comment by toastyishere21** [comment]
> Read all the post. There is nothing to do brside repair the so

 repair the hardware it surely isnt a software issue.

**Comment by impeeza** [comment]
> > Read all the post. There is nothing to do brside repair the so
> 
> repair the hardware it surely isnt a software issue.

Damn keyboard and autocorrector, thanks @toastyishere21 for make me to see the typo

**Comment by toastyishere21** [comment]
> > > Read all the post. There is nothing to do brside repair the so
> > 
> > 
> > repair the hardware it surely isnt a software issue.
> 
> Damn keyboard and autocorrector, thanks @toastyishere21 for make me to see the typo

i was looking through google and youtube mr. i saw that people factory reset their switches and said it would fix "faults" im amused that wouldnt work for the booting up cfw.
