### ISSUE TITLE
(Request) Upload fusee secondarys contents in the hekate source code.

### ISSUE THREAD

**Issue by Aliasim800** [CTCaer/hekate#470]
would please appreciate it if the contents of fusee secondary (kips, warmboot like lp0fw.bin, exosphere and other contents) would be uploaded into the hekate source code.

**Comment by Masamune3210** [comment]
....its an entirely separate project though, why would it be uploaded here?

**Comment by Aliasim800** [comment]
Because fusee secondary is part of hekate and fss0 uses it which is also part of hekate and the main booting process hekate uses.

**Comment by arch-box** [comment]
fusee secondary can be found here: https://github.com/Atmosphere-NX/Atmosphere/tree/master/fusee/fusee-secondary

**Comment by Masamune3210** [comment]
Fuses secondary is not part of hekate, it's part of atmosphere, just like fusee primary....

**Comment by bottmint** [comment]
You can easily get the contents of fusee-secondary by compiling atmosphere yourself.

**Comment by Aliasim800** [comment]
thats the point, you should be able to get its contents without compiling atmosphere because its a big part of hekates boot process, maybe its not entirely part of hekate but fss0 uses it.

**Comment by Masamune3210** [comment]
No. It's. Not.  

Hekate is a bootloader, it couldn't give to piles of manure what it's booting most of the time. Fss0 is part of the boot process because that's how the switch boots. It has nothing to do with hekate.  If you want easier access to a component of atmosphere, take it up with them.

**Comment by CTCaer** [comment]
FSS0 is Fusee Secondary Storage. That's a component of Atmosphere and not hekate's.
It is used to pack every HOS boot time replacements. Security monitor, warmboot binary and kips (for now).

hekate is a bootloader that supports **natively** booting anything that is open source.
I have 0 reason to fork something only to increase the build times for hekate from mere seconds to an hour.
Especially when it takes you 10s to download and drag n drop both releases and done.
Or just change the makefile of atmosphere to pack all kips and stuff into a folder for easy copy paste.
