### ISSUE TITLE
[Enhancement] Install running version of Hekate as reboot payload

### ISSUE THREAD

**Issue by clamintus** [CTCaer/hekate#471]
Hi, I thought it would be useful to have an option that replaces `atmosphere/reboot_payload.bin` with the current running Hekate bin payload, or maybe even a switch to make it automatically replace the reboot payload when a higher version of Hekate is injected

**Comment by r1cola** [comment]
this may already be implemented via the updater2p function...

**Comment by CTCaer** [comment]
This already exists in hekate. in Nyx got to Options tab and enable it. And read its description to see how it works.
