### ISSUE TITLE
SD & eMMC data (@LBA 00540000) do not match! Verification failed.. Please try again.. Failed!

### ISSUE THREAD

**Issue by thien302466** [CTCaer/hekate#472]
Hello! I followed https://nh-server.github.io/switch-guide/ to the letter, and when I tried to make a backup through "eMMC RAW GPP" it doesn't get past 9%! I am using a 256gb microSD card.

**Comment by thien302466** [comment]
Also when I press the "launch" option, and select FSS0, it shows a message for a split second before rebooting back to hekate menu. The message says unknown pkg1 version.

**Comment by impeeza** [comment]
Hi. Have you checked the sd using h2testw?

**Comment by thien302466** [comment]
I am checking as of now! Will keep you posted!

**Comment by thien302466** [comment]
Did you want me to test the WHOLE thing or just whats left?

**Comment by thien302466** [comment]
Only 63033 of 98116 is being tested right now, appox. 1h 30m should be the time

**Comment by impeeza** [comment]
yes if is big, can take lot of time, but you will be sure.  another question: is the SD formatted ExFAT or plain FAT?

**Comment by thien302466** [comment]
The only formatting I've done was https://nh-server.github.io/switch-guide/user_guide/emummc/partitioning_sd/ labeled "Format for emuMMC setup . I had to choose this because I had no idea how to update my cfw and other things in 2019, so all it did was delete everything...? Since I didn't know how to do anything, I just started copying and pasting randomly trying to replace things, so the last option I had was to delete everything... Then I followed this guide to reinstall everything, and here I am, with just these two problems: the mismatch, and the unknown pkg1 version.

**Comment by CTCaer** [comment]
Your sd card is probably fake.
Send me a screenshot (3 finger tap) or a photo Console info -> Sd card.

**Comment by thien302466** [comment]
How does one do that?

**Comment by CTCaer** [comment]
>Send me a screenshot (3 finger tap) or a photo **Console info -> Sd card**.

**Comment by thien302466** [comment]
I still don't know where that is... Unless you mean't data management?

**Comment by CTCaer** [comment]
In hekate menu.
![image](https://user-images.githubusercontent.com/3665130/89272212-7eb3f880-d646-11ea-9af9-fb65a2ece0b3.png)

**Comment by thien302466** [comment]
OH! Of course.

**Comment by thien302466** [comment]
![0AE40D96-0635-4FE2-8077-F796B72C493F](https://user-images.githubusercontent.com/10149335/89272595-fdd40d00-d603-11ea-9b51-4e110fcdc2fd.jpeg)

**Comment by thien302466** [comment]
Ah, so it was 128gb

**Comment by CTCaer** [comment]
Yeah it's fake
In red, the info that gives it away.
![image](https://user-images.githubusercontent.com/3665130/89273337-1239f900-d648-11ea-8b00-a8ac09074fcc.png)

**Comment by thien302466** [comment]
So I need an actual one? This links to both problems?
