### ISSUE TITLE
Missing Pin, would this solve the problem?

### ISSUE THREAD

**Issue by tegutistgut** [CTCaer/hekate#475]
Hello. 
I'm sorry for disturbing, but I want to be sure that I don't make things worse.
I have the same pin broken like on this video (www.youtu.be/F4aNuKR8Ies) and I want to ask 1 thing:

Here is my issue: https://github.com/CTCaer/hekate/issues/467

If I would follow the steps on this video (www.youtu.be/F4aNuKR8Ies), would my problem get solved?

I don't want to risk breaking anything, so please only say something if you are very sure

TIA

**Comment by impeeza** [comment]
This was already asked. And closed because is not an issue of software. Is a hardware issue and should be resolved on hardware. Please DO NOT OPEN ISSUES FOR ASKING SUPPORT. USE THE CORRECT SUPPORT CHANNELS

**Comment by CTCaer** [comment]
>DO NOT OPEN ISSUES FOR ASKING SUPPORT. USE THE CORRECT SUPPORT CHANNELS

@impeeza do not act like that here. Even if you are right about what it is.

--------------------
@tegutistgut Yes this will fix your setup.
And yeah here is not a general support forum.

**Comment by impeeza** [comment]
Hi, You are right, I don't mean to be so harsh, I Apologize.  Regards
