### ISSUE TITLE
"Contact me!" displayed next to display panel model

### ISSUE THREAD

**Issue by cadenmr** [CTCaer/hekate#476]
As the title says.

Model: AUO A062TAN0X
ID: [30] 95 [0F]

**Comment by CTCaer** [comment]
Thank you. I will add the number.

so 94 is for AUO A062TAN01
so 95 is for AUO A062TAN02 (yours)

**Comment by CTCaer** [comment]
Added in: https://github.com/CTCaer/hekate/commit/461d14c39a54fc58b8875776eaebf7ae0f9bd493
