### ISSUE TITLE
Failed to apply nosigchk

### ISSUE THREAD

**Issue by IvanNegrete** [CTCaer/hekate#483]
When booting to emummc through hekate that error appears and won't let me enter HOS. The error doesn't show up when using hekate to load fusee-primary. AMS 0.14.3 Hekate 5.3.3 FW 10.2.0

**Comment by Masamune3210** [comment]
1. Don't expect support for piracy
2. Make sure all your stuff is updated first before you update the firmware next time, really helps headaches
