### ISSUE TITLE
Mariko + SX Core/OS payload support 

### ISSUE THREAD

**Issue by toratti** [CTCaer/hekate#484]
Rquesting Mariko + SX Core/OS payload support for hwinit  so lockpick_RMC would utilize it and work.

Thanks.

**Comment by CTCaer** [comment]
Mariko support will eventually come.
As for SX OS, piracy is not supported.

**Comment by toratti** [comment]
As for hekate it is as much piracy related as SX OS. Thanks.

**Comment by Conan179** [comment]
sx use atmos code, without licenz, atmos from githb directly donst start copyd games.

**Comment by toratti** [comment]
Be at is may, not the place or the time for the discussion. As the behavior seems to mutual related to the scene.

Put to mention I do not support piracy, but reserve and deserve to modify stuff I buy as I see fit.

Best Regards.
