### ISSUE TITLE
Weird Big unreadable Font / Warning: Nyx is missing! & Failed to init sd card

### ISSUE THREAD

**Issue by popy2k14** [CTCaer/hekate#485]
Hi, using newest "hekate - CTCaer mod v5.3.3 & Nyx v0.9.4" with an 512 GB Sandisk MicroSD Card.
Mostly on boot i now get the attached unreadable font with an message in the foreground.
I am booting the payload directly with my internal trinket.
Updated a few days ago from 5.3.2 and had hopes the issue is fixed.
Sadly it's not.

Any hints what the issue can be?
Windows does'nt find any errors on the micro SD card.

PS.: Upgraded 2 months ago from an 400 GB Sandisk MicroSD to an 512 GB.

thx and keep up the good work.

![IMG_20200919_163415](https://user-images.githubusercontent.com/6324597/93670034-5f5b1880-fa98-11ea-8686-f64b06914784.jpg)

**Comment by popy2k14** [comment]
Also got the following errors: Warning: Nyx is missing! & Failed to init sd card

Also tried/checked the following:
- hekate payload always gets found from my trinket chainloader and gets booted (most of the time without nyx)
- replacing the payload.bin (chainloaded from trinket) with any other payload always loads the payload correctly
- replacing the payload.bin (chainloaded from trinket) with SXOS one works correctly and brings me straight into SXOS or Stock Firmware when i am interrupting SXOS bootloader with vol+ key and press stock firmware

When booted to stock or SX anything working as expected. Official downloaded/bougth games like Suoer Mario Odyssey loads normally and plays normally.

How can i get logs when i cant input something on the touch because i cant read anything, neither sometimes nyx isnt loading?
How can i help you debugging?

**Comment by r4dius** [comment]
Got the same thing once after upgrading hekate / nyx 5.3.3, powered the console off for half hour before looking for the problem but then it booted correctly ..

**Comment by popy2k14** [comment]
yeah, when i shut it down with long power press and restart it, sometimes it works.
Now gone back to the SXOS payload for an workaround, that always works.

How can i help to debug this issue?
Seems an microsd reading/timing issue because trinket chainloader, SXOS & HOS can read the SD without an issue!

PS.: FAT32 formated

**Comment by r4dius** [comment]
Mine is xfat, btw this morning it won't run for the first time again, got a nys is missing message, then the nyx with scrambled like your screenshot again, I put the sd on pc and transfered sept and hekate files again, looks like it's always ok,
I used the ftp from sxos the first time I updated and the problem occured...

**Comment by popy2k14** [comment]
I have not updated hekate with ftp or something like this.
Updated with pc and also tried to recopy the bootloader directory without success.

**Comment by r4dius** [comment]
Did you update sept too ?

**Comment by popy2k14** [comment]
Yes, sorry forgot to say this.
Hrkate + nyx + atmosphere incl Sept.

**Comment by r4dius** [comment]
Ok still randomly buggy for me too.., will try redoing the sd to check

**Comment by popy2k14** [comment]
Any hints?
Is the same sd card working after redoing/reformating everything?

**Comment by CTCaer** [comment]
Can you drag n drop the bootloader folder from v5.3.**2** or v5.3.**1** release and tell me results?
No need to inject an older payload. Just drag n drop the folder. It will throw an error about dragons, it's ok.

Basically the test here is to check if a change in Nyx v0.9.4 created that issue.

**Comment by popy2k14** [comment]
Test the following with clean bootloader dirs (stright from the zip's):

- hekate 5.3.3 + Nyx v0.9.4 -> Nyx is missing
- hekate 5.3.3 + Nyx v0.9.3 -> Nyx is missing
- hekate 5.3.3 + Nyx v0.9.2 -> Nyx is missing

Switched to sx os payload after i created this ticket, this always works.
Now it seems something changed, because now i dont get this weird big font sometimes, i ALWAYS get -> Nyx is missing.

The microsd is good (tested on 2x windows PCs , Android & SX OS on the switch).

Is there anything i can do to help debugging?

thx

**Comment by popy2k14** [comment]
Tried another/older fresh FAT32 formated MicroSD Card JUST with hekate -> booted 10x times in hekate with Nyx without an issue.
Will now backup and redo/reformat the 512 GB Sandisk MicroSD card. Will come back here.

**Comment by CTCaer** [comment]
Take a photo of Console info -> SD card. Either via Nyx if it loads or from text UI.

**Comment by popy2k14** [comment]
Have done the following:

- "diskpart clean" on windows
- recreated 1 exFat partition with windows storage manager (just to have the partition)
- reformated the sd with guiformat.exe (fat32formatter with gui) with fat32 and cluster site of 32kB
- recopied just hekate + atmosphere + Nintendo folder
- fixes archive bits like described here: https://gbatemp.net/threads/how-to-fix-archive-bit-for-all-sd-files-and-folders.515258/
- boot 10x hekate 5.3.3 + Nyx 0.9.4 without an issue
- booted into hekate -> stock sysnand -> started mario odyssey -> Works

Here is the SD info:
![IMG_20200926_160024](https://user-images.githubusercontent.com/6324597/94342608-7064d600-0012-11eb-9f2e-fd215d737c8c.jpg)

Can you see something special about my card?

Will now copy back custom fw and see how it goes.

PS.: in the beginning (when i got this SD all worked normally (on fat32) like now), the issues just popped up a few days after updating hekate. Dont want to blame hekate :-) just reporting how the issue popped up.

**Comment by CTCaer** [comment]
Your card is legit. Other than that it's one of those sandisk U1 cards, it should not have an issue.
Also I don't mind blaming hekate. I prefer catching an issue if it really is an issue.
But if the issue was really hekate, I would have the github issues here filled with that.

The ultimate test is to get a emmc backup. Then exactly after, check this section:
![image](https://user-images.githubusercontent.com/3665130/94342825-7495f100-001c-11eb-96ca-4657a44159e7.png)
If not all are zeroes or fails, reopen the issue.

**Comment by popy2k14** [comment]
Copied back my stuff and booted stock 10.1.0 without issues multiple times from hekate.
Done the backup, and no errors:
![IMG_20200926_212808](https://user-images.githubusercontent.com/6324597/94348975-e849f500-0040-11eb-8353-2e3744b138fa.jpg)

Then booted one time sx os 3.0.5, powered it off and want to load hekate:
![IMG_20200926_213038](https://user-images.githubusercontent.com/6324597/94348984-f7c93e00-0040-11eb-8514-dfb930e4d4f2.jpg)

Switched to sx os payload again -> this time got black screen also on sx os sometimes on boot. Seems completly random :-(
Updated sysnand and emunand to 10.2.0.... nothing changed.

Please see this thread here: https://gbatemp.net/threads/sx-os-3-0-5-boot-hangs.573854/
This post also had the pixalated issue: https://gbatemp.net/threads/sx-os-3-0-5-boot-hangs.573854/#post-9202664

Maybe some sx os <> hekate relaited stuff going on?

**Comment by CTCaer** [comment]
You should have told me that you chainload like that.
I thought you just used their dongle.

Anyway that piracy thing has a completely broken hw init.
Also further discussion about sx is not allowed and also not my issue.

**Comment by popy2k14** [comment]
Hekate dont work when i'll: Power on my switch -> trinket loads HEKATE payload directly from sdcard.
So no chainloading from piracy thing bootloader :-)

**Comment by impeeza** [comment]
Hi, but you issue appears after use SX-OS so there is no way you receive support of that on the open code community.  Any support must come from they. You pay for the software THEY MUST GIVE THE SUPPORT

**Comment by fgmelo** [comment]
Same happens with me

**Comment by domtaquito** [comment]
Let me try and save someone time if they come across this again...
The EXACT same thing just happened to me and I solved it no less than 5 minutes from writing this comment.
I upgraded to a new 500GB SD card and had the issue. I compared the files from my old SD card and realized there was only 1 difference apart from other switch folders...
I had the payload.bin file in the root of the SD card. It needed to be in /bootloader/payloads/
Moved the file there and was able to push Hekate no problem. No more weird text glitch thing.

**Comment by popy2k14** [comment]
In my case the glitch never happend after ditching SX-OS alltogether and just use ATMO.
So the issue clearly popped up after booted SX-OS one time and after that hekate.
So for me issue is solved.

**Comment by SensitiveBug** [comment]
I also ran into this issue.  It happened after installing eMMC but I think I also ran into it before once. (I only own a switch for a few days)
It turned out my memory card is a fake one and got corrupted every time.  I had a 256GB card which turned out to be only 32GB.

**Comment by captain-black** [comment]
I meet the sam problem, Sandisk 512G U1 A1 SD, It can boot into Hekate, but shown unreadable font. 
I'm using hekate 5.8.0 + nyx 1.3.0

**Comment by captain-black** [comment]
oh! I fount it! It's a microSD card slot problem...the connector is loose contact! But my 64G SD card is still working so well.
So weird!
I opened my switch shell, make a filler-piece to press the connector, it works with my 512G SD now!

**Comment by CTCaer** [comment]
If nyx loads and fails to load resources from sd (like fonts), it almost always is a sd reader connection issue.
That one sd works and another doesn't is because you move around the connector when you eject/insert it. So it's pure luck there.

**Comment by captain-black** [comment]
My 64SD always works, but 512 SD not!
like this video: 
https://www.youtube.com/watch?v=F4aNuKR8Ies
