### ISSUE TITLE
Unknown pkg1 version. Failed to launch HOS!

### ISSUE THREAD

**Issue by squimples** [CTCaer/hekate#487]
I've never done this before and I do not know what I'm doing. I believe I've got hekate on my switch but when I try to launch, then press CFW (I'm following along to a youtube video) the error message "Unknown pkg1 version. Failed to launch HOS!" pops up. I've tried reading other posts but I don't understand what to do or what I did wrong

**Comment by impeeza** [comment]
RTM 8D

**Comment by squimples** [comment]
can i just restart the process or is there something I should do first?

**Comment by CTCaer** [comment]
Make sure you have the latest hekate.
Assuming that this is your first time running CFW and not in emuMMC, this error would be thrown if you have the latest Switch OS version and old hekate.
