### ISSUE TITLE
sd & emmc data (@lba 00088000) do not match 

### ISSUE THREAD

**Issue by ItsRoryG** [CTCaer/hekate#489]
Having the following issue when restoring eMMC recently - getting error code sd & emmc data (@lba 00088000) do not match. I have been using this SD Card without issue for around 3 months. I get to around 13 minutes and I get the sd & emmc data (@lba 00088000) do not match verification failed issue, running on the latest version of Hetake.

SD Card is a 64GB Kingston card. I suspect its an issue with the SD card itself as I use SanDisk for my other 3 switches. 

Anything I can do here?

**Comment by CTCaer** [comment]
Your card is probably fake.

Take screenshot from `Console info -> Sd card` (either tap with 3 fingers or press the capture button on jc or take a photo) and up it here.

**Comment by ItsRoryG** [comment]
@CTCaer SS as requested:

https://i.imgur.com/Z2al66q.png

Would the issue be caused by it being exFAT? As I mention it worked fine for 3 months then suddenly the issue appeared.

**Comment by CTCaer** [comment]
Card seems legit. And no, exfat should not affect the behavior. At least inside hekate.
That issue can only appear if sd card is fake or sd card reader has issues or there's some filesystem corruption.
Try to check the following section after running backup again and failing.
![image](https://user-images.githubusercontent.com/3665130/94342424-ac4f6980-0019-11eb-8652-9037ec310447.png)
These are indicators of issues of the first 2 reasons.

Other than that, there's nothing more I can do to help pinpoint the cause.
