### ISSUE TITLE
[Feature Request] Add more folders then just the nintendo folder to emuMMC

### ISSUE THREAD

**Issue by Alexander3a** [CTCaer/hekate#493]
Yeah so just like the the title says i woud like to add folders other then the nintendo folder to the emuMMC ini file.
So that when u install some patches that start on atmosthere bootup so they dont get applyed since i woud be using a differnt atmosthere folder when using cfw on sysnand to play online

**Comment by CTCaer** [comment]
You should request that in atmosphere repo.
Currently that can't be controlled by hekate or anything.
