### ISSUE TITLE
[Feature Request] Warn when booting CFW on SysMMC

### ISSUE THREAD

**Issue by laurinneff** [CTCaer/hekate#496]
This would be a nice feature, as sometimes it can happen that I accidentally tap the wrong option.

**Comment by impeeza** [comment]
I do use a different them for SysNand and EmuNand (Dark/light) so is easy identificable

**Comment by CTCaer** [comment]
Well, don't tap the wrong option.
If you don't use sys cfw just delete the boot entry.
