### ISSUE TITLE
Disallow booting If emummc patch fails and emummcforce=1

### ISSUE THREAD

**Issue by AuroraWright** [CTCaer/hekate#499]
As seen due to https://github.com/CTCaer/hekate/issues/498 , if emummc patching fails (due to new FS and whatnot) hekate allows to continue booting with a redirected Nintendo folder even if emummcforce is specifically set to 1.
I think for consistency's sake (and to avoid mistakes, as Power and Vol are close enough) boot should not be allowed in these circumstances.

**Comment by CTCaer** [comment]
Issue will stay open until I push a release
