### ISSUE TITLE
Having Issues creating backup files.

### ISSUE THREAD

**Issue by Buwutiful** [CTCaer/hekate#501]
Whenever I run the Backup eMMC BOOT0 & BOOT1 option, i keep getting the "File not found or could not be loaded!" and "Verification failed..." text. Unless there is a solution to this already, I'm not entirely aware of it yet. I'm using a Sandisk Ultra 256GB microsd XC1. It has already been formatted to Fat32.

**Comment by Buwutiful** [comment]
A similar thing happens with using eMMC RAW GPP, but it goes on for an hour until it gives me an error.

**Comment by Buwutiful** [comment]
I figured out I had a slight format issue so this is no longer a problem for me.

**Comment by Buwutiful** [comment]
Nevermind, I thought it was fixed, but the issue popped back up again.

**Comment by Buwutiful** [comment]
Alright I'll keep it closed... in the end the sd card was corrupted. :(

**Comment by CTCaer** [comment]
Get a photo from Console info -> SD card
