### ISSUE TITLE
Waiting for LUN.

### ISSUE THREAD

**Issue by naldo29** [CTCaer/hekate#502]
How do i fix this on UMS i cant use it, it says waiting for LUN and then it says timed out please help thanks!

**Comment by CTCaer** [comment]
That's normally when host does not enumerate the usb device.
Check your cable or that your usb hub (internal-chip or external hub) can provide enough power.

**Comment by naldo29** [comment]
> That's normally when host does not enumerate the usb device.
> Check your cable or that your usb hub (internal-chip or external hub) can provide enough power.

well my usb hub is connected to the wall, also i tried connecting it straight to my pc through usb 3.0 and it didnt work, do you think it might be a driver issue? maybe i messed that up?

**Comment by naldo29** [comment]
also the usb gamepad works fine

**Comment by CTCaer** [comment]
Well normally after the OS gets the device descriptors and sees that it's a UMS device, it sends a LUN request that tells the device what drive to mount. In this case it's always 0. As per specifications this must be sent before proceeding to enabling UMS.
What OS you use?

**Comment by naldo29** [comment]
> Well normally after the OS gets the device descriptors and sees that it's a UMS device, it sends a LUN request that tells the device what drive to mount. In this case it's always 0. As per specifications this must be sent before proceeding to enabling UMS.
> 
> What OS you use?

Win 10

**Comment by CTCaer** [comment]
Check if you use some weird usb filters or a custom mass storage driver.
For some reason it never sends the LUN request.

If you are up to the task you can also download wireshark, install it (select usbpcap) and then run it as admin and select your usb hub where switch is connected. Then inject hekate and start ums.

**Comment by naldo29** [comment]
> Check if you use some weird usb filters or a custom mass storage driver.
> 
> For some reason it never sends the LUN request.
> 
> 
> 
> If you are up to the task you can also download wireshark, install it (select usbpcap) and then run it as admin and select your usb hub where switch is connected. Then inject hekate and start ums.

![image](https://user-images.githubusercontent.com/35706559/97786368-76a22100-1b81-11eb-8be6-d33962c92360.jpeg)![image](https://user-images.githubusercontent.com/35706559/97786369-773ab780-1b81-11eb-96b3-706537299b9a.jpeg)thats the driver and im gonna try the wireshark thing although ive never tried it before.

**Comment by CTCaer** [comment]
Yeah somehow you installed libusbK driver on the mass storage device.
Proper is:
![image](https://user-images.githubusercontent.com/3665130/97787384-796d3800-1bba-11eb-98c5-da9059e576dc.png)


Hit `update driver` and choose `USB Mass Storage Device` driver.

**Comment by naldo29** [comment]
Thanks so much!
