### ISSUE TITLE
load custom driver?

### ISSUE THREAD

**Issue by KAMELCOLTD** [CTCaer/hekate#504]
Features:
add load custom driver ?

Idea:
since we can disabling joycon driver ; jcdisable=0

So What?:
i mean maybe we can load or enable another driver's?
Sixpair for example or a custom driver that could support aio controllers including joycons?
Hummm

**Comment by CTCaer** [comment]
hekate uses baremetal drivers. It's not Linux.
That means that the driver you want to load needs porting. Also you will need to port a bluetooth driver for having bluetooth controllers.
