### ISSUE TITLE
[Feature request] Button to remove custom theme

### ISSUE THREAD

**Issue by fennectech** [CTCaer/hekate#505]
A button that deletes /atmosphere/contents/0100000000001000    That's literally all.   Firmware updates often result in users having to remove custom themes.  Having a button to do it for you would be nice.   At the moment  if your in this situation you have no access to HOS

**Comment by CTCaer** [comment]
I don't actually hardcode any atmo paths except /sept.

You can write a super minimal payload that does that and then returns to hekate if wanted.
(The nyx storage saves hekate binary in ram, which you can directly call it)
