### ISSUE TITLE
Write Error   Com failure 3

### ISSUE THREAD

**Issue by fennectech** [CTCaer/hekate#506]
I get alot of "write error" and "com failure 3" and the disk umounts when using USB mass storage

**Comment by fennectech** [comment]
Turns out this is related to failed writes on a sdcard.   A corrupted file  being replaced from caja (forked version of gnome's file manager) causes the falure

**Comment by CTCaer** [comment]
If there are failures to write SD, OS is notified and tries again and again. If it continues to fail it automatically rejects the whole drive. I can't do anything on that. As for com failure, it's a usb port/cable issue.

**Comment by fennectech** [comment]
Its definitly not a port / cable error. As the drive isn't being touched.  And it works fine if i copy the content to another directory on the drive and cut and paste it to the right locations.  But i see the issue with filesystem corruption.    The port and cable are fine and haven't had issues for anything else.  Also. Using cp from the command line to copy the data works just fine.   It usually applies to 0 byte files that are created by a failed write.

**Comment by NotPikaQuin** [comment]
> If there are failures to write SD, OS is notified and tries again and again. If it continues to fail it automatically rejects the whole drive. I can't do anything on that. As for com failure, it's a usb port/cable issue.

it is a usb port error thank you
