### ISSUE TITLE
Sd and Emmc data <@LBA 033B0000> do not match

### ISSUE THREAD

**Issue by Tayden0113** [CTCaer/hekate#512]
I started to perform a full GPP Nand backup, and it got about 88% through the backup when it gave me this error. I looked up the issue and it seems this has happened before but with different codes. Should I downgrade to an older version of Hekate? Is there a step I'm missing or something I didn't do correctly? Here's the guide I used. https://nh-server.github.io/switch-guide/user_guide/emummc/sd_preparation/

**Comment by impeeza** [comment]
Did you test your SD card, for me the erorr was a fake SD.

**Comment by Tayden0113** [comment]
> Did you test your SD card, for me the erorr was a fake SD.

How would I do that?

**Comment by impeeza** [comment]
You can use h2testw to test the sd on the pc,

**Comment by CTCaer** [comment]
That's because your sd card is probably fake. Post a screenshot or photo of Tools -> SD card info from Nyx

**Comment by CTCaer** [comment]
Based on lack of reply from user, seems that the sd card was changed to a proper one.
