### ISSUE TITLE
HOS 11.0.0 support details

### ISSUE THREAD

**Issue by acnh420** [CTCaer/hekate#514]
Hello there, 
I noticed Hekate needs a new update to support the new atmosphere that was created because of the new switch update! 
Thank You!

**Comment by CTCaer** [comment]
The update will happen tomorrow.

**Comment by impeeza** [comment]
hi, Thanks a lot for all your effort!!!!

**Comment by gdicaterina** [comment]
Thanks!!!

**Comment by switchtonite** [comment]
> w.

Thanks for your hard work did the update get posted yet?

**Comment by CTCaer** [comment]
Yep https://github.com/CTCaer/hekate/releases/latest

**Comment by switchtonite** [comment]
> 
> 
> Yep https://github.com/CTCaer/hekate/releases/latest

I get a blue screen of death when i load it

**Comment by CTCaer** [comment]
@switchtonite Update atmosphere to latest.

**Comment by switchtonite** [comment]
> 
> 
> @switchtonite Update atmosphere to latest.

yeah i did
