### ISSUE TITLE
updated to hekate 5.5, how do I download atmosphere 0.17.0. ?

### ISSUE THREAD

**Issue by wetzthebetz81** [CTCaer/hekate#518]
Where can I download Atmosphere 0.17.0  ?

**Comment by Roxas-Dev** [comment]
Atmos 0.17.0 hasn't been released yet 

https://github.com/Atmosphere-NX/Atmosphere/releases

**Comment by wetzthebetz81** [comment]
Yes I know. So why does the release of hekate 5.5. say Atmosphere has to be updated to 0.17.0?

It is not compatible yet.

**Comment by masagrator** [comment]
Because it was announced that 0.17.0 will have Mariko support, so futureproofing

**Comment by wetzthebetz81** [comment]
Ok, that makes sense. Thanks. I thought that was my problem because my games still ain't working. I updated my Switch to 11, updated atmosphere to 0.16.0 and updated hekate tot 5.5. Am I missing something?

**Comment by urherenow** [comment]
Depends when you updated AMS. The build was re-uploaded with bugfixes.

**Comment by wetzthebetz81** [comment]
Thanks. Could it be the Sigpatches? I didn't update them.

**Comment by urherenow** [comment]
If you're trying to play pirated software, then yes, it could be. If carts aren't working you need to disable nogc and reboot, keeping in mind that downgrading might not work very well after upgrading your gamecard slot. IMHO, it's not worth it to downgrade anyway.

**Comment by CTCaer** [comment]
Mariko supported atmosphere (0.17.0) will be released when it will be ready.

Also no piracy mentions
