### ISSUE TITLE
Black screen once I run cfw-sys (or stock)

### ISSUE THREAD

**Issue by psytech69** [CTCaer/hekate#519]
Black screen once I run cfw-sys (or stock)

### What's the issue you encountered?
On the launch screen of **HEKATE**, once I choose "cfw-sys" or "Stock", the SWITCH screen stays black. No error message is displayed and I have to press OFF button for 10 seconds to unlock the SWITCH device.

### How can the issue be reproduced?
Today, I formatted SD card.
I got the new files from "https://www.sdsetup.com/".
I downloaded the package "Recommended Defaults" and "Minimal" to perform 2 separate tests.
The problem persists with either the "Recommended Defaults" or "Minimal" package. And to test the "Minimal" launch, I formatted SD card again and copied the "Minimal" package to the empty SD card.

### System Firmware Version
Switch: 11.0.0
New files from   https://www.sdsetup.com/   
-> Atmosphere v0.16.0/2020.12.03.r1 / Hekate 5.5.0

### Additional context?
Before the HOS 11.0.0 update, I had no problems running "cfw-sys" as usual.

**Comment by CTCaer** [comment]
Did you update to latest atmosphere? There was a new 0.16.0 revision pre-release.
(11.0.0 sys *cfw* and *stock* boots perfectly fine here. But well, it was with first revision also.)

Have in mind that packages like that come with many sysmodules which might not be updated to work on 11.0.0 or new atmosphere and effectively black screen you or fatal.
Try with a clean atmosphere folder first.
