### ISSUE TITLE
New to switch modding, need a little help.

### ISSUE THREAD

**Issue by Cheatermcgee** [CTCaer/hekate#522]
Hey all. I recently started looking into loading cfw onto my switch. Bought everything to do it, followed the cfw guide and when i go to launch atmosphere from hekate, im getting "unknown pkg1 version. HOS version not supported!" any and all help is appreciated.

**Comment by urherenow** [comment]
Github isn't a support forum, and you haven't provided nearly enough information, such as Switch model and FW version. Please ask your questions at gbatemp, and please provide as much info as possible when doing so.
