### ISSUE TITLE
[Feature request] Add File system consistency check of the microSD

### ISSUE THREAD

**Issue by JrRadiant** [CTCaer/hekate#525]
Hi all!..

It would be super nice to have a tool in Hekate for some sort of checking the consistency of the FAT's file table of the microSD, in manual mode or by demand, just like a **chkdsk** or **fsck** in PC, so one can without the need for the PC, USB cable and / or card reader and USB tools.
Is it possible?

What do you think about it?..

**Comment by CTCaer** [comment]
Every proper FAT integrity checker/fixer needs porting many libraries to baremetal.
This is a task that I'm unfortunately unwilling to do. Especially when I don't trust said libraries for fixing fat32/exfat issues.
