### ISSUE TITLE
T210b01: coreboot not allowed!

### ISSUE THREAD

**Issue by WTZ91** [CTCaer/hekate#528]
I had upgraded to OFW 11. 

I found hekate 5.5 and l4t ubuntu. After installation, when I try to load ubuntu got this error.  

Does anyone have similar issues?

**Comment by balika011** [comment]
Coreboot doesn't work on mariko.

**Comment by WTZ91** [comment]
Will it be supported in the future?

**Comment by CTCaer** [comment]
Already answered and also it's stated in changelog.
coreboot.rom is disallowed on Mariko for your own protection.
Support will be ready when it's ready basically.

**Comment by ShadePhenix** [comment]
@CTCaer 
Hi!

First of all, thanks for the great work you are doing!

I have searched but couldn't find the answer to my question.
As far as I understand, coreboot.rom is still not allowed on Mariko for protective reasons, and there is no timeframe for when this will be supported.
My question is:
Is there any other way for booting into Ubuntu/Android? Or is the only option to wait for support?

Many thanks.

SP

**Comment by lmm1191** [comment]
Is there a progress on running Lakka/Linux/Android for Mariko?

**Comment by greymanwalking** [comment]
I created an account just to ask when will this be supported on switch mariko device ?
Would really like Android/Ubuntu on my switch pleaseee

**Comment by CTCaer** [comment]
Android/Ubuntu is not supported on mariko.
If it ever gets a support you will hear it.
(Also coreboot will not be used there)

**Comment by Masamune3210** [comment]
You did. Believe me there will be surely lots of noise if Mariko ever gets support. If you wanted a tablet strictly for Android, why didnt you just buy a android tablet?

**Comment by krzysztofkrzeslak** [comment]
my objective is to have Ubuntu or some other plain Linux distro, not android so there's not much choice then and Switch seemed like the best choice, which now seems wasn't, so I guess I need to sell and look for a V1 version.

**Comment by CTCaer** [comment]
L4T is not ported to mariko (v2/lite/oled) yet
