### ISSUE TITLE
Errors booting

### ISSUE THREAD

**Issue by gary822** [CTCaer/hekate#529]
I have updated to the new atmosphere and the new hekate CTC.
But when I'm booting from hekate I become an error "Unknown pkg1 version"

When I booting atmosphere with the fuse-primary it's startet.
See the picture.![image](https://user-images.githubusercontent.com/48492786/101940305-95ff8580-3be6-11eb-93e7-f782837f9389.jpeg)

**Comment by CTCaer** [comment]
You didn't update hekate.
Updating requires the bootloader folder to be updated and **also** injecting the latest payload at least once.
You still inject an old payload (<= 5.3.4).
