### ISSUE TITLE
1 bit mode SD Card no longer boots Horizon with 5.5.0 and 5.5.1

### ISSUE THREAD

**Issue by fvig2001** [CTCaer/hekate#535]
My Switch has a broken SD pin and it's stuck in 1 bit mode. I was using it with 5.3.4 and Atmosphere on 10.2 without issues (except for the slow SD speeds). I tested Atmosphere 16.1 and Hekate 5.5.0/5.5.1 and only black screen is encountered after picking my CFW setting (basic only). I currently reverted to 5.3.4 and its matching Atmosphere and it's still working.

I have the same setup on another Switch (without the issue) and Horizon boots there. I used that good switch's SD card on my bad switch and the it only encounters black screen after.

Both SD cards are fat32.

*edit:
I tried Atmosphere 16.1 + hekate 5.3.3 and horizon booted 10.2.

Thanks.

**Comment by CTCaer** [comment]
It tries to run sept. Sept does not support 1bit mode and black screens without any error screen.

(If as you said was running it before, find me in retronx discord if you want a solution for 11.0.x)
