### ISSUE TITLE
failed to apply noldrchk

### ISSUE THREAD

**Issue by Themainman1360** [CTCaer/hekate#538]
I receive the title's message whenever attempting to boot into emmummc, this happened as soon as I updated to the latest Atmosphere 0.16.2.

**Comment by urherenow** [comment]
Need more info. Model, FW version (both sys and emu, if different), and hekate version all were not mentioned. I have the latest of everything and have no such issue. FW 11.0.0 on a release model.

**Comment by Themainman1360** [comment]
Ah it must be that I didn't grab the latest patches. I'll see if that does the trick!

**Comment by CTCaer** [comment]
Piracy is not supported
