### ISSUE TITLE
Feature Request (dim screen brightness when using UMS)

### ISSUE THREAD

**Issue by fennectech** [CTCaer/hekate#539]
When using UMS ive noticed that the battery still drains    so it would be nice to limit the brightness to make the battery last longer during those long file copies

**Comment by CTCaer** [comment]
Well draining depends on many factors (which sd card or emmc, joycon connected, etc).
I will think about that and maybe do it like in usb gamepad function.

**Comment by CTCaer** [comment]
Added in latest release
