### ISSUE TITLE
[Bug] hekate change the emummc when restoring

### ISSUE THREAD

**Issue by D3fau4** [CTCaer/hekate#546]
When you turn on "SD emuMMC Raw Partition" if you have 2 emummc automatically changes to the first emummc.

**Comment by CTCaer** [comment]
Currently Backup/Restore for emuMMC is only available for the **first found** emuMMC partition.

**Comment by impeeza** [comment]
You can use external tools as, [emutool](https://gbatemp.net/threads/emutool-move-partition-emu-on-another-sd-switch-emu-type-on-sxos-and-more.550756/) to backup/restore EMUMMC partitions.
