### ISSUE TITLE
Issues with SD or is it BUG

### ISSUE THREAD

**Issue by elozbay** [CTCaer/hekate#548]
Hi guys!

Can someone please help me and guide me step by step, how to go about solving this. :(
Tried to install the new hekate and I get this error

![1](https://user-images.githubusercontent.com/76888691/103469457-80085f00-4d65-11eb-9e11-a2dd5743a71f.jpg)
![2](https://user-images.githubusercontent.com/76888691/103469463-8a2a5d80-4d65-11eb-8d49-03d234e765d2.jpg)
![3](https://user-images.githubusercontent.com/76888691/103469469-957d8900-4d65-11eb-8eb7-6b82c87b47d6.jpg)
![4](https://user-images.githubusercontent.com/76888691/103469473-9c0c0080-4d65-11eb-9783-b57d390415dc.jpg)

**Comment by impeeza** [comment]
Not a bug, please read the readme file. Almost sure your SD card is fault.  Update to the latest hekateand use a new SD fir testing

**Comment by balika011** [comment]
Looks like an improperly seated or damaged sdcard reader.

**Comment by elozbay** [comment]
> Not a bug, please read the readme file. Almost sure your SD card is fault. Update to the latest hekate and use a new SD fir testing

I put in another SD card and reformatted it and put in the new hekate (updated) and the stil same error :(

**Comment by elozbay** [comment]
> Looks like an improperly seated or damaged sdcard reader.

I put in another SD card and reformatted it and put in the new hekate (updated) and the stil same error :(

**Comment by impeeza** [comment]
Sounds like a fault card reader on the switch. search the net for solutions

**Comment by impeeza** [comment]
Sure you will need to apply the solution on: https://gbatemp.net/threads/problem-with-sd-card-reader-seat-from-nintendo-switch-mother-board.552215/#post-8867689

Please sell help on the correct site

**Comment by CTCaer** [comment]
That's a HW issue with your sd card reader's connector.
