### ISSUE TITLE
Random crash when installing software to NAND.

### ISSUE THREAD

**Issue by micktu** [CTCaer/hekate#549]
Methods employed:
 * DBI "Install to NAND."
 * HOS "Move software to internal storage"
 * Game Card Installer "Nand Install"

A crash stack appears a few gigabytes into transfer pretty consistently.![image](https://user-images.githubusercontent.com/132598/103510906-bb428500-4e6e-11eb-89d2-d2f694e8fe70.jpeg)

**Comment by CTCaer** [comment]
Not a hekate issue and also piracy is not supported.

**Comment by micktu** [comment]
Thank you for your response. Privacy really should have no place in the homebrew scene.
