### ISSUE TITLE
[Enhancement] Patch conditions "autonogc"

### ISSUE THREAD

**Issue by fOmey** [CTCaer/hekate#552]
If you boot into an older firmware (4.1.0 in my case) you receive a crash on startup if your game cart firmware is on a newer unsupported version.. a work around is to remove the psychical game cart which avoids this crash, however this requires you to boot back into hekate and then boot back into the OS.

A good quality of life change would be for the autonogc conditions to also apply the patch when booting into older firmware with newer game cart firmware to avoid the startup crash entirely.

Love your work, excellent job so far.. all the best.

**Comment by CTCaer** [comment]
This actually complicates the whole thing a lot.
And it's something that I don't want, especially when you can easily fix your use case by forcing nogc.

Add this in the relevant boot entry:
```ini
kip1patch=nogc
```
