### ISSUE TITLE
Green Screen when Partitioning

### ISSUE THREAD

**Issue by Vampitech** [CTCaer/hekate#557]
Hello

When i try to partition or flash android to the SD a Green Striped screen jump up. In a previous attemp i got an exception.  I tried with 2 SD and this problem occurs in both. This is with de latest Hekate 5.5.2

Here is a pic

![image](https://user-images.githubusercontent.com/47399571/103957429-b30d7280-5118-11eb-8aa6-b9f34c8e1a12.png)

**Comment by CTCaer** [comment]
https://github.com/CTCaer/hekate/issues/554
Redownload the release.
Also don't worry, this happened after partitioning was finished.
