### ISSUE TITLE
Hekate wont mount SD

### ISSUE THREAD

**Issue by EauSP** [CTCaer/hekate#561]
I have this problem here that shows a screen asking me to update bootloader folder and warning me of some missing or old files, I've tried to download the latest releases of everything I needed but this keeps showing up. To clarify, I've been using Hekate CTCaer 5.0.0 and 5.0.1 but no one has had a good result for me.
![hekate](https://user-images.githubusercontent.com/77455940/104624670-20c71a80-5694-11eb-8bf7-7ccf2fa7559b.jpeg)
I'm sorry if I made any mistakes, English isn't my first language, and I'm also grateful in advance to anyone who helps me.

**Comment by CTCaer** [comment]
You are using more than 1.5 years old hekate.
Update to latest and also make sure your sd card is using the MBR partition scheme.
And also make sure that your sd card is bigger than 2GB. SDSC cards are not supported. Only SDHC and SDXC are.
