### ISSUE TITLE
v5.5.3 Reboot/Restart Issue in Atmosphere 17.1 (no mesosphere), HOS 11.0.1

### ISSUE THREAD

**Issue by parasupaman** [CTCaer/hekate#564]
With latest v5.5.3.  Choosing to 'Restart', reboots to a blank screen.  Blank screen does not appear to be in RCM mode, since no payload can be injected.

Requires holding the power button for over 10 seconds to force complete shutdown.  Then enter RCM mode as usual and inject payload again manually.  Have reverted to v5.5.2 and there is no issue.

Tested with Atmosphere 17.1 (no mesosphere), HOS 11.0.1.
hekate_ctcaer_5.5.3.bin copied/renamed to:  'atmosphere\reboot_payload.bin'

**Comment by CTCaer** [comment]
Make sure that reboot_payload.bin and update.bin are not corrupt. Redownload release just in case also.
I tested that with both meso and non-meso builds and both could reboot into hekate v5.5.3. Sys and emu via the power menu reboot option.
