### ISSUE TITLE
black screen on mariko with sx gear boot.dat

### ISSUE THREAD

**Issue by gigigadda** [CTCaer/hekate#565]
starting the hekate5.5.3.bin file via the boot.dat and boot.ini of the sx gear 1.1 package on mariko (LITE and Classic) motherboard I get black screen. With version 5.5.2 fully operational. HOS 11.0.1 (with Starcraft NX no issue)

**Comment by CTCaer** [comment]
Redownload release. There was an update to it that fixes that.

**Comment by gigigadda** [comment]
thank you
