### ISSUE TITLE
FATFS Error13

### ISSUE THREAD

**Issue by DrVollKornBrot** [CTCaer/hekate#571]
New sd card (Samsung EVO Select 512GB).
Latest version of Hekate.
I tried FAT32 and exFAT, both result in the same issue:
![Unbenannt](https://user-images.githubusercontent.com/78275056/106364992-e667a980-6332-11eb-8131-798a583bf896.png)

**Comment by CTCaer** [comment]
You either have GPT instead of MBR or your fat partition has weird fat header.
Use switch or sd association format tool and then copy the files back and reformat via hekate.
