### ISSUE TITLE
Failure to backup BOOT0 & BOOT1

### ISSUE THREAD

**Issue by SpectralSlog** [CTCaer/hekate#574]
When I try and backup BOOT0 and BOOT1 I get this error
![nyx20210208_094023](https://user-images.githubusercontent.com/70807650/107236512-c64f7e80-69f3-11eb-8650-543b293029b4.jpg)

I also get a similar error when trying RAW GPP
![nyx20210208_095804](https://user-images.githubusercontent.com/70807650/107236865-1d555380-69f4-11eb-80fb-b1cd3d934bec.jpg)

I know that I do have an emuMCC partition because I just opened it and it looks fine.

Please help! Thanks.

**Comment by CTCaer** [comment]
Go to partition manager and the moment the pop up that has your partition table shows up, take a screenshot (3 finger tap or screenshot button on jc) or a photo.
Up it here

**Comment by SpectralSlog** [comment]
@CTCaer This?
![nyx20210208_131021](https://user-images.githubusercontent.com/70807650/107262979-328bab80-6a0f-11eb-871c-a44a93d85125.jpg)

**Comment by CTCaer** [comment]
You didn't create your emummc via hekate and thus it has wrong MBR entry.
emuMMC partition type is not exFAT (x07), it's xE0.
Correct that with a hex editor (it's in sector 0) and it will be found.
