### ISSUE TITLE
[Feature Request] emummc.ini path boot entry key/value

### ISSUE THREAD

**Issue by annson24** [CTCaer/hekate#577]
Option to include a path in hekate_ipl.ini or in individual inis for which emummc.ini to use. This is favorable for those people who use multiple EmuMMCs.

**Comment by CTCaer** [comment]
Already supported. Use:

```ini

emupath={SD folder}
```
Forces emuMMC to use the selected one.
(=emuMMC/RAW1, =emuMMC/SD00, etc).
emuMMC must be created by hekate because it uses the raw_based/file_based files.
