### ISSUE TITLE
sd and emmc data <@LBA 00008000>, do not match

### ISSUE THREAD

**Issue by iSkrrtt** [CTCaer/hekate#579]
Says “verification failed, please try again... Failed!”

I installed correctly and it gets stuck at 6%/3m 41s. 

boot0 and boot1 backed up fine. 

Any help would be appreciated
Thanks!

![F53A3A1A-9B5E-4271-ADE5-14E5D3AFD414](https://user-images.githubusercontent.com/79194083/108182632-35edf980-70d7-11eb-9986-6cd8fa8a1376.jpeg)

**Comment by CTCaer** [comment]
Your sd card is probably fake.
If you want to validate that easily, send me a screenshot or photo from Console info -> SD card.

**Comment by CTCaer** [comment]
No reply from user so I assume they got a proper sd card

**Comment by Masamune3210** [comment]
Might try it with a fat32 FS, exfat is known to have gigantic issues on switch when it comes to HOS so maybe card FS damage?

**Comment by ace90249** [comment]
![20221007_061459](https://user-images.githubusercontent.com/10873611/194562942-f07ae1af-c377-4f83-844b-9437100b6a0b.jpg)
I
![20221007_061533](https://user-images.githubusercontent.com/10873611/194562948-627fe31c-48da-4eee-a4a7-86559631923e.jpg)
 Have 
![20221007_061716](https://user-images.githubusercontent.com/10873611/194562953-bf0f1dfb-0f97-43e0-91c9-8b170ad985f0.jpg)
same issue. Please help...

**Comment by ace90249** [comment]
![20221007_061847](https://user-images.githubusercontent.com/10873611/194563153-61d01f30-0c91-43eb-a348-0e8cbbeba874.jpg)
And mybother Switch has this issue if u know anything about this mess lol. Thank you

**Comment by impeeza** [comment]
You just open several reports, and all of then indicate you have a Corrupted SD card.
