### ISSUE TITLE
Push/pull file from SD a la adb or UMS request

### ISSUE THREAD

**Issue by mariogamer2** [CTCaer/hekate#58]
Remembered this not so long ago from a past issue.
Since we got module now, this would be good as one.

**Comment by ValliantStorme** [comment]
It might be more convenient to just be able to launch memloader

**Comment by mariogamer2** [comment]
Yeah maybe.
But I remember that CTCaer was kinda positive on it? I think it was on the original repo so it got deleted.

**Comment by mariogamer2** [comment]
Yeah maybe.
But I remember that CTCaer was kinda positive on it? I think it was on the original repo so it got deleted.

**Comment by RenaKunisaki** [comment]
I wonder if there could be a sysmodule that implements adb push/pull?

**Comment by CTCaer** [comment]
Sysmodule? As in HOS sysmodule? Wrong project.
If you mean a hekate module, then yeah it could.
But I will not develop it. 
(For me, my custom memloader's UMS is enough.)

**Comment by fennectech** [comment]
does your custom memloaders ums launch sd automaticly?   Ive been looking for a memloader that doesnt load the menu

**Comment by deurk** [comment]
> does your custom memloaders ums launch sd automaticly? Ive been looking for a memloader that doesnt load the menu

I'd be interested by it if you found something that worked.

**Comment by CTCaer** [comment]
Added in version
