### ISSUE TITLE
Support for Hidden Partition SXOS

### ISSUE THREAD

**Issue by norvinguerrero** [CTCaer/hekate#582]
Please, we need support from hekate for Hidden Partition emunand native of SXOS, we need hekate to recognice the Hidden Partition of SXOS emunand for all in one sistems in one micro SD card. Help me please. I waiting for your help.
Imagine how great it would be to have atmosphere, SXOS, Linux and Android in a single micro SD, wouldn't that be great?.

**Comment by urherenow** [comment]
This isn't a help forum, and it already works perfectly fine with SX hidden partition. Go search gbatemp.

**Comment by CTCaer** [comment]
I don't want to imagine it.

**Comment by norvinguerrero** [comment]
> This isn't a help forum, and it already works perfectly fine with SX hidden partition. Go search gbatemp.

Thanks, I go to search
