### ISSUE TITLE
hekate_ipl.ini is missing from hekate_ctcaer_5.5.4_Nyx_1.0.1.

### ISSUE THREAD

**Issue by Chummpp** [CTCaer/hekate#583]
According to the switch hacking guide at nh-server.github.io the ini file hekate_ipl is suppose to be included with hekate, but instead its missing or removed. According to this https://github.com/CTCaer/hekate/blob/master/res/hekate_ipl_template.ini it was part of hekate on January 2021 but it was removed without any reason for the latest version.

Do you have a reason for removing it and not telling anyone?

**Comment by CTCaer** [comment]
Well I didn't tell anyone because it was never bundled in the 3 years of hekate.
(Btw the date on a commit means when changes made on that file.)

You should re-read the guide. You probably missed the step on where you get it.
