### ISSUE TITLE
Problems in the stared

### ISSUE THREAD

**Issue by naostelar** [CTCaer/hekate#585]
Hi, i have a problem with the new Hekate. In my screen appears this tittle: OLD NYX GUI FOUND/ THERE WILL BE DRAGONDS!
UPDATE YOUR BOOTLOADER FOLDER!

I updated
![IMG_20200408_022227__01](https://user-images.githubusercontent.com/80188593/110229986-0d397280-7ed3-11eb-9c83-3a9a21528175.jpg)
 the folder from the Hekate 5.5.4 but this no fixed the problem.

Can you help me?

**Comment by urherenow** [comment]
You need to extract THE ENTIRE ZIP, and overwrite files. You are failing to do that.
