### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Daigo1317** [CTCaer/hekate#588]
how can i install 2 different versions of android on the same sd?  if not, you can add this option.

**Comment by EmreTech** [comment]
You shouldn't ask this here, ask this in the Switchroot server.

I heard you can do this by manually adding new Android partitions, but I don't know how to exactly do it.

**Comment by CTCaer** [comment]
It's a niche case that will be never be added in hekate.
If you still want to do that for whatever reason, seek help in the appropriate switch android channels
