### ISSUE TITLE
Battery percentage went crazy

### ISSUE THREAD

**Issue by PlasticLover69** [CTCaer/hekate#589]
In Hekate and HOS the battery percentage is going like 100%, 2 seconds later is 84%, then 51 % then 12 % then 1 % then 98 %, and it keeps going like that, the mV is around 4000 right now so it's not gonna turn off but the percentage is really messed up, is my battery dead?

**Comment by CTCaer** [comment]
Your fuel gauge is desynced. You will need to calibrate it with full charge cycles
