### ISSUE TITLE
Switch does not execute sysnand mode

### ISSUE THREAD

**Issue by iixela** [CTCaer/hekate#591]
Hi!
even with the error SD-Card is initialized in 1-bit mode, previously it could be run SYSNAND o STOCK MODE, but not anymore.

Any way to load Custom Firmware from internal memory without using SD?

Thanks!

**Comment by Masamune3210** [comment]
nope, sd is required. have you tried to reseat the reader?

**Comment by CTCaer** [comment]
> Hi!
> even with the error SD-Card is initialized in 1-bit mode, previously it could be run SYSNAND o STOCK MODE, but not anymore.
> 
> Any way to load Custom Firmware from internal memory without using SD?
> 
> Thanks!

Not possible. Basically, it's time to finally fix your connector.
