### ISSUE TITLE
Cannot launch Stock SYSNAND

### ISSUE THREAD

**Issue by Windwalker14** [CTCaer/hekate#593]
Updated to 12.0 (accidentally), and now get the following when trying to boot to Stock SYSNAND

Unknown pkg1 version.
HOS Version not supported!
Trying backup bootloader...
Found pkg1 ('20210129111626').

Unkown pkg1 version.
HOS version not supported!

Failed to launch HOS!

**Comment by MMJv3** [comment]
wait for an update

**Comment by impeeza** [comment]
Duplicate a issue do not help, #592  is the same.

You should read it.

Use your sysNand/emuNand backup to downgrade or just wait.

**Comment by r1cola** [comment]
yes, this will have to wait for both AMS and Hekate updates...be patient...
