### ISSUE TITLE
Hekate 5.5.5, HOS 12.0.0 sleep broken 

### ISSUE THREAD

**Issue by ajbritain4** [CTCaer/hekate#595]
Hey, having an issue with the newest Hekate on my Switch. It’s a patched Erista model with SX Core chip flashed with spacecraft-nx, with Hekate as the payload.bin

Booting stock through Hekate 5.5.4 and HOS 11.0.1 on the sysMMC, stock boot worked absolutely fine. 

With stock boot through 5.5.5 and HOS 12.0 sysMMC, the system hangs to a black screen on sleep.

5.5.5 and CFW emuMMC on 11.0.1 works absolutely fine. I have used a clean bootloader folder and made the ini file again from scratch with the same result. Thanks for reading and let me know if you need any more info 

UPDATE: seems to be working ok again with the Atmosphere 19.0.1 update - didn’t know that could affect sleep in sysNAND but there we go. Thank you!

**Comment by all4free** [comment]
Switch lite on SX lite chip. Hecate 5.5.5. Updated emunand to 12.0.0. when loading emunand blank screen.

**Comment by ajbritain4** [comment]
> Switch lite on SX lite chip. Atmosphere 0.19.0. Hekate 5.5.5. Updated emunand to 12.0.0. when loading emunand blank screen.
> OFW 12.0.0 loading successfully.

Think that sounds like a different problem, might be better in a separate issue?
