### ISSUE TITLE
"Contact me!" displayed next to touch panel model

### ISSUE THREAD

**Issue by JulienMaille** [CTCaer/hekate#597]
So I contact you :-)
```
Touch Panel:
Model: Unknown Contact me!
ID: 9C555976 (Unknown - Error)
FTB ver: 16F2
FW rev: 2D61
```

**Comment by CTCaer** [comment]
Your touch IC customized config for firmware seems to be missing or sth.
And thus the command that checks touch panel model can't be sent. I would suggest to boot once in HOS first.

**Comment by JulienMaille** [comment]
That′s correct, now I can see the full details
