### ISSUE TITLE
Reboot error

### ISSUE THREAD

**Issue by Aquixium** [CTCaer/hekate#599]
I rebooted my switch back to the Hekate menu with Hekate Tool Box and now my Switch won't turn on. I am wondering how I could fix this, any and all help will be appreciated.

**Comment by impeeza** [comment]
Hi, his is no a support channel, please use support pages, forums or similar.

The posibilities are, you mesed up your SD card contents or if you have a EmuMMC partition, select on Windows "repair" partition and that get screwed up.  on that case you will need restore a backup.
