### ISSUE TITLE
SD format never readable

### ISSUE THREAD

**Issue by Nintenking** [CTCaer/hekate#6]
I'm on 5.1, and whenever I try to "launch firmware" it says that my SD (2GB, if this could be the problem) isn't in a "Fat" format. I tried Fat, Fat32 and exFat by now, but it's always the same problem. Any idea what could I do?

**Comment by CTCaer** [comment]
https://github.com/nwert/hekate/issues/28
SDSC cards are not supported.
And it's in my low priority list for now.

Please try a SDHC or SDXC card.

**Comment by Nintenking** [comment]
Thank you, didn't know about SDSC not being supported, now I managed to do everything perfectly fine!
