### ISSUE TITLE
Freezing when trying to backup (USB Tools > BOOT0)

### ISSUE THREAD

**Issue by Whitesttax** [CTCaer/hekate#602]
![sd](https://user-images.githubusercontent.com/20992483/115964472-073b3780-a4fb-11eb-9596-cd043ea9b53a.jpg)
Trying to install atmosphere on a 12.0.1 Switch. After placing bootloader with latest hekate on SD and injecting 5.5.5 I go to Tools > USB tools > Boot0 and it won't show up on Windows as a drive so I can't use NxNandManager. Also if I try to remove the USB C cable hekate freezes and I need to hold power to turn it off.

Managed to install atmosphere by using SD Backup. I installed atmosphere today on another Switch and it didn't have the issue so no idea why it happened. Also tried fat32 with no luck. Anyway they're both running atmosphere now.

**Comment by CTCaer** [comment]
The card is legit and I don't see other errors.
Contact me in retronx discord, I think I know what's the issue.

**Comment by CTCaer** [comment]
If you still have that issue contact me or directly use the new option in nyx.ini (currently it's only editable manually and not via ui)
