### ISSUE TITLE
Archive bit fix don't count correctly

### ISSUE THREAD

**Issue by Borrajo** [CTCaer/hekate#603]
Hekate 5.5.5
Hekate 5.5.5 When I run the archive bit fix and finished with some files unset, hekate always say 1 unset, doesn't count correctly anymore how it did before

**Comment by CTCaer** [comment]
That it doesn't count how you think it should count, it doesn't mean it doesn't count correctly.

**Comment by xXxQuiquexXx** [comment]
But we really know that the fix is ​​being done on more than 1 file and it always says that only 1 was repaired and shows only one folder
