### ISSUE TITLE
Switch can not be detected by Windows

### ISSUE THREAD

**Issue by Initializist** [CTCaer/hekate#604]
I'm on Hekate 5.5.5. When I tried to mount the SD card in the switch by USB tool, the screen showed that the status is started UMS.  However, my laptop played a sound and not recognized the device. When I check the "Devices and Printers" on my laptop, my switch is listed as UMS. 
![Screenshot 2021-04-30 185959](https://user-images.githubusercontent.com/40130258/116761678-4a5b4600-a9e6-11eb-8a3f-e03eaa070718.jpg)

**Comment by impeeza** [comment]
Yes that's correct, if the problem is you don't see the «drives» you need to open storage manager and assign letter to the SD card volume. Take care to no edit any emummc partition of you have one

**Comment by Initializist** [comment]
Thank you! I will try to see if it works.

**Comment by Initializist** [comment]
It got fixed, Thank you again!
