### ISSUE TITLE
hekate_ipl.ini does not update properly ?

### ISSUE THREAD

**Issue by T1nd4** [CTCaer/hekate#608]
hekate_ipl.ini does not update with emuMMC boot options after created emuMMC with hekate 5.5.5
- took a new SD
- partition SD card as usual (full)
- goto emuMMC/create emuMMC
When finished "hekate_ipl.ini" is not updated with emu entries in launch section.

I'm 10.0.4 original firmware, using atmosphere 19.2 hekate 5.5.5 pack.
When I use sd card with atmo 18.01, hekate_ipl.ini updated well after created emuMMC.

I fixed the my 19.2 installation with adding next lines in my hekate_ipl.ini
Then all works fine.

[CFW - emuMMC]
fss0=atmosphere/fusee-secondary.bin
kip1patch=nosigchk
emummcforce=1
atmosphere=1
icon=bootloader/res/icon_payload.bmp

[Stock - sysMMC]
fss0=atmosphere/fusee-secondary.bin
emummc_force_disable=1
stock=1
icon=bootloader/res/icon_switch.bmp

**Comment by CTCaer** [comment]
Nothing adds sections in hekate_ipl.ini.
User is supposed to add them by studying the readme first or get a ready made.

**Comment by impeeza** [comment]
Tonight is the RTFM night ^_^   ^_^    ^_^

**Comment by T1nd4** [comment]
Huhu...
I never had to setup manually my ini. I thought it was done directly by hekate. That’s probably the problem with all the all in one builds.
Thanks

________________________________
De : impeeza ***@***.***>
Envoyé : Tuesday, May 11, 2021 8:13:49 AM
À : CTCaer/hekate ***@***.***>
Cc : T1nd4 ***@***.***>; Author ***@***.***>
Objet : Re: [CTCaer/hekate] hekate_ipl.ini does not update properly ? (#608)


Tonight is the RTFM night ^^ ^^ ^_^
