### ISSUE TITLE
Text showing up as squares

### ISSUE THREAD

**Issue by theEofE** [CTCaer/hekate#610]
Everytime I boot up hekate the text just shows up as squares

**Comment by impeeza** [comment]
Let me check my 8 ball...


«nope, please provide more information»


Please give us your configuration. Versions, etc.

Seying that. I am 99.999999% sure you didn't copy all files to you Sd Card. Read the readme.md and installation instructions and that should work.

**Comment by Masamune3210** [comment]
Likely either not all files were copied or some files have become damaged somehow

**Comment by theEofE** [comment]
yeah nevermind, it didn't work.

**Comment by Masamune3210** [comment]
You could try disconnecting it and reconnecting it and seeing if that helps. Its just under the back case, so you don't even have to dig for it. just be careful to not strip out the screws in the back panel like I did

**Comment by theEofE** [comment]
it's now working
