### ISSUE TITLE
HOS 12.0.2 support

### ISSUE THREAD

**Issue by loopoutgh** [CTCaer/hekate#611]
New HOS fw, 12.0.2. Breaking hekate latest version's capability to boot clean sysnand with ofw through fusee secondary?

**Comment by impeeza** [comment]
What is the issue? Did you find a bug?

**Comment by loopoutgh** [comment]
Not yet, just giving a heads up on the update since probably will need some update on hekate's part to boot the newer fw as other times before.

**Comment by CTCaer** [comment]
12.0.2 was already pushed.
If you want it now, you can compile master or dev branch here (both were updated).

**Comment by ctotheharrison** [comment]
Accidently updated the firmware to 12.0.2. 

Now getting a Fatal Error Package1. any ideas on if ive royally screwed up?

**Comment by impeeza** [comment]
This space is for reporting bugs and issues.  For supporting go to the propper channels.  If you read this issue and the release oage Hekate already support the new firmware. 

Please **read** the other components documentation about support on 12.0.2 firmware

**Comment by CTCaer** [comment]
Update hekate. I already posted a 12.0.2 compatible release.

https://github.com/CTCaer/hekate/releases/latest
