### ISSUE TITLE
emunand loading problem

### ISSUE THREAD

**Issue by theEofE** [CTCaer/hekate#615]
i just created my emunand via SD Partition, and every time I boot on to the "CFW (emunand)" I get 

"Unknown pkg1 version.
 HOS version not supported!
 Or emuMMC corrupt!
 Trying to backup bootloader...
 found pkg1 (//).

 Unknown pkg1 version
 HOS version not supported
 Or emuMMC corrupt
 
  Failed to launch HOS!"

is it because I have a fake or defective SD card? here is the info of my SD card: 
![sdcardinfo](https://user-images.githubusercontent.com/83994186/118379555-3ea47d80-b5a9-11eb-8a82-cc7030d69dc8.png)

**Comment by urherenow** [comment]
Yup. Your card is fake, and/or your card slot is broken.

**Comment by theEofE** [comment]
> Your card is fake, and/or your card slot is broken.

oh ok

**Comment by CTCaer** [comment]
Card is 100% fake.
