### ISSUE TITLE
Atmosphere crash (black screen) after start from hekate after back to bootloader hekate from android 10

### ISSUE THREAD

**Issue by Cacadoo22** [CTCaer/hekate#626]
after update hekate to 5.5.7 i`ve starting experience issue with starting up atmosphere 0.19.4 (HOS 11.0.1) after back to bootloader hekate from android 10 - KO rate is 100% starting from hekate ver 5.5.7 (switch on erista cpu)

**Comment by CTCaer** [comment]
v5.5.7 update was ultra minimal and had zero changes that affect booting other than 12.0.3 support.
Your files are corrupted. So repaste anew.
If that's not fixed then your directory record is corrupted, so follow that guide https://github.com/CTCaer/hekate/issues/614#issuecomment-840080851
