### ISSUE TITLE
I updated my switch on accident and now it is somewhat bricked

### ISSUE THREAD

**Issue by DrQuack102** [CTCaer/hekate#635]
So I used hekate and everything worked fine, until I accidentally updated my switch, and can no longer boot the switch up, even under stock. I need some help as to what I should try to do next .Would reverting firmware help any? The specific error message I get is "Unknown pkg1 version, HOS version not supported! Failed to launch HOS!"

**Comment by Yoti** [comment]
Update your hekate SD card files and send new hekate.bin payload to the system.

**Comment by DrQuack102** [comment]
So I am still fairly new to modding in general, so how should I go about updating? Cause I saw that there was a update.bin file, but I don't know much about bin files, or do you mean redownload hekate? Because I already tried that, and still got the same message.

**Comment by CTCaer** [comment]
use the button Logs ON at top right in Launch and post a image of the log after launching.

**Comment by DrQuack102** [comment]
![Uploading 4F558F31-33D1-4B21-841E-6192955705BE.jpeg…]()

**Comment by CTCaer** [comment]
you didn't upload the image.. You posted before the uploading finished

**Comment by DrQuack102** [comment]
![5B84CB45-CF4E-45F6-8401-251A9DF5D7C3](https://user-images.githubusercontent.com/87552021/126053691-5bea367b-4d3e-46f5-9e6a-05fc3375b723.jpeg)

My bad, should be here now

**Comment by CTCaer** [comment]
Update hekate.
Go to https://github.com/CTCaer/hekate/releases
get the release zip and follow the "How to update:" in big bold letters there.

**Comment by DrQuack102** [comment]
So my issue is that file, I can't seem to find it to inject it.

Ig that may have been better to start off with

**Comment by CTCaer** [comment]
![image](https://user-images.githubusercontent.com/3665130/126123766-fd0c6468-401f-4cef-8958-7b4d536a2609.png)
![image](https://user-images.githubusercontent.com/3665130/126123801-37c57593-9616-48f7-bd1c-93e3643517c2.png)

**Comment by DrQuack102** [comment]
Thank you for helping me with my issue, and idk how I didn’t see that when I downloaded it the first time. But now I’m getting this issue after the logos pop up, and I just updated hekate, how would I go about updating sept? And the atmosphere as you said I should?
![image](https://user-images.githubusercontent.com/87552021/126198701-c418f9e0-88ac-4e16-9331-1b062528839f.jpg)

**Comment by impeeza** [comment]
Please direct support question to discord, gbatemp or orhers sources of support, this site is for bug report. And clearly you have a serious case of no reading instructions  Your problem is easily solved reading the installation guide of Hekate and Atmosphère

**Comment by brandonrc** [comment]
I had this same issue. 

> ![5B84CB45-CF4E-45F6-8401-251A9DF5D7C3](https://user-images.githubusercontent.com/87552021/126053691-5bea367b-4d3e-46f5-9e6a-05fc3375b723.jpeg)
> 
> My bad, should be here now

Had the same issue. I just to the hekate menu at boot. Selected the emuMMC and the migration button. Then repaired the raw emuMMC and it started right up after that.

**Comment by Switchfan12** [comment]
I tried this and now my entire screen is just a weird yellow color

**Comment by impeeza** [comment]
closed issue from 2 years ago, don't think will help you.

any support should be looked for on respective sites, discord or GBATemp.
