### ISSUE TITLE
[Feature request] Do not allow reboot to OFW if AutoRCM is on

### ISSUE THREAD

**Issue by Yoti** [CTCaer/hekate#640]
I'M NOT ASKING FOR HELP! THIS IS BUG REPORT!

I think I found another small bug in the hekate/nyx. One can't do a reboot to OFW while having AutoRCM on. So, hide or disable button/add a warning to this window.

**Comment by masagrator** [comment]
Well, this is not a bug. This is how AutoRCM works. 
For reboot to OFW you MUST disable AutoRCM. There is no other way.

**Comment by impeeza** [comment]
Or press VOL- while booting and select the corresponding boot on NYX

**Comment by daylightEX** [comment]
Yeah same thing is happening to me.

**Comment by CTCaer** [comment]
I won't implement that in the end. Too many variables to account for (specifically on patched units).
