### ISSUE TITLE
Linux and android installation from hekate

### ISSUE THREAD

**Issue by zmijek-ok** [CTCaer/hekate#643]
When i try to install linux or lineage-os, it shows error coreboot mariko, any solution?
Of course i created linux partition before or android partition.

**Comment by masagrator** [comment]
V2 and Lite don't support linux and android.

**Comment by CTCaer** [comment]
it doesn't say `error coreboot mariko`
it says **Coreboot not allowed on Mariko!**
Which is self explanatory about its incompatibility.
