### ISSUE TITLE
[bug] Backlight doesn't dim if UMS is launched via hekate storage

### ISSUE THREAD

**Issue by lowburger** [CTCaer/hekate#646]
Hi, when I use ums usb connection on hekate screen brightness stays low and it's great for spending a lot of time on files.

Problem comes when I use that homebrew https://github.com/HookedBehemoth/studious-pancake for straight reboot in hekate ums usb connection and screen brightness stays high... I think that's bug on hekate side? If wrong I open issue on homebrew instead. Thx your help!

**Comment by CTCaer** [comment]
Brightness can't be forced by apps that use hekate's storage to manage its boot.
So that issue is def in nyx.

**Comment by CTCaer** [comment]
Fixed in latest release
