### ISSUE TITLE
[BUG] cannot show the last boot option label

### ISSUE THREAD

**Issue by carcaschoi** [CTCaer/hekate#649]
in the launch menu
![16297166231272082284472941285942](https://user-images.githubusercontent.com/64573431/130437125-f42e9799-e3f2-4421-921a-f50263c87322.jpg)

「Hack sysnand」 word doesn't show up

**Comment by masagrator** [comment]
Upload here hekate_ipl.ini

**Comment by carcaschoi** [comment]
> Upload here hekate_ipl.ini

This is the bug of hekate. I know what I am doing.

**Comment by carcaschoi** [comment]
My hekate_ipl.ini config:

[config]
autoboot=0
autoboot_list=0
autohosoff=1
autonogc=1
backlight=100
bootwait=5
updater2p=1

{ShallowSea(CFW packs for atmosphere and sxos)}
{Github: https://github.com/carcaschoi/ShallowSea}

[CFW Ams (fss0)]
fss0=atmosphere/fusee-secondary.bin
atmosphere=1
logopath=bootloader/bootlogo.bmp
icon=bootloader/res/atmosphere.bmp
kip1patch=nosigchk
cal0blank=1

[CFW Ams (fusee-primary)]
payload=bootloader/payloads/fusee-primary.bin
icon=bootloader/res/atmosphere.bmp

[Stock OFW (No CFW)]
emummc_force_disable=1
fss0=atmosphere/fusee-secondary.bin
icon=bootloader/res/icon_stock.bmp
stock=1

[Hekate menu]
icon=bootloader/res/icon_hekate.bmp
payload=/bootloader/update.bin

[CommonProblemResolver]
icon=bootloader/res/icon_payload.bmp
payload=bootloader/payloads/CommonProblemResolver.bin

[Lockpick RCM]
icon=bootloader/res/icon_lockpick.bmp
payload=bootloader/payloads/Lockpick_RCM.bin

[TegraExplorer]
payload=bootloader/payloads/TegraExplorer.bin
icon=bootloader/res/icon_payload.bmp

[Hack sysnand]
fss0=atmosphere/fusee-secondary.bin
logopath=bootloader/bootlogo.bmp
icon=bootloader/res/atmosphere-sys.bmp
atmosphere=1
emummc_force_disable=1

**Comment by carcaschoi** [comment]
studio pancake overlays can show the config. Hekate cannot show the name of it but the current launch function is still work.

Sorry for my poor English

**Comment by Masamune3210** [comment]
> > Upload here hekate_ipl.ini
> 
> This is the bug of hekate. I know what I am doing.

Should probably not be super aggressive to people you are asking for help from or reporting an issue to.....

**Comment by CTCaer** [comment]
Bug is on the label

**Comment by carcaschoi** [comment]
> > > Upload here hekate_ipl.ini
> > 
> > 
> > This is the bug of hekate. I know what I am doing.
> 
> You know what you are doing, but in first post you have used japanese quotation, while in ini file it's not used. You clearly don't understand possible implications of that, so stating that you know what you are doing in this case is baffling.

I am sorry for my misunderstanding. I misread it as 「Update here hekate_ipl.ini」lol😣

**Comment by CTCaer** [comment]
Fixed in latest release

**Comment by DraconicNEO** [comment]
> 
> 
> in the launch menu ![16297166231272082284472941285942](https://user-images.githubusercontent.com/64573431/130437125-f42e9799-e3f2-4421-921a-f50263c87322.jpg)
> 
> 「Hack sysnand」 word doesn't show up

Sorry if this is off topic but where did you get the icon for the sys cfw?
