### ISSUE TITLE
Add GUI + Touch screen support via a module.

### ISSUE THREAD

**Issue by CTCaer** [CTCaer/hekate#65]

**Comment by fennectech** [comment]
The people over at 
https://github.com/Guillem96/argon-nx/ have this.

**Comment by balika011** [comment]
I have no idea where they got the idea from... [https://github.com/balika011/hekate](https://github.com/balika011/hekate)

**Comment by fennectech** [comment]
If we’re lookign for touchscreen firmware. We can ether take it from HOS or distribute in /bootloader somewhere.

**Comment by CTCaer** [comment]
https://github.com/CTCaer/hekate/commit/c41f98039c0c7328c10a56958956bbc0a5626ee7
