### ISSUE TITLE
failed to match warmboot with fuses-Sleep Mode won't work

### ISSUE THREAD

**Issue by crazypat33** [CTCaer/hekate#659]
Hello !
Sorry for my english I'm French :(
I have a Mariko switch + sx core 3.1.0 + emuNAND
OFW 10.1.0

I have Atmosphere + Hekate 5.6.0

When I want to launch Atmosphere I have the error
_Failed to match warm boot with fuses - Sleep Mode won't work_

pgkg1 ('20200303104606)
Burnt Fuses (ODM 7/6) 14-0  HOS 11.0.0  12.0.1
ODM Fields (4,6,7) 00010A40 00000000 00003FFF

There was already a topic for this problem but it's closed, so I open this one.

I'm totaly noob, can you help me with simple instructions ?
Thanks !

**Comment by CTCaer** [comment]
You should run at least once Stock mode (Stock is via hekate. Basically like OFW but with custom bootloader) or Sys CFW. (Preferably stock, so you don't introduce discrepancies to your Sys).
That will create a folder in sd root called `warmboot_mariko`. Always back it up when you format your card.

An extremely simple way to boot Stock is with the following in your hekate_ipl.ini.
```ini
[Stock]
fss0=atmosphere/package3
stock=1
emummc_force_disable=1
```
If you still have an older atmosphere, you can replace `package3` with `fusee-secondary.bin`.
Atmosphere fss0 is needed so hekate can pull Exosphere from it. Don't worry, the gist of it is that nintendo can't actually detect that change. It would be like running OFW.
After that reboot and done.
