### ISSUE TITLE
i found a problem

### ISSUE THREAD

**Issue by MoraGMXD** [CTCaer/hekate#662]
hello I found a problem when I start the fusee normal load but when the nintendo switch loading screen ends the screen remains black

**Comment by Masamune3210** [comment]
If it's making it to the switch logo it's not a problem with Hekate. Go make a issue in the atmosphere repo and follow the template

**Comment by MoraGMXD** [comment]
ok thanks

**Comment by CTCaer** [comment]
Bootong via fusee issues should be reported in atmosphere repo.
On the other hand, your issue is probably an outdated sysmodule.
