### ISSUE TITLE
It is possible to restore emummc into sysnand?

### ISSUE THREAD

**Issue by davedave85** [CTCaer/hekate#667]
hi,

i want to to know if its possible to restore emummc into sysnand and if the procedure is the same to restore any backup?

**Comment by impeeza** [comment]
Hi, this is not an issue.  This space is for report bugs.  

The answer to your question is on the main page ot nyx section. There states how to restore a backup, if you use a hidden partition you must make a backup to files of it. Then restore that backup on the sysnand. You can use nyx or emutool for the backup.

**Comment by davedave85** [comment]
> Hi, this is not an issue. This space is for report bugs.
> 
> The answer to your question is on the main page ot nyx section. There states how to restore a backup, if you use a hidden partition you must make a backup to files of it. Then restore that backup on the sysnand. You can use nyx or emutool for the backup.

thanks and sorry

**Comment by impeeza** [comment]
Worry not 😀 you can get help on discord or gbatemp or another forum you like

**Comment by davedave85** [comment]
oh its possible to share the discord? 😀

**Comment by impeeza** [comment]
I don't know which because I don't use discord but I think can be found using Google 👍
