### ISSUE TITLE
Question: reboot to payload

### ISSUE THREAD

**Issue by vobo70** [CTCaer/hekate#669]
Hello,
I just updated Hekate to newest version and NeutOS also, and when I do reboot to payload
(reboot_payload.bin in atmosphere folder is renamed hekate_ctcaer_5.6.3.bin)
i reboot to neutos.
What I am doing wrong?
regards,
Maciek

**Comment by impeeza** [comment]
for the first you are asking support on a issue report space.  this space is for report bugs.  for support you can go to Discord, GBATemp or any forum you like.  NeutOS is an unofficial fork of Atmosphére so no supported by hekate nor others homebrew can be given, please go to NeutOS support page for support.  or change to official Atmosphére and make your setup manually.

**Comment by vobo70** [comment]
OK; I will do that
