### ISSUE TITLE
Add a Confirmation Screen before Booting Default Config when No SD Card

### ISSUE THREAD

**Issue by 3096** [CTCaer/hekate#67]
Sometimes user could forget that no SD card is in the Switch then accidentally boot stock Horizon, which can be quite dangerous.

**Comment by CTCaer** [comment]
Pff.
https://github.com/CTCaer/hekate/issues/49
https://github.com/CTCaer/hekate/commit/d33f60e924098a2f3283b3c1a7d9c4c8001ebcaf#diff-799c7cc4c061751437d68637b5d9ae27R1767

**Comment by 3096** [comment]
Lol. I did see that issue title when checking duplicates but I stopped reading at the word "failure" thinking it was about something else.
Sorry, ADHD.

Thanks tho
