### ISSUE TITLE
Typo in line 108 of readme: `If emuMMC is enabled, emummc_force_disabled=1 is required.`

### ISSUE THREAD

**Issue by Kupie** [CTCaer/hekate#670]
Instead of saying:
`If emuMMC is enabled, emummc_force_disabled=1 is required.`

It should say:
`If emuMMC is enabled, emummc_force_disable=1 is required.`

https://github.com/CTCaer/hekate/blob/master/README.md?plain=1#L108

**Comment by CTCaer** [comment]
Fixed. Thanks
