### ISSUE TITLE
old nyx gui found there will be dragons

### ISSUE THREAD

**Issue by Marshmellin** [CTCaer/hekate#678]

**Comment by impeeza** [comment]
¿?

**Comment by urherenow** [comment]
Dude made it abundantly clear that he can't follow directions, starting with deleting the template instead of using it, I'll bet even reading it.

OP: you can't simply inject the new .bin. You have to extract ALL of the files too, overwriting the old ones.

**Comment by impeeza** [comment]
Ah, I now understand, that error is for not read the release and follow the instructions for updating.

Not a bug or an issue!

This thread must be closed

**Comment by Marshmellin** [comment]
I don’t understand English very good so this is confusing for my. I’m gonna try it later but I literally renewed the bin 1000 times.

**Comment by urherenow** [comment]
That's your problem. You don't "renew the bin". You extract the entire .zip file, overwriting all other files.

There is 1 and only 1 thing that causes this error. The hekate.bin your injecting is newer than the nyx.bin on your card.

**Comment by Marshmellin** [comment]
Ok so I need to inject a newer version of the nyx
Or I need to inject a older version of hekate?

**Comment by urherenow** [comment]
You need to go to the releases page, download the .zip file, and extract everything inside, onto the root of your sd card.

**Comment by Marshmellin** [comment]
Thank you so much. Right now I can't check it but when I can I'll write to you

**Comment by urherenow** [comment]
Please don't here. Go to discord or gbatemp, and close this issue. This space is for reporting bugs, it's not a support forum.

**Comment by Marshmellin** [comment]
What discord?

**Comment by Marshmellin** [comment]
Can you give me the link?

**Comment by impeeza** [comment]
Literally any web browser will give you a link as answer.

**Comment by urherenow** [comment]
ReSwitched or RetroGamer

**Comment by impeeza** [comment]
Gbatemp

**Comment by CTCaer** [comment]
Dunno why that convo reached that point, but just extract the bootloader folder from release zip into sd card.
No matter how many times you replace the binary, you will always get the same message if you don't update that folder.

**Comment by Marshmellin** [comment]
Thanks

**Comment by janAkali** [comment]
Some archivers fail to extract hekate zip archives correctly. In my case, xarchiver on linux was not extracting anything in bootloader directory except `update.bin`:

![](https://d.l3n.co/cNybY0.png)

Solution: I used 7zip inside terminal to extract all files. This fixed the error.
