### ISSUE TITLE
Updated switch now new hakate not working

### ISSUE THREAD

**Issue by Obliviondarkness2** [CTCaer/hekate#683]
Hey guys

Soo my hakate 13.1 loads up and the switch logo comes up then it throws up an error

**Comment by impeeza** [comment]
Hi,  if Hekate passes generally is not a Hekate problem, this is not a support site, please go to one of them (discord, gbatemp, etc.) and provide more information, b.e. your complete configuration, exact error and time when you got it.

please close this issue.
