### ISSUE TITLE
Windows will detect UMS device but can't assign a letter

### ISSUE THREAD

**Issue by EpicLPer** [CTCaer/hekate#685]
Heya!

I've browsed the issues a bit but couldn't find this particular weird case here.  
Plugged the Switch in, started UMS and while the device and driver is correctly recognized and being displayed it doesn't actually show any partitions despite saying the drive is Online.  

![image](https://user-images.githubusercontent.com/8442196/144106572-d4c730da-4c95-4397-812e-785fa470dccf.png)  

![image](https://user-images.githubusercontent.com/8442196/144106720-7d8d49da-0190-4c63-8c90-d02cc4d0072b.png)

Could this be due to an incompatible SD Card (using this one: [Amazon Link](https://www.amazon.de/gp/product/B08GXXKY6P/ref=ppx_yo_dt_b_asin_title_o00_s00?ie=UTF8&th=1))? Tho would be weird since everything else seems to work perfectly normal (EmuMMC, Android, Backups, etc.).

Thanks for help already!

**Comment by CTCaer** [comment]
You should fix your windows installation first.
That error in disk management is not ok.

After that, try again and if you still have the problem, *reopen the issue*.

(Have in mind that probably I won't be able to do anything. That's because it seems like a host issue. But we'll see after you fix that.)

**Comment by EpicLPer** [comment]
I hope commenting doesn't automatically open the issue again but yes, you were right and sorry for opening one too early :(

Just to give details on how/why this happened: I had VMware running in the background to mess with the (old) Android partition files, and apparently even if you deny the automatic USB connection prompt you get to attach the USB device to the VM it'll still not fully be recognized by host. I had to fully close VMware to fix this.
