### ISSUE TITLE
Partition Manager backup/restore does not copy over attributes metadata on folders

### ISSUE THREAD

**Issue by Chariblaze** [CTCaer/hekate#686]
Running Hekate 5.6.5. Test with sysMMC:
1. Reduce SD card contents to less than 1 GB contents. Install a small game to test with, like the Twitch app.
2. Mount SD card.
3. Set archive bit on all game files/folders: `F:\>attrib +A Nintendo\Contents\registered\* /S /D`
4. List archive bits on game files/folders:  `F:\>attrib Nintendo\Contents\registered\* /S /D`
5. Format with Hekate's Partition Manager, using the automatic backup/restore.
6. Mount SD and list archive bits again: `F:\>attrib Nintendo\Contents\registered\* /S /D`

Trying to launch installed games without the archive bits causes them to error out. Using the Fix Archive Bit tool resolves the issue.

---

![hekate games error cropped](https://user-images.githubusercontent.com/25140801/144319815-faf15bd7-4ae5-4e43-b321-c35e570fd1ee.jpg)

![nyx20211202_181120](https://user-images.githubusercontent.com/25140801/144334478-9516f267-167b-4ca7-a513-d9ad578cc4d5.png)

**Comment by CTCaer** [comment]
That's actually weird, because I made sure to copy over the attributes:
https://github.com/CTCaer/hekate/blob/master/nyx/nyx_gui/frontend/gui_tools_partition_manager.c#L179
This basically sets the copied file's attributes to the attributes of the source file. And 0xFF mask allows every attribute from the original to be set on the new file.
```c
FRESULT f_chmod (
  const TCHAR* path, /* [IN] Object name */
  BYTE attr,         /* [IN] Attribute flags */
  BYTE mask          /* [IN] Attribute masks */
);
```
```
f_close(&fp_dst);                 // Syncs and closes destination file
f_chdrive(dst);                   // Changes main disk to destination, so relative path based functions like f_chmod work
f_chmod(path, fno.fattrib, 0xFF); // sets attributes to the dst file from src file and uses relative path.
```


Hmm...

**Comment by Chariblaze** [comment]
> Btw just making sure, I assume you had correct archive bits before the backup/restore, right?

Yeah. I've also had Nyx set/unset the bits on its own in a fun loop:

1. Partition/format with backup & restore
2. Fix archive bits (5 set)
3. Partition/format with backup & restore
4. Fix archive bits (5 set)
5. ...

**Comment by Chariblaze** [comment]
It's specifically folders that don't have their attributes copied, files are fine.

1. `F:\>attrib +A /s /d *`
2. `F:\>attrib /s /d * > attribs-before-format.txt`
3. Unmount, partition/format in Nyx.
4. `F:\>attrib /s /d * > attribs-before-format.txt`
5. Compare txts with Notepad++ Compare plugin or something similar.

**Comment by CTCaer** [comment]
Found the issue in the code and it's exactly as described.
Thanks for reporting that and actually investigating it.

Will be fixed in next version.

**Comment by CTCaer** [comment]
Get latest release that fixes that.
Thanks for testing and actually finding the issue on your own
