### ISSUE TITLE
About translation

### ISSUE THREAD

**Issue by yyoossk** [CTCaer/hekate#688]
I want to translate it into Japanese
Doesn't it support language files?

**Comment by yyoossk** [comment]
I tried the translation, but the characters were garbled
Can't change the font file?

**Comment by CTCaer** [comment]
https://github.com/CTCaer/hekate/issues/252
mentioning main thread and closing duplicate

**Comment by TheTokenMoose** [comment]
> The gui based on [lvgl](https://lvgl.io/), build your own font c file(see this [interui_30.c](https://github.com/CTCaer/hekate/blob/master/bdk/libs/lvgl/lv_fonts/interui_30.c) as template) and bitmap(res.pak in release zip file, start with 0x7900) with Japanese words, enable [LV_TXT_UTF8](https://github.com/CTCaer/hekate/blob/master/bdk/libs/lv_conf.h#L129), add [custom font](https://github.com/CTCaer/hekate/blob/master/bdk/libs/lv_conf.h#L206) and recompile.
> 
> This is my work. I use LvglFontTool and HarmonyOS Sans font to build a c file font. And replace the default font from interui_30 to this.
> 
> ![nyx20220420_164213](https://user-images.githubusercontent.com/8280291/169643560-065419ae-a3a0-444a-97ff-5c07df929ec4.jpg) ![nyx20220420_164203](https://user-images.githubusercontent.com/8280291/169643564-90080cdf-a4f2-47ef-ab0e-038dcde6b6b0.jpg)

My Hekate UI is in Chinese, like this. I'm wanting to change it to English without a fresh install. Is it possible to reverse this type of change by just replacing the files on my SD card with the same version source files? I hope this isn't a dumb question, I'm new to this..

**Comment by easyworld** [comment]
> > The gui based on [lvgl](https://lvgl.io/), build your own font c file(see this [interui_30.c](https://github.com/CTCaer/hekate/blob/master/bdk/libs/lvgl/lv_fonts/interui_30.c) as template) and bitmap(res.pak in release zip file, start with 0x7900) with Japanese words, enable [LV_TXT_UTF8](https://github.com/CTCaer/hekate/blob/master/bdk/libs/lv_conf.h#L129), add [custom font](https://github.com/CTCaer/hekate/blob/master/bdk/libs/lv_conf.h#L206) and recompile.
> > This is my work. I use LvglFontTool and HarmonyOS Sans font to build a c file font. And replace the default font from interui_30 to this.
> > ![nyx20220420_164213](https://user-images.githubusercontent.com/8280291/169643560-065419ae-a3a0-444a-97ff-5c07df929ec4.jpg) ![nyx20220420_164203](https://user-images.githubusercontent.com/8280291/169643564-90080cdf-a4f2-47ef-ab0e-038dcde6b6b0.jpg)
> 
> My Hekate UI is in Chinese, like this. I'm wanting to change it to English without a fresh install. Is it possible to reverse this type of change by just replacing the files on my SD card with the same version source files? I hope this isn't a dumb question, I'm new to this..

Simply replace `/bootloader/sys/res.pak` with the version from the corresponding official zip file.

**Comment by TheTokenMoose** [comment]
> > > The gui based on [lvgl](https://lvgl.io/), build your own font c file(see this [interui_30.c](https://github.com/CTCaer/hekate/blob/master/bdk/libs/lvgl/lv_fonts/interui_30.c) as template) and bitmap(res.pak in release zip file, start with 0x7900) with Japanese words, enable [LV_TXT_UTF8](https://github.com/CTCaer/hekate/blob/master/bdk/libs/lv_conf.h#L129), add [custom font](https://github.com/CTCaer/hekate/blob/master/bdk/libs/lv_conf.h#L206) and recompile.
> > > This is my work. I use LvglFontTool and HarmonyOS Sans font to build a c file font. And replace the default font from interui_30 to this.
> > > ![nyx20220420_164213](https://user-images.githubusercontent.com/8280291/169643560-065419ae-a3a0-444a-97ff-5c07df929ec4.jpg) ![nyx20220420_164203](https://user-images.githubusercontent.com/8280291/169643564-90080cdf-a4f2-47ef-ab0e-038dcde6b6b0.jpg)
> > 
> > 
> > My Hekate UI is in Chinese, like this. I'm wanting to change it to English without a fresh install. Is it possible to reverse this type of change by just replacing the files on my SD card with the same version source files? I hope this isn't a dumb question, I'm new to this..
> 
> Simply replace `/bootloader/sys/nyx.bin` with the version from the corresponding official zip file.

Thank you, that worked instantly. Appreciate it.

**Comment by xElChoco** [comment]
Hi TheTokenMoose, i'm also trying to change my chinese hatake to english. Can you please explain me a little more how did you managed to do it?

**Comment by TheTokenMoose** [comment]
> Hi TheTokenMoose, i'm also trying to change my chinese hatake to english. Can you please explain me a little more how did you managed to do it?

I downloaded the official zip file, opened it and copied the file '''/bootloader/sys/nyx.bin'' onto my SD card replacing the same file. This solved it for me immediately.

**Comment by L1keava** [comment]
> The gui based on [lvgl](https://lvgl.io/), build your own font c file(see this [interui_30.c](https://github.com/CTCaer/hekate/blob/master/bdk/libs/lvgl/lv_fonts/interui_30.c) as template) and bitmap(res.pak in release zip file, start with 0x7900) with Japanese words, enable [LV_TXT_UTF8](https://github.com/CTCaer/hekate/blob/master/bdk/libs/lv_conf.h#L129), add [custom font](https://github.com/CTCaer/hekate/blob/master/bdk/libs/lv_conf.h#L206) and recompile.
> 
> This is my work. I use LvglFontTool and HarmonyOS Sans font to build a c file font. And replace the default font from interui_30 to this.
> 
> ![nyx20220420_164213](https://user-images.githubusercontent.com/8280291/169643560-065419ae-a3a0-444a-97ff-5c07df929ec4.jpg) ![nyx20220420_164203](https://user-images.githubusercontent.com/8280291/169643564-90080cdf-a4f2-47ef-ab0e-038dcde6b6b0.jpg)

@easyworld 可以问一下添加汉字的方法吗，想添加一些汉字，使用了https://lvgl.io/tools/fontconverter 转换文字后格式却不太一样，不知道是哪里的问题。十分感谢

**Comment by alerene** [comment]
@easyworld 
Thanks to you, I managed to implement the Latin characters:
ÈÑàáèéíñòóùú.
I had to create them by hand; it wasn't very difficult.

<img width="1280" height="720" alt="Image" src="https://github.com/user-attachments/assets/7dd09dda-238b-45c7-9050-f22245b2da00" />

<img width="1280" height="720" alt="Image" src="https://github.com/user-attachments/assets/37790178-3b43-42c3-810b-ac7544d62ec5" />
