### ISSUE TITLE
Charging speed limited to 7.5w

### ISSUE THREAD

**Issue by ded-doggo** [CTCaer/hekate#691]
Battery info always displays the "Input wattage limit" to be 7.5w and while charging it says it's drawing 1300mA.
Shouldn't it be able to draw 18w?

**Comment by CTCaer** [comment]
Nope. I don't do PD in hekate.
So when you connect charger while in it, it will do auto negotiation to 5V or 15V if supported and then set 500mA max.
(15 * 0.5 = 7.5)

**Comment by ded-doggo** [comment]
Why Is that?
