### ISSUE TITLE
boot hekate and cfw off USB drive

### ISSUE THREAD

**Issue by CrCrate** [CTCaer/hekate#697]
my sd card slot broke and gives "sd card failed to initialize" when i try to boot. i tried replacing the reader but it seems to be an issue with the motherboard connector.

is there a way to boot homebrew from a usb stick instead of a sd card?

**Comment by Masamune3210** [comment]
Nope

**Comment by CTCaer** [comment]
nope and possibly never with the amount of work it needs to support usb host mode
