### ISSUE TITLE
Make Command Error

### ISSUE THREAD

**Issue by sth5playz** [CTCaer/hekate#702]
Whenever i try to run make i get this error

Makefile:5: /opt/devkitpro/devkitARM/base_rules: No such file or directory
make: *** No rule to make target '/opt/devkitpro/devkitARM/base_rules'.  Stop.

Anyone know how to fix?

**Comment by urherenow** [comment]
GitHub isn't a help forum, and this area is to report bugs. Go to gab temp and click the link in my thread. Or google it. Your problem is that you haven't installed devkitarm properly with the proper libraries.

**Comment by CTCaer** [comment]
you are missing devkitarm-rules
