### ISSUE TITLE
OLED Switch Can't boot sysnand with emummc enabled.

### ISSUE THREAD

**Issue by Ninjistix** [CTCaer/hekate#704]
Console Info: White OLED Console
Chip: OLED v2
FW: 13.2.1
Atmosphere: 1.2.6
Hekate: 5.7.0
Sigpatches: 13.2.1-1.2.6

This is my current hekate_ipl.ini
```
[config]
autoboot=0
autoboot_list=0
bootwait=3
verification=1
backlight=100
autohosoff=1
autonogc=0
updater2p=1


{--- Custom Firmware ---}
[CFW (SYSNAND)]
emummc_force_disable=1
payload=bootloader/payloads/fusee.bin
icon=bootloader/res/sysnand.bmp
{}

[CFW (EMUMMC)]
emummcforce=1
payload=bootloader/payloads/fusee.bin
icon=bootloader/res/emummc.bmp
{}
```

With EMUMMC disabled I can boot into atmosphere SYSNAND, with EMUMMC enabled I can only boot into EMUMMC, even if I choose SYSNAND it still take's me to EMUMMC.

this this config allows me to boot into both SYSNAND AND EMUMMC, but I was told that package3 no longer supports the current sigpatchs.

```
[config]
autoboot=0
autoboot_list=0
bootwait=3
verification=1
backlight=100
autohosoff=1
autonogc=0
updater2p=1


[CFW (SYSNAND)]
emummc_force_disable=1
fss0=atmosphere/package3
icon=bootloader/res/sysnand.bmp
{}

[CFW (EMUMMC)]
payload=bootloader/payloads/fusee.bin
icon=bootloader/res/emummc.bmp
{}
```

**Comment by CTCaer** [comment]
>Asking for piracy help

...
