### ISSUE TITLE
Weird resizing issue

### ISSUE THREAD

**Issue by sthetix** [CTCaer/hekate#705]
So, I just found out that when we resize the emuMMC using Hekate to 12GB, we will have 4.6GB of free space

While doing the same with the NXNANDManager will give us 9.3GB of free space.

How to fix this issue?

I am using Hekate 5.7.0 on the OLED. 

Thx

![1](https://user-images.githubusercontent.com/22261135/151315529-409e05ee-ebb3-4694-9450-9897f2ea00f1.jpg)
![hekate](https://user-images.githubusercontent.com/22261135/151316547-9fe4f294-1f40-446d-bed2-550dc2ca4870.jpg)

**Comment by impeeza** [comment]
I think is because you did select the option "format use partition" on NXNANDMANAGER

**Comment by CTCaer** [comment]
There's an existing convo here https://github.com/CTCaer/hekate/issues/675 for OLED generally and also that resizing issue.

If possible, I need some log from the nyx.bin I provided there.
