### ISSUE TITLE
Fix Archive Bit error Nyx exception occured 

### ISSUE THREAD

**Issue by quakcertsep** [CTCaer/hekate#706]
When I try to fix my archive bit it says 
"Nyx exception occured (LR 8100E4C):
DABRT
Press any key. . ."
Is this because I have a duplicate ini file in bootloader ini for hekate? I'm not sure of the cause. Does this error happen when there is nothing to fix or it tries to fix a nintendo folder file?

**Comment by CTCaer** [comment]
The LR 8100E4C number sent misses a digit.
Try to get the error again.

**Comment by CTCaer** [comment]
Seems user bailed out
