### ISSUE TITLE
Latest release is not correctly shown in github

### ISSUE THREAD

**Issue by Devilmoon** [CTCaer/hekate#709]
https://github.com/CTCaer/hekate/releases/latest/ redirects to https://github.com/CTCaer/hekate/releases/tag/v5.6.5 instead of https://github.com/CTCaer/hekate/releases/tag/v5.7.0
Going to https://github.com/CTCaer/hekate/releases also shows 5.6.5 as the latest release; the only way to find the actual latest is to manually go to Tags instead of Releases

**Comment by CTCaer** [comment]
what the hell
where did it go

**Comment by urherenow** [comment]
On my phone, it shows up under all releases...

![image](https://user-images.githubusercontent.com/6448336/153679122-90c43139-c58d-467f-8737-02efd815bae8.png)

**Comment by CTCaer** [comment]
It doesn't show up anywhere for me (pc/phone). Only the direct links work.
Anyway, hopefully github will fix that

**Comment by CTCaer** [comment]
Seems fixed now, after editing and saving release with no changes.
Thanks for reporting. Reopen if it happens again.
