### ISSUE TITLE
remove or skip backup erpt_reports and other log and error log folders

### ISSUE THREAD

**Issue by ImanCol** [CTCaer/hekate#711]
When I make a partition of the MicroSD, if I don't delete these folders that atmosphere creates, Hekate will create a backup and restore them, if I have occupied less than 1GB in the MicroSd. This makes it take too long to partition the MicroSD as these atmosphere log folders contain thousands of files

**Comment by CTCaer** [comment]
Delete them then

**Comment by ImanCol** [comment]
lol
