### ISSUE TITLE
stuck in the menu

### ISSUE THREAD

**Issue by ertyplax** [CTCaer/hekate#714]
when i inject the payload, access the menu and click on launch or more configs it says "no main boot entries found...", then it says to check if there are boot entries on "hekate_ipl.ini" but  when i checked the file was missing

**Comment by impeeza** [comment]
Exactly. You need to read the installation instructions on readme and create a hekate_ipl.ini file which suits you.  Please this space is for issues, bug report or enhancements request.  Go to support sites like gbatemp or discord for help

**Comment by ertyplax** [comment]
ok thanks
