### ISSUE TITLE
Nyx exception when performing specific sequence of actions

### ISSUE THREAD

**Issue by v1993** [CTCaer/hekate#715]
All of those are done with touchscreen (except for the last step)

1. Select "Options"
2. Press "Auto Boot"
3. Pick configuration
4. Press "Save Options"
5. Press "OK!"
6. Press "B" the physical button

This will result in the following error:

```
Nyx exception occurred (LR 81040D0C):
RESET
Press any key...
```

**Comment by impeeza** [comment]
Can confirm happen the same to me
![IMG_20220301_083852](https://user-images.githubusercontent.com/41979604/156179370-b5785bd4-c3c3-4af7-8f9c-f926a3538dd7.jpg)

**Comment by CTCaer** [comment]
Thanks. That's a null pointer dereference.
Any place elsewhere that this also happens?
(Basically I manually manage where B button acts like back/close/etc. The above case is one that I set it and not clear it when the dialog closes.)

**Comment by impeeza** [comment]
That little rascals (null pointers) they hide everywhere.  Thanks for your effort

**Comment by CTCaer** [comment]
Fixed in latest version. Thanks for reporting it.
