### ISSUE TITLE
[bug] nyx missing in first run

### ISSUE THREAD

**Issue by lowburger** [CTCaer/hekate#717]
Hi, I report bug in hekate latest version I find when I make setup for friend.

Copy hekate files in empty sd card, sending payload and nyx missing message appear, after reload all works fine. Thx

**Comment by CTCaer** [comment]
Yeah 5.7.0 has a bug where on the `first boot with no hekate_ipl.ini` it will create it and then unmount sd card.
And because after that the sd is unmounted it won't find the files.

For now, until I push the fix, you just reload on first ever boot without .ini.

**Comment by CTCaer** [comment]
Fixed in latest version
