### ISSUE TITLE
"SD has GPT only!"

### ISSUE THREAD

**Issue by RiifromAnotherPlanet** [CTCaer/hekate#719]
I switched my 64gb SD card to a 128gb And been running into endless problems.

Fusee payload wont work ( failed to mount sd card) so I tried with hetake. After a loooot of troubleshooting (formatting sd to fat32, redownloading everything, rewritting hetake ipl.ini) I got Atmosphere to launch but now I get

SD has GPT only!

Found pkg1 ( '20220105094454')

Identified pkg1 and mkey 12

Loaded config and pkg1

CFW mode

Generated keys

No mandatory secmon or warmboot provided!

Failed to launch HOS!

I cant find anyone with the same problem and I'm tired

**Comment by urherenow** [comment]
This isn't a support forum, and you formatted it wrong. Just format it within nyx and copy your files back afterwards.

**Comment by RiifromAnotherPlanet** [comment]
Thanks so much and I'm sorry, I'll be more careful next time. Should I delete the post?

**Comment by urherenow** [comment]
There's no deleting it, but you can close the issue as the author. If allowing nyx to format solved your problem, then yes, close it.

**Comment by CTCaer** [comment]
You should use Nyx to format as already suggested. Other than that, post a screenshot or photo from `Console info -> microSD`

**Comment by RiifromAnotherPlanet** [comment]
Thanks for all the help. Nyx is the same as hetake right? So I should format my sd card from my switch and not my pc (having a backup on my pc as formatting deletes data. 

![20220313_030653](https://user-images.githubusercontent.com/101304201/158047501-3692eab3-401c-4d17-b112-9f955d9de0cd.jpg)
)

**Comment by Masamune3210** [comment]
Yes, Nyx is Hekate's GUI and extended tools. If there is a small enough amount of files on the card, the formatter will even backup and replace the files for you, just select to format with the sd card being one contiguous fat32 partition

**Comment by RiifromAnotherPlanet** [comment]
Where is that option? What's it's name? I've searched for some formatting tool and I can't find anything by that name

**Comment by Masamune3210** [comment]
I believe it's in tools or utilities and named partition SD card or something similar. I'm not near my switch right now, sorry

**Comment by urherenow** [comment]
Yes, make sure your files are backed up, and don't forget your emummc backup, if you're using a partition based emummc, then let nyx partition your card.

**Comment by RiifromAnotherPlanet** [comment]
Thank you all so much! Really. For someone who was posting the wrong thing everyone was so ready to help. It made me feel so welcomed even though I know so little. Have a good one!
