### ISSUE TITLE
logo of bootloader menu

### ISSUE THREAD

**Issue by thomleg50** [CTCaer/hekate#72]
hi,
i would like to know how to change the logo of the bootloader and waht format it's needed and size.
Thanks you

**Comment by CTCaer** [comment]
https://github.com/CTCaer/hekate/blob/master/README_BOOTLOGO.md

**Comment by thomleg50** [comment]
it's not that i mean the logo in right-down of the bootloader menu

**Comment by CTCaer** [comment]
Check the code. All details are inside.

**Comment by thomleg50** [comment]
i tried but i've got that :
https://cdn.discordapp.com/attachments/474297106602000403/480766571850235915/JPEG_20180819_175431.jpg

**Comment by pcwizard7** [comment]
is there a way to change the menus text size as its very hard to read?
