### ISSUE TITLE
UMS mounting issue

### ISSUE THREAD

**Issue by Dola-Shuvi** [CTCaer/hekate#721]
Good day,
I have recently modded my V1 switch and so far it's working great. The only issue I have run into is using mounting the SD card via UMS, both in hekate as well as TegraRcmGUI. The switch gets detected as a device on my PC but shows up with 0MB storage and doesn't get assigned a driver letter. Diskpart lists the disk correctly but also can not find any partitions. Outside of UMS the SD card works perfectly and is less than a month old.

So far I have only found #685 and #604 which are the exact issue I'm experiencing, however there is no detailed information on how it was eventually fixed. I believe this is some sort of driver issue with Windows but I'm honestly lost on how to fix it as there is nothing being logged in event viewer. If possible I would like to avoid having to wipe my Windows install.

Some additional information on my setup:
Switch is running firmware 13.2.1
SD card is 256GB formatted as FAT32+emummc
Using hekate v5.7.0 & Nyx v1.2.0
CFW is Atmosphère 1.2.6
USB port used is a 3.0 port connected to the motherboard 3.0 header (additionally tested with a 2.0 port integrated into my SD reader)

I would appreciate any help or additional information that  could lead to a solution for this issue.

Thank you in advance for any help and for creating this amazing project.

**Comment by CTCaer** [comment]
Well MBR and HW seems fine.

In your case I would check that you didn't replace the UMS drivers with sth else like libusbk.
That's how it should show up:
By connection:
![image](https://user-images.githubusercontent.com/3665130/158221625-c5d78c86-5721-4590-8483-270ffd0b1f07.png)
By type:
![image](https://user-images.githubusercontent.com/3665130/158221695-c3eaecd5-3dfe-426e-a3e1-fc459a62a40b.png)

**Comment by Dola-Shuvi** [comment]
Looks to me like it loaded the correct drivers properly. I did a test under Debian and it properly mounted there so I assume a hardware issue can be ruled out at this point.
![mmc_2022-03-14_18-34-24](https://user-images.githubusercontent.com/16194579/158229300-86ef44ee-1d85-4d08-a434-2f988a543743.png)
![mmc_2022-03-14_18-36-10](https://user-images.githubusercontent.com/16194579/158229302-fd6538b6-04a6-4b43-b684-1fd8d5d03971.png)
![mmc_2022-03-14_18-01-38](https://user-images.githubusercontent.com/16194579/158223136-4319fe6e-7ad1-457a-b3a3-0e75d5805259.png)

**Comment by CTCaer** [comment]
I see you are having too many ext storage readers (probably an all-in-one), did you check the proper driver in disk management?
Because being empty would match the other ones and not hekate UMS.
Also I see you have a filter driver that shouldn't have been there normally. What's fltsrv.sys?
Also send a screenshot from Volumes tab (hit the Populate button first).
![image](https://user-images.githubusercontent.com/3665130/158236356-160e8ee1-8e6f-4673-9680-c9006098cb72.png)

**Comment by Dola-Shuvi** [comment]
Correct, the ext storage reader is an all-in-one connected to an internal USB 2.0 header on my mainboard.
The console was connected to a USB 3.0 port on the chassis frontpanel that links to a USB 3.0 header on the mainboard however.
The driver fltsrv.sys is by Acronis and a part of Acronis True Image, a backup software.

Amazingly enough, simply disabling my all-in-one SD reader in device manager somehow allowed my PC to read the SD card via UMS. After disabling and re-enabling my SD reader it now somehow works at the same time.
![mmc_2022-03-14_19-31-53](https://user-images.githubusercontent.com/16194579/158238135-934129c9-d924-417a-b516-1f5896099db0.png)
![mmc_2022-03-14_19-50-06](https://user-images.githubusercontent.com/16194579/158240902-607d9171-8c31-403b-ab18-c95c39f3f164.png)

I can't seem to reproduce the issue after this anymore so I'll assume it was Windows being up to weird stuff.

Thank you so much for taking time out of your day to help me troubleshoot this issue. I greatly appreciate it and look forward to the future of this amazing project.

**Comment by Masamune3210** [comment]
Likely when you disabled and reenabled the SD reader, it unloaded the filter driver or something else that was conflicting. I would restart and try just to make sure the issue doesn't come back

**Comment by Dola-Shuvi** [comment]
I doubt that is the case as even after a reboot UMS and the SD reader both continue to work at the same time.

**Comment by rockisch** [comment]
Just for further confirmation, was having the same issue, and I also had an all-in-one SSD reader. Disabling it also fixed the issue for me.

**Comment by rom4ster** [comment]
This is unacceptable. Please fix this as this can cause a lot of grief during the setup process. I literally spent 3 hours trying to get this to work.

**Comment by Masamune3210** [comment]
Saying things are "unacceptable" in a free piece of software and in a function that is objectively not required to set up a system is probably not the best of ideas. If it's so "unacceptable", then don't accept it and set the SD card up the old fashioned way.

**Comment by rom4ster** [comment]
This issue is closed meaning it is refused to be worked on. An issue like this can cause a lot of grief and I think it deserves either to be worked on, or a reasonable explanation on why it cannot be fixed. Closing the issue and basically ignoring people who are having this issue (because it is closed) is probably more mean than saying "unacceptable" if I am honest.

**Comment by impeeza** [comment]
Is not an Hekate Issue is your PC OS issue, if you need further support you can go to Discord or GBATemp lots of people look in to that sites than here and you will get help promptly.
