### ISSUE TITLE
14.0 Update not supported

### ISSUE THREAD

**Issue by ItsThatGuy555** [CTCaer/hekate#725]
I updated my switch not even thinking about tried to launch payload and got the unknown pkg1 error

**Comment by Masamune3210** [comment]
Here we go again lmao

Update just came out, things need to be updated to support the new update, especially low level things lile Hekate and Atmosphere. Just gonna have to be patient unless you want to downgrade which is not recommended

**Comment by MarioMasta64** [comment]
both are updated

**Comment by CTCaer** [comment]
Get latest release
