### ISSUE TITLE
Can't boot in cfw on my 2.0.0 Switch

### ISSUE THREAD

**Issue by Q113P** [CTCaer/hekate#73]
So I'm trying to backup my Switch. I backed up my NAND but now need to backup thr key files. Anyway, when I load v3.2 payload (don't know what version of it was on the tutorial) I can't choose the first cfw option to boot into and the second option is the one that works for me but it's not cfw sadly. My system is  XAJ400045????? (don't want to share full number incase it could be tracked lol). Anyway can I please get help so I can finish backing up to retrieve those files and get into hekate cfw. Also if you share the proper sd card files because don't know why don't work.

**Comment by CTCaer** [comment]
You don't need to enter HOS to backup. Even if you could backup from there, who backups a live system?

Check your ini if it doesn't boot. Many packages out there are constantly breaking the ini parser.
Clean it up a little.
