### ISSUE TITLE
When I flash android at final step nothing happens?

### ISSUE THREAD

**Issue by DarkdraxH2O** [CTCaer/hekate#730]
The boot.img and twarp.img and tegra210-
icosa.dtb show that the file exists because it says files found in the video it had two options continue and ok it only shows ok for me and android doesn’t boot at all and when I check the files in the micro card. The boot, twarp, and icosa files are gone I’m assuming that’s what flashing does but why does the prompt to continue not show? Even though I did all the steps properly?

**Comment by CTCaer** [comment]
https://wiki.switchroot.org/en/Android/Setup-10
