### ISSUE TITLE
Archive Bit Nyx exception occurred 

### ISSUE THREAD

**Issue by Calebcoolguy1** [CTCaer/hekate#733]
While trying to perform Fix Archive Bit (all folders) the screen froze at this point. I've tried about 3 times to get past this point.
![image](https://user-images.githubusercontent.com/102933701/161460024-92b67ae6-087f-4580-8bf2-de4c2e2f618f.png)
On the 3rd attempt, I pressed the close button at the top right and got this message
![image](https://user-images.githubusercontent.com/102933701/161460216-0e9c2144-f37c-4db3-a938-75b70965faf4.png)
(It says specifically: Nyx exception occurred <LR 81000E84> DABRT)
I'm assuming that this might have something to do with the freezing of the Archive Bit but i'm not entirely sure.

**Comment by BeastMiner32** [comment]
I have also been getting a similar issue while trying to resolve an issue i was having with Smash Ultimate. Mine has a slightly different code with (LR 81000E14) DABRT and the error shows up without interaction. I am going to format my sdcard and check if it works any better then. But i will keep a backup of this particular version of this.

**Comment by urherenow** [comment]
Check your sd info screen for a 1bit width and for a suspect serial number. Also for storage space. If those look good, run h2testw on your card (use all available space).

**Comment by Calebcoolguy1** [comment]
I'm not totally sure where to find the information on the 1bit width or suspect serial number, is any of that here or am I on the wrong screen.
![image](https://user-images.githubusercontent.com/102933701/161619434-56dc4edd-4121-4ba1-98f2-621f84d313b4.png)

**Comment by CTCaer** [comment]
@Calebcoolguy1 that has nothing to do with 1bit more or anything. 99.9% it's corruption.
Especially when you use exfat.
In your case I would do a check and repair of it with chkdsk.
And reply with results of chkdsk and a rerun of archive bit fixer.

I guess I will put some protections against such hangs and and inform user for possible corruption.

**Comment by Calebcoolguy1** [comment]
Yeah I switched from exfat to FAT32 and now fix archive bit works as normal, thanks for the help!
