### ISSUE TITLE
[Feature Request] Add support for emummc options when using payload chainloading.

### ISSUE THREAD

**Issue by a31user** [CTCaer/hekate#737]
I would like to request you for emummc options when using payload chainloading. Emummc options such as emummcforce=1 works well on fss0, but won't work on payload chainloading. If people use sxos or reinx which won't work with fss0, emummc options won't work with downgraded emummc.

**Comment by urherenow** [comment]
Your quarrel is with reinx and sx, not hekate. SX is dead, so good luck with that. Not that you could ever communicate with the author anyway.

fss0 has nothing to do with either or with emummc anyway.

**Comment by urherenow** [comment]
It has N O T H I N G to do with hekate. If you load a payload, NO hekate options matter at all. It's up to that payload to support emummc. Stop bugging the hekate dev.

**Comment by CTCaer** [comment]
Piracy cfw discussion is not allowed
