### ISSUE TITLE
[bug] nyx missing when payload launch fail

### ISSUE THREAD

**Issue by lowburger** [CTCaer/hekate#746]
Hi, I report quite small bug where nyx do not reload.

1. Create config for test.bin payload in hekate_ipl.ini
2. Select from launch menu this missing payload

Result: Payload missing message then after pressing button hekate load with nyx missing message instead of reload nyx.

Thx

**Comment by CTCaer** [comment]
Thanks for reporting that.
I missed that case when I did the simplification of the sd mount/unmount calls.

**Comment by CTCaer** [comment]
Fixed in 5.8.0.
Thanks for noticing and reporting that.
