### ISSUE TITLE
Unknown pkg1 version. HOS version not supported! Or emuMMC corrupt!

### ISSUE THREAD

**Issue by ThinkpadT530user** [CTCaer/hekate#749]
Hi again, after supposedly fixing my boot 0 and pkg2 error, I am greeted with a completely new problem. And now all it says is Unknown pkg1 version. HOS version not supported Or emuMMC corrupt! Trying backup bootloader... Found pkg1 <''>. Unknown pkg1 version. HOS version not supported! Or emuMMC corrupt! Failed to launch HOS! Press any key...

**Comment by impeeza** [comment]
Buddy. Please seek for help on a proper site. This space is for bug report.

On gbatemp.net you are welcome to ask for help. You also can go to discord or similar site.


Regards

**Comment by CTCaer** [comment]
Did you try to flash it on emuMMC (big button at the bottom in backup/restore screen enables emummc support)?
If yes, get a screenshot of console info -> microsd

**Comment by ThinkpadT530user** [comment]
i did, still didn't work so i just migrated the sysmmc to emummc and started again.
