### ISSUE TITLE
hekate freezes randomly

### ISSUE THREAD

**Issue by gusmmm** [CTCaer/hekate#751]
after entering RCM and injecting hekate on a switch v1 firmware 14.1.1, hekate freezes randomly - sometimes imediately, sometimes after browsing some of the menus, sometimes while making a backup of the system. how can I check what's wrong? thanks!

**Comment by CTCaer** [comment]
edit bootloader/nyx.ini `bpmpclock=1` to `bpmpclock=2`. Save and safely eject and reload nyx and tell me what happens.

**Comment by masagrator** [comment]
Well, would be nice to have a pic of this error.

**Comment by CTCaer** [comment]
@gusmmm you should contact me in discord in order to save time because that seems like a hw issue.
(you can join retronx or switchroot and then send a pm to me)

**Comment by CTCaer** [comment]
User threw piracy stuff in the mix so no support will be given.

**Comment by gusmmm** [comment]
Thank you for your time.
