### ISSUE TITLE
Error backing up eMMC

### ISSUE THREAD

**Issue by basedADS** [CTCaer/hekate#752]
Hi, I am consistently getting an error trying to back up eMMC RAW GPP:
 SD & eMMC data (@LBA 03488000) do not match! 
Verification failed

Is there any way to rectify this?

**Comment by impeeza** [comment]
Yes, you can ask for help on the correct sites for that, b.e. discord or gbatemp. Is for sure your sd card is damaged. Use h2wtest to test and fat32gui to format and try again
