### ISSUE TITLE
Used Hekate emummc partition tool, and it wiped and corrupted the other partition. 

### ISSUE THREAD

**Issue by CypherVault** [CTCaer/hekate#753]
HI, ill try to be as detailed as possible, im besides myself right now. 

I used the hekate emummc oartition tool, gave the partition 29 gb, and then ran the setup in that partition, then went to use USB tools on the switch, and my real partition said F:/ cannot be accessed without formatting. Now i cant access anything on that part of the sd card. someone please help as i thought it would leave my files alone? i have not disturbed the partiiton since then someone please help.

**Comment by CypherVault** [comment]
here is photo:
<img width="628" alt="Screenshot 2022-06-16 122246" src="https://user-images.githubusercontent.com/98853849/174119063-13e349b1-031d-45a6-ac83-5e670e9040d4.png">

**Comment by Masamune3210** [comment]
Open up disk management and take a screenshot of your disks, post it here please

**Comment by CypherVault** [comment]
<img width="1280" alt="Screenshot 2022-06-16 125114" src="https://user-images.githubusercontent.com/98853849/174124511-53607377-4262-42bc-82f2-c71504141e3d.png">
i read again the notes at the bottom of the screen it formats the user partition and i didnt use a save transfer tool.

**Comment by Masamune3210** [comment]
According to explorer and disk management in the photos you sent, your fatè2 switch SD partition is mounted as D:\, not F:\

**Comment by CypherVault** [comment]
correct. i thought that was my original partition, but it turns out hekate just formatted my ENTIRE user partition deleting all my user data

**Comment by CTCaer** [comment]
User skipping 3 warnings and a full on time limited warning for button press, is not an issue of the app.

And btw the F:/ drive there is emuMMC and you can't access it. Also save files live in eMMC or in emuMMC partition. Not in the FAT one. FAT one only has game data which can be redownloaded in OFW.
