### ISSUE TITLE
HOS panic occurred!

### ISSUE THREAD

**Issue by adamatti** [CTCaer/hekate#755]
Hi,
I was following [this tutorial](https://www.youtube.com/watch?v=r4SKbKbZHto&ab_channel=KlutchxGaming) and now I am facing this issue:

![image](https://user-images.githubusercontent.com/89515/174899566-0367ac75-b29a-4d3a-92cb-d2a90d9a83b2.png)

```
HOS panic occurred!
color , code 04
press any key
```

Any advice? anything that I could try? anything that I am missing?

Thanks in advance

**Comment by impeeza** [comment]
Yes the follow advises:

1. Please go to a proper support site like discord or GBATemp.
2. NEVER follow video guides, they can be outdated even the very next day.
3. Use https://nh-server.github.io/switch-guide/ for your homebrew installation.
4. on GBATemp there are several threads about the exact same error, almost all are for wrong Hekate_ipl.ini entries.

please only report bugs on this site.
