### ISSUE TITLE
[Feature Request] Key Bindings Manager

### ISSUE THREAD

**Issue by Bladen123** [CTCaer/hekate#756]
Hello CTCaer may i ask u if its possible to have a key binding like the VOL Down for Hekate at Boot ?

If we use the AutoBoot to set a Key.

For example 
Hold VOL UP for OFW Stock
Hold VOL DOWN for Bootloader Hekate
Hold R for Atmosphere FUSEE
Hold L for Atmosphere FSS0

Would that be possible from the coding side ? i would be thankfull and would donate you for all your previous work and this Feature if u can make it happen . Thank you

**Comment by CTCaer** [comment]
It would be possible.
But unfortunately I don't push changes that promote laziness.
Currently, booting something else is 2 taps away, instead of doing random key combos that can be easily forgotten the next day.

(Also it's too much UI work for something like that)
