### ISSUE TITLE
[Feature request] Mount only one partition of SD card

### ISSUE THREAD

**Issue by billyea** [CTCaer/hekate#760]
On some devices, such as Android phones, mounting the SD card over USB will be unreadable because the whole SD card (multiple partitions) will be mounted and the phone will detect only one of the partitions (with incompatible file system).

Is it possible for Hekate to instead present just one selected partition over USB to the external device?

**Comment by CTCaer** [comment]
Android and its completely garbage google configured sgdisk is out of scope.
Use something better that understands Hybrid MBR (an app that mounts in android or different OS/device)
or repartition/reformat your SD and remove switch android.
