### ISSUE TITLE
hekate issue

### ISSUE THREAD

**Issue by Lofiif** [CTCaer/hekate#761]
With a friend that had no problem using hekate, we tried on my switch but I have a graphic issue when I launch hekate.
I did every last updates he told me to do but it did not fix it. Here's what it looks like, I hope it can be fix. Also putting my sd card data if needed.
![graphic issue](https://user-images.githubusercontent.com/108824593/177653507-f2598a58-4c4f-42f2-9581-6eabdb8564ef.png)
![sd card](https://user-images.githubusercontent.com/108824593/177653514-87b0214b-51ef-48dc-86cb-1711b06c0eaf.png)

**Comment by impeeza** [comment]
You need to delete your bootloader folder on SD card (backup it first) and then create a new one uncompressing the downloaded latest release of Hekate. You can restore HELATE_IPL.INI file but ONLY that file,. If you use them, reinstall sigpatches

**Comment by impeeza** [comment]
Normally this is a res.pak damaged file.

**Comment by CTCaer** [comment]
Yeah seems like res.pak is corrupted or missing
Backing up hekate_ipl.ini and deleting bootloader folder and pasting anew and restoring hekate_ipl.ini is the way to go.
