### ISSUE TITLE
[bug] physical button navigation doesn't close prompts

### ISSUE THREAD

**Issue by monstrosities** [CTCaer/hekate#763]
There's a minor issue with physical button navigation where going back doesn't close prompts but transitions the screen in the background. Maybe not actually a bug but a small oversight.

Example:

Step 1 - Disconnect UMS:

![prompt1](https://user-images.githubusercontent.com/97065893/178118632-c7ed36f0-6940-48ce-8d02-ce8a9375213d.png)

Step 2 - Press the physical back button "B", instead of the prompt being closed the screen transitions back in the background:

![prompt2](https://user-images.githubusercontent.com/97065893/178118655-625921b0-9196-431a-827d-57dafdc99316.png)

It also happens with partition manager prompts and probably other prompts.

**Comment by CTCaer** [comment]
Well not a bug exactly, but limited usage of that feature.
The main cause is also the reason I don't have normal button support.

For making this work, I will need to have a list of button history and it's annoying to keep track of.
Maybe eventually when I will remove virtual mouse and add proper gamepad support, this will go away.
Until then it will work like that (only on windows Close button and not pop ups).

**Comment by monstrosities** [comment]
Ok, it was more of a "you might have missed this" type of thing rather than a real problem but the explanation makes sense.
