### ISSUE TITLE
trying to backup eMMc RAW GPP error message: SD & eMMC data (@LBA 00400000) do not match! Verification failed..

### ISSUE THREAD

**Issue by roobdog293000** [CTCaer/hekate#767]
![image](https://user-images.githubusercontent.com/95704859/180672631-2184c47f-bf66-4299-bf22-24500bd18ac6.png)

**Comment by impeeza** [comment]
This is not a support forum, this questions will be better answered on GBATemp or Discord,  saying this first test your SD card using H2testW,  if your card it's OK go to GBATemp on the help forums.
