### ISSUE TITLE
"Contact me!" displayed next to display panel model

### ISSUE THREAD

**Issue by grave35** [CTCaer/hekate#769]
As the title says.

Model: AUO A062TAN02 (30950F)
ID: [30] 97 [0F]

**Comment by CTCaer** [comment]
A new one? I guess you don't have access to the LCD's back side, correct?

What's peculiar is that nintendo used 95 in your cal0. You didn't repair your lcd panel, right?

**Comment by grave35** [comment]
This is not a new device. The LCD came from the store as a spare part for repair. I don't have access to the back of the lcd.  I saw in the menu "Contact me!" and informed you.

**Comment by CTCaer** [comment]
Makes sense now. You or the repair shop didn't get any pictures of the back at all?
I would help to have the actual model number.

**Comment by CTCaer** [comment]
Well photos are not legible in that store.
The issue is that adding that info to hekate is a 2-way process. I report ID in hekate but the model is still unknown.
Unfortunately, no one ever contacted me with any unknown actual model (not just id).
I just basically find the models by researching google images and piecing the puzzle together.

Anyway, thanks.

**Comment by grave35** [comment]
The seller sent me this photo.
![S22264e9403d040a48cf8700bd7e76572j png](https://user-images.githubusercontent.com/1205082/182622837-d3b22269-548b-4658-8f33-805f44498bb4.jpeg)

**Comment by CTCaer** [comment]
Thanks. That actually helps a lot (assuming it's from the panel sold to you and not another one).

Although it makes things weird:
```
 * [30] 93 [0F]: AUO A062TAN00 (59.06A33.000)
 * [30] 94 [0F]: AUO A062TAN01 (59.06A33.001)
 * [30] 95 [0F]: AUO A062TAN02 (59.06A33.002)
 * [30] 97 [0F]: AUO A062TAN02 (59.06A33.002)
 * [30] XX [0F]: AUO A062TAN03 (59.06A33.003) [UNCONFIRMED ID]
 ```
 
Except if A062TAN03 aka 59.06A33.003 has an id of 0x98.
And I maybe the assumed A062TAN00  is actually a 01 model.

I will add that info into sources.
