### ISSUE TITLE
Missing LP0 <sleep mode> lib!

### ISSUE THREAD

**Issue by simistef** [CTCaer/hekate#776]
Hi there, i was trying to update my hetake 5.6.5 to latest version 5.8 using the guide here: rentry.org/UpdateCFW

When turning on my Switch, i get this:

```
Missing LP0 <sleep mode> lib!
Update bootloader folder!
Press any key ...
```

If i press any key thakes me to next screen where i can see hekate v5.6.5 very basic menu. at the bottom of this screen i see:

`Warning: Nyx is missing!`

Please let me know what i can do next. As said, i have followed the ReEntry guide...

Thanks

**Comment by urherenow** [comment]
Github isn't a help forum.
