### ISSUE TITLE
[Feature request] passthrough zeroes nand dumping

### ISSUE THREAD

**Issue by monstrosities** [CTCaer/hekate#777]
Hello,

Would it be possible for hekate to offer a "passthrough zeroes" nand dump option where unallocated data is zeroed out similar to what PC tools like hacdiskmount and nxnandmanager do? 

The purpose being to be able to store highly compressed nand backups as is possible with a backup made from a console fresh out of the box. It would be especially useful now since on recent firmware versions if you do an official factory reset in HOS the whole nand is filled with garbage data. The double sized OLED nand would also benefit greatly.

Thanks.

**Comment by CTCaer** [comment]
Nope because it would take forever to backup (cpu/crypto engine too slow) and also it would mean I will need to edit FatFS driver in order to create maps of used/unused areas.
It's way faster to just dump it and clear unused areas with the aforementioned tools.
