### ISSUE TITLE
[Request] Nyx: support for hue AND nobox icons

### ISSUE THREAD

**Issue by impeeza** [CTCaer/hekate#779]
On Hekate 5.8.0 if you use a file icon with "HUE" format, named *_hue.bmp, it is displayed well and with the color for the interface but if THE SAME file is renamed `*_hue_nobox.bmp` then the hue color isn't used, the icon is show without the gray background but white.

![nyx20220721_015750](https://user-images.githubusercontent.com/41979604/180149872-505a53cd-7226-4bf5-9790-23dd2b8f389e.png)

On this example all icons are the special ones with "Hue" format, but the second one is named `payload_hue_nobox.bmp` I don't know if is the wanted behavior or a bug introduced with the new functionalities.

**Comment by CTCaer** [comment]
Next version will have it. (If I don't forget again to look at open issues. ^^)

**Comment by impeeza** [comment]
Thank you very much for your hard work

**Comment by CTCaer** [comment]
Added in 1.5.0

**Comment by fooness** [comment]
@CTCaer @impeeza Could you maybe link to *any at all* documentation/example on how to create “32-bit BMP” with transparency, so probably *ARGB*. Sorry for posting a comment to this closed issue, but for the life of me I could not find any working solution or proper answer on how to create these images (on macOS).

I tried creating such a `_hue.bmp` file with Illustrator, Photoshop, InkScape, GIMP, and ImageMagick, but to no avail. Nyx only ever displays the default switch image in the launch menu, even though when opening *my file* and [`hekate/nyx/resources/icon_lakka_hue.bmp`](https://github.com/CTCaer/hekate/blob/master/nyx/resources/icon_lakka_hue.bmp) seeminly look the same in Photoshop and ImageMagick’s `idenfity -v`.

@impeeza May I ask you to please share the atmosphere `_hue.bmp` file which is displayed in your screenshot above?

Thank you very much!
