### ISSUE TITLE
No main boot entries found

### ISSUE THREAD

**Issue by HeJerry** [CTCaer/hekate#780]
use 5.8 lanch 5.7.2  
launch have issue “
No main boot entries found...
check that bootloader/hekat_ipl.ini has boot entries 
or use More configs button for more boot entries”
but enter More config have issue
"No .ini or boot entries found...
Check that a .ini file exists in bootloader /ini/
and that it contains at least one entry "
i don't know how to fix it

**Comment by impeeza** [comment]
Hi, this space is not for support, is for report bugs and issues.

for support please go to proper channels like GBATemp, Discord or similar.

you may have a corrupted/fault SD Card. on the Noob Paradise Thread of GBATemp you will get help easy.

**Comment by CTCaer** [comment]
You are expected to make one or put a premade .ini.
None is shipped by default.

If you want to do it manually, you can check several template entries here:
https://github.com/CTCaer/hekate/blob/master/res/hekate_ipl_template.ini
