### ISSUE TITLE
Hekate screen unelligible 

### ISSUE THREAD

**Issue by ace90249** [CTCaer/hekate#782]
![20221007_061847](https://user-images.githubusercontent.com/10873611/194563820-78a8c0c5-e0bd-4595-816b-2a2bff17eb20.jpg)

**Comment by impeeza** [comment]
You just open several reports, and all of then indicate you have a Corrupted SD card.

**Comment by CTCaer** [comment]
Your sd card is fake. And like the other report, it causes such issues.
It even says so.
![image](https://user-images.githubusercontent.com/3665130/194584902-a657897f-2231-4cab-b4fc-2d49f23c884d.png)
