### ISSUE TITLE
Freeze after update to 5.9.0

### ISSUE THREAD

**Issue by Heib386** [CTCaer/hekate#783]
Hekate freezes after update to 5.9.0
Does not react to any input

**Comment by LeddaZ** [comment]
Same here, booting 5.9.0 payload with 5.8.0 bootloader folder works

**Comment by CTCaer** [comment]
What's bpmpclock in nyx.ini?
If it's 1, try with 2 and report back.

**Comment by muxi1** [comment]
I can also confirm this. I use an Erista v1 and the problem occurs irregularly after a reboot from Tegra Explorer or also when booting via a payload transmitter. There is no nyx.ini present in my setting.

**Comment by LeddaZ** [comment]
> What's bpmpclock in nyx.ini? If it's 1, try with 2 and report back.

I have 2 already, putting 1 has the same issue.

**Comment by LeddaZ** [comment]
[https://i.imgur.com/nHerWsg.png](Image)

**Comment by arch-box** [comment]
Erista. 
CPU Speedo 0: 1999
CPU Speedo 1: 3397
CPU Speedo 2: 2005
SoC Speedo 0: 1896
SoC Speedo 1: 0x7F
SoC Speedo 2: 0

**Comment by CTCaer** [comment]
possible fix:
[nyx.zip](https://github.com/CTCaer/hekate/files/9768474/nyx.zip)

**Comment by Whovian9369** [comment]
Note: Started writing this before the possible fix was posted, so this is meant as a reply to the main issue.

Also having this issue with 5.9.0 and mainly (but not *always*) when I reboot into Hekate from another payload 
For example, I had a freeze when rebooting from Lockpick_RCM 1.9.8 using the "Reboot to Hekate" menu option, and Atmosphere 1.4.0 (pre-release) using the automatic reboot after updating the HOS firmware.
Time, temperature, and batty level all showed as `00:00`/`00.0`/etc when this happened.

Curiously for me, I proceeded to try rebooting to Hekate via LP_RCM and it worked again just fine. 

I'll try and test the possible fix, thanks!

**Comment by CTCaer** [comment]
Doubt it matters from where it's injected/loaded.
Hopefully it's what I think it is and is fixed by that bin above.

**Comment by Whovian9369** [comment]
> Doubt it matters from where it's injected/loaded. Hopefully it's what I think it is and is fixed by that bin above.
No immediate freeze when rebooting from AMS 1.4.0 (PR) so I'm considering it fixed for myself, thanks!

**Comment by CTCaer** [comment]
Thanks for reporting that. I will wait for all of them here and then push it in release.

**Comment by LeddaZ** [comment]
The fix works for me too

**Comment by Heib386** [comment]
Fix works for me too, thanks

**Comment by CTCaer** [comment]
@Glitch-Code-Design @muxi1 @arch-box ?

**Comment by CTCaer** [comment]
Pushed fix to release. Anyone having that issue can redownload the release.
