### ISSUE TITLE
Blue Screen after update to 15

### ISSUE THREAD

**Issue by DasFx-zz** [CTCaer/hekate#789]
Hi.

i updated your Version from Hektate and Switch to 15.

If I try to boot to stock, I get a blue screen. 
if I start Tegraexplorer and select Boot normal, stock OS 15 start and work normally.

Any ideas what’s not working?

Switch is an Mariko

**Comment by TTghostsemir** [comment]
I actually had it too!
Have then made Hekate again on it and then it went 🤷‍♂️

**Comment by CTCaer** [comment]
you need to update both hekate and atmosphere. otherwise you get blue or yellow screens, depending on what's older.
