### ISSUE TITLE
4.0 issues

### ISSUE THREAD

**Issue by bakugo** [CTCaer/hekate#79]
* If there are no boot entries in hekate_ipl.ini, the launch menu can't be used for payloads or extra inis either
* Selecting "payloads" or "more configs" when there are no items in the corresponding SD folder results in an empty screen that can't be exited
* Payload launcher doesn't work with some payloads, it just turns off the screen and the console must be force shut down (happens with fusee example and SX loader)

Was this release tested at all?

**Comment by CTCaer** [comment]
<img src="https://user-images.githubusercontent.com/3665130/44514503-fb9f6f00-a6c8-11e8-857d-cba653f15a2f.png" width="32" height="32" />

https://github.com/CTCaer/hekate/commit/5328f89ffe356c5c89e21e39adbfcf2c198c6095
You had 2 full days and a half to test it! What did you do all that time??
You are not paid to lay around and sleep..

**Comment by CTCaer** [comment]
https://github.com/CTCaer/hekate/issues/86
https://github.com/CTCaer/hekate/issues/78
https://github.com/CTCaer/hekate/issues/77

Also about the payloads, fusee is currently broken anyway.
Hekate can boot exosphere like before.
