### ISSUE TITLE
Failed to backup RAW GPP/ hekate 5.9.0/ Nyx 1.4.0

### ISSUE THREAD

**Issue by Richmong97** [CTCaer/hekate#790]
Hello, I have a problem when making a backup in RAW GPP and they are these errors "fatal error when writing to the SD" and "Error writing 8192 blocks \@LBA" I investigated and found that the same problem occurred on June 29, 2019, the exact same thing happens to me, is there a way to fix it? I will really appreciate the help (Sorry for my English, I'm using a translator)

**Comment by Richmong97** [comment]
the information requested @Masamune3210 
![Uploading 20221020_104439_HDR.jpg…]()

**Comment by Masamune3210** [comment]
You submitted the comment too fast, the picture didn't finish uploading

**Comment by Richmong97** [comment]
![20221020_104439_HDR](https://user-images.githubusercontent.com/116294975/197010205-583f3481-2b9c-4d60-82c2-6bc8a42417af.jpg)

**Comment by Richmong97** [comment]
I'm not sure if it's a problem with the SD card or a bug with my console @Masamune3210

**Comment by CTCaer** [comment]
Your issue seems to be broken pin on sd reader - since your sd is legit.
(That, assuming you don't have corruption on your filesystem)

You should retry to backup and when that error happens, go into microsd info and take a screenshot again. Without reloading hekate/Nyx.
The screenshot will show what it is:
- 0 errors is fs corruption
- errors is sd reader issue.

**Comment by Richmong97** [comment]
A few minutes ago I started doing everything again but as soon as I tried to start hekate I got an error indicating a problem with the SD card reader Reboot the device and it didn't recognize the SD card, so reboot the device but this time pressing on the SD card slot It recognized the SD card without any problem, so I decided to start hekate (always pressing on the slot) Did BOOT0 AND BOOT1 without any problem, then I started RAW GPP and everything was fine until I decided to remove my finger from the afternoon SD slot, as soon as I did it the error appeared. I'll post the photos below.

**Comment by Richmong97** [comment]
![20221021_103832](https://user-images.githubusercontent.com/116294975/197252620-b4c89f4b-e9f5-46b1-815e-70f6e9fcd239.jpg)
![20221021_104945](https://user-images.githubusercontent.com/116294975/197252718-307534ff-0f2b-4d84-a65a-0995c8a3f239.jpg)

**Comment by Masamune3210** [comment]
You might be able to get away with replacing the SD card reader board , but if the pin is truly broken or there is a issue with the connector, nothing is going to be able to fix it short of a solder job

**Comment by Richmong97** [comment]
I really appreciate your help, thanks for everything and for helping me solve the problem
