### ISSUE TITLE
nyx is missing

### ISSUE THREAD

**Issue by sharkzealot** [CTCaer/hekate#794]
every time i try to boot hekate 5.9.0 i get Warning Nyx is missing! this is the first time im doing this so i could just be making a dumb mistake

thanks in advance!

**Comment by impeeza** [comment]
Git Hub issues is no a support site, is for bug report.

please go to a support site like discord or GBATemp.

saying that, you have a damaged SD,  run H2testW on it. or you have a bad sd reader, reset or replace

then using a know good sd download A NEW copy of hekate and extract to SD root

**Comment by sharkzealot** [comment]
oh, my bad thanks anyways. its a brand new SD card tho but i'll try it

**Comment by Masamune3210** [comment]
Pretty sure its just a missing bootloader folder
