### ISSUE TITLE
black screen

### ISSUE THREAD

**Issue by Penixlast14** [CTCaer/hekate#796]
whoops, sent the issue without adding a description;

Switch got bricked with a blue screen because I went on YouTube, tried to boot into OFW, doesn't work (blue screen), tried to go and do factory settings, doesn't work (blue screen), I try to do CFW by booting up atmosphere, shows a glitchy splash mess, I try to inject Hekate 5, doesn't work, just a black screen with no backlight, same with Hekate 4
except that Hekate 3 works just fine, what's the problem

**Comment by CTCaer** [comment]
that's a ram issue.
hekate 3 works because it has the least ram usage.
throw a message in discord (send dm via retronx) if you are interested in where.
