### ISSUE TITLE
Having issues in hekate 5.9.0 home (touch screen)

### ISSUE THREAD

**Issue by PoleoDeMenta** [CTCaer/hekate#797]
Hi!
First of all, I'm sorry if my issue is been already posted, but I'm having some trouble with this... Idon't know anything about programming, so I don't want to touch by myself things...

I'm following a tutorial so I can get into hekate 5.9.0 on my Nswitch... I follow all the steps one by one, but, when i try to access to the hekate home screen, it seems to get frozen, and touch screen does not give any answer. Also I find quite weird, that time, temperature, etc values are all in zero, as the image I show:

![hekate-home](https://user-images.githubusercontent.com/118895240/203526002-ff2dafb7-d83e-4a03-9abb-47b7e0e596d5.jpg)

I already tried with 3 different SD cards (128, 256 and 32 GB respectively), formatted in FAT32, exFAT... and all of them have the same issue, so I don't know how to continue...
Please, if anything else is needed, please tell me, as I said, I dont have much knowledge in this...

Thanks!!!

**Comment by neo305** [comment]
I’d say try an original install and not use a custom pack and see if you get same results

**Comment by impeeza** [comment]
1) This is not a support Forum, please go to Discord or GBATemp.
2) download the original release from this repo and install again.

**Comment by CTCaer** [comment]
as said above get the official release
