### ISSUE TITLE
Grow up

### ISSUE THREAD

**Issue by goukifafa** [CTCaer/hekate#8]
Some people are different. Don't spit your dummy out when people use your "open source" code for something your opposed to.

**Comment by AnalogMan151** [comment]
You know this isn't the same person who maintains this fork, right? The person you're talking about is not being alerted to your message or even knows you're posting it here.

**Comment by Karthik99999** [comment]
Yeah, you should see who this is going to before you send something. This is even not the place for this. This is for issues in the code, not with the person.
