### ISSUE TITLE
When formatting microSD cards take SDA's recommendations into account.

### ISSUE THREAD

**Issue by profi200** [CTCaer/hekate#801]
From a quick glance i could not tell if hekate does take the recommendations from "SD Specification Part 2 File System Specification" (Can't link it here. Search for it.) into account. While they do recommend exFAT only for SDXC cards i got improved random read/write by applying the recommendations for FAT32 on SDXC cards as well. Also see my (unfinished) [tool](https://github.com/profi200/sdFormatLinux).

Benchmarks (ignore the SSD one): https://www.dropbox.com/sh/cz8i1z4nq4tvqo5/AADQMv8xn9U1icis0tA5asfca/benchmarks

edit:
Almost forgot but i also recommend doing a TRIM/erase (Linux: blkdiscard) on the whole card before reformatting. This has noticeably improved performance for old SD cards for me. Some cameras do this as well. It does help.

**Comment by impeeza** [comment]
https://www.openimpulse.com/blog/wp-content/uploads/wpsc/downloadables/SD-Card-File-System-Specifications-.pdf but is marked as confidential ;(

**Comment by profi200** [comment]
Well, hence why i said i can't link it here.

**Comment by CTCaer** [comment]
It does and then more.
Like day 1 of the partition manager release

**Comment by profi200** [comment]
Good to hear. Will have a deeper look at what your partition manager does when i have time.
