### ISSUE TITLE
Blank boxes after first boot

### ISSUE THREAD

**Issue by Frosty3001** [CTCaer/hekate#809]
This is my first time with Switch emulation so I'm being as cautious as possible with the process. I injected hekate_ctcaer_6.0.1.bin and TegraRcmGUI showed "RCM O.K." but there's no text in the boxes on the Switch. This isn't my own photo but this is exactly what it looks like on my end.
![g7g7sa55fx771](https://user-images.githubusercontent.com/121648703/210025831-5c923678-e406-45c9-9c9c-f39aabee18cf.jpg)
I've searched everywhere online for an answer but none of the images showed blank boxes like this one.

**Comment by impeeza** [comment]
Its mire likely what you are missing some files on your sd card or the folder RED inside the BOOTLOADER one

**Comment by Frosty3001** [comment]
> Its mire likely what you are missing some files on your sd card or the folder RED inside the BOOTLOADER one

Did you mean the res folder? I have a "res" folder but not a "red" folder.

**Comment by impeeza** [comment]
Yes res. Sorry a typo. And remember to check the content of the res folder

**Comment by Frosty3001** [comment]
I have icon_payload.bmp and icon_switch.bmp both at 145KB

**Comment by CTCaer** [comment]
You have corrupted files or filesystem.
Backup your hekate_ipl.ini and the inis, assuming they are not corrupted, delete bootloader folder and reextract the release zip.
