### ISSUE TITLE
Partition displayment.

### ISSUE THREAD

**Issue by garobcsi** [CTCaer/hekate#812]
After creating linux and android partition it only shows one of them. (Linux partition is not present on the display)

![20230102_222435.jpg](https://user-images.githubusercontent.com/77503417/210279851-e9490180-3214-48b9-a924-1aafe670eab3.jpg)![20230102_134155.jpg](https://user-images.githubusercontent.com/77503417/210279856-c9649126-c000-429a-a1d2-1caebc630a5f.jpg)

**Comment by CTCaer** [comment]
Seems that you skipped all the reading
![image](https://user-images.githubusercontent.com/3665130/210280463-a4786959-d292-43ad-970c-d4b99cccf470.png)
