### ISSUE TITLE
i need help getting hekate on emmc to work

### ISSUE THREAD

**Issue by hannescam** [CTCaer/hekate#816]
please help getting hekate on emmc to work 
i tried to change this line in sd.c from: "res = f_mount(&sd_fs, "0:", 1);" to: "res = f_mount(&sd_fs, "1:", 1);" and it did allways complain that there was no sd installed (i made a fat partition on the emmc with all the files on it)

**Comment by CTCaer** [comment]
Check issues for where to start, another user asked also. Any further help won't be provided by me though (since it's a waste of valuable time).

**Comment by hannescam** [comment]
@CTCaer could you say wich things i need to modify and please reopen this issue
