### ISSUE TITLE
hekate exception orrcrred (LR FDF7E14B)

### ISSUE THREAD

**Issue by Aoi-cn** [CTCaer/hekate#818]
```
Failed to init or mount SD/
hekate exception orrcrred (LR FDF7E14B)
RESET
Press any key...
```
This occurs with the screen blurred..
I uses hekate v5.7.2

**Comment by BeckysFootSlave** [comment]
> 

Why?
Use 6.0.1

**Comment by Aoi-cn** [comment]
> > 
> 
> Why? Use 6.0.1

I was playing ns sports, then the screen become black suddenly. When i restart the maching, it shows the code up there..

**Comment by impeeza** [comment]
looks like a SD Card Corruption.
