### ISSUE TITLE
Can`t see any screen wehn i inject

### ISSUE THREAD

**Issue by lkgames256** [CTCaer/hekate#820]
It does not show any kind of screen after injecting

**Comment by masagrator** [comment]
If you use TegraRCMGUI, send screenshot of it after pushing payload

**Comment by lkgames256** [comment]
![image](https://user-images.githubusercontent.com/108570960/216784957-141e1cec-16c9-48d3-8460-cf485ba9224d.png)

**Comment by masagrator** [comment]
Your Switch is patched. No RCM for you.

**Comment by lkgames256** [comment]
Okay but Thanks
