### ISSUE TITLE
Reboot to OFW should be disabled if AutoRCM is enabled

### ISSUE THREAD

**Issue by Yoti** [CTCaer/hekate#821]
It goes to the RCM mode instead of OFW.
I suggest disable or add a note to the item.

**Comment by urherenow** [comment]
And I suggest you learn what AutoRCM does. This isn’t a bug.

**Comment by Yoti** [comment]
@urherenow it is. Nyx can check for the AutoRCM state and can disable this button if it's On. Also, I told this to CTCaer early and he asked to open an issue IIRC.

**Comment by Masamune3210** [comment]
Its a bug that it lets you try, knowing that it will fail. Its not a bug that it fails

**Comment by urherenow** [comment]
@Yoti, It isn’t a simple matter of “disabling a button” for RCM. Again, learn what AutoRCM does. I get the feeling that disabling the “Reboot to OFW” button is what will be done here (for cases where AutoRCM is detected).

**Comment by Masamune3210** [comment]
Why are you being so malicious? Also, I'm pretty sure that's what they are talking about disabling, making it so that the Reboot to OFW button is disabled if AutoRCM is detected as enabled

**Comment by CTCaer** [comment]
Behavior changed in latest
