### ISSUE TITLE
Hekate Update for v 16.0 switch

### ISSUE THREAD

**Issue by bdawg1989** [CTCaer/hekate#826]
Hello,

Now that Atmosphere is pre-released and working with the new 16.0 switch update, what is the ETA on a new update for Hekate?  

I’m getting a pkg1 error when launching the new atmosphere.

**Comment by North-West-Wind** [comment]
While we wait for that, is there a way to boot into sysMMC without Hekate?

**Comment by TTghostsemir** [comment]
Yes with the Fusee.bin

**Comment by warnooob** [comment]
it won't boot into syscfw with the fusee.bin unless you don't have an emummc in the first place

**Comment by North-West-Wind** [comment]
@warnooob I was trying to figure it out and I did. You have to disable emuMMC in `emuMMC/emummc.ini`. Change `enabled=1` to `enabled=0`

**Comment by NudelsHelp** [comment]
@warnooob How???

**Comment by iero19** [comment]
Is this pkg1 error because of Hekate not being updated yet? https://imgur.com/a/Law0Oyz

**Comment by warnooob** [comment]
@iero19 yes, use fusee for now while you wait for hekate to update for 16.0.0. remember to delete your sysmodules and themes too, both will result in atmosphere getting an error on boot

**Comment by iero19** [comment]
Got it. I have no idea what sysmodules are and I do not have any themes installed, so I think I'm safe in that aspect. Is there a way to boot into sysMMC for now?

**Comment by NudelsHelp** [comment]
@warnooob how to Delete them?

**Comment by North-West-Wind** [comment]
If that's the case, you can add that section manually:
```ini
[Fusee]
icon=bootloader/res/icon_payload.bmp
payload=bootloader/payloads/fusee.bin
```

**Comment by CTCaer** [comment]
New version released

**Comment by NudelsHelp** [comment]
Okay but i Need to have the Pre Release of Atmosphere or the 1.4.1?

**Comment by North-West-Wind** [comment]
Pre release (1.5.0). 1.4.1 doesn't work with switch 16.0.0.
