### ISSUE TITLE
res.pak not found or corrupted with new version

### ISSUE THREAD

**Issue by bdawg1989** [CTCaer/hekate#828]
Hello, on new formatted sd I added new version of atmosphere and new hekate + nyx release.

On injecting I get failed to load GUI resources!
res.pak not found or corrupted.

**Comment by shae23** [comment]
That's Tesla Menu preventing the boot. Go to your atmosphere/contents folder and delete the folder 420000000007E51A

**Comment by masagrator** [comment]
Or if you have 16.0.0, use this
https://github.com/ELY3M/Tesla-Menu/releases/

**Comment by CTCaer** [comment]
As for the actual hekate error, it's well what it says it is:
failed to load GUI resources!
res.pak not found or **corrupted**.

Repaste release and make sure you safely eject.

**Comment by kisiwasitarou** [comment]
OVL Release #1 - 16.0.0 support fix
