### ISSUE TITLE
Add possibility to use joker "*" in kip1 param path for file name

### ISSUE THREAD

**Issue by jlozes** [CTCaer/hekate#83]
It could be intresting to have this possibility to simplify the configuration file.

For example:

"
[all modules]
kip1=modules/newfirm/loader.kip
kip1=modules/newfirm/sm.kip
kip1=modules/newfirm/pm.kip
kip1=modules/sys-ftpd.kip
kip1=modules/xor.play.kip
kip1=modules/sys-netcheat.kip
kip1=modules/switch-rich-presence.kip
kip1patch=nosigchk
"

This one could be:

"
[all modules]
kip1=modules/newfirm/*.kip
kip1=modules/*.kip
kip1patch=nosigchk
"

Thanks.

**Comment by CTCaer** [comment]
hmmm not a bad idea.

But it's needed? I mean that it's a "set it and forget it" thing the ini configuration.

**Comment by jlozes** [comment]
Needed no but it could be useful in some case, for example to test more quickly a set of modules.

**Comment by CTCaer** [comment]
My current plan btw, is for this to be worked on for a later version.

**Comment by CTCaer** [comment]
https://github.com/CTCaer/hekate/commit/1392e6eaf49b4f593e5b3ee42c76993c45f638d8

**Comment by jlozes** [comment]
Thanks, this will be useful.
