### ISSUE TITLE
Yellow screen with previous atmosphere

### ISSUE THREAD

**Issue by myeuropeanPAL** [CTCaer/hekate#830]
Hello, not sure if this is a bug, but I get a yellow screen when booting with the latest hekate v6.0.2 and the previous atmosphere 1.4.1 on firmware 15.0.1
It is booting just fine with atmosphere 1.5.0 pre-release.
Thank you.

**Comment by urherenow** [comment]
No, it's not a bug. Hekate is meant to be updated WITH Atmosphere, and you've discovered a major reason for that. This is why although it's possible you'll see an in-between hekate update (to fix a bug or add a feature), you will NEVER see it released before the Atmosphere release, when it's required to run on the latest firmware.
