### ISSUE TITLE
switch won't boot to ofw either cfw

### ISSUE THREAD

**Issue by Amoniak200** [CTCaer/hekate#835]
I've spent whole day trying to fix my switch after missclicking update to 16.0.0

So on, I can't turn my switch normally cause of autorcm, but i can enter hekate, firstly there is problem with res.pak, then on "launch" i have that "Check that bootloader/hekate_ipl.ini has boot entries" and after injecting fusee payload, only what i see is fast flash of atmosphere logo, then switch just blacking out.

I have tried sigpatches, aio, system wipe, everything...

Still nothing, i've had enough of this, any spark of hope would be good :(( 

I am considering if this isn't an switch reader problem... 
This is not an sd prob, checked sd card.

**Comment by CTCaer** [comment]
I can't give you support if you don't use hekate to boot.
Plus it seems your sd is corrupted or the update went wrong.
And piracy is not supported.
