### ISSUE TITLE
Can’t boot up

### ISSUE THREAD

**Issue by TrueTexan21** [CTCaer/hekate#838]
I was playing ACNH and needed to reset my modem and router. Once it was connected again I tried accessing the internet in ACNH and was hit with an error telling me that I needed to update the system. 

Someone in Hangouts suggested that I update since the current release is stable enough. 

I updated Hekate and Atmosphere and I get this error as soon as I try to load up CFW. Any suggestions on how I can fix this?
![029247AD-F954-4746-B678-DED63EF6221D](https://user-images.githubusercontent.com/82775893/224194330-474349f1-f45a-4a53-93ef-9fed26e7c3c5.jpeg)

**Comment by Masamune3210** [comment]
1. This has nothing to do with hekate
2. Delete your custom home menu theme

**Comment by TrueTexan21** [comment]
Oh, okay. Thanks so much. I didn’t realize it would cause an issue.

**Comment by Masamune3210** [comment]
Custom themes are irrevocably linked to the version of Home Menu that they were made with, when you update the firmware you must remove them or else this will happen every time

**Comment by TrueTexan21** [comment]
I’ve removed the whole “downloads” folder that contains the custom themes
but I’m still getting an error. Is there something else I must do in
addition to removing the files?

**Comment by Masamune3210** [comment]
You must remove the actual theme and not just the downloads. Look for a folder with the same name as the title ID in atmosphere\contents

**Comment by urherenow** [comment]
The error tells you which folder to delete. 0100000000001000. How do you think we know it’s your theme causing this? Try googling for 2 seconds before making an issue. Perhaps even look at the closed issues. This only happens to people like every single major firmware update…

**Comment by Masamune3210** [comment]
Please, for the love of God, chill out on being so malicious.

**Comment by urherenow** [comment]
> Please, for the love of God, chill out on being so malicious.

For the love of god, stop entertaining people posting on github issues, when it isn’t an issue with the project in question. Especially when it’s been asked and answered several times, and your “help” is cryptic as hell. You could have mentioned that the program ID in the crash screen, is the name of the contents folder that should be backed up then deleted. Then Google that same number if it doesn’t fix the issue (which would also lead to checking if another folder is present.

Github isn’t a support forum.
