### ISSUE TITLE
emmc slower mode (200 MB/s) - hwfly

### ISSUE THREAD

**Issue by Crypto90** [CTCaer/hekate#839]
Hi

I just installed the hwfly v5 chip to my new switch oled and run into an issue.
My emmc init fails and it falls back to slower mode and works fine with a 200MB/s connection.

My emmc should be totally fine and working. I think its the wires from point C and/or B (I used very thin coated copper wires from an old FAN which are probably 0.1mm).
I also lost the B point on the hwfly chip itself and soldered it onto a very very very little dot which was left from under where the pad was.

I found this issue topic:
https://github.com/CTCaer/hekate/issues/680

where its about the wire length, bad wires, interferences, signal integrity.

I could create a sysnand backup and extracted the keys.

the emmc chip got not reflowed, I put it under, fixed it with anchor points and it got the right values. I don't think its the emmc itself.

Now my question:
Does this issue comes from wrong wires? Or does this come from a probably bad B point on the hwfly chip?
Is thee any alternative point where I can solder the B point on the hwfly chip?

I purchased alternative wires with 0.1mm, they look basically the same as the ones I got out of the old fan. So I don't know if its worth the replacement. I think I should first check that B point on the hwfly chip.

How should I proceed to fix this issue?

Many thanks!

**Comment by CTCaer** [comment]
You are completely in the wrong place to ask that.
(And yeah it's almost always signal integrity)
