### ISSUE TITLE
Generate checksums with backups

### ISSUE THREAD

**Issue by Zer0t3ch** [CTCaer/hekate#84]
I've been having some intermittent issues with SD corruption on exFAT (since switched to FAT32 to see if that helps anything) and it would be great to know that my backups are still good by the time I pull them off the card.

On top of possibly generating a checksum at the end of the backup process, is it possible to generate the checksum in-line with the backup process? (i.e. if it somehow gets corrupted in the process of being written, a post-write checksum of the file wouldn't show anything wrong, a checksum of the data coming directly from the NAND would)

**Comment by CTCaer** [comment]
Actually I thought of this process many times.

The last month, I have something that works and does not complicates things. It also takes around 2minutes to complete.

Of course Full verification is enough. But if your sd card has bad sectors and if you connect it to pc it corrupts, then a checksum file is needed.

What works in most cases is to produce 3 files. These will have the SHA256 of BOOT0, BOOT1 and if partition style is used, to create on of these.

Of course checksum of partial backup will complicate things. As long as it stays on the partitions start-end sectors it can be easily done.

Anyway, I'll clean it up and make a commit.

**Comment by Zer0t3ch** [comment]
> Of course Full verification is enough

Ah, I actually forgot that Hekate already verified post-backup when posting this. I suppose as long as the checksum is generated pre-verification, and verification comes back good, then the checksum is guaranteed to be good.

> Anyway, I'll clean it up and make a commit.

Nice, thanks for all your hard work!

**Comment by Zer0t3ch** [comment]
Good to know, thank you.

**Comment by CTCaer** [comment]
Moved the checksum of the whole emmc and boot0/1 to that issue
