### ISSUE TITLE
Error code LR 400E720

### ISSUE THREAD

**Issue by Synxian** [CTCaer/hekate#842]
While using the usb mass sotrage tool to change some files in the atmosfere folder, my file explorer stopped working and the switch screen started to have some interference (the same as the photos), then i started to get this error:
`hekate exception occured (LR 4000E720):
Hang detected in LP0/Minerva!`
I formatted my sd card, but the error persisted, and sometimes this happens to the screen:
![WhatsApp Image 2023-04-01 at 18 23 31 (1)](https://user-images.githubusercontent.com/82783188/229314478-442a9a9c-708b-4576-acd3-e2eb6f7d0f96.jpeg)
![WhatsApp Image 2023-04-01 at 18 23 31](https://user-images.githubusercontent.com/82783188/229314480-359ea5e9-54af-461b-8ca0-f7215440e370.jpeg)
![WhatsApp Image 2023-04-01 at 18 23 31 (2)](https://user-images.githubusercontent.com/82783188/229314481-45fd7a55-a680-429b-9d5f-7a1e99900c6c.jpeg)
When loading whit the OFW, the screen goues black after nintendo logo

- Sd card formatted with fat32

**Comment by balika011** [comment]
Memory issue. Probably your switch was dropped and it has a bend in the case looking from the charge port side.

**Comment by Synxian** [comment]
I don't see any bends,  and i was playing perfectly fine yesterday, on another hand, now i turned it on with the ofc and the screen was blue

**Comment by Synxian** [comment]
> Memory issue. Probably your switch was dropped and it has a bend in the case looking from the charge port side. The most common fix is reflow the cpu.

As i don't have the tools nedeed for a reflow, i'll have to wait till monday, thanks for the reply, after the blue screen i think it's probably this

**Comment by SocialleyWebsite** [comment]
Same issue with mine
