### ISSUE TITLE
White screen on switch OLED

### ISSUE THREAD

**Issue by zakwarrior** [CTCaer/hekate#843]
Hello,

I'm getting a 70/80% white screen when i load new hekate 6.0.3 on switch oled, 

It's not a full white screen, i cannot upload a picture since my phone broke few days ago and i'm waiting for a new one, 

Screenshot fonction doesn't work i tried it with this white screen but it doesn't work, so i uploaded an image that i did with pain to show you what it looks like

This happens just after hekate logo, so the start logo show up normaly then when the time bar is finished i get this white screen

I went back to 6.0.2 and everything works fine like it should

![Sans-titre](https://user-images.githubusercontent.com/5190445/230696350-032a070d-6b38-461f-8439-f85fdddd5468.jpg)

If you need any info on this oled or whatever let me know

**Comment by CTCaer** [comment]
Did you redownload the release and repasted it and safely eject to make sure it wasn't corrupted?

**Comment by zakwarrior** [comment]
Yeah I'm well aware for that since I also code programs and scripts, I've been doing this many times the same way, i will try again tomorrow but i always prefer to delete all the older stuff on the sd and replace with new files since I have my ini files and the rest saved. Never had this issue before

Envoyé à partir de Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________
