### ISSUE TITLE
ito test : force open (1) chn: 2 the touchscreen calibration failed

### ISSUE THREAD

**Issue by Chekeleke** [CTCaer/hekate#849]
I Replaced the Digitizer. the touchscreen works but some spots don't. When I try to do the screen calibration I get this error ito test : force open (1) chn: 2 the touchscreen calibration failed. Tried my times not lock. the digitizer is fine because I installed android and run screen touch pass all the spots were fine. Any solution pls? thanks

**Comment by Chekeleke** [comment]
Here are some pictures. The first  one is the error and the second one the test I did on android 

![20230427_093233](https://user-images.githubusercontent.com/131993684/234924593-a25d8b27-8bf7-4109-b910-f8206f9ba503.jpg)
![Uploading 20230427_105611.jpg…]()

**Comment by Chekeleke** [comment]
I left the dot floating  on purpuse, if not will close the windows  as finished. Here is a picture   of HW info 
![20230427_115936](https://user-images.githubusercontent.com/131993684/234936144-761b730e-2acb-49c4-9992-e38e67ac6054.jpg)

**Comment by CTCaer** [comment]
Panel is paired to the touch ic, so it's a connector/flex/hw issue.
