### ISSUE TITLE
Making NYX snappy on Mariko 

### ISSUE THREAD

**Issue by Leerz** [CTCaer/hekate#851]
it is known that Hekate runs the snappiest on Erista, Icosa
but it's a little slower, navigating to menus on Mariko Devices, is there a settings i can change for this?

it works perfect, just would be nice if it's snappier

**Comment by masagrator** [comment]
This is because Hekate on Mariko doesn't train RAM, so RAM runs at lowest possible clocks. This is not an issue with settings.

**Comment by Leerz** [comment]
> o RAM run

i kinda understand that it isn't an issue with the settings, and thank you for the insight about why this happens

so perhaps, for QOL or peeking interest of others .

https://github.com/CTCaer/hekate/blob/2f1d1572f799b8e708068ad1463c1fa80491998b/modules/hekate_libsys_minerva/sys_sdrammtc.c

**Comment by CTCaer** [comment]
With Nyx v1.4.0 (hekate 5.9.0), it became snappy enough on mariko for its use case.
Waterfall rendering is gone, lists and tickers are responsive, and so on.
There's not gonna be dram training just for only that. At least not in the foreseeable future.
