### ISSUE TITLE
problem while injecting payload

### ISSUE THREAD

**Issue by Mohabou7152007** [CTCaer/hekate#858]
Hi,when I inject the payload I get this message in yellow
''nyx exeption occurred (LR 810412CC):UNDEF''

**Comment by CTCaer** [comment]
Without doing anything?

**Comment by Mohabou7152007** [comment]
After I tried to download a game my microSD card got corrupted so I formated it in Fat32 and I downloaded atmosphere, bootloader, Sigpatches... And after I injected the payload I got the message

**Comment by CTCaer** [comment]
piracy is not supported

**Comment by impeeza** [comment]
@Mohabou7152007 your card is fake or aged to damage, use a new card and start over.
