### ISSUE TITLE
Backup eMMC error

### ISSUE THREAD

**Issue by LePumpkinKing31** [CTCaer/hekate#859]
I really hate having to ask, but during the eMMC RAW GPP backup it hits 95% at rawnand.bin.13, does 3 failed passes, then aborts. After that it says my eMMC is in slow mode and I have to reboot

**Comment by CTCaer** [comment]
Get screenshot of emmc info pop up and below pop up and also sd card info screenshot.
All that **after** a failed attempt to backup emmc.

**Comment by CTCaer** [comment]
You didn't send the most important thing I asked.

Get screenshot of **emmc info** pop up and below pop up.
All that after a failed attempt to backup emmc.

That means go to console info -> emmc info and get a screenshot of the pop up that will show up in there. Then close it and get a screenshot of the actual emmc info.

**Comment by LePumpkinKing31** [comment]
Didn't realize what you meant rip. It fails pretty consistently and only takes a few minutes so its ok. Hopefully this is what you needed.

Before fail (actual emmc info)
![nyx20240527_211727](https://github.com/CTCaer/hekate/assets/49045001/1849eb09-2925-471e-9d77-1964fe02937b)

After fail
![nyx20240527_213016](https://github.com/CTCaer/hekate/assets/49045001/1b578233-6405-423d-852d-f24e0223d11d)

**Comment by CTCaer** [comment]
Have you ever tried to continue the backup from where it was left?
It clearly fails on part 13, so you can just add the index file back and it will continue from there.
Here, paste the `partial.idx` from that zip into sd root and it will continue from part 12.
[partial.zip](https://github.com/CTCaer/hekate/files/11708671/partial.zip)

Anyway, that's a hw issue and I can't help fixing it.
