### ISSUE TITLE
Nyx exception occurred <LR 81064C78>

### ISSUE THREAD

**Issue by Bonanno1234** [CTCaer/hekate#863]
I cannot press any button, and need to restard alot of time to make this work again, is these snyway to fix this thing? Thank you
Nintendo switch V1 ( Green Series ) 
16.0.3 Firmware
fully update to date
Brand sd card from sandisk
![received_223454003880486.jpeg](https://github.com/CTCaer/hekate/assets/109894777/a8071f12-7abb-4128-a861-34dc982ab454)

**Comment by CTCaer** [comment]
You are not fully up to date.
Update to latest first and then when it happens post that message again so I can see where it dies (the number 81064C78 will change).

**Comment by Bonanno1234** [comment]
> You are not fully up to date. Update to latest first and then when it happens post that message again so I can see where it dies (the number 81064C78 will change).

Thank you but i have a quick fix by use TegraRCMGui and choose Fusee to boot on EMMU. My brother has take the switch and go to travel :(

**Comment by CTCaer** [comment]
Well anyway, if it happens again, it's either corruption of the bootloader folder and files or you must use `bpmpclock=2` or `bpmpclock=3` in `nyx.ini`

**Comment by Bonanno1234** [comment]
Thank you for help me ^^ Have a good day <3
