### ISSUE TITLE
Nyx missing :/

### ISSUE THREAD

**Issue by Moshi0ijbol** [CTCaer/hekate#872]
Soo trying to mod my switch from android. but having major issues. Followed the switch homebrew guide. I have latest version of hekate. trying to launch to create a backup but i can’t launch! nyx is missing and “Failed to init SD Card.” error pops up. I feel like i’ve hit a wall and can’t find answers anywhere ‘-.- help please. I absolutely beg of you

**Comment by impeeza** [comment]
Hello there, this is not a support site, This is a BUG REPORT zone, please read the documentation on https://github.com/CTCaer/hekate/ there is all you need.

May be your card is damaged or your console have a broken sd card reader.

for further support go to a right site, Discord, GBATemp are example of support sites.

**Comment by Moshi0ijbol** [comment]
That’s the thing. The file is there. my sd card is new. got it on the 21st. my switch never had an sd card in it before so i highly doubt the reader is damaged

**Comment by impeeza** [comment]
Anyway test it.

**Comment by Moshi0ijbol** [comment]
i just did again.. still nothing😥

**Comment by CTCaer** [comment]
You are supposed to extract the bootloader folder from the release zip in your sd card root
