### ISSUE TITLE
Wrong time / year in filesystem

### ISSUE THREAD

**Issue by dandud100** [CTCaer/hekate#874]
When I booted "hekate v6.0.5 & Nyx v1.5.4" it asked me to set a time on first boot, and I 100% set the year to 2023, now all files generated from hekake (backups for example) are marked with the timestamp 2024 in Windows!

I verified that by trying to change the time again and it was definitely on 2023.

**Comment by impeeza** [comment]
look your time offset setting.

**Comment by CTCaer** [comment]
Will be fixed in next version. Currently year it's off-by-one. So select 2022 in the list.

**Comment by CTCaer** [comment]
Fixed in Nyx 1.5.5
There's no need to set the offset again for anyone that set 2022 btw since that used 2023 in older one.

If someone want's to fix the year from 2024 to 2023 for existing folder/files can follow @lucasaf04 linux/macos commands
