### ISSUE TITLE
My switch does not boot up hekate bootloader

### ISSUE THREAD

**Issue by CasseiaN** [CTCaer/hekate#876]
hey guys. i bought a used switch lite with chipset installed. The guy says he was able to boot up hekate bootloader and tinfoil to download games. But it does not work. When i install the required files to the sd card and put it in my sisters switch the hekate bootloader opens up just fine. but when i do it to my switch lite it does not open up the bootloader it just opens the official software of nintendo. why may this be?
pls i need help

**Comment by impeeza** [comment]
Hello there, this is not a support site, you could get more help on discord or GBATemp.  

both consoles have the same modchip installed? 

which console is you sister's one?

what are the leds of the modchips telling you?
