### ISSUE TITLE
2168-0002(0x4a8)

### ISSUE THREAD

**Issue by namujcd43** [CTCaer/hekate#879]
I'm not really a home brewer by craft, but I downloaded the latest Hekate file I, booted well I, uninstalled all themes, and reinjected update payload into the switch. so it boots up fine and i can ply games but once i try to get into JKVS files  it gives me this code i tried to see if i had it in the atmosphere folder to delete in the contents but there is no folder there in the sd.  please help and if its not to hard can you break it down to me like a noob(i am) . thanks for the help.
![-5398257458670379182](https://github.com/CTCaer/hekate/assets/142839745/5a4bca66-b0d6-4308-a62b-2e773a74d3e6)

**Comment by CTCaer** [comment]
That's not a hekate issue. Ask JKVS dev.
But just in case run archive bit fixer in hekate -> tools -> 2nd tab at the bottom.
And make sure hbmenu exists.

**Comment by namujcd43** [comment]
Thank you for the  response  how would I be able to get the hbmenu folder if they're not there.
Sent from my T-Mobile 4G LTE Device
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
