### ISSUE TITLE
Fastboot menu - Boot options

### ISSUE THREAD

**Issue by Shiftone** [CTCaer/hekate#884]
Suggesting this as an enhancement.

Funciton is similar to autoboot but instead of booting a single congfiguration, Fastboot would present the options set up in hekate_ipl.ini allowing for quick selection between Emunand CFW, SysCFW, Stock etc.

Feature could work like this;

Enable fastboot
Next coldstart Hekate presents boot options

Optional timeout to load first entry automatically if no user interaction with x seconds

**Comment by CTCaer** [comment]
What you are proposing can already be done with hekate's boot storage. Read the readme on how to force the menu.
