### ISSUE TITLE
USB gamepad not working

### ISSUE THREAD

**Issue by Ixolaro** [CTCaer/hekate#887]
hey, i wanted to try out HID emulation USB gamepad but it didn't work. joycons are all fine and hekate recives input but not the HID emulation

**Comment by CTCaer** [comment]
What's the actual issue? And also in which OS?
(Linux has evtest where the gamepad can be tested, windows has the game controllers utility and no clue on mac)

Generally when I added that back in 2020, I actually tested it in windows, linux and android and it was fine in all of them.

**Comment by Ixolaro** [comment]
hello thanks for responding. i use windows

**Comment by Ixolaro** [comment]
the issue is that windows detects the device but does not recive any input
