### ISSUE TITLE
make kip module with usb file transfer support (replace default hid device for file transfer)

### ISSUE THREAD

**Issue by Rolfiatina** [CTCaer/hekate#89]

**Comment by m4xw** [comment]
A storage driver can be implemented for the existing usb stack in form of a bso (so no kip/horizon)
Probably only after ccplex is ironed out.
If you want it for Horizon you are in the wrong place.

**Comment by CTCaer** [comment]
As was pointed out, hekate is a bootloader to boot horizon.
Also for HOS, the only option is to have support for MTP (so the card does not need to be dismounted).
For a bootloader shared library, check the development of hekate as it expands further.
