### ISSUE TITLE
Hall effect sticks drifting issue in Nyx

### ISSUE THREAD

**Issue by Clydefrosch22** [CTCaer/hekate#890]
On a new switch lite with picofly chip and new gulikit sticks, Hekate seems to detects movement making the cursor appear and wander typically to the bottom right of the screen.
It's the same issue described here https://github.com/CTCaer/hekate/issues/847

The sticks are calibrated and show no sign of drift or ghost inputs whatsoever during normal switch play or in the calibration menu, they are not being touched during startup to either.

Anytime i reload hekate with the reload button, the cursor will move differently. Its either straight right, hard down and right or slow down and slow right.

Is it possible the calibration hekate performs at startup doesn't play well with the hall sensor sticks? 

It is not at all a big deal and if there is no solution or no incentive to look into it, that's fine too.

**Comment by CTCaer** [comment]
>Is it possible the calibration hekate performs at startup doesn't play well with the hall sensor sticks?

As you guessed hekate uses its own dynamic calibration and is done when they are detected and joycon init finishes, so it's fully controlled.

So it could be. If you want to test a mitigation for that, find my discord tag in retronx and pm me.

**Comment by redbeard1083** [comment]
For whatever it is worth I have the exact same setup and see the same behavior.

**Comment by ermonas** [comment]
Same setup, same issue. I’m willing to help debug a possible solution, if you need any help. Thanks!

**Comment by CTCaer** [comment]
Test:
[nyx.zip](https://github.com/CTCaer/hekate/files/12909212/nyx.zip)

**Comment by redbeard1083** [comment]
Issue resolved for me.  Thank you!

**Comment by DiamondYuan** [comment]
Issue resolved for me too.

**Comment by ermonas** [comment]
I can confirm the fix works too! Thanks!

**Comment by HexNoob2** [comment]
I tried this zip and it also fixed my issue:  Left stick always going down at about 50% in hekate.  Thank you.

**Comment by harvestry-of-ghosts** [comment]
> Test: [nyx.zip](https://github.com/CTCaer/hekate/files/12909212/nyx.zip)

I do not have Hali sticks and this issue was happening to me with the latest nyx. Tried this and it immediately went away. Can you please explain what changes were made to fix it? Some people in #847 said it is 100% related to stick drift. Is that accurate? As I experience zero drifting during game play and zero drifing during the iitial loading of Hekate. It ONLY happens when reloading it. Is the fix going to be in 1.5.7?

**Comment by CTCaer** [comment]
Fixed in Nyx 1.6.0

**Comment by mbuna1992** [comment]
Hi sorry have this issue, where do i put the nyx file?

**Comment by Leerz** [comment]
> Hi sorry have this issue, where do i put the nyx file?

roo:\bootloader\sys\nyx.bin
