### ISSUE TITLE
boot.dat error !

### ISSUE THREAD

**Issue by Narayan62** [CTCaer/hekate#891]
Hello
since version 6.0.2, it is impossible to launch the sxos payload with hekate. I have a boot.dat error.
version 6.0.1 and below, it works very well.
is a bug? will you solve this problem? is there a solution ?

Thanks for your help

**Comment by impeeza** [comment]
No piracy is supported by Hekate, only no piracy CFW is supported, use Atmosphère.

**Comment by CTCaer** [comment]
Piracy is not supported. Also what year is it...
