### ISSUE TITLE
Battery Desing Capacity

### ISSUE THREAD

**Issue by capybara33** [CTCaer/hekate#892]
Hello, I have switch oled model but console use battery very fast because battery capacity is lower then 800 mah. I used Battery Desync Fix tool after the capacity increased to 6813 mah but its higher then design capacity. How can I turn it to desing capacity. Note: Design capacity is 4667 mah. 

Thank you

**Comment by capybara33** [comment]
I'm afraid the battery will be damaged

**Comment by CTCaer** [comment]
Get the latest version (v1.2.2) of [Battery Desync Fix NX](https://github.com/CTCaer/battery_desync_fix_nx#battery-desync-fix-nx) in case you didn't already and rerun it.
Just make sure you follow the guide to the letter if you use both sys and emu.
