### ISSUE TITLE
microSD slot fail

### ISSUE THREAD

**Issue by kikenobi** [CTCaer/hekate#893]
In case of SD slot failure, is there any possibility of start Hekate from USB with no using the SD slot?

**Comment by impeeza** [comment]
Duplicated, please look into closed issues, and the answer is no, it can not be done

**Comment by CTCaer** [comment]
On erista (v1), you can just inject it and get the TUI. Just enough to test sd slot via console info -> sd card.

**Comment by kikenobi** [comment]
Thanks for your anwers. 
I've checked sd slot and it is dead... Is there anything to deal with it?

**Comment by Visualwit** [comment]
> Thanks for your anwers. I've checked sd slot and it is dead... Is there anything to deal with it?

Get a replacement.
