### ISSUE TITLE
Optimized Firmware 17.0.0 + Atmos 1.6.0 support

### ISSUE THREAD

**Issue by Arch9SK7** [CTCaer/hekate#894]
I'm pretty certain you are already working on it. But I thought I would open this just in case.

**Comment by RyabDev** [comment]
Yeah it seems at the moment it is completely non-functional. Loads to a black screen or atmosphere goes to kernel panic.

**Comment by Visualwit** [comment]
What is taking so long?

**Comment by RyabDev** [comment]
> What is taking so long?

This stuff is done in their free time. Give them time.

**Comment by Kinokoda** [comment]
> What is taking so long?

patience is a wonderful thing, please obtain some. :)

**Comment by impeeza** [comment]
> What is taking so long?

Aleays you can ipen a development IDE and start to code by yourself.
The cide is open, and the developers had invested lots and lost of their free time and knowledge on the this, then give to all us for free.

So please, give some credit and if you like to get a very quick development you can pay to somebody a lot of money, code all the needed changes by yourself. or grateful wait.

Please by respectful

**Comment by Kinokoda** [comment]
> > What is taking so long?
> 
> Aleays you can ipen a development IDE and start to code by yourself. The cide is open, and the developers had invested lots and lost of their free time and knowledge on the this, then give to all us for free.
> 
> So please, give some credit and if you like to get a very quick development you can pay to somebody a lot of money, code all the needed changes by yourself. or grateful wait.
> 
> Please by respectful

oh huh its impeeza. heyo, thanks for helping peeps out over on gbatemp, you deserve the pog award.

**Comment by SciresM** [comment]
let's not shit up CTCaer's issues, guys. He works really hard, and I know for a fact that he's already put a bunch of work into 17.0.0 stuff.

**Comment by ThatOneOcto** [comment]
> What is taking so long?

Is this real?

**Comment by GelidaAvis** [comment]
> It's insane looking at the previous releases just how fast these devs are at updating the projects after a new switch firmware release, just over 24hours and AMS has a pre-release that works.
> 
> 
> 
> also, hekate worked fine for me on a fresh unit. I did get a kernal panic once, but after running again worked fine. I'm going to hold off on booting into AMS fully though just in case.

how were you able to boot? once i installed ams 1.6.0 it won't boot, just gives me a panic.

**Comment by TwistedTempest** [comment]
> > It's insane looking at the previous releases just how fast these devs are at updating the projects after a new switch firmware release, just over 24hours and AMS has a pre-release that works.
> > also, hekate worked fine for me on a fresh unit. I did get a kernal panic once, but after running again worked fine. I'm going to hold off on booting into AMS fully though just in case.
> 
> how were you able to boot? once i installed ams 1.6.0 it won't boot, just gives me a panic.

I had the same issue, delete mission control or whatever folder under atmosphere/contents is failing. According to SciresM there is a possibility for soft bricks, but it could just be something not up to date

**Comment by Vinfall** [comment]
Read 

> > It's insane looking at the previous releases just how fast these devs are at updating the projects after a new switch firmware release, just over 24hours and AMS has a pre-release that works.
> > also, hekate worked fine for me on a fresh unit. I did get a kernal panic once, but after running again worked fine. I'm going to hold off on booting into AMS fully though just in case.
> 
> how were you able to boot? once i installed ams 1.6.0 it won't boot, just gives me a panic.

Read carefully, you get a panic on first boot. But later on it should work fine. If not, try load payloads/fuse.bin instead of selecting nyx launch option. Note this would launch Atmosphere directly and thus ignores launch configs set in `hekate_ipl.ini`.

**Comment by CTCaer** [comment]
https://github.com/CTCaer/hekate/releases/latest
