### ISSUE TITLE
Failed to match warmboot with fuses

### ISSUE THREAD

**Issue by afaty-man** [CTCaer/hekate#895]
I habe an issue, when i trying to on my mariko switch i see the error "Failed to match warmboot with fuses"
What should i do? Please help me
Pkg1 20230906134551

**Comment by Masamune3210** [comment]
![Screenshot_2023-10-18-11-17-52-31_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/CTCaer/hekate/assets/1053504/4914c929-1ab7-40eb-b810-32e879183e35)
