### ISSUE TITLE
[Enhancement] Add option to put Joycons in Low-Power-State (to save Battery!)

### ISSUE THREAD

**Issue by mvergaraq** [CTCaer/hekate#896]
**Feature I'm suggesting:**
It is known that with the Joycon Toolkit (Windows) we can set the joycons to low power state which truly turns them off, avoiding that they get discharged when not using them in a long time [(stethix has a video on this)](https://www.youtube.com/watch?v=CZxwVnLc83o). It really is just two steps: 1) sending subcmd 07 to clear the pairing data of the joycon 2) sending subcmd 08 together with subcmd argument 01 to set the joycon in low power state. This feature would be awesome to have on the Switch as it really makes the joycons battery last a lot longer when not using the console in a long time. It's also great when you have a set of joycons that you only use with friends/guests. Using a Windows PC each time is a hassle.

**Expected behavior**
A button in the Tools section to put connected Joycons in Low Power State

**Comment by CTCaer** [comment]
Use the joycon toolkit.
Generally, "features" that can exist only to save 2-30s of someone's time every several months won't ever be added.

Btw, have in mind or general info for anyone that wants to use that;
you should never store anything with lithium battery at full charge.
Make sure it's at around 3700-3800mV when using that.
