### ISSUE TITLE
make kip module with emulate "test internet connection" after i add new wifi connection with no internet (or with wrong internet gateway and dns in settings) for easy use software like ftpd for safetly use file transfer over wlan 

### ISSUE THREAD

**Issue by Rolfiatina** [CTCaer/hekate#90]

**Comment by m4xw** [comment]
The development of "kip modules" is not relevant to the hekate project.
Please open the Issues on any relevant CFW repository or start a project yourself.

**Comment by CTCaer** [comment]
Same as
https://github.com/CTCaer/hekate/issues/89
