### ISSUE TITLE
Use SD card for various Switch consoles (feature request)

### ISSUE THREAD

**Issue by b1tfan** [CTCaer/hekate#900]
I have some Switch consoles at home and want to share the SD cards between them. I do so moving everything from SD root to a folder named wtith the serial number (e.g. XKJ123456789). This is done for all consoles that i run with the SD. 512GB cards offer nowadays plenty of storage. For using the SD with the specific Switch, I move the content of its folder to the root dir.

It would be a fantastic option for Hekate to do that automatically when entering the GUI. Could be done by a config file, where it's recorded what the current setup is and by detecting a different serial # to offer the change.

**Comment by CTCaer** [comment]
Out of scope. You can make a very simple intermediate payload for that if you want.
Also I hope that these switches are not v1/v2, otherwise you are risking of breaking the sd mobo connector.
