### ISSUE TITLE
hekate exception occurred (LR 4000E854): HANG DETECTED IN LP0/MINERVA!

### ISSUE THREAD

**Issue by BastCer** [CTCaer/hekate#908]
Hello, I have a problem with the Nintendo Switch.
Every time I start in RCM the console gives me this message

hekate exception occurred (LR 4000E854):
HANG DETECTED IN LP0/MINERVA!
Press any key...

When I press any key the console screen remains with black and white lines
I already tried changing the SD card and replacing all the files, but still with the same error
I have a doubt that it could be something internal to the console.
I hope someone can help me.
regards
![1](https://github.com/CTCaer/hekate/assets/152461182/c19438a5-3df7-4310-a6b2-83e2032a0356)
![2](https://github.com/CTCaer/hekate/assets/152461182/9292007b-1b86-4b0e-97f2-45317a4e3f36)

**Comment by CTCaer** [comment]
Check that your sd card is not fake or corrupted.
Also that your sd reader and its connector is fine.
If none of the above is the issue then:
Your ram chips or ram solder balls or the ram solder balls at the soc side have an issue.
