### ISSUE TITLE
Touch Perfect on HEKATE but nothing in SYSNAND/EMUNAND

### ISSUE THREAD

**Issue by edufalaschi** [CTCaer/hekate#911]
So, i had some touch problems when installing a modchip (faulty clean Up my work), and run the hekate calibration option (my fault thinking that it'll fix my problem).
The touchscreen was perfect before the modchip installation. Now i have everything perfect (Good config with sysnand/emunand).
The touchscreen works PERFECT in Hekate, but not working in sysnand/emunand.

What can i do?
BTW i have another V2 working perfectly fine with same modchip. Just in case if i need It for something.

EDIT: Now i remember, when i run the hekate calibration option, i was getting a issue in HOS that the volumen keeps getting + without touching the button.
Can i do something to get my touchscreen work on sysnand/emunand?

**Comment by CTCaer** [comment]
Well can't do anything when there's a hw issue. Just replug the touch panel flex. Other than that, dunno.
