### ISSUE TITLE
Hekate exception occurred (LR EB00003E) RESET

### ISSUE THREAD

**Issue by zitlalyr2** [CTCaer/hekate#913]
![image](https://github.com/CTCaer/hekate/assets/49773770/c8df32d3-f24f-4362-a51d-bf8207ba9f07)

Every time I boot up through payload this happens.
I separate issue but when i try to boot through ofw to get past hekate, it’s just a black screen.
Maybe it’s internal damage? I tried replacing the sd reader just in case, but that isn’t the problem.

**Comment by zitlalyr2** [comment]
When switching the readers, I also get this screen as well. No other information.
![image](https://github.com/CTCaer/hekate/assets/49773770/21c3c322-3e06-40a8-94b4-892789472bfd)
![image](https://github.com/CTCaer/hekate/assets/49773770/58237c79-8e84-480b-9911-0df60278f82f)
Would I just have to update?

**Comment by impeeza** [comment]
Could be an hardware damage.

try another SD Card with only Hekate on it  and if the same error, could be a reader or connector damage.

**Comment by CTCaer** [comment]
One of your ram chips or the ram solder balls on SoC are broken.
Easily observed by the background artefacts.
![image](https://github.com/CTCaer/hekate/assets/3665130/319da994-8151-4c41-9ca9-8048b7fe162f)
Reflow of the soc or/and ram chips might fix that.
