### ISSUE TITLE
missing lp0 sleep lib

### ISSUE THREAD

**Issue by superxoi** [CTCaer/hekate#916]
i bought a BSoD switch lite, changed the emmc to rebuild the nand but the console keep showing error code i could not enter hekate. i have used 2 micro sd cards. the first one was sandisk the console boot and show "missing lp0 sleep lib" error immediately.  the second was samsung which delay for 3 seconds before showed the error " hang detected in lp0/minerva" . 
please help me. thank in advance.

**Comment by CTCaer** [comment]
Show me a photo of the screen with these error messages. Should be as clear as possible (not blurry)

**Comment by superxoi** [comment]
![Uploading IMG_20240113_215405.jpg…]()
Sr but my phone camera is bad. Bear with me. This one is from my sandisk one. 
![IMG_20240113_215930](https://github.com/CTCaer/hekate/assets/133989111/efb81cb5-18f7-4192-afc0-00e8fb6b4486)

**Comment by superxoi** [comment]
When i press a button it shoew this one
![Uploading IMG_20240113_220131.jpg…]()

**Comment by superxoi** [comment]
This one is from another card 
![IMG_20240113_220500](https://github.com/CTCaer/hekate/assets/133989111/33268b3d-c711-45f2-a1dd-3b7c4b0e7740)

**Comment by superxoi** [comment]
Sometime i got this one 
![IMG_20240113_215405](https://github.com/CTCaer/hekate/assets/133989111/6ac4af76-9108-4be7-9bac-2c451af9289e)
It showed hekate logo but a crashing one.

**Comment by superxoi** [comment]
When i enter payload section it showed none in there. But in the sd card definitely has 4 payload. Is there a possibility that my sd card reader are bad. 
![IMG_20240113_220918](https://github.com/CTCaer/hekate/assets/133989111/9fb9d155-d8cd-4be3-bbf7-802024a66fc5)

**Comment by superxoi** [comment]
I have just clean the sd card a bit and it showed the new one error code.
![IMG_20240113_221406](https://github.com/CTCaer/hekate/assets/133989111/899bcfeb-bfab-444e-97ad-8950566db7ea)
 "Hekate exception occurred (lr 84014de4) 
Undef "

**Comment by CTCaer** [comment]
No need for more pics.
All of them show the issue:
![image](https://github.com/CTCaer/hekate/assets/3665130/419468d9-be80-4ded-942b-f0bd45598661)

APU ram solder balls or ram chips issue.
Start by reflowing apu.
You can normally see if it's aput by opening it up, pressing down and holding the apu and hit power and see if it works.

Other than that I can't help since it's a hw issue.
