### ISSUE TITLE
Hekate boot logo stuck & error <LR EB006426>

### ISSUE THREAD

**Issue by Limpidit7** [CTCaer/hekate#917]
HI
I'm inquiring about a problem that I couldn't solve during the Nintendo Switch repair

There was no short circuit on the board, charge 0.4A, and black screen

When I moved the EMMC and attached it to the hacked switch, I could see the file normally and there was no problem

After the apu and ram reflow, the bluescreen will appear

APU and RAM Reball

There is no blue screen, but only a black screen

Is it a apu problem or a Ram problem?

Is there a way to test the RAM?

Similar to the memtest program..

![photo_2024-01-17_00-47-41](https://github.com/CTCaer/hekate/assets/156829299/1ce17dbb-da4d-4f86-bde5-756e19a2110a)
![photo_2024-01-17_00-47-43](https://github.com/CTCaer/hekate/assets/156829299/92158657-b6d5-4360-a73b-e3bd91f3f92b)
![photo_2024-01-17_00-47-37](https://github.com/CTCaer/hekate/assets/156829299/f64b9bbf-f5c8-47b8-9f6a-b0f8b071ce07)
![photo_2024-01-17_00-47-34](https://github.com/CTCaer/hekate/assets/156829299/6b19b9a9-fcdb-4c22-a28e-513552bb60da)
![photo_2024-01-17_00-47-32](https://github.com/CTCaer/hekate/assets/156829299/7b0c6b70-f6ed-44cd-a79a-5d7efbafc60d)
![photo_2024-01-17_00-47-29](https://github.com/CTCaer/hekate/assets/156829299/8ebb205a-131e-491b-8738-99ef199aee4a)
![photo_2024-01-17_00-47-27](https://github.com/CTCaer/hekate/assets/156829299/fc465355-c446-4701-a7a1-ec413711c4b5)
![photo_2024-01-17_00-47-25](https://github.com/CTCaer/hekate/assets/156829299/c5719413-0a9d-40fe-bceb-4ce070a2387e)
![photo_2024-01-17_00-47-23](https://github.com/CTCaer/hekate/assets/156829299/d563e61a-38c6-46b2-beb8-4b74b6335ce8)

**Comment by CTCaer** [comment]
It's a ram based issue and you basically can't find why it's caused easily.
The are always 4 reasons:
APU ram pads solder balls shorted or broken
RAM chips pads solder balls shorted or broken
Dead RAM chips
Passive components for power delivery or data are missing or shorted or dead

hekate uses ram right away (way before screen is on) so it's easy to hang like that.
