### ISSUE TITLE
Failed to init sd card

### ISSUE THREAD

**Issue by artslay** [CTCaer/hekate#918]
This happens when the console is completely rebooted. It takes several attempts for the card to be detected and the console to boot
![nyx20210609_033309](https://github.com/CTCaer/hekate/assets/16070464/c53aff19-6b3b-45cc-b996-77a48691e7c8)

**Comment by CTCaer** [comment]
You still have that issue?

**Comment by artslay** [comment]
> You still have that issue?

Yes.

**Comment by CTCaer** [comment]
do you see init/read errors when that happens in the micro sd info? because it looks like an issue with your sd reader.
that info is provided in hekate TUI also, when the GUI fails to load.

**Comment by artslay** [comment]
> do you see init/read errors when that happens in the micro sd info? because it looks like an issue with your sd reader. that info is provided in hekate TUI also, when the GUI fails to load.

No, there were no errors.

**Comment by CTCaer** [comment]
That's a hw issue or something, since you are the only one having it.
So because of that it's not easy to identify the cause and doubt it can be mitigated by software.
If you want though, you can contact me in discord. You can find my discord tag via retronx discord.

**Comment by DKingAlpha** [comment]
This is happening to me now.

I had other files load from sdcard before hekate, and hekate is load from FAT32 sdcard too, they all good until hekate runs to TUI saying failed to init sdcard. I believe this is not a hardware issue.

To solve this issue, I boot into OFW from hekate TUI, then slowly pop/insert sdcard until OFW prompts to reboot to use sdcard.

**Comment by Masamune3210** [comment]
If its happening in Horizen, its a hardware issue. Nothing hekate does with the SD card would affect how OFW handles it.
