### ISSUE TITLE
[Feature Request] Flip the screen 180 degrees

### ISSUE THREAD

**Issue by MazuNX** [CTCaer/hekate#920]
Having an option in the settings to flip the screen would allow people to use Hekate's usb mass storage feature, while having their switch on a stand. Obviously this can't be done as is, with the usb port on the bottom of the switch, which interferes with the switch sitting level on the stand. I would just set the switch down on a table, but I don't like putting that weight on the joy-con triggers.

If you're not interested in adding this, I understand. I can always buy some flat pad-like stand to keep the switch suspended horizontally.

**Comment by CTCaer** [comment]
Somehow I missed that request.
It's an understatement if I said that this is the weirdest request-reasoning I ever saw for a "feature".

Also even if the joycon back shell wasn't made to be used as legs for resting placement, the triggers would hit the top of their housing so it would still not affect them.
