### ISSUE TITLE
Failed to match warmboot with fuses

### ISSUE THREAD

**Issue by QB1n** [CTCaer/hekate#921]
I habe an issue error "Failed to match warmboot with fuses"
What should i do? Please help me!!!
Pkg1 20230906134551
![IMG_20240118_160454](https://github.com/CTCaer/hekate/assets/157575968/6b80385c-24b0-4d28-96fc-454308440254)
![IMG_20240118_160504](https://github.com/CTCaer/hekate/assets/157575968/a631a0e8-1484-48e3-a792-3d946f7d7821)
![IMG_20240118_160531](https://github.com/CTCaer/hekate/assets/157575968/66ee0301-f963-4e75-96bf-bf0aef539187)

**Comment by urherenow** [comment]
https://github.com/CTCaer/hekate/issues/616

as well as a few others.

**Comment by CTCaer** [comment]
> #616

That's wrong issue
Correct solution is to boot stock or sys cfw once
