### ISSUE TITLE
Yellow screen after update

### ISSUE THREAD

**Issue by Dragon3200** [CTCaer/hekate#924]
I was using the stock boot but had to stop using the switch for some days

the switch turn off by battery, after charge it and turn it on, i try to load the stock boot but it says hos not compatible

after read was because i had an outdated version of hekate, I updated to latest version

but now everytime i try to load the Stock version it go to yellow screen

is there a way to fix this? i dont want to lose my save files

**Comment by CTCaer** [comment]
You need to update atmosphere also. (atmosphere's secmon is still used in stock)
