### ISSUE TITLE
Move to a larger microsd card?

### ISSUE THREAD

**Issue by baqlias** [CTCaer/hekate#929]
My apologies if you've seen this question before, or if I'm asking this in the wrong forum! I've just received an OLED Switch with Picofly and a 128GB microSD card. Hekate and Atmosphere are installed and working fine, along with a few games. The card is nearly full and I would like to expand to a larger card. I have a 512 GB card on hand. I have tried to do this on my own but keep running into errors. Would I be better off setting up the larger card from scratch? Can someone point me to some place that shows how this can be done?  Thanks!!

**Comment by urherenow** [comment]
Gbatemp or retronx on discord
