### ISSUE TITLE
Updating with the use of "update.bin" skips the use of a custom bootlogo

### ISSUE THREAD

**Issue by Huntereb** [CTCaer/hekate#93]
Placing "/bootloader/update.bin" on the sd card causes the update binary to launch, but skips application of "bootlogo.bmp" regardless of the config settings.

**Comment by fennectech** [comment]
What’s update.bin for?  My Google fu has failed me

**Comment by CTCaer** [comment]
it's the update chainloader of hekate v4.

No google required, written in front page and in releases..

**Comment by fennectech** [comment]
Wow. I spent like 5 minutes looking at that page before i went for google. Then finally asked here.   I need to sleep xD.  It’s 4 am here.

**Comment by CTCaer** [comment]
https://github.com/CTCaer/hekate/commit/b54cbbfc3c90e9fdad06750b9f82c3e2e8e6b679
