### ISSUE TITLE
[feature request] - BCM & CYW stats - BSOD / EMMC

### ISSUE THREAD

**Issue by Leerz** [CTCaer/hekate#935]
We already have stats for most of the max control ic's and PD controller.

we have stats for fuel gauge which works exceptionally well diagnosing broken switches with bad fuel gauge.
we have stats for the PD controller and charge profile (in absence of a VIN/USB meter)

would it be great and have stats to communicate with the BCM and CYW wireless chips?
this could help aid diagnose failed chips (stuck on Nintendo switch logo) instead of guessing if it's an m92 issue or the wireless chip.

i know the alternative would be to just boot android or linux and see if they get wireless comms but having it alongside existing stats in hekate would be really really good.

also a take on BSOD switches, which aren't always APU or RAM, would be nice to memtest like how the emmc and sdcards are benchmarked.

**Comment by CTCaer** [comment]
The wifi chip is connected to PCIE.
So there's no chance I'm gonna create pcie drivers and then broadcom drivers only to identify such issue.
So yeah, just use linux. There's a reason I still allow an existing linux installation to be run on any device just by using the same sd or usb stick/hdd/ssd on another one.

As for the last thing, if it's not apu or ram then there's no point to a memtest thing.
