### ISSUE TITLE
Cancelling autoboot with - Button does not work anymore

### ISSUE THREAD

**Issue by tatundria** [CTCaer/hekate#936]
Any idea why Hekate`s latest version does not allow to cancel autoboot by pressing - at boot? It is not working for me. Instead, I had to disable autoboot inside the .ini file to get into Hekate.

**Comment by impeeza** [comment]
My console vulnerable using RCM Loader, I can cancel autoboot just fine.

**Comment by tatundria** [comment]
I use HWfly and I cannot cancel autoboot with Hekate’s latest version…

**Comment by urherenow** [comment]
Try adjusting your bootwait time up a bit...

**Comment by impeeza** [comment]
by example, mine is 1 second, and I have plenty time to interrupt the autoboot:

![image](https://github.com/CTCaer/hekate/assets/41979604/4753a8f3-ea0f-49fc-81d5-a15c3178ea9e)

Another thing, you will see a horizontal bar growing from left to right at the bottom of screen while you can interrupt the process.

but you can put some bigger value to test.

**Comment by tatundria** [comment]
I already did that. 10 seconds. But it is not responding to - button at boot (the -button is operational)

**Comment by Clydefrosch22** [comment]
just to be sure, you're pressing volume -, not select button -, right?

**Comment by tatundria** [comment]
Yes. Volume - on the left joycon.

**Comment by urherenow** [comment]
Vol is not on the joycon. 🤣

**Comment by impeeza** [comment]
@tatundria are you joking?  are you do not using Vol- ON THE TABLET to interrupt the autoboot?
