### ISSUE TITLE
Auto NGC Does Not Work

### ISSUE THREAD

**Issue by harvestry-of-ghosts** [CTCaer/hekate#938]
Enabling the Auto NGC option in Hekate does not disable the card slot in emuMMC.

This was my original ini file:

[config]
autoboot=0
autoboot_list=0
bootwait=3
backlight=58
noticker=0
autohosoff=1
autonogc=1
updater2p=1
bootprotect=0

[Atmosphere emuMCC]
payload=bootloader/payloads/fusee.bin
icon=bootloader/res/icon_payload.bmp

[Stock sysMMC]
fss0=atmosphere/package3
stock=1
emummc_force_disable=1
icon=bootloader/res/icon_switch.bmp

I was told I'm having the problem because I need to boot with Hekate's FSS0. Under the advice of others, I added the following entries to my ini. Booting with either still does not disable the card slot when in emuMMC.

[Atmosphere emuMCC fss0]
fss0=atmosphere/package3
kip1patch=nosigchk
emummcforce=1
atmosphere=1
autonogc=1
icon=bootloader/res/icon_payload.bmp

[Atmosphere (emuMMC fusee load)]
payload=bootloader/payloads/fusee.bin
emummcforce=1
icon=bootloader/res/icon_payload.bmp

The ONLY thing that seems to disable the slot is using the stratosphere.ini to disable it.

**Comment by urherenow** [comment]
because you're using fusee in emuMMC. If you're not using fss0, you're not using hekate's config files. And you obviously did not setup nogc in Atmosphere's ini files...

**Comment by harvestry-of-ghosts** [comment]
> because if you're using fusee in emuMMC, you're not using hekate's config files. You need nogc in Atmosphere's setup, in that case.
> 
> Is this statement true for you? "Automatically applies nogc patch if unburnt fuses found and a >= 4.0.0 HOS is booted"
> 
> If it's not true, then of course it won't be disabled, because there is no point.

Thank you for the reply. So to confirm that I understand you correctly... Since I already tried using Hekate fss0 instead of fusee and the slot was still not disabled, it means that there are no unburnt fuses and thus Auto NGC is working as intended. Is that correct? In which case the only option to disable the slot when a persons Switch had 17.0.1 at the time of the emuMMC creation is the stratosphere.ini setting.
