### ISSUE TITLE
Hekate exception occurred (4000E854): Hang detected in LP0/Minerva > Missing LP0 (sleep) lib! Missing Minerva lib! Update bootloader folder

### ISSUE THREAD

**Issue by crossholo** [CTCaer/hekate#939]
Using fw 16.0.0, AMS 1.5.2, latest Hekate release (v6.1.0) on a Hwfly/Picofly modchip (not sure which since the ebay listing had both in the description).

The switch worked fine for a day or two, until it white-screened. After a force restart, this was the error I got:

`hekate exception occurred (4000E854):
Hang detected in LP0/Minerva!`
This same error persisted even after formatting the micro-sd and setting it up again.

![hekate old error](https://github.com/CTCaer/hekate/assets/110487978/bba317c1-c304-42be-a631-1655bcf4942c)

After swapping to another microsd, this new error came up:

`Missing LP0 (sleep) lib!
Missing Minerva lib!
Update bootloader folder!`

Not sure if the pattern in the background means anything.

![hekate new error](https://github.com/CTCaer/hekate/assets/110487978/05fb5fe7-636b-497c-bd09-b0a4c2dd5efe)

**Comment by impeeza** [comment]
duplicated, search on closed issues.

**Comment by CTCaer** [comment]
Ram issue (at soc or ram side). I replied to you in discord also.
