### ISSUE TITLE
Hetake exception ocurred <LR 4000A068>

### ISSUE THREAD

**Issue by RobertoJim** [CTCaer/hekate#940]
Hi, 
I get this exception code when I insert hekate in the micro SD card. I can't find the source of the problem or where to find documentation about exception codes, could someone tell me how to solve it?
![IMG20240323153723](https://github.com/CTCaer/hekate/assets/49876476/de6b3b38-5c78-4a4d-adef-906be36917b5)

![IMG20240323153746](https://github.com/CTCaer/hekate/assets/49876476/8fba70ce-af21-4aea-8af6-495439a124af)

I have checked the micro SD slot to see if it is damaged, but everything seems to be OK. In addition, I have tried with several Sandisk micro SD, both extreme plus and plus, both 128GB.
![IMG00001](https://github.com/CTCaer/hekate/assets/49876476/55e33fbf-be34-45a9-87b4-cf5a6f21f2b7)
![IMG00004](https://github.com/CTCaer/hekate/assets/49876476/b0ff1a0e-7a6c-43a3-b91a-3bacba4c6a13)

**Comment by impeeza** [comment]
Hekate works with the others cards?

**Comment by urherenow** [comment]
I’m pretty sure this is the person I’ve been replying to on temp. Upon trying to launch ofw, blue screen… so it’s a hardware issue (likely from the chip install).
