### ISSUE TITLE
Restore Fuel Regs from dump

### ISSUE THREAD

**Issue by xgoofyx** [CTCaer/hekate#941]
Hello! In the Battery Info section there is a button "Dump Fuel Regs". How can I restore the dump I made?

**Comment by impeeza** [comment]
You don't need to restore them, you can force a battery sync, look in to the documentation.

**Comment by CTCaer** [comment]
I don't find the full restore/cloning of battery characteristics regs ok.
The dumping is there mostly for researching purposes.
