### ISSUE TITLE
Blue screen when booting stock after updating hekate

### ISSUE THREAD

**Issue by klenndal** [CTCaer/hekate#946]
When I boot stock through the launch option I get a blue screen. I can launch stock though the mod chip bypass by holding down the volume buttons when the system is booting. I can boot into CFW without any problems. Stock firmware version is 18.0.0, CFW is on 17.0.1.

[hekate_ipl.ini.txt](https://github.com/CTCaer/hekate/files/14806995/hekate_ipl.ini.txt)

**Comment by yoho2chn** [comment]
are you on 1.6.2 atm? 
Try ATM1.7.0PRE-release, I was same until I realize it was just dumb mistake.

**Comment by klenndal** [comment]
Fixed, thank you
