### ISSUE TITLE
UMS SD card isn't working

### ISSUE THREAD

**Issue by x676278** [CTCaer/hekate#948]
When I select tools-USBtools-SD card, the other machines show waiting to connect, my machine shows USB activated, no prompts after connecting using the cable, but the switch does not show up in my PC drive list at all, there is no way for me to securely pop it up on the PC side, but my Another switch works fine in the same operating environment, I don't know what other information I need to provide, please let me know if you can, this problem has been bothering me for a long time and I haven't been able to find a solution, please help me!
![UMS SD](https://github.com/CTCaer/hekate/assets/29781319/4ac796f1-bc93-480f-b2f3-51d77d6c8b12)

**Comment by impeeza** [comment]
can you please try with the official release from https://github.com/CTCaer/hekate/releases and repeat the test?

please also send a screenshot of the microSD Card Info Page ( Console info -> storage & battery info, microSD)

thanks.

**Comment by x676278** [comment]
> can you please try with the official release from https://github.com/CTCaer/hekate/releases and repeat the test?
> 
> please also send a screenshot of the microSD Card Info Page ( Console info -> storage & battery info, microSD)
> 
> thanks.

I have updated to the latest version, but the problem is still there, here is my SD card information, please help me analyze it, thank you very much for your reply!
![O](https://github.com/CTCaer/hekate/assets/29781319/9f221c67-6dbe-48f9-a902-3c93dd63deec)
![P](https://github.com/CTCaer/hekate/assets/29781319/af0d3070-eee4-44f8-9aac-968a782cec4a)
![QQ图片20240401180706](https://github.com/CTCaer/hekate/assets/29781319/08961bed-d0e2-4916-86ef-77734db12a98)

**Comment by impeeza** [comment]
Well ExFAT can be prone to corruption you should use FAT32 on the SD Card.

But in this case can you please test the USB connection by using the gamepad emulation on the same page is ums. With that were can check the port, cable and connector.  You should see a USB gamepad connected to your PC

**Comment by x676278** [comment]
> Well ExFAT can be prone to corruption you should use FAT32 on the SD Card.
> 
> But in this case can you please test the USB connection by using the gamepad emulation on the same page is ums. With that were can check the port, cable and connector. You should see a USB gamepad connected to your PC

it's worked，but UMS SD card still fail
![Uploading 1.jpg…]()

**Comment by x676278** [comment]
![1](https://github.com/CTCaer/hekate/assets/29781319/08f730b0-9225-4bd1-bfd2-9e4d95aa89f6)
![2](https://github.com/CTCaer/hekate/assets/29781319/755e814d-877c-4320-9318-7e13cf7fd74b)

**Comment by impeeza** [comment]
With this we checked the PC USB Port, The Cable, The Console USB Connector, The USB Stack on NYX.

here any developer could give us a hint.

**Comment by CTCaer** [comment]
Play with `bpmpclock=` in `nyx.ini` and it will solve your issue (read the readme). If not reopen the issue.
Also have in mind that no support is generally given for modded versions of hekate/Nyx.
