### ISSUE TITLE
nyx exception occured (LR 81065db4) undef

### ISSUE THREAD

**Issue by MarcinhoLetsCode** [CTCaer/hekate#951]
Sometimes hekate freezes too

**Comment by Almasora5** [comment]
I have the same problem and I cannot do anything in hekate, has anyone solved it?

**Comment by giannicolicchia** [comment]
Any news on this?

**Comment by MarcinhoLetsCode** [comment]
if you guys are trying to back up sysnand and create an emunand, i found a way of doing that:
1-to backup sysnand i used an earlier version of hekate (hekate_ctcaer_4.10.1), without GUI,
2-to create a emunand i had to use (hekate_ctcaer_5.1.0_Nyx_0.8.3), gave me error on first try, but worked when i tryied again
3-Updated hekate and everything normally

*if boot entries are empty:
1-( https://github.com/CTCaer/hekate/issues/456 ) 
2-( https://rentry.org/EristaEmuNAND )

*if some error about "Unknown pkg1 version" occurs:
1-( https://rentry.org/EristaEmuNAND )

**Be Careful Following**
**Try At Your Own Risk**

**Comment by CTCaer** [comment]
Piracy is not supported

**Comment by Maario01** [comment]
Same here... No solution?

**Comment by impeeza** [comment]
> Same here... No solution?

Piracy is not supported

> Piracy is not supported

**Comment by MarcinhoLetsCode** [comment]
Sadly The only solution i found was using an earlier version of the program :/

**Comment by MarcinhoLetsCode** [comment]
Help us to solve this error
