### ISSUE TITLE
Hekake won’t boot after updating Switch to 18.0

### ISSUE THREAD

**Issue by locksoft** [CTCaer/hekate#952]
I updated the stock partition of the Switch to 18.0. On the emusys I still have Atmosphere 17.0.
When I boot the Switch I see for a second the Nintendo logo, then the screen goes black and the chip led is pulsing green.
What can I do?
Thanks.

**Comment by urherenow** [comment]
You need to reset/retrain your chip. When you update the normal way (OFW), going between certain firmware versions will update your boot0 as well, overwriting whatever the chip does to boot0 when you train it.

How to reset the chip? Depends on the chip. You need to look that up yourself. I personally have an hwfly chip, and have to open the back of the Switch, and power on while shorting 2 points.

**Comment by locksoft** [comment]
Thank you, I've your same one, HwFly v.5 and the two points short solved the issue.
Sorry for the noob question, but it was my first experience with this weird behavior.
