### ISSUE TITLE
emuMMC wont start - error 2002-4153 program: 0100000000000031

### ISSUE THREAD

**Issue by santiagoahumada13** [CTCaer/hekate#957]
when i try to enter mi emummc partitios i get this error after the nintendo logo, ive tried updating everything, even overlay modules, deleting cofig folder and i still cant access my system, help please 
![20240421_185211](https://github.com/CTCaer/hekate/assets/124843945/19025492-c093-4571-97e6-a9ae116d70c8)

**Comment by impeeza** [comment]
Backup and delete SD:/atmosphere/contents folder.

Normally is an outdated sysmodule.

please next time ask for help on GBATemp or Discord, https://gbatemp.net/threads/homebrew-crashes-indicate-0100000000000031-as-culprit.632198/

**Comment by CTCaer** [comment]
Or corrupted data or mismatched. Maintenance mode might also fix it.
But for sure here's the wrong place to get support for such things.
