### ISSUE TITLE
regarding ddr200

### ISSUE THREAD

**Issue by Stashboy** [CTCaer/hekate#958]
DDR200 isn't working but shows as available in hekate[
![teamgroup 256gb](https://github.com/CTCaer/hekate/assets/111486898/aaf9ac4e-5ad4-4366-8875-bfd74924033f)
![hekate sd info](https://github.com/CTCaer/hekate/assets/111486898/be4abb9d-c179-4fec-a3e7-f3e58d91d407)
](url)

**Comment by urherenow** [comment]
What do you mean by "isn't working"? Can OFW read and write to the card, but CFW can't? Can NYX not save the screenshot to it when you use the button, instead of taking a picture of the Switch?

**Comment by Stashboy** [comment]
I was told to say that. But basically when trying to flash ubuntu-jammy, I get stuck on the "booting" screen indefinitely. Theofficialgman was able to provide me with a modified boot file that disabled ddr200 and then I was able to boot ubuntu-jammy.
![JAMMY](https://github.com/CTCaer/hekate/assets/111486898/dc064610-9f71-4825-a63e-4ffd972736f2)

**Comment by CTCaer** [comment]
hekate just reports if the card supports it.
It doesn't actually use it, and never will (there's no point in that context).

If my implementation works for that card in l4t is also another story.
(It's basically compatible only with Samsung cards and some others. So you only know via testing it.)

Also opening such issues here is the wrong place. hekate has nothing to do about it.
