### ISSUE TITLE
RAM Options?

### ISSUE THREAD

**Issue by Kurausukun** [CTCaer/hekate#963]
I know this may not be the appropriate place to ask, so let me know if I should close this and move it somewhere else. I saw in the info for the latest release that there are options for setting the RAM speeds to specific values as well as overclocking, but I couldn't find any info on how exactly this is done. The main README.md says to refer to a "README_CONFIG" file, but I found no such file. Where can I find info on what options there are for this? I don't currently want to OC necessarily, but it would be nice to be able to set my RAM speed to 1600 globally without having to go through sys-clk.

**Comment by CTCaer** [comment]
That's not for HOS. As it's described, it's for L4T and you can read the relevant info in the relevant wiki.
