### ISSUE TITLE
Wrong base address for SYSCTR0

### ISSUE THREAD

**Issue by hexkyz** [CTCaer/hekate#97]
SYSCTR0_BASE is defined as 0x7000F000, but it should be 0x700F0000!

**Comment by CTCaer** [comment]
I hope no debug or actmon relied on this..

**Comment by hexkyz** [comment]
I don't think anything major relies on it, but it might be a hindrance for homebrew apps that want to know the freq value.

**Comment by balika011** [comment]
That's nice we found the same problem on the same day independently.

**Comment by CTCaer** [comment]
https://github.com/CTCaer/hekate/commit/fdd94ffd2b190962571bcbdc0928f75dbb088304#diff-058c75ac0c7cc8df93f445f8f441b9ffR53
