### ISSUE TITLE
How do i hack my switch

### ISSUE THREAD

**Issue by CaraAntimateria** [CTCaer/hekate#972]
OK so basically yesteraday i was ready to hack it from scratch, i bought everything the jig the memory of 256 gb and the usb c data cable and all. So i came to my house and i tried entering the brand new sd to my switch and it said that i needed to update my console to use the sd so i had no other option so i did and then i saw that it was just released yesterday the 1.8.1.0 so nobody had the files to inject the payload to my switch can somone help me?

**Comment by urherenow** [comment]
GitHub isn’t a support forum. Go to discord or gbatemp for help. Or maybe just google it.
