### ISSUE TITLE
Blue when launching atmosphere from Hekate

### ISSUE THREAD

**Issue by AxelLaisney** [CTCaer/hekate#975]
Hello! Despite installing everything updated (hekate and atmosphere) I can't launch atmosphere from hekate. But I can launch it directly using the new fusee.bin. I am using rekado to inject the payload and yes I updated the fusee.bin in bootloader/payload file by the one providing on atmosphere github page. I have a switch v1.

**Comment by CTCaer** [comment]
use v3 and update all relevant payloads.
Duplicate of https://github.com/CTCaer/hekate/issues/969
