### ISSUE TITLE
Hekate won't load on Switch lite and adds a weird display issue

### ISSUE THREAD

**Issue by ArvsAndCarbs** [CTCaer/hekate#976]
Upon updating to 6.2.0, hekate stop loading properly if at all. It also introduced LCD artifact the resembles vignette effect or old gameboy screen effect on NO SD screen and faintly but visible on OFW.

Same setup worked on V2 unit.
I'm using 6.1.1 on 18.1 lite and it seems fine

**Comment by CTCaer** [comment]
NO SD screen is not a hekate thing.
If you are using some weird sdloader that corrupts the new hekate and can't function, I suggest you to update it.
A hos update always causes it to reset.

Reopen this issue if a proper sdloader still has issues.
