### ISSUE TITLE
Unable to boot Linux on v6.2.0 with erista (v1) switch

### ISSUE THREAD

**Issue by LuckyK65** [CTCaer/hekate#978]
Hekate 6.2.0 v3 breaks linux booting as when you try to launch it, it gets frozen at the loading screen, after 10 minutes it still stays at the screen. Downgrading to 6.1.1 fixes the issue so something is wrong with the latest version.

**Comment by iodn** [comment]
Same here, my Ubuntu version 22 was working fine before the update to Hekate 6.2.0 v3. After the update, Ubuntu seems to freeze on the boot screen.

**Comment by CTCaer** [comment]
Assuming this is related to https://github.com/CTCaer/hekate/issues/973
I want model info.

**Comment by LuckyK65** [comment]
Its the 2017 switch model

**Comment by iodn** [comment]
> Assuming this is related to #973 I want model info.

Yeah, it looks like this is related indeed. 
My model is also a 1st gen switch (XAJ7002).

**Comment by CTCaer** [comment]
Fixed the issue. Get **_v4.zip**

**Comment by Fra2605** [comment]
Excuse me, I have the same problem even if I have updated hekate

**Comment by Fra2605** [comment]
(V1 switch)

**Comment by Fra2605** [comment]
Linux stuck on boot screen

**Comment by azerty229** [comment]
v6.2.0 v4 no boot linux ubuntu 22 and 24 (erista v1 switch)

**Comment by azerty229** [comment]
No boot kubuntu v24 on Switch erista v1 and hekate 6.2 V4

**Comment by CTCaer** [comment]
@Fra2605 First of all don't spam, here's not a chat. Edit your posts.
@Fra2605 @azerty229 you are supposed to replace the payload you use to inject via PC or rcm loader or whatever.
So extract the bootloader folder to sd root and then inject the correct 6.2.0 hekate and not an older version as you do.

**Comment by azerty229** [comment]
I have already changed all the bootloader directory I even formatted my sd card and I took hekate v6.2.0 v4 but no kubuntu boot

**Comment by gitaccountme** [comment]
Hello
I'm confirming the same issue with Switch OLED model (linux is stuck on booting) I tried the following things with no avail :
- Upgrading to 6.2.0_V4.
- Formatting the SD card adding 6.2.0_V4  re-partitioning it again for fresh linux instantiation 
- Changing the SD card adding 6.2.0_V4.
- Changing from Ubuntu to Fedora 
- Downgrading to  hekate v6.1.1 

All resulted the same issue, note that Android and CFW boot are working fine

**Comment by CTCaer** [comment]
@gitaccountme you are not confirming the same issue.
sd card and ddr200 issues are not a hekate issue and neither the same with above.
seek support to the correct place.

**Comment by gitaccountme** [comment]
@CTCaer 

Hi sorry but I didn't get it how it's sd card and ddr200 issue?

My issue is:  "linux is stock on booting as when you try to launch it, it gets frozen at the loading screen, after 10 minutes it still stays at the screen"

**Comment by CTCaer** [comment]
This not a hekate issue and support for that doesn't belong here. Seek help and the no ddr200 boot.scr in the l4s discord (find it in the wiki).

**Comment by CTCaer** [comment]
v6.2.1 stable release is out
