### ISSUE TITLE
A suggestion for logopaths

### ISSUE THREAD

**Issue by Chernyash** [CTCaer/hekate#982]
Add an option so that you can put random pictures in logopaths. Let's say: logopath=bootloader/res/bootscreens/*.bmp and it randomly selected an image

**Comment by CTCaer** [comment]
Duplicate of https://github.com/CTCaer/hekate/issues/356

(No one reboots so often to guarantee a binary size increase just for being bored. It's not a wallpaper that you constantly look at.)
