### ISSUE TITLE
L4T infinite boot

### ISSUE THREAD

**Issue by artslay** [CTCaer/hekate#988]
Switch Lite, Jammy was working on 6.1.1 on 6.2.0 v4 - not working. Just infinite boot. After reboot Error Failed to mount rootfs.

**Comment by CTCaer** [comment]
That's not an issue with hekate, even if you restore it you will still get failed to mount rootfs.
Seek support to distro's support.

**Comment by artslay** [comment]
> That's not an issue with hekate, even if you restore it you will still get failed to mount rootfs. Seek support to distro's support.

problem with infinite boot
