### ISSUE TITLE
Lakka

### ISSUE THREAD

**Issue by Awetspoon** [CTCaer/hekate#991]
Hello since this new version  of Hekate . Lakka having some troubles booting.  If booted out of android and went into Lakka and it gets stuck on Lakka load screen. Normally I power off then get into Hekate. Boot into emmuc. Boot back to Hekate and try Lakka. Sometimes I get past the stuck logo. If all fails I have to repeat this process and when Lakka does the first loading line I have to press the -volume and power button once and it's gets me back in without redo the files.

Not sure why when I switch between android and Lakka Lakka seems to mess up.

Many thanks Marcus

**Comment by CTCaer** [comment]
You need to update everything that is hekate. You are doing r2p and load an old revision.
A new hekate will come tomorrow though anyway.
