### ISSUE TITLE
Trollface on Hekate and making cursor inverted 

### ISSUE THREAD

**Issue by Dominic-Dom** [CTCaer/hekate#993]
I updated hekate and now theres a trollface cursor making everything inverted. Is there a way to remove this?

**Comment by impeeza** [comment]
A screenshot please.

maybe you downloaded a non official Hekate release, always use https://github.com/CTCaer/hekate/releases

If any please share with us your current `SDMC:/bootloader` files and a screenshot

**Comment by impeeza** [comment]
¿?

**Comment by AvnerSounds** [comment]
I am having the same issue, what was the resolution?

**Comment by AvnerSounds** [comment]
My date was set incorrectly and it was an April fools joke, lol I was making it much more complicated

**Comment by impeeza** [comment]
ha ha ha, @CTCaer is a rascal,  you got me on that:

![image](https://github.com/user-attachments/assets/3cd237f6-10a3-40ba-a6c1-1862e4b2943b)

I think the Hekate Archives Page 872 should be added to the scriptures:

https://x.com/CTCaer/status/1342243940347613187?s=20

**Comment by Tymek1850** [comment]
Did you fix it?

**Comment by urherenow** [comment]
There is nothing to fix. Except for maybe the date on your console, if you're seeing this issue right now 🤣
