### ISSUE TITLE
release notes need updating

### ISSUE THREAD

**Issue by theofficialgman** [CTCaer/hekate#994]
current release notes include:

Click to expand FAQ notes
Which Linux/Android distributions are supported in Partition Manager?
For L4T Linux you can use the official Ubuntu Bionic 3.4.0 and newer or any other supported distro.
For android you can get Android 10 or 11.

the text should be updated to reflect hekate's ability to partition for android 14

**Comment by CTCaer** [comment]
Well no one uses the faq to decide what is supported by the partition manager.
It's just a hint on existing users. New ones just blindly follow a guide.
But anyway it will be changed.

Btw if you are gonna start opening issues and start reporting typos and other non-issues, please don't.
