### ISSUE TITLE
Keep having this show up when i inject hekate and it says nyx is missing

### ISSUE THREAD

**Issue by Blinkifyourok** [CTCaer/hekate#995]
![RDT_20240711_2058554356456384791065006](https://github.com/user-attachments/assets/c48486a4-83b0-4106-bd27-d3c6305a9af0)
![RDT_20240711_2248037904569061864932920](https://github.com/user-attachments/assets/0ed848a9-5d10-445c-a570-52cb1c9cae6c)

**Comment by urherenow** [comment]
And it also says to update your bootloader folder. So do that.

**Comment by Blinkifyourok** [comment]
How do I do that

**Comment by urherenow** [comment]
Download the latest release. Grab the bootloader from the .zip, and drop it into your sd card. Overwrite all files, if asked.

In short: RTFM.

**Comment by Blinkifyourok** [comment]
I've done that though I just keeps saying it

**Comment by impeeza** [comment]
@Blinkifyourok this is not a support channel is only to report REAL issues on the code.

please search for help on Discord or GBATemp.

This problem is more like you have a fake/damaged sd card.

**Comment by CTCaer** [comment]
extract the zip in the sd root and not a subfolder, and also to the correct partition if more than 1 fat partitions exist for some reason
