### ISSUE TITLE
Regarding custom background + icons

### ISSUE THREAD

**Issue by Stashboy** [CTCaer/hekate#997]
Hello, is there a written guide on replacing the background + icon files with custom made designs? I couldn't find anything of that sort which is why I'm reaching out. Thanks.

**Comment by impeeza** [comment]
https://github.com/CTCaer/hekate?tab=readme-ov-file#bootloader-configuration
and
https://github.com/CTCaer/hekate/issues/779

For support please go to a support site like discord or GBATemp, this space is for bugs and issues report ONLY.

**Comment by CTCaer** [comment]
https://github.com/CTCaer/hekate/blob/master/nyx/README_RES.md is a thing
