### ISSUE TITLE
About “battery desync fix nx”this tool

### ISSUE THREAD

**Issue by hukaka22** [CTCaer/hekate#998]
Hello! I use “battery desync fix nx”this tool to calibrate my switch lite battery,In emuMMC I do 2 full charging cycles (0% -> 100% -> 0% -> 100% -> 0%).but in hekate and DBI the battery age always keep 89%~91%.I change the new battery and 5000mA battery and do same 2 charging cycles,but also have this problem,why? How can I solve it? Thanks!
If I change the 5000mA battery to switch lite,hekate can show the right capacity?

**Comment by CTCaer** [comment]
piracy and piracy tools are not supported.
and also all that has nothing to do with hekate
